### ISSUE TITLE
Can this function library be implemented in c++

### ISSUE THREAD

**Issue by tankeliang** [jitsi/lib-jitsi-meet#1005]
Can this function library be implemented in c++？
Because I wanted to implement a non-browser-based desktop program in c++, but failed to connect to the jisti XMPP server。
thank you

**Comment by damencho** [comment]
Nope.

**Comment by tankeliang** [comment]
Thank you for your reply. Is it feasible for me to connect jitsi-based web server to XMPP server using gloox (XMPP c++ library)? like strophe.js？
thank you

**Comment by damencho** [comment]
Yes, you can it is a standard xmpp, but then you will need to integrate it with webrtc for the media part ... It is a ton of work, not that it is not possible, but you will need to spent months and months of doing this integration where you can install and if you want you can modify an already working desktop app jitsi-meet-electron, you will have a working desktop app in few minutes.

**Comment by damencho** [comment]
And please use the community forum for questions before opening new issues.

**Comment by tankeliang** [comment]
Ok, thank you very much. We also considered using electron before, but considering that our own hardware terminal meeting product (Linux) also needs to connect to jitsi for meeting, so we need to use c++/c to realize the connection. Is there a c++/c way for client demo to access jitsi? You said into the community to ask questions, because of our side of the reason, into the community to ask questions failed.
thank you

**Comment by visbs** [comment]
@tankeliang can u post an simple example code or guide me on how you were able to come up with a solution finally.
