### ISSUE TITLE
does this still rely on mslabel?

### ISSUE THREAD

**Issue by fippo** [jitsi/lib-jitsi-meet#1030]
(i'll ignore the template, claiming special privileges as :older_man:)

It seems that the [following code](https://github.com/jitsi/lib-jitsi-meet/blob/c8c9c43830fa12a82da52440a6e898ac72d02020/modules/RTC/TraceablePeerConnection.js#L1177) would break if `a=ssrc:123 mslabel:something` were to removed from Chrome.
```
    const problematicSsrcIds = ssrcLines.filter(ssrcLine =>
        ssrcLine.attribute === 'mslabel' && ssrcLine.value === '-')
        .map(ssrcLine => ssrcLine.id);
```
I [intend to stop chrome from generating these lines](https://webrtc-review.googlesource.com/c/src/+/168244) but writing the PSA about this found old strophe.jingle code and checked this repository too.

tagging @emcho @saghul. Let me know if you would be ok with this getting removed. The code in question should be easy to update to `ssrcLine.attribute === 'msid'`. And even there it only seem to look for the special '-' stream (aka "no stream") so the breakage should be limited.

**Comment by saghul** [comment]
Calling in the cavalry: @bbaldino @bgrozev @JonathanLennox @gpolitis

**Comment by gpolitis** [comment]
I'm not sure what's being deprecated here. If it's about the `mslabel` attribute, then I'm pretty sure we don't care about it in the bridge. If, on the other hand, it's about removing recv-only ssrcs, then this may have some negative side effects.. the bridge will drop RTCP packets, such as PLIs, from clients without any ssrcs announced. At least that was the case in old bridge, I'm not sure if the new bridge is more flexible.

**Comment by fippo** [comment]
no, ssrcs will still be there, both in the `a=ssrc:1234 msid:stream track` as well as the `a=ssrc:1234 cname:something` lines. I'm firmly in the "we love ssrcs and find your concerns about collisions not applicable to our use case" camp.

It is just the extra `a=ssrc:1234 mslabel:track` and `a=ssrc:1234 label:stream` that will be gone.

(also I assume the bridge has hardcoded the good old video 0x01 and [0xfa17fa17](https://cs.chromium.org/chromium/src/third_party/webrtc/media/engine/webrtc_voice_engine.h?type=cs&q=0xfa17fa17&sq=package:chromium&g=0&l=298) for audio :-))

**Comment by bgrozev** [comment]
Thanks for reporting, @fippo !

I am not aware of anything in our code that has a good reason to require  `mslabel` or `label`. I grepped through `lib-jitsi-meet`, `sdp-interop` and `sdp-simulcast` and I don't see anything apart from the code @fippo referenced. But I don't have a good understanding of the client. It would be nice if we could do a practical test, I guess we'll be able to do it when Canary hits.



> (also I assume the bridge has hardcoded the good old video 0x01 and [0xfa17fa17](https://cs.chromium.org/chromium/src/third_party/webrtc/media/engine/webrtc_voice_engine.h?type=cs&q=0xfa17fa17&sq=package:chromium&g=0&l=298) for audio :-))

Actually, we don't. We jump through hoops on the clients to make sure they always use a signaled SSRC :)

**Comment by fippo** [comment]
I wasn't worried that you would only notice when this hits + breaks stable, more about the long update cycle of opensource deployments.

since @saghul mentioned the focus elsewhere this might be the clientside code of 
https://github.com/jitsi/jicofo/blob/e412d07b669c9b4428fe088101569599a640193f/src/main/java/org/jitsi/jicofo/ParticipantChannelAllocator.java#L445-L458
so unrelated to chrome.

Will give you an extra heads up when I land the change after the next branch cut and then close here.

**Comment by fippo** [comment]
https://groups.google.com/forum/#!topic/discuss-webrtc/jcZO-Wj0Wus -- PSA sent, should land in Chrome Canary some time this week.

**Comment by fippo** [comment]
related, since I just gave my simulcast munging code a hard look: make sure you don't make assumptions about the number of a=ssrc lines :-)

**Comment by fippo** [comment]
all gone - and more than two years later the "downstream project" that has been blocking the removal has been updated.
