### ISSUE TITLE
Database Table issues 

### ISSUE THREAD

**Issue by febin123-tech** [jitsi/lib-jitsi-meet#1032]
@saghul @bostondv 

We have implemented the storage via mysql/postgres. On checking we could find that the tables are create under the db we updated on the conf files, but seems that the tables are empty. 

Configurations:

===========

Component "conference.eshtest-vc.lycheemcr.com" "muc"
  --storage = "null"
   storage = "sql"
    sql = {
        driver = "PostgreSQL"; -- May also be "MySQL" or "SQLite3" (case sensitive!)
        database = "p*o**dy"; -- The database name to use. For SQLite3 this the database filename (relative to the data storage directory).
        sql_manage_tables = "true"; -- Specifies whether Prosody will automatically create/update the tables it needs (recommended).
        host = "1**.209**6.*8"; -- The address of the database server (delete this line for Postgres)
        port = 5**2; -- For databases connecting over TCP
        username = "p*o**dy"; -- The username to authenticate to the database
        password = "******"; -- The password to authenticate to the database
    }

============

Ports are up on the server.

=========

root@ubuntu-s-2vcpu-4gb-nyc3-01:/var/log/jitsi# netstat -ntlp | grep 3306
tcp        0      0 1**.**9.**.68:3306      0.0.0.0:*               LISTEN      1105/mysqld     
    
==========

Please have a check on the issue

**Comment by saghul** [comment]
This is a Prosody issue really. Please ask their forums or on our community, maybe someone who uses it like that has experience.

**Comment by febin123-tech** [comment]
Hello,

Please let me know the settings to save the jitsi chat storage.
