### ISSUE TITLE
Jitsi chat history

### ISSUE THREAD

**Issue by valsaraj** [jitsi/lib-jitsi-meet#1049]
Hi,

We are using JS API for displaying chat history. Currently we are getting only current session history. Is there any way to get previous session histories as well?

Thanks!

**Comment by saghul** [comment]
Yes and no :-) The current (and the default) configuration destroys rooms when they are empty so all chat history is loost. If you have your own self-hosted Jitsi intance you can configure it not to do this and keep history.

This needs to be configured in the MUC component part of the Prosody (the XMPP server which power the Jitsi signaling) configuration.

**Comment by valsaraj** [comment]
Thanks for reply. Would you share some link to check the required configuration change?

**Comment by saghul** [comment]
Sure thing, check here: https://prosody.im/doc/modules/mod_muc also make sure the storage is not set to "null".

**Comment by valsaraj** [comment]
storage = "internal" is set. Would you confirm in which file the history will be saved?

**Comment by valsaraj** [comment]
When I configure storage = "sql", following error showing on prosody status with the latest jitsi-meet quick install:

> modulemanager: Error initializing module 'storage_sql' on 'conference.test.com':
>                                                       no field package.preload['DBI']
>                                                       no file '/usr/lib/prosody/DBI.lua'
>                                                       no file '/usr/local/share/lua/5.1/DBI.lua'
>                                                       no file '/usr/local/share/lua/5.1/DBI/init.lua'
>                                                       no file '/usr/local/lib/lua/5.1/DBI.lua'
>                                                       no file '/usr/local/lib/lua/5.1/DBI/init.lua'
>                                                       no file '/usr/share/lua/5.1/DBI.lua'
>                                                       no file '/usr/share/lua/5.1/DBI/init.lua'
>                                                       no file '/usr/lib/prosody/DBI.so'
>                                                       no file '/usr/local/lib/lua/5.1/DBI.so'
>                                                       no file '/usr/lib/x86_64-linux-gnu/lua/5.1/DBI.so'
>                                                       no file '/usr/lib/lua/5.1/DBI.so'
>                                                       no file '/usr/local/lib/lua/5.1/loadall.so'
>                                               stack traceback:
>                                                       /usr/lib/prosody/core/modulemanager.lua:31: in function </usr/lib/prosody/core/moduleman
>                                                       [C]: in function '_real_require'
>                                                       /usr/bin/prosody:190: in function 'require'
>                                                       /usr/lib/prosody/util/sql.lua:11: in main chunk

**Comment by saghul** [comment]
Internal storage should work. It's not ideal, but it should work.

**Comment by valsaraj** [comment]
@saghul 
would you tell me where is the internal storage path configured. When we do text chat, is there any settings need to store that in file/DB to show the previous chat when client connects again?

**Comment by saghul** [comment]
It’s configure in the server, Prosody. On the MUC component. The config options you can use are listed above on this thread. (A link)

**Comment by valsaraj** [comment]
Yes, I configured like in that link:
Component "conference.test.com" "muc"
    max_history_messages = 20
    storage = "sql"

But there is no entry came in tables even though the tables created:
prosody=# \dt
            List of relations
 Schema |      Name      | Type  | Owner 
--------+----------------+-------+-------
 public | prosody        | table | pdusr
 public | prosodyarchive | table | pdusr
(2 rows)

The prosody version by default installation is 0.10.0.

Any idea?

**Comment by saghul** [comment]
No idea sorry. Never used the sql backend myself.

**Comment by valsaraj** [comment]
@saghul 
Do you have idea about how we can verify file storage saves the chat history? I wonder whether prosody 0.10.0 supports this.

**Comment by saghul** [comment]
should be stored in /var/lib/prosody

**Comment by limer-org** [comment]
Hello, I have a request for information. I have my hosted Jitsi and I would like to be able to save the chat history of a room - I make a random room - I conduct a conversation and I have a chat record with important information described. Is it possible to save this so that I can return to this room and have this chat recording available?

**Comment by saghul** [comment]
Yes, take a look at the persistency options here: https://prosody.im/doc/modules/mod_muc

**Comment by limer-org** [comment]
Thank you. It worked.

**Comment by chagai95** [comment]
Would it make sense, after using this config to add a feature to Jitsi, in which the mesaages are all cleared when a meeting is explicitly being left (the last person, or when forcing everyone to leave?)

**Comment by saghul** [comment]
That is already the default behavior.
