### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by sujasundaresan** [jitsi/lib-jitsi-meet#1050]
How can we fetch the Chat History for a particular room using the lib-jitsi-meet API?

**Comment by saghul** [comment]
Please see: https://github.com/jitsi/lib-jitsi-meet/issues/1049

**Comment by sujasundaresan** [comment]
@saghul 

If a room have several days of chat, then using the "max_history_messages" property, we can only fetch limited number of records. I would like to show, the prior message history(all chat message), if the user would like to see. Is that possible?

**Comment by saghul** [comment]
That is a Prosody setting / limitation, nothing we can do on our side since lib-jitsi-meet connects to Prosody as an XMPP client.
