### ISSUE TITLE
Configure JWT tokens

### ISSUE THREAD

**Issue by valsaraj** [jitsi/lib-jitsi-meet#1052]
How to configure JWT tokens in latest jitsi-meet?
We followed this https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md and installed jitsi-meet.

**Comment by saghul** [comment]
Please ask such questions in our community. We try to keep GH issues strictly for bug reports.

**Comment by 1dl3** [comment]
I had a dependency problem while configuring jitsi-meet and jwt as well so I went ahead and installed [docker-jitis-meet](https://github.com/jitsi/docker-jitsi-meet#quick-start). 
After filling in the blanks in the .env file it seems to work as expected
