### ISSUE TITLE
Screen sharing: Mouse cursor invisible in Firefox

### ISSUE THREAD

**Issue by itpflop** [jitsi/lib-jitsi-meet#1055]
When sharing application windows in Firefox (68.6.0esr on Debian 10) the mouse cursor is not visible. I think this could be solved by adding “cursor: "always"” at

https://github.com/jitsi/lib-jitsi-meet/blob/47c2bc65457b0cd1620e171cf79ffe4d49d071c5/modules/RTC/RTCUtils.js#L478

See also: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/cursor

**Comment by Zeik0s** [comment]
This also applies to Firefox 74.0.1 on Windows 10. Would love to see that fixed.

**Comment by lupoDharkael** [comment]
Same here.

Operating System: Fedora 31
Mozilla Firefox 75.0

**Comment by sapkra** [comment]
Here is a discussion about it too. I've posted my findings over there:
https://community.jitsi.org/t/show-mouse-cursor-when-sharing-the-screen/25009

**Comment by jallamsetty1** [comment]
This is FF bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1625694
I verified this 2 weeks back, the bug has been fixed in FF76 on all platforms except linux.
Having said that, I think we should still add the cursor constraint for getDisplayMedia, its on my plate, will hopefully get to it soon.

**Comment by sapkra** [comment]
Since this was a bug in Firefox which is now fixed, I will close this issue.
