### ISSUE TITLE
Anonymous/guest-users can create rooms when guest access =false and allow_empty_token=true, using JWT tokens

### ISSUE THREAD

**Issue by bitmeal** [jitsi/lib-jitsi-meet#1057]
I am using the jitsi docker containers, but based on the behavior think this has nothing to do with the docker containers being used; all options can be configured, but the behavior of one option is not as expected:

## Description
---
When using jwt as authentication mechanism with `allow_empty_token=true` (in my case setting `JWT_ALLOW_EMPTY=1` in `.env`-file for docker-compose) creation of new channels is possible without any authentication. `ENABLE_GUESTS=0` is set and when using `JWT_ALLOW_EMPTY=0` both options are respected and anonymous users cannot join meetings and cannot create new rooms.

## Current behavior
---
Anonymous/guest users without authentication can create (and join these) new rooms.

## Expected Behavior
---
Anonymous/guest users should only be able to join existing rooms, but not be able to create new ones.

## Steps to reproduce
---
Use jitsi docker containers and set in `.env`:
```
ENABLE_GUESTS=0
ENABLE_AUTH=1
AUTH_TYPE=jwt
JWT_ALLOW_EMPTY=1
```

# Environment details
---
Using jitsi docker behind dockerized nginx with config below. 
`DOCKER_HOST_ADDRESS` and `PUBLIC_URL` are set accordingly and everything else seems to work.
JWT tokens are generated by the mattermost plugin (and working).
```
server {
    server_name ############
    include /etc/nginx/cert/ssl.conf;

    access_log  /var/log/nginx/########access.log;


      # web
      location / {
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Frame-Options SAMEORIGIN;
          proxy_cache off;
          proxy_pass http://dockerjitsimeet_web_1:80;
      }

      location ~ ^/(?!(http-bind|external_api\.|xmpp-websocket))([a-zA-Z0-9=_äÄöÖüÜß\?\-]+)$ {
          rewrite ^/(.*)$ / break;
      }
      # BOSH
      location /http-bind {
          proxy_pass      http://dockerjitsimeet_prosody_1:5280/http-bind;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_cache off;
          proxy_set_header Host $http_host;
      }
      # xmpp websockets
      location /xmpp-websocket {
          proxy_pass http://dockerjitsimeet_prosody_1:5280;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_cache off;
          tcp_nodelay on;
      }
 }
```

**Comment by maxired** [comment]
Hi,

from what I understand from documentation, this is intended.
You would have to setup two domains in jicofo https://github.com/jitsi/jicofo#secure-domain

But as you can see on https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#jitsi-meet-options

> At current level of integration every user that joins the conference has to provide the token and not just the one who creates the room. It should be possible to change that by using second anonymous domain, but that hasn't been tested yet.

**Comment by Noext** [comment]
i use 

ENABLE_GUESTS=1
ENABLE_AUTH=1
AUTH_TYPE=jwt
JWT_ALLOW_EMPTY=1

**Comment by saghul** [comment]
Three current behavior is expected. You’re basically allowing the token not to be specified which means unauthenticated users will be ale to use the service.
