### ISSUE TITLE
How can I trigger some thing on JitsiMeetJS.errors ?

### ISSUE THREAD

**Issue by ShahidNaumanTEO** [jitsi/lib-jitsi-meet#1058]
Hi, I am following the example code at [https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example](https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example)

I need to know, how can I trigger some thing on any error? Specifically like on `JitsiMeetJS.errors.track.TRACK_NO_STREAM_FOUND` 

Quick response will highly be appreciated.

**Comment by sapkra** [comment]
You catch a specific error by checking which kind of error it is. This should always be possible if a promise returns an [`JitsiTrackError`](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md#jitsitrackerror).

```typescript
JitsiMeetJS.createLocalTracks(...).catch((error) => {
  if (error.name === JitsiMeetJS.errors.track.TRACK_NO_STREAM_FOUND) {
    console.error('TRACK_NO_STREAM_FOUND');
  }
})
```
