### ISSUE TITLE
e2ee

### ISSUE THREAD

**Issue by AmilKey** [jitsi/lib-jitsi-meet#1086]
## Description
---
I'm trying to enable e2e encryption, I see you merged PR https://github.com/jitsi/lib-jitsi-meet/pull/1080 , but when I ran on my server I see black screen for all users. 
Also that does not work on https://meet.jit.si

# Environment details
---
chrome canary v84
enable chrome://flags/#enable-experimental-web-platform-features

**Comment by fippo** [comment]
Does https://webrtc.github.io/samples/src/content/peerconnection/endtoend-encryption/ work?
Chrome 84.0.4112.0 or later should be good.

e2ee still requires some special flags in the url hash. I *think* this is what we used in the demo (@saghul correct me if I'm wrong):
```
`#config.disableSimulcast=true&config.p2p.enabled=false&config.enableP2P=false&config.startWithVideoMuted=true`
```
Don't enable video unless there is at least one other participant.

**Comment by AmilKey** [comment]
@fippo @saghul thanks! But I have one problem.
I managed to start the video, but I can’t hear anyone and no one can hear me either

**Comment by dekkosecure** [comment]
We have one person joined with Chrome 81 (no insertable streams) and two people with Chrome 84 (insertable streams ON). 
All three can see video. I would assume that Chrome 81 person won't see video, since it encrypted?

**Comment by fippo** [comment]
@AmilKey: audio is not working yet, @saghul is on it.

@dekkosecure: due to the way we handle decrypt errors currently (by passing the maybe unencrypted frame to the decoder) Chrome 84 will see video from the Chrome 81 participant.
That is about to change since it is confusing. The chrome 81 participant should "garbage" similar to what Emil has shown in the video. Make sure you're setting #e2eekey with a lowercase 'k' -- been there, done that.

**Comment by dekkosecure** [comment]
Roughly, what the estimate to get audio working?

**Comment by saghul** [comment]
It will be ready when it's ready. Please be patient.

**Comment by burdges** [comment]
In this vein, is there any wishlist of things for which Jitsi might want outside collaboration, auditor funding, etc. in relation to E2E encryption?  There are many quite a lot of people interested in chipping in for that sort of thing right now.  

Also, there are issues around statistical leaks anytime the underlying data involved human behavior, like ssh leaks keystrokes.  Anyone interested in that sort of thing?

**Comment by dekkosecure** [comment]
@fippo @saghul you have done a brilliant job! And I am sure plenty people around also appreciate it.

One more question.
With e2ee conference, how does jvb do the bundle? it does not do any decryption, or still decryption is required?

The main worry that keys still passed to jvb and jvb does bundling via trans-crypt.
This is regarding e2ee with use of insertable streams

**Comment by saghul** [comment]
@burdges We are not criptographers, so any help is more than welcome. Since this is security related, feel free to reacch out to security@jitsi.org

What we have right now is a prototype. The current plan is to move to Matrix's olm library, but that may take a bit and we'll iterate some more on the current setup before we go there.

So yeah, all kinds of feedback regarding this implementation are welcome!

**Comment by saghul** [comment]
> One more question.
> With e2ee conference, how does jvb do the bundle? it does not do any decryption, or still decryption is required?
> 
> The main worry that keys still passed to jvb and jvb does bundling via trans-crypt.
> This is regarding e2ee with use of insertable streams

The jvb does not (and will not) get the key. It doesn't need it. We leave enough of the packet unencrypted (10 bytes for now, but we can and will go down to 1 or 2) for the briddge to be able to route the packet properly.

The jvb never touched the actual media, but it required metadata in the packet header.

**Comment by fippo** [comment]
> We leave enough of the packet unencrypted (10 bytes for now, but we can and will go down to 1 or 2) 
Actually 10, 3 or 1, depending on the packet type. See also https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/e2ee.md

**Comment by AmilKey** [comment]
@fippo @saghul 
I found one problem, when I turn on the camera, then turn it off, then participants see the my frozen picture and the video stream is not restored. it is reproducible on http://meet.jit.si
I think it is due to InsertableStreams.
chrome canary v84

**Comment by dekkosecure** [comment]
@fippo @saghul
Once you use JVB with Chrome 83+ you cannot enable video back. It is frozen. Need to re-enter conference.

**Comment by olyaeloquera** [comment]
@fippo @saghul
Hi Guys,
Do you have an indication where the problem with frozen re-enabled video could be? Or a possible workaround?
Thank you!

**Comment by fippo** [comment]
#1147 should fix that hopefully

**Comment by saghul** [comment]
Yep, continuing on https://github.com/jitsi/lib-jitsi-meet/pull/1147
