### ISSUE TITLE
5 fps when screen sharing in p2p mode in Chrome

### ISSUE THREAD

**Issue by rksm** [jitsi/lib-jitsi-meet#1089]
## Description
The frame rate when screen sharing gets limited to 5 fps as e.g. described here: https://community.jitsi.org/t/desktop-sharing-frame-rate-config-override-not-working-on-meet-jit-si-fps/20819/3.

This issue does not occur when running the connection over jvb.

This is independent from the constraints passed to getUserMedia or the constrains applied to MediaStreams.

## Possible Solution
Removing `a=x-google-flag:conference` from the SDP that gets patched into via `mungeRemoteDescription` will result in the frame rate not being limited to 5 fps.

## Steps to reproduce
Create a two participant call at https://meet.jit.si/. Share one screen, observe fps count in the stats or chrome://webrtc-internals.

**Comment by rksm** [comment]
Also, disabling simulcast via the server config or with `JitsiMeetJS.init({disableSimulcast: true})` does not change the behavior, the flag is still added.

**Comment by jallamsetty1** [comment]
Hey there, thank you for analyzing and figuring out the solution for this. I will give this a try and see if it fixes the low fps issue with screensharing, thanks !

**Comment by jallamsetty1** [comment]
This has been fixed here - https://github.com/jitsi/lib-jitsi-meet/commit/3794646b5cbe6ceb877acdf0aab999e858d5c630

**Comment by psi-4ward** [comment]
Hi there,
I've run into the 5-FPS thing as well and wondered why Screenshare makes 30 FPS with `disableSimulcast=true`.

`disableSimulcast=false; testing.capScreenshareBitrate=1` brings 5 FPS.

So I think we need to respect capScreenshareBitrate here: https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/TraceablePeerConnection.js#L2442 ?

**Comment by saghul** [comment]
I think the patch @jallamsetty1 mentioned was reverted then reworked... and we *just* landed some more fixes in this area yesterday, so I'd recommend re-evaluating with our latest unstable release. If you still see problems please feel free to open a new GH issue.

**Comment by psi-4ward** [comment]
For the docs: https://chromium.googlesource.com/external/webrtc/+/master/media/engine/simulcast.cc#466

**Comment by psi-4ward** [comment]
@saghul: as I see @jallamsetty1 removed the `capScreenshareBitrate` config and derives it from `desktopSharingFrameRate`.

So setting `desktopSharingFrameRate.max > 5` leads to have simulcast  **enabled** for Screenshare and now there's no ability control this anymore. => bad

**Comment by psi-4ward** [comment]
I've patched it for my needs for now. Just for the record:

Give back the ability to control screenshare-simulcast:

```diff
diff --git a/modules/xmpp/JingleSessionPC.js b/modules/xmpp/JingleSessionPC.js
index d56b46dfdc3fd382c8be706fece75d6389afe2a6..14747a8553beea0888d586296faa4776c11c7c06 100644
--- a/modules/xmpp/JingleSessionPC.js
+++ b/modules/xmpp/JingleSessionPC.js
@@ -355,8 +355,9 @@ export default class JingleSessionPC extends JingleSession {
 
             // Disable simulcast for low fps screenshare and enable it for high fps screenshare.
             // testing.capScreenshareBitrate config.js setting has now been deprecated.
-            pcOptions.capScreenshareBitrate = !(typeof options.desktopSharingFrameRate?.max === 'number'
-                && options.desktopSharingFrameRate?.max > SS_DEFAULT_FRAME_RATE);
+            // pcOptions.capScreenshareBitrate = !(typeof options.desktopSharingFrameRate?.max === 'number'
+            //     && options.desktopSharingFrameRate?.max > SS_DEFAULT_FRAME_RATE);
+            pcOptions.capScreenshareBitrate = options?.disableSimulcastScreenshare || false;
 
             // add the capScreenshareBitrate to the permanent properties so that it's included with every event that we
             // send to the analytics backend.
```

Make `desktopShareBitrate` config-able and do not set conference flag for disabled screenshare simulcast.

```diff
diff --git a/modules/RTC/TraceablePeerConnection.js b/modules/RTC/TraceablePeerConnection.js
index f74ca469df2f0206a195ae5688d6357c1bbaaf44..c677b7ae00ca4a32f81aa27da30fc322ffc6aa2e 100644
--- a/modules/RTC/TraceablePeerConnection.js
+++ b/modules/RTC/TraceablePeerConnection.js
@@ -28,7 +28,7 @@ import { SIM_LAYER_RIDS, TPCUtils } from './TPCUtils';
 const logger = getLogger(__filename);
 const DEGRADATION_PREFERENCE_CAMERA = 'maintain-framerate';
 const DEGRADATION_PREFERENCE_DESKTOP = 'maintain-resolution';
-const DESKTOP_SHARE_RATE = 500000;
+const DESKTOP_SHARE_RATE = window.config?.desktopShareBitrate || 500000;
 const HD_BITRATE = 2500000;
 const LD_BITRATE = 200000;
 const SD_BITRATE = 700000;
@@ -2439,7 +2439,7 @@ TraceablePeerConnection.prototype.setRemoteDescription = function(description) {
 
     if (browser.usesPlanB()) {
         // TODO the focus should squeze or explode the remote simulcast
-        if (this.isSimulcastOn()) {
+        if (this.isSimulcastOn() && !this.options.capScreenshareBitrate) {
             // eslint-disable-next-line no-param-reassign
             description = this.simulcast.mungeRemoteDescription(description, true /* add x-google-conference flag */);
             this.trace(
```

**Comment by saghul** [comment]
Why would you want to have simulcast disabled?

**Comment by psi-4ward** [comment]
I've some more participants in the conference and the one who does the screenshare has the main focus. If the bandwidth goes down the screenshare should not use a scaled down track - better suspend tracks from other participants. 

The screenshare also has some important text which gets not readable using the lower track so it's useless at all.

Hope I could clarify the usecase?

**Comment by saghul** [comment]
Hum.



> I've some more participants in the conference and the one who does the screenshare has the main focus. If the bandwidth goes down the screenshare should not use a scaled down track - better suspend tracks from other participants.

There are 2 reasons why a track would be scaled down on the sending side: CPU overuse (I wonder if this is kicking in, since screens can have a large resolution and at 30fps that's a lot of data) or layer suspension (if nobody is receiving you in the upper layer we drop it. Am I missing any case here @jallamsetty1 ?

For receivers, they'll get the highest layer if the user is "on stage", which is the case because switch to this mode when someone starts sharing.

Have you actually tested the current code in practice?

**Comment by psi-4ward** [comment]
> For receivers, they'll get the highest layer if the user is "on stage", which is the case because switch to this mode when someone starts sharing.

Jitsi often chooses a lower layer if the sender is "on stage" - thats our main problem and the reason why we don't want "lower layers" for screenshare.

**Comment by saghul** [comment]
> Jitsi often chooses a lower layer if the sender is "on stage"

That shouldn't happen.  Again, have you tested these changes from yesterday?

**Comment by psi-4ward** [comment]
Yes I did. WebRTC-Internals tells me on the sender side 3 outbound-rtp and receiver starts with high resolution-one and then it goes down when the bitrate starts to grow

**Comment by psi-4ward** [comment]
PS: Updated the Patch to not disable simulcast for video sharing.

**Comment by jallamsetty1** [comment]
> I've some more participants in the conference and the one who does the screenshare has the main focus. If the bandwidth goes down the screenshare should not use a scaled down track - better suspend tracks from other participants.
> 
> The screenshare also has some important text which gets not readable using the lower track so it's useless at all.

Chrome produces only 2 simulcast streams of the same resolution (as that of the captured desktop) but with different bitrates, one with 5 fps and the other with 30 fps (provided the client has enough resources). Layer suspension has no effect on screenshare, all streams are sent always since they are of the same resolution.
It is possible that the encoding endpoint doesn't have enough resources to encode 30 fps at the captured resolution and therefore downsamples it to a lower resolution.
What kind of machine are you testing this on ?
> 
> Hope I could clarify the usecase?

**Comment by jallamsetty1** [comment]
> PS: Updated the Patch to not disable simulcast for video sharing.

Are you reproducing this behavior on https://jayallamsetty.jitsi.net/ ?

**Comment by psi-4ward** [comment]
> It is possible that the encoding endpoint doesn't have enough resources to encode 30 fps at the captured resolution and therefore downsamples it to a lower resolution.

That's a very interesting point which I could observe many times BUT what means "not enough resources"? I've g4dn.2xlarge AWS instances and the res-monitor does not hit CPU and/or GPU limits so there should be enough space for encoding the 2 layers. 
But I see downsampling when some more participants join. Is this by chance or does Chrome thinks the VM has not enough power? For me it "looks like" is has to do with the number of participants. 

PS: The VM joins with lastN=0 and does not receive anything.

Thanks a lot for your investigation!!! 
Everything we tried - having one screenshare layer has given us the very best results combined with simulcast for webcams. 

> Are you reproducing this behavior on https://jayallamsetty.jitsi.net/ ?

I can run some tests next week but I'm pretty sure it will produce same results. My Setup runs runs on jvb 2.1-478, jicofo 1.0-740 and jitsi-meet (incl lib) is nearly up-to-date with current master.

**Comment by jallamsetty1** [comment]
> > It is possible that the encoding endpoint doesn't have enough resources to encode 30 fps at the captured resolution and therefore downsamples it to a lower resolution.
> 
> That's a very interesting point which I could observe many times BUT what means "not enough resources"? I've g4dn.2xlarge AWS instances and the res-monitor does not hit CPU and/or GPU limits so there should be enough space for encoding the 2 layers.

Are you running Ubuntu on these instances ? I am not able to reproduce the issue on macOS and Win10. It could be something specific to chrome on Linux. 

> But I see downsampling when some more participants join. Is this by chance or does Chrome thinks the VM has not enough power? For me it "looks like" is has to do with the number of participants.
> 
> PS: The VM joins with lastN=0 and does not receive anything.
> 
> Thanks a lot for your investigation!!!
> Everything we tried - having one screenshare layer has given us the very best results combined with simulcast for webcams.
> 
> > Are you reproducing this behavior on https://jayallamsetty.jitsi.net/ ?
> 
> I can run some tests next week but I'm pretty sure it will produce same results. My Setup runs runs on jvb 2.1-478, jicofo 1.0-740 and jitsi-meet (incl lib) is nearly up-to-date with current master.

**Comment by psi-4ward** [comment]
No, we have Win10 Nvidia-Gaming AMI running. 

For now we gave unified-plan on Chrome a try and this works great so far. Do you have plans when you deprecate planB? We could also discuss our exp. using unfied-plan but thats probably off-topic here.

**Comment by jallamsetty1** [comment]
> No, we have Win10 Nvidia-Gaming AMI running.
> 
> For now we gave unified-plan on Chrome a try and this works great so far. Do you have plans when you deprecate planB? We could also discuss our exp. using unfied-plan but thats probably off-topic here.

We have started working on ironing out the last few issues that we know of in our Unified plan implementation. It is encouraging that it is working great so far for you. Can you please open a different issue for that and tag me there so that we can continue the discussion there ?

**Comment by ProdigyView** [comment]
Was a new issue ever opened? I am experience this now. In my webrtc-internals on chrome, its showing the max is 5 fps for screening sharing. I have
- desktopSharingFrameRate : { min :5, max :60 } in my options passed into initJitsiConference
- room.setDesktopSharingFrameRate(60);

It is recording when I looked at request was made, but the graphs in webrtc-internals only show 5 fps.

**Comment by saghul** [comment]
This issue is years old and a lot has changed. Please open a new one and provide as many details as possible.
