### ISSUE TITLE
Authenticated users in Openfire don't generate MUC events

### ISSUE THREAD

**Issue by deleolajide** [jitsi/lib-jitsi-meet#109]
I traced the problem to here
https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/xmpp/strophe.emuc.js

```
        var room = this.rooms[Strophe.getBareJidFromJid(from)];
        if(!room)
            return;
```

it should be return true otherwise the handler is treated as a oneoff and is never called again

**Comment by sapkra** [comment]
Seems to be fixed.
