### ISSUE TITLE
Enabling live streaming does not work

### ISSUE THREAD

**Issue by cobaltway** [jitsi/lib-jitsi-meet#1090]
Hello,

I'm trying to enable live streaming using the lib and Jibri.
Code used is the following:
```js
room.sendCommand('jibri', {
  name: 'jibri',
  attributes: {
    action: 'start',
    recording_mode: 'stream',
    streamid: '...', // stream key
    xmlns: 'http://jitsi.org/protocol/jibri'
  }
}
```
No error is thrown but the expected http-bind request does not seem to be done at all.

**Comment by cobaltway** [comment]
Update, found an undocumented method:
```
room.startRecording({
  mode: 'stream',
  streamId: 'wawawa'
});
```

It does the request but get answered:
> <error type="cancel"><not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>

Missing something?

**Comment by fmalbacete** [comment]
Hi @cobaltway  did you have any Luck ?
I'm on the same issue.

Thanks!

**Comment by cobaltway** [comment]
@fmalbacete 

Yes, actually, I think my code was fine. It is related to access configuration on Prosody.

Two solutions : 
- You authenticate your user on your client (using username/password or token directly).
- You change your Prosody configuration so the recorder domain can be accessed by anonymous users.
