### ISSUE TITLE
Failed to load Jitsi API ReferenceError: $ is not defined  

### ISSUE THREAD

**Issue by hengsovandara** [jitsi/lib-jitsi-meet#1113]
Hello everyone, I am newbie to stream server and I have 
here is the script
> <script src="https://meet.jit.si/libs/lib-jitsi-meet.min.js"></script>

> JitsiMeetJS.init(initOptions)

 then 

> JitsiMeetJS.JitsiConnection(null, null, options)

 which options is set 

> const options = {
        hosts: {
          domain: 'beta.meet.jit.si',
          muc: 'conference.beta.meet.jit.si' // FIXME: use XEP-0030
        },
        serviceUrl: '//server.com/http-bin',,
        // The name of client node advertised in XEP-0115 'c' stanza
        clientNode: 'https://beta.meet.jit.si'
      };

and I get the error below. Could anyone tell me please where I misunderstand or errors.

![Screen Shot 2020-04-22 at 6 23 18 PM](https://user-images.githubusercontent.com/27750377/79976289-85b76080-84c6-11ea-8727-ff5a3e71e60b.png)

**Comment by everflux** [comment]
You did not include jquery, therefore `$` is undefined.

**Comment by hengsovandara** [comment]
@everflux thank you every much. I understand how to fix it :).

**Comment by farooqkz** [comment]
Why should be this library dependent on a library such as jQuery when it seems the dependency can be easily removed?

**Comment by saghul** [comment]
> Why should be this library dependent on a library such as jQuery? Can't it be easily removed?

strophe.js, the library we use work dealing with XMPP requires it.
