### ISSUE TITLE
Error disconnecting when serviceUrl includes https://

### ISSUE THREAD

**Issue by nchapman** [jitsi/lib-jitsi-meet#1118]
I was having issues disconnecting from Jitsi Meet during window unload. It turns out when disconnecting, that `https:` is prepended to the `serviceUrl`:

https://github.com/jitsi/lib-jitsi-meet/blob/5e76c1ff05ebd662b466d77db84da4757718fde0/modules/xmpp/XmppConnection.js#L417

Maybe `sendBeacon` doesn't support URLs that start with `//`? Either way it seems like it should check the URL format before prepending `https:`.

**Comment by damencho** [comment]
What do you have in bosh setting? is it // or https:// ?
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L31

**Comment by nchapman** [comment]
Yeah I'm using `https://meet...` for the bosh setting because I'm using the library stand-alone for a custom integration.
