### ISSUE TITLE
iOS 13.x / iPadOS , Safari , the enableNoisyMicDetection: true blocks sending audio/mic

### ISSUE THREAD

**Issue by ibrainventures** [jitsi/lib-jitsi-meet#1126]
Self hosted jitis meet Instance. (ubuntu 19.04 , stable jitsi package)

Trying to optimize the web/safari behaviour.

if the **enableNoisyMicDetection: is set to true,** Safari Client Microphone is
not sending any audio / mic signal  (clients: Chrome, Firefox, (Win10) and Ipad / Iphone peers)

## Possible Solution

workaroung:; with the 

**enableNoisyMicDetection: false** 

setting the audio / mic signal is coming fine

may it depends on the wasm element
(btw, the mimetypes inside nginx actually has no wasm mimtetype)

**Comment by jallamsetty1** [comment]
#1132 - fixed

**Comment by jallamsetty1** [comment]
Fixed as part of #1132

**Comment by ibrainventures** [comment]
Hi @jallamsetty1  👍   thank you very much for this turbo-fast fixing .. 

I am flying now on the unstable ubuntu package path and will test the new behaviour, if any
problem, i will report back inside this git-issue.

Is it okay for the offical ios and android app to work with the unstable path? (deploy for a small usage group - around 30 peers)
