### ISSUE TITLE
Experimental "navigator.permissions" property unsupported on macOS Safari

### ISSUE THREAD

**Issue by Shotster** [jitsi/lib-jitsi-meet#1130]
The [experimental permissions property](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions) of the navigator object is apparently not supported in Safari version 13.1 (15609.1.20.111.8), which results in errors when making calls to `isDevicePermissionGranted()`...

https://github.com/jitsi/lib-jitsi-meet/blob/08d0cd46a8e717009db70b03ddaa8250b221e621/JitsiMediaDevices.js#L149

**Comment by jallamsetty1** [comment]
Fixed as part of #1135
