### ISSUE TITLE
how to support nonstandard display size

### ISSUE THREAD

**Issue by zsinba** [jitsi/lib-jitsi-meet#1139]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
My camera outputs a non-standard size, which is 1280*1024.
But when I put it on the screen, it turns into 1280 * 720, which is a distortion of the display. How can I support this non-standard size display?
## Current behavior
---
The true size of the hardware is 1280*1024, and the display output is 1280*720. The display is distorted

## Expected Behavior
---
According to the size of the input hardware, 1280*1024 is displayed on the screen as 1280*1024, without distortion

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---
Lib-jitsi-meet, called through javascript, custom interface

**Comment by saghul** [comment]
What constraints are you passing when creating local tracks?

**Comment by zsinba** [comment]
At the time of initialization, no explicit restrictions are given.
In the jitsi background, the config configuration file is also unrestricted. All are default values.

**Comment by zsinba** [comment]
any suggest?

**Comment by saghul** [comment]
Try to pass an ideal height constraint of 1024 and see if that works.

**Comment by zsinba** [comment]
it's don't work. 
I can get 1280*720 only.
but the camera is 1280*1024; 

any other suggestions?

thanks very much.

**Comment by zsinba** [comment]
any can help?

thanks
