### ISSUE TITLE
How to obtain network status information

### ISSUE THREAD

**Issue by zsinba** [jitsi/lib-jitsi-meet#1141]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Just like the jitsi-meet, it displays data about the state of the network. Is there an interface to return this data when I go through lib-jist-meet?
![image](https://user-images.githubusercontent.com/890157/80859641-00396a80-8c95-11ea-99bc-56b1a1fa5908.png)

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by zsinba** [comment]
any teacher can help?

**Comment by ashitikov** [comment]
You could use LOCAL_STATS_UPDATED event as well as REMOTE_STATS_UPDATED. Check the docs for more information.

**Comment by zsinba** [comment]
thanks, let's have a try.
