### ISSUE TITLE
Screensharing stopped working on upgrade

### ISSUE THREAD

**Issue by nboullis** [jitsi/lib-jitsi-meet#1144]
## Description
---
About 1 monh ago, I installed jitsi-meet version 1.0.4101-1 (with jitsi-meet-web version 1.0.3729-1) on a Debian server. Screensharing used to work fine on my Debian Stretch 9.12 laptop with Chromium version 1.0.3729-1.

I recently upgraded the server to jitsi-meet-web version 1.0.4025-1. There were some fine improvements, but screensharing stopped working on my laptop. Upgrading again to jitsi-meet-web version 1.0.4074-1 did not help.

Note that screensharing works on the same laptop with Firefox ESR version 68.7.0esr-1~deb9u1. It also works for other users with different OSes with Google Chrome.

## Current behavior
---

When I click the Screensharing icon, nothing happens.
If I open the Console in the Developer tools, I can see two errors logged:

- `[features/base/tracks] Failed to create local tracks`
- `[conference.js] <Object.toggleScreenSharing>:  Failed to switch to screensharing`

both with message `"User canceled Chrome's screen sharing prompt"`

## Expected Behavior
---

Chromium should ask me what screen/application window/Chromium tab I want to share.

## Possible Solution
---

No idea, except downgrading.

## Steps to reproduce
---

Connect to a conference on https://meet.jit.si/, using Chromium on Debian Stretch, and click the Screensharing icon.

# Environment details
---

Debian Stretch 9.12 with Chromium 73.0.3683.75-1~deb9u1

**Comment by sapkra** [comment]
Can you check if this problem still occurs with the latest release?
