### ISSUE TITLE
Problem with Token 

### ISSUE THREAD

**Issue by rafaelpstein** [jitsi/lib-jitsi-meet#1150]
Hi guys,

I'm trying to implement jitsi through token but I'm having a problem.
It looks like something is wrong with the generated token.
Below the prosody log and the settings inserted in jwt.io to generate the token

My logs:

May 06 20:03:44 mod_bosh        info    New BOSH session, assigned it sid 'c18daaa2-57bc-421f-89ef-d5a3869312a0'
May 06 20:03:44 general warn    Error verifying token err:not-allowed, reason:Invalid issuer ('iss' claim)

Jwt

Header
{
  "alg": "HS256",
  "typ": "JWT"
}

Payload
{
  "context": {
    "user": {
      "avatar": "https:/gravatar.com/avatar/abc123",
      "name": "John Doe",
      "email": "jdoe@example.com",
      "id": "test"
    },
    "group": "test"
  },
  "aud": "my hostname",
  "iss": "my_app_id",
  "sub": "myjitsi.xxx.com",
  "room": "*"
}

HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
  --here i put my app-secret ---
)

**Comment by rafaelpstein** [comment]
Sorry, after remove group,id and change my aud and iss the error change.
when i access roomx , i receive loop  error Unforunately, something went wrong 
and prosody log i see

May 06 20:22:56 bosh69a4af8d-4045-4591-8d9b-d8d61a25bdcc        info    BOSH client disconnected: session close
May 06 20:22:57 conference.xxx.yyy.com:muc_domain_mapper     warn    Session filters applied
May 06 20:22:57 mod_bosh        info    New BOSH session, assigned it sid 'b84474bb-4363-4533-a6e2-aa6bb140cd51'
May 06 20:22:57 boshb84474bb-4363-4533-a6e2-aa6bb140cd51        info    Authenticated as f751bd92-8e20-402c-8400-7217ed018b22@xxx.yyy.com
May 06 20:22:58 focus.xxx.yyy.com:component  warn    Component not connected, bouncing error for: <iq to='focus.xxx.yyy.com' xml:lang='en' id='23c40f33-445c-471e-8049-8b93a2ea0b49:sendIQ' from='f751bd92-8e20-402c-8400-7217ed018b22@xxx.yyy.com/dZvArK6m' type='set'>
May 06 20:22:59 focus.xxx.yyy.com:component  warn    Component not connected, bouncing error for: <iq to='focus.xxx.yyy.com' xml:lang='en' id='00b8aba7-e1d0-4379-b47f-bd33405800a2:sendIQ' from='f751bd92-8e20-402c-8400-7217ed018b22@xxx.yyy.com/dZvArK6m' type='set'>
May 06 20:23:01 focus.xxx.yyy.com:component  warn    Component not connected, bouncing error for: <iq to='focus.xxx.yyy.com' xml:lang='en' id='23d9176b-c903-4c05-9d36-7351343825ff:sendIQ' from='f751bd92-8e20-402c-8400-7217ed018b22@xxx.yyy.com/dZvArK6m' type='set'>

**Comment by rafaelpstein** [comment]
Sorry again,   restarted the machine and it worked

**Comment by h0jeZvgoxFepBQ2C** [comment]
So this can be closed?
