### ISSUE TITLE
Pass custom params while user join and get on another side.

### ISSUE THREAD

**Issue by Pinank** [jitsi/lib-jitsi-meet#1153]
I needed to pass some custom params except names to pass. This would be user's details on the platform. I required that on other side as well.

I check all the options but i did not found any helpful link. If anyone is having solution than please help me out. I want details on  **USER_JOIN** event and i have to pass it while joining room (conference).

**Comment by jallamsetty1** [comment]
@Pinank https://community.jitsi.org/ is a better place for these sort of questions, please start a new topic there if you see that it hasn't been discussed before. Please refrain from opening github issues here for seeking information. I will be closing this one.
