### ISSUE TITLE
desktopSharingChromeSources don't change screen sharing options

### ISSUE THREAD

**Issue by IL55** [jitsi/lib-jitsi-meet#1167]
It seems parameter was renamed, or extension doesn't support it anymore?
I tried different combinations: like 
`desktopSharingChromeSources: ["screen", "tab"],`
or `desktopSharingChromeSources: ["tab"],`
And see all share (window, screen tab, audio) options when I try to share desktop.

**Comment by jallamsetty1** [comment]
Yes, this option has been renamed to `desktopSharingSources` since we no longer use chrome extension.

**Comment by fritzgithub** [comment]
I try the same, configuration of the screenshare items, to no avail.
I use both above mentioned options, no effect.

The comments in the current config (taken from a session at https://meet.jit.si/) make it even more confusing:

```
 //deprecated desktop sharing settings, included only because older version of jitsi-meet require them
   desktopSharing: 'ext', // Desktop sharing method. Can be set to 'ext', 'webrtc' or false to disable.
   chromeExtensionId: 'kglhbbefdnlheedjiejgomgmfplipfeb', // Id of desktop streamer Chrome extension
   desktopSharingSources: ['screen', 'window'],
  ...
   //new desktop sharing settings
   desktopSharingChromeExtId: 'kglhbbefdnlheedjiejgomgmfplipfeb', // Id of desktop streamer Chrome extension
   desktopSharingChromeSources: ['screen', 'window', 'tab'],

```
`desktopSharingSources` is labeled deprecated
`desktopSharingChromeSources` is labeled new

When opening the screensharing with this config, then I get all the options: screen, window and tab. 
So `  desktopSharingSources: ['screen', 'window'],` does not seem to work.

**Comment by ankar84** [comment]
> When opening the screensharing with this config, then I get all the options: screen, window and tab.
> So ` desktopSharingSources: ['screen', 'window'],` does not seem to work.

Hey, @jallamsetty1 
Can you comment that issue?
Thanks!

**Comment by jallamsetty1** [comment]
> > When opening the screensharing with this config, then I get all the options: screen, window and tab.
> > So ` desktopSharingSources: ['screen', 'window'],` does not seem to work.
> 
> Hey, @jallamsetty1
> Can you comment that issue?
> Thanks!

Are you seeing this on Electron ? `desktopSharingSources` is only applicable to electron client. There is no way to control what options will be shown on the browser.
