### ISSUE TITLE
Failed to load Jitsi Meet API - Error in lib-jitsi-meet during initJitsiConference (TypeError: Cannot read property ‘substr’)

### ISSUE THREAD

**Issue by samuelpeixoto** [jitsi/lib-jitsi-meet#1170]
I'm trying to use the **Jitsi Meet API** to create Jitsi Meet video conferences with custom GUI.

I’m receiving a `Uncaught TypeError: Cannot read property 'substr' of null` when calling `initJitsiConference()`.

**Characteristics of the system environment:**
* The default Jitsi Meet installation has not been changed;
* I didn't install / configure the Prosody JWT token authentication plugin;
* I am running the test.html application on one domain, example: https://mydomain1.com and Jitsi Meet on other domain, for example: https://meet.myotherdomain2.com

**I get the following error message:**

    Uncaught TypeError: Cannot read property 'substr' of null - JitsiConference.js:276
        at se.resourceCreator (JitsiConference.js:276)
        at A.createRoom (xmpp.js:475)
        at se._init (JitsiConference.js:310)
        at new se (JitsiConference.js:130)
        at c.initJitsiConference (JitsiConnection.js:113)

**Looking at JitsiConference.js on line 276 i see this:**

![image](https://user-images.githubusercontent.com/57121605/82052030-5644df80-9691-11ea-8e9d-3ae4b8f45326.png)

**My API javascript (mydomain.com/test.html) looks like this:**

    <script src="vendor/jquery/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/strophe.js/dist/strophe.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/strophejs-plugin-disco/lib/strophe.disco.js?v=1"></script>
    <script src="https://m101.reuniaofacilws.com.br/libs/lib-jitsi-meet.min.js"></script>
    <script type="text/javascript">
    JitsiMeetJS.init();

    const options = {
    	serviceUrl:'https://meet.jit.si/http-bind',
    	hosts: {
    		domain: 'meet.jit.si',
    		muc: 'conference.meet.jit.si',
    	},
    	bosh: 'https://meet.jit.si/http-bind',
    	useStunTurn: true
    }

    var connection = new JitsiMeetJS.JitsiConnection(null, null, options);

    const confOptions = {
    	openBridgeChannel: true
    }

    room = connection.initJitsiConference("testconference1", confOptions);
    </script>

I tried with other public instances:

* meet.jit.si
* jitsi2.linux.it
* jitsi-1.belnet.be
* jitsi.riot.im
* de-bra-1.jitsi.rocks
* meet.xrv.pt

**And got similar errors:**
![image](https://user-images.githubusercontent.com/57121605/82052287-c5223880-9691-11ea-9b9a-ad557d0e0886.png)

What mistake should I be making?
Thanks in advance for any help! 
_*Excuse me, my English language is weak._

**Comment by samuelpeixoto** [comment]
Complementing the description of the issue...
**Log file (Jicofo.log) I found [WARNING] and [SEVERE]**

    Jicofo 2020-05-15 20:05:23.771 WARNING: [22] org.jitsi.jicofo.FocusManager.log() No dedicated JVB MUC XMPP connection configured - falling back to the default XMPP connection
    ...
    Jicofo 2020-05-15 20:05:24.335 SEVERE: [28] org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getFeatures().144 Failed to discover features for speakerstats.meet.myserver.com: XMPP error reply received from speakerstats.meet.myserver.com: XMPPError: service-unavailable - cancel
    Jicofo 2020-05-15 20:05:24.337 SEVERE: [28] org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getFeatures().144 Failed to discover features for focus.meet.myserver.com: XMPP error reply received from focus.meet.myserver.com: XMPPError: service-unavailable - wait
    Jicofo 2020-05-15 20:05:24.345 SEVERE: [28] org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getFeatures().144 Failed to discover features for conferenceduration.meet.myserver.com: XMPP error reply received from conferenceduration.meet.myserver.com: XMPPError: service-unavailable - cancel
    ...
    Jicofo 2020-05-15 20:05:29.629 WARNING: [40] org.jitsi.jicofo.bridge.BridgeSelector.log() No pub-sub node mapped for jvbbrewery@internal.auth.meet.myserver.com/2671872e-fccb-49e9-866b-28813c831825
    ...
    Jicofo 2020-05-15 20:05:29.651 INFO: [55] org.jitsi.jicofo.bridge.JvbDoctor.log() Scheduled health-check task for: jvbbrewery@internal.auth.meet.myserver.com/2671872e-fccb-49e9-866b-28813c831825
    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/usr/share/jicofo/lib/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
    WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release


**Log file (jvb.log) I found [WARNING]**

    2020-05-15 20:05:24.645 WARNING: [22] Videobridge.start#906: No authorized source regexp configured. Will accept requests from any source.

**Comment by eduardoflorence** [comment]
You need add:
```
<script src="https://cdn.jsdelivr.net/npm/strophe.js/dist/strophe.js"></script>
<script src="https://cdn.jsdelivr.net/npm/strophejs-plugin-disco/lib/strophe.disco.js?v=1"></script>
```
in mydomain.com/test.html

**Comment by samuelpeixoto** [comment]
Hello, @eduardoflorence thanks for your help.
I added the references to the javascripts:
```

<script src="vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/strophe.js/dist/strophe.js"></script>
<script src="https://cdn.jsdelivr.net/npm/strophejs-plugin-disco/lib/strophe.disco.js?v=1"></script>
<script src="https://m101.reuniaofacilws.com.br/libs/lib-jitsi-meet.min.js"></script>

```
**But the problem persists.**
![image](https://user-images.githubusercontent.com/57121605/82125224-e0b53e00-977a-11ea-99d3-400367ec519e.png)

Thanks, I will keep trying

**Comment by eduardoflorence** [comment]
Modify your const options for:

```
const options = {
	serviceUrl: 'https://**beta**.meet.jit.si/http-bind',
	hosts: {
		domain: '**beta**.meet.jit.si',
		muc: 'conference.**beta**.meet.jit.si',
	}
}
```

Obs: bosh is deprecated

**Comment by samuelpeixoto** [comment]
Analyzing more carefully, I concluded that I was not waiting (`addEventListener`) for the CONNECTION_ESTABLISHED event and with some modifications to the code, it seems that everything is working.

**Code with addEventListener:**

    function onConnectionSuccess(){
    	const confOptions = {
    		openBridgeChannel: true
    	}
    	room = connection.initJitsiConference("abcdef", confOptions);
    	room.myUserId();
    	console.log('CONNECTION_ESTABLISHED');
    }

    JitsiMeetJS.init();

    JitsiMeetJS.setLogLevel(JitsiMeetJS.logLevels.ERROR);

    const options = {
    	serviceUrl:'https://<?php echo $domain; ?>/http-bind',
    	hosts: {
    		domain: '<?php echo $domain; ?>',
    		muc: 'conference.<?php echo $domain; ?>',
    	}
    }

    var connection = new JitsiMeetJS.JitsiConnection(null, null, options); 

    connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_ESTABLISHED, onConnectionSuccess);

    connection.connect();

`Thank you all for your time and dedication.`
