### ISSUE TITLE
Conference 'setStartMutedPolicy' method not working:

### ISSUE THREAD

**Issue by Pinank** [jitsi/lib-jitsi-meet#1171]
I am trying to use following methods using conference object but its not giving expected behaviour.

```
const room = connection.initJitsiConference(roomName, confOpts);
room.setStartMutedPolicy({audio: true, video: true});
room.getRole();
room.isModerator();
```

Can anybody help me with this to get out. I want to mute remote users tracks.

**Comment by eduardoflorence** [comment]
It didn't work with me either. What I did then:

```
jitsi.createLocalTracks(optionsTrack).then(this.onLocalTracks);
...
onLocalTracks = async (tracks) => {
    localTracks = tracks;
    ...
    for (let i = 0; i < this.localTracks.length; i++) {
       localTracks[i].mute()
    }
   ...
}
```

**Comment by Pinank** [comment]
@eduardoflorence it should work with your way. What i want is all participant should be joined muted.

**Comment by tiofabby** [comment]
Hi @Pinank 
Were you able to fix such issue?
I am having same concern indeed, room.setStartMutedPolicy({audio: true, video: true}) does not make new participants joining in muted mode..
I am executing such command after having the room created and running.. maybe it works only if room is not running yet?
Thank you
Fabrice

**Comment by vinh-smartdev** [comment]
I also have the same issue, even I set it in jistiConfig before the conference start or via ```setStartMutedPolicy``` function after conference start
