### ISSUE TITLE
Flexible managing of receiving video quality

### ISSUE THREAD

**Issue by bukharin** [jitsi/lib-jitsi-meet#1175]
Hi,

I try to acomplish video quality managing (simulcast enabled) using lib-jitsi-meet. I whould like to specify video quality for specific participants to implement my application video layout logic. In my application users may specify explicitly which participants they whould like to see.

For example, I want setup:

Receive 720p for participant 1
Receive 360p for participants 2 and 3
Receive audio only for all others

Api that I found in lib-jitsi-meet:

`setReceiverVideoConstraint(quality)` - specify video quality for selected participants
`selectParticipants(ids)` - specify participants to receive video in specified quality
`setLastN(n)` - setup max receiving video for last N active participants
`pinParticipant(id)` - force select participant ?

It seems that this API is not low level enough for my case? Or lib-jitsi-meet has an other api to acomplish this?

**Comment by veemex** [comment]
Good question, trying to do the same. Does anyone know how to achieve this ?

**Comment by jallamsetty1** [comment]
Work is under progress on the bridge side for allowing different video constraints to be set per endpoint. Maybe @gpolitis can update here once it is available.

**Comment by gpolitis** [comment]
Thanks @jallamsetty1.

This has been a long standing backend issue https://github.com/jitsi/jitsi-videobridge/issues/147 that is now being addressed in https://github.com/jitsi/jitsi-videobridge/issues/147.

What the above PR does is make it possible for the client to send _video constraints_ messages to the bridge, like this one: ```[{'endpoint_id': XXX, {'ideal_resolution': 720}}]```, on a per endpoint or track basis. These new video constraints effectively replace 4 different messages (setting last-n, setting selected endpoints, setting pinned endpoints and setting the max resolution).

The motivation behind the backend work was somewhat different so the client side work is not planned at this point as far as I know, but it shouldn't be hard to expose the methods in lib-jitsi-meet.

**Comment by bukharin** [comment]
@gpolitis I see that you have merged https://github.com/jitsi/jitsi-videobridge/pull/1250 but it seems that you doesn't expose this API, right?

**Comment by veemex** [comment]
IS this done/finished ? Thanks !

**Comment by jienco** [comment]
I just found this could solve the problem I just described in this Jitsi community post https://community.jitsi.org/t/being-able-to-select-remote-participants-for-high-res-and-participants-for-setlastn-separately/72792

I am looking forward for this feature. Is there any plan for implementation on lib-jitsi-meet? Thank you very much

**Comment by rn-1984** [comment]
Hi all,
 Jumping in on this issue as well. Has there been any progress with this in the past 4 months? 

We would really like to set our video experience of Jitsi fantastic. 

Is there an option to set the minimum video quality to unselected participants? 

And also,  does anyone know how we can stop participants from broadcasting 180p? I'd like to have Simulcast work with only two stream or even better process only one stream which changes according to JVB signaling. 

I.E. have  the JVB tell the endpoint send out just 720p or just 360p the lowest. 

Thanks @jallamsetty1 @gpolitis

**Comment by veemex** [comment]
@jienco . Your commits are great, when do you think this will be merged to lib-jitsi-meet ? Is this working locally for you ? Thanks !

**Comment by jienco** [comment]
Thanks @veemex ! I was able to confirm that the messages were sent to the video bridge, but then I found the issue that I reported here: jitsi/jitsi-videobridge#1458, fixing that would be needed for those messages to take effect

**Comment by jienco** [comment]
I think this issue can be now closed after the new implementation of `setReceiverConstraints` 

https://github.com/jitsi/handbook/commit/c22ec0392c2835cc989ef085e98de89c940e28ed

https://github.com/jitsi/lib-jitsi-meet/commit/d1505231a5fd20eb7b7579bdaa203917d209a5e2

Thank you very much Jitsi Dev Team!
