### ISSUE TITLE
did room.meetingId disappear?

### ISSUE THREAD

**Issue by davidroberthoare** [jitsi/lib-jitsi-meet#1176]
## Description
I’m using lib-jitsi-meet on a custom install. I had been using room.meetingId to successfully log unique conversation IDs to our server, but after an update yesterday that now seems to no longer be an available parameter…?

## previous behavior
conference.room.meetingId used to get a unique ID for each conversation-session (ie. not per-user, but per-session, so user1, 2 and 3 in a conversation will all have the same sessionID)

## Current behavior
parameter does not seem to exist...

## Expected Behavior
looking for some way to identify a 'conference session' of a particular room.

# Environment details
updated 2 days ago on ubuntu18 to most recent jitsi via apt install jisti-meet

**Comment by damencho** [comment]
That is being set by this module: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_meeting_id.lua
Maybe turn on debug on your prosody and see whether you see this printed: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_meeting_id.lua#L18
