### ISSUE TITLE
Add official options for higher-quality audio

### ISSUE THREAD

**Issue by marc-fouquet** [jitsi/lib-jitsi-meet#1179]
For use-cases like piano-lessons via Internet or anything else involving music/musicians, there should be options for the server admin to choose a higher audio bitrate.

Currently there is an undocumented option "stereo" which does not add stereo capability, but at least raises the audio bitrate from something like 40 to 70 kBit/s. There are also options to disable various aspects of audio processing, which is also helpful.

Being the admin, I would like to decide for my server that audio bandwidth is not an issue and transmit "CD-quality" audio (i.e. 44.1kHz, 16 Bit, Stereo, >128 kBit/s Opus).

**Comment by mark-orion** [comment]
Two thumbs up for this. All audio/opus related options should be available in the advanced audio settings menu of the jitsi-meet web ui.

**Comment by saibotma** [comment]
According to https://github.com/jitsi/jitsi-meet/blob/df6eff880485a0b2c56e37c7639bd3212c641ac9/config.js it is now possible to set `opusMaxAverageBitrate` (also via a config query parameter).

**Comment by saghul** [comment]
Oops, forgot to close this one. Indeed we have implemented those options.
