### ISSUE TITLE
Sometimes get error "Bridge Channel send: no opened channel"

### ISSUE THREAD

**Issue by nikitaodnorob** [jitsi/lib-jitsi-meet#1183]
Hello! My code of connection sometimes works but sometimes I get error "Bridge Channel send: no opened channel". What could be the reason? My options of connection and conference:
```js
const connectionOptions = {
    hosts: {
        domain: 'meet.jit.si',
        muc: 'conference.meet.jit.si',
        focus: 'focus.meet.jit.si',
    },
    serviceUrl: 'https://meet.jit.si/http-bind?room=' + roomName,
    clientNode: 'http://jitsi.org/jitsimeet',
    useStunTurn: true
};

const conferenceOptions = {
    openBridgeChannel: true
};
```

If I open `about:webrtc`, there will be some connections with `ICE State = failed` and 3 connections with `ICE State = success`

# Environment details
Firefox 76

**Comment by nikitaodnorob** [comment]
I want to complement the issue.

I created a client for voice chatting. Connection params was specified in the issue

Then `user1` create jitsi room and `user2` enter it. There are three options:
1. The RTC datachannel is creating successfully and fast, and text chatting (using `sendEndpointMessage`) is available instantly. It's excellent!
2. The RTC datachannel is creating successfully after few fail attempts (there are 1-2 errors `<_send>:  Bridge Channel send: no opened channel`). Text chatting still is working, it's OK
3. The RTC datachennel is creating successfully after many fail attempts (there are 3 or more errors `<_send>:  Bridge Channel send: no opened channel`). Text chatting NOT working already. Clients get event `rtc.data_channel_open` and `room.rtc._channel.isOpen() === true`, but when `user1` send messages, `user2` don't get them (same in reverse order)

I don't understand, why in last case messages don't receive via datachannel if the datachannel was opened successfully. For example, I have log:
```
2020-07-22T10:57:26.371Z [modules\RTC\BridgeChannel.js] <_send>:  Bridge Channel send: no opened channel.
2020-07-22T10:57:26.383Z [modules\RTC\BridgeChannel.js] <_send>:  Bridge Channel send: no opened channel.
2020-07-22T10:57:36.370Z [modules\RTC\BridgeChannel.js] <_send>:  Bridge Channel send: no opened channel.
2020-07-22T10:57:36.384Z [modules\RTC\BridgeChannel.js] <_send>:  Bridge Channel send: no opened channel.
2020-07-22T10:57:36.630Z [modules\RTC\BridgeChannel.js] <_send>:  Bridge Channel send: no opened channel.
datachannel opened // got event 'rtc.data_channel_open'
true // result of room.rtc._channel.isOpen()
```
But clients don't receive messages from another

Maybe I have to recreate datachannel after many failed attempts?

**Comment by AymericG** [comment]
If you enable tracing:

`JitsiMeetJS.setLogLevel(JitsiMeetJS.logLevels.TRACE)`

Do you see this warning? 

`"Failed to send E2E ping request or response"`

If so, try to disable e2eping:

`e2eping: { pingInterval: -1 }`

(Doesn't work for me though)

**Comment by nikitaodnorob** [comment]
@AymericG it will not work because bridge channels were removed from Jitsi Meet. Now I should use `openBridgeChannel: 'websocket'`

**Comment by sahin52** [comment]
But if bridge channels were removed, why do I get this error? We are using a proxy, and proxy does not support every connection. What could be the reason behind?
