### ISSUE TITLE
Creation of a custom UI

### ISSUE THREAD

**Issue by ReveredMachine** [jitsi/lib-jitsi-meet#1194]
I followed this example in order to create a custom UI https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example and I also checked this guide https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md#installation.

The javascript library was created by just checking out this repository and issuing
```
npm install
```

I checked the prosody log and saw that the user has successfully joined the room, but currently the creation of the local tracks is failing.

```
JitsiMeetJS.createLocalTracks({ devices: [ 'audio', 'video' ] })
    .then(onLocalTracks)
    .catch(error => {
        throw error;
    });
```

With the following error (taken from the firefox console):
```
2020-05-28T19:29:28.763Z [modules\RTC\RTCUtils.js] <newObtainAudioAndVideoPermissions>:  Using the new gUM flow lib-jitsi-meet.min.js:20:26369
2020-05-28T19:29:28.763Z [modules\RTC\RTCUtils.js] <newObtainAudioAndVideoPermissions/i<>:  Got media constraints:  
Object { video: {…}, audio: {…} }
lib-jitsi-meet.min.js:20:26369
2020-05-28T19:29:28.798Z [modules\RTC\RTCUtils.js] <init/<>:  Available devices:  
Array [ MediaDeviceInfo ]
lib-jitsi-meet.min.js:20:26369
2020-05-28T19:29:28.800Z [modules\RTC\RTCUtils.js] <_newGetUserMediaWithConstraints/</<>:  Failed to get access to local media.  NotFoundError: The object can not be found here. [object Object] lib-jitsi-meet.min.js:20:26369
uncaught exception: Object
```

I also tried chrome, but got the same problem.

What could be the reason for this error ?

**Comment by Pinank** [comment]
@ReveredMachine You need to pass some extra configs.

Try following:

```
{
    devices: [ 'audio', 'video' ],
    resolution: 1280,
    minFps: 30,
    maxFps: 60,
    constraints: {
            video: {
            aspectRatio: 16 / 9,
            height: { ideal: 720, max: 720, min: 460 },
            width: { ideal: 1280, max: 1280, min: 800 }
        }
}
}

OR

{
    devices: [ 'audio', 'video' ],
    resolution: 1280,
    minFps: 30,
    maxFps: 60
}
```


this configs varies browser wise

**Comment by sapkra** [comment]
@ReveredMachine Were you able to fix it? If it is still a problem, please comment again.
