### ISSUE TITLE
Just playing

### ISSUE THREAD

**Issue by roberto497** [jitsi/lib-jitsi-meet#1196]
I need an example of just playing, without sharing the audio and audio, only the creator of the room would have their audio and video shared, the other participants will just watch

**Comment by sapkra** [comment]
There are several solutions like streaming to YouTube using jibri but it should also be possible to start a room with audio and video muted and then only the moderator can unmute itself. I'm sure you will find a proper solution in the [community forum](https://community.jitsi.org/).
