### ISSUE TITLE
third participant video is blur

### ISSUE THREAD

**Issue by ThanakornNG** [jitsi/lib-jitsi-meet#1199]
when third participant join the room remote video track had a bad quality

how can i improve quality of third participant video  im try using setSenderVideoConstraints(1080) and setReceiverVideoConstraints(1080) on every client side but it seem nothing change, im testing it on network with 100mbps up/down

**Comment by jallamsetty1** [comment]
What browser are you seeing this on ? Can you check if the receive resolution on the remote participant is < 720p ? If you are seeing this on chrome, it means that the media is now routed through the bridge and the bridge thinks that your clients do not have enough downlink b/w to send the full 720p (or 1080p if you changed your video constraints in config.js to 1080).

**Comment by ThanakornNG** [comment]
how can i check remote receive resolution?, all my client are using network with 100mbps up/down i think it has enough bandwidth to send >720p video

**Comment by ThanakornNG** [comment]
i'm already fix it by collect all participant in to array and using selectparticipants instead of selectparticipant
ex. selectparticipants(array)
