### ISSUE TITLE
JWT token and room claim

### ISSUE THREAD

**Issue by Noext** [jitsi/lib-jitsi-meet#1200]
## Description

any one with a jwt token can create a room even if the token has a room claim

## Current behavior

only people with token in url can create room

given this payload on the token

`  "exp": 1591197032,
  "iat": 1591186232,
  "room": "ROOM_1",
  "aud": "my_jitsi_app_id",
  "iss": "my_jitsi_app_id",
  "sub": "DOMAIN"
}`

this token should be only allowed to create the room "ROOM_1" but if you go to domain/ROOM_2  there is no verification and the owner of this token can create the ROOM_2 and he will be admin on this room

## Expected Behavior

the previous token should not be allowed to open ROOM_2 even less be admin in this room.

## Possible Solution

verify the room claim in the token before openning a room and give the admin right.

## Steps to reproduce

follow the readme and create a jwt with a room claim

# Environment details
 
last version

**Comment by damencho** [comment]
Have you enabled token verification for that muc component? 
https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_token_verification.lua

**Comment by Noext** [comment]
> Have you enabled token verification for that muc component?
> https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_token_verification.lua

yes
`Component "DOMAIN" "muc"
    storage = "memory"
    muc_tombstones = false
    restrict_room_creation = "local"
    modules_enabled = {
       "token_verification";
    }
`

**Comment by damencho** [comment]
Do you have allow_empty_token = true?

**Comment by Noext** [comment]
> Do you have allow_empty_token = true?

Yes because i need to allow Anonymous user to join already created room without token

**Comment by damencho** [comment]
Can you show your full prosody config, masking the sensitive data?

**Comment by Noext** [comment]
> Can you show your full prosody config, masking the sensitive data?

here is my full prosody config : https://pastebin.com/z6fMPW1P

**Comment by damencho** [comment]
Interestingly, I cannot repro. What about jicofo config, what do you have there?

**Comment by Noext** [comment]
> Interestingly, I cannot repro. What about jicofo config, what do you have there?

here is my sip-communicator.properties https://pastebin.com/vnKgwhFF

currently for me i can repro this behavior every time , i simple generate a jwt token on my backend with a "ROOM_1" claim , with this token i can create the ROOM_1, and after creating the ROOM_1 i can  go to domain.org/room_2  without token in url and room_2 will be created , and if i try to create room_3 with the token in the url i'm redirected to the authError page.

currently the check work when someone has the token in the url ( cant create room_3 with a token in the url that has claim on room_1 ) but if someone has created a room he can create many room witout giving a token in the url

**Comment by damencho** [comment]
There is org.jitsi.jicofo.auth.URL=EXT_JWT:jitsi-meet.example.com 
I'm not sure about the value it brings at the moment and need to check it, but it should work and without it ...

**Comment by Noext** [comment]
> There is org.jitsi.jicofo.auth.URL=EXT_JWT:jitsi-meet.example.com
> I'm not sure about the value it brings at the moment and need to check it, but it should work and without it ...

very thx, i have put the EXT_JWT:jitsi version , and it is working like expected
