### ISSUE TITLE
ERROR TypeError: "i.Strophe.getNodeFromJid(...) is null"

### ISSUE THREAD

**Issue by hrueger** [jitsi/lib-jitsi-meet#1204]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I try to make `lib-jitsi-meet` work in my Angular project.
I copied the code from [here](https://gist.github.com/drew-thompson/4d93be95a82d054924dad311ed1e26fe) and modified it slightly, see here: https://gist.github.com/hrueger/a992592054d74a603ff90d84ce1b1473

I get the following error: 
```
ERROR TypeError: "i.Strophe.getNodeFromJid(...) is null"
    resourceCreator lib-jitsi-meet.min.js:2437
    createRoom lib-jitsi-meet.min.js:2428
    _init lib-jitsi-meet.min.js:2437
    se lib-jitsi-meet.min.js:2437
    initJitsiConference lib-jitsi-meet.min.js:2437
    ngOnInit home.component.ts:58
    ...
```

## Current behavior
It throws the error above.

## Expected Behavior
It doesn't throw an error.

## Possible Solution
???

## Steps to reproduce
See the code above, it should also run without angular, if you call the `ngOnInit()` method.

# Environment details
I copied the `lib-jitsi-meet.min.js` file from [here](https://meet.jit.si/libs/lib-jitsi-meet.min.js) to `_libs/lib-jitsi-meet.min.js` in my project, so that I can import it (see my gist above).

**Comment by hrueger** [comment]
Exactly the same error happens when I use the code from here: https://github.com/jitsi/lib-jitsi-meet/issues/1083#issue-598247524

**Comment by TessyPowder** [comment]
Any updates ? Semms like this should work

**Comment by hrueger** [comment]
Sorry to do another ping here but this is really preventing us from using this library

**Comment by sapkra** [comment]
Some were mentioning that two dependencies are missing using the hosted file: https://github.com/jitsi/lib-jitsi-meet/issues/1206
Can you try if adding these solves your problem?

**Comment by hrueger** [comment]
@sapkra Thanks for your answer, however, it still doesn't work, I get the same error message.
I also tried using your package, but I couldn't import it:
![grafik](https://user-images.githubusercontent.com/18656830/95228019-1a0c4a00-07ff-11eb-97e6-e55fff3491c7.png)
```TypeScript
import * as JitsiMeetJS from "@lyno/lib-jitsi-meet";
```
It worked using
```TypeScript
const JitsiMeetJS = (require as any)("@lyno/lib-jitsi-meet");
```
but that doesn't give me types. Anyway, I get the same error message.

Is your project OpenSource? And are you using the `meet.jit.si` servers?

**Comment by sapkra** [comment]
Ok, it was worth a try. The types are not completely working because they are autogenerated. I'm importing some types directly like `JitsiRemoteTrack` to make at least my implementation a little bit more type safe.

```typescript
import JitsiMeetJS from '@lyno/lib-jitsi-meet';
import JitsiRemoteTrack from '@lyno/lib-jitsi-meet/modules/RTC/JitsiRemoteTrack';
```
My project is currently closed source and I'm using the docker setup.

**Comment by hrueger** [comment]
I don't have any problems using a self hosted instance so it seems like this is a problem with the `meet.jit.si` instance.

**Comment by DarkTrick** [comment]
I had the same error message. And if I'm not mistaken you're doing the same mistake as me.

You do ( https://gist.github.com/hrueger/a992592054d74a603ff90d84ce1b1473#file-home-component-ts-L55 )
```
this.connection = this.createConnection(this.options);
...
this.room = this.connection.initJitsiConference("aseifnlasiylidwueiawjdlxiawhuawhakduyh", this.confOptions);
```

However, you can only call `initJitsiConference` after the `CONNECTION_ESTABLISHED` event.

This is the structure you need:
```
JitsiMeetJS.init(jitsiInitOptions);
// equivalent to your `createConnection`
connection = new JitsiMeetJS.JitsiConnection(null, null, jitsiConnectionOptions);

// calling this now would produce an error, so don't call it
// conference = connection.initJitsiConference('testconference', conferenceOptions);

// *****HERE IS THE IMPORTANT PART*****
connection.addEventListener(
  JitsiMeetJS.events.connection.CONNECTION_ESTABLISHED,
  function () {
    // call initJitsiConference only AFTER the connection was established.
    conference = connection.initJitsiConference('testconference', conferenceOptions);

    // The rest of your code
   }
);

```

**Comment by hrueger** [comment]
@DarkTrick Thank's so much! Now it's working.
