### ISSUE TITLE
Missing strophe-plugins (disco and caps plugins are required)!

### ISSUE THREAD

**Issue by MadonnaEssam** [jitsi/lib-jitsi-meet#1206]
I face with this error " Missing strophe-plugins (disco and caps plugins are required)!" , I imported this line

`import JitsiMeetJS from ‘lib-jitsi-meet’
`
inside package.json
`“lib-jitsi-meet”: “^1.0.6”,
`
i added this line.

and lastly:

inside index.html i added all these lines:

```
<script src="lib-jitsi-meet/libs/strophe/strophe.js"></script>
<script src="lib-jitsi-meet/libs/strophe/strophe.disco.min.js?v=1"></script>
<script src="https://meet.jit.si/libs/lib-jitsi-meet.min.js">
```

**Comment by kik-doctor** [comment]
Here is the same issue.

**Comment by sahil-nagpal1** [comment]
Same error

**Comment by solarkraft** [comment]
This keeps popping up since I switched from Webpack to Vite.

**Comment by saghul** [comment]
Our bundle includes both. If you made your own build then you'll need to take care of it yourself...

**Comment by solarkraft** [comment]
FWIW, using solyd's version, I managed to get it working by including `import "strophejs-plugin-disco/src/strophe.disco"`. The plugin appears to be built in a way in which it will run when bundled with Webpack, but not with Vite.

**Comment by vh-machado** [comment]
> FWIW, using solyd's version, I managed to get it working by including `import "strophejs-plugin-disco/src/strophe.disco"`. The plugin appears to be built in a way in which it will run when bundled with Webpack, but not with Vite. Letting Vite compile it lets it go through fine.

Where did you import?

**Comment by saghul** [comment]
Closing since our bundle already includes them.

**Comment by vikaschouhan97** [comment]
> > FWIW, using solyd's version, I managed to get it working by including `import "strophejs-plugin-disco/src/strophe.disco"`. The plugin appears to be built in a way in which it will run when bundled with Webpack, but not with Vite. Letting Vite compile it lets it go through fine.
> 
> Where did you import?



> FWIW, using solyd's version, I managed to get it working by including `import "strophejs-plugin-disco/src/strophe.disco"`. The plugin appears to be built in a way in which it will run when bundled with Webpack, but not with Vite. Letting Vite compile it lets it go through fine.

Hey, I'm also facing same issue can you tell me where did you import this ? I tried on app.tsx but it's not working.

**Comment by solarkraft** [comment]
I'm using vanilla JS and importing strophe in my helper class's file. 
It can apparently be imported after lib-jitsi-meet, but it has to be imported before it is instantiated. 
That's what works for me.
