### ISSUE TITLE
[feature] Developing lib-jitsti-meet as an NPM package

### ISSUE THREAD

**Issue by Payetus** [jitsi/lib-jitsi-meet#1220]
Adding lib-jitsti-meet as a library source is complex. https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web

Most of this do not work properly. It would be grate  to be able to use the library in a project as follows:
```
import JitsiMeetJS from '@jitsti/lib-jitsti-meet'

JitsiMeetJS.init(initOptions);
```

**Comment by saghul** [comment]
See https://github.com/jitsi/lib-jitsi-meet/pull/1026

**Comment by Payetus** [comment]
Although #1026 creates a npm package itmakes no mention about hinting. If you take for example https://www.npmjs.com/package/@lyno/lib-jitsi-meet the package generates a minified JS wich you can import but offer no type IDE help, while if you import from source you can import the types from the generates jsDocs
