### ISSUE TITLE
Possibility of changing value for channelLastN after conference was initialized

### ISSUE THREAD

**Issue by jienco** [jitsi/lib-jitsi-meet#1250]
Hello, first of all thank you very much for this amazing library.

Currently, as far as I know, it is only possible to set the value of channelLastN [when we initialize the conference](https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiConnection.js#L112).

According to [this issue in jitsi-videobridge](https://github.com/jitsi/jitsi-videobridge/issues/577), it seems that it would be possible to alter that value during usage of the conference (after initialization). The use case would be similar to what is mentioned in that issue, where based on the participants that are visible, the amount of video tracks received by the client could be adjusted in order to reduce bandwidth/CPU usage.

Would it be possible to add this feature to lib-jitsi-meet? Thanks very much for considering.

**Comment by jienco** [comment]
By looking more into the code I found this method [JitsiConference->setLastN](https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiConference.js#L1309) that seems would fit the need I describe. Could someone confirm if it is ok to call this method after the conference was initialized, so that it takes effect dynamically?

**Comment by damencho** [comment]
Yep, you can use that after conference had started. This is how audio-only mode works, setting lastN to 0.

Please, use the community forum for questions or problems before opening new issues.

**Comment by jienco** [comment]
@damencho Thank you for the quick answer. I apologize, next time will post in the community forum.
