### ISSUE TITLE
How can I implement JITSI in my react app?

### ISSUE THREAD

**Issue by qasimfida** [jitsi/lib-jitsi-meet#1252]

**Comment by saghul** [comment]
Please stop opening duplicates. Your question was answered.

**Comment by qasimfida** [comment]
> Please stop opening duplicates. Your question was answered.

I did not get the answer properly

**Comment by denen99** [comment]
where is this answered?   Sharing a generic JS snippet does not help for react integration.  the JS API requires Strophe and Strophe Disco and the exposure of those global variables is actually a big complex.
