### ISSUE TITLE
If participant video is mute - No video tracks on remote user end

### ISSUE THREAD

**Issue by paritoshcodertc** [jitsi/lib-jitsi-meet#1254]
if new user connects with video mute, then other participants can't see his video tracks. There are only audio tracks available.

**Comment by ashitikov** [comment]
That's right. What do you expect instead of this behavior, that on remote side will be video track but muted? 
Just do not rely on it. Think it as no video track = video track muted. I see no problem here.

**Comment by sapkra** [comment]
I can't see any problem either.
