### ISSUE TITLE
Remote users are not receiving some messages 

### ISSUE THREAD

**Issue by Razvan-Stafan** [jitsi/lib-jitsi-meet#1269]
Hi guys!  
I'm trying to create a video clint using lib-jitsi-meet in my Angular app.

## Description
I have a problem when I'm removing local tracks in Firefox.  
At the beginning I create the local tracks. Everybody who joined the room is receiving the tracks that are added to the room.  
At a moment I decide to remove my local tracks (in Firefox) whithout leaving the room, the other participants in room are not receiving `JitsiMeetJS.events.conference.TRACK_REMOVED`. It seems that nothing is send on the network (I don't see any call to the server when I remove a track but I see it when I add one)
It seems that  when I'm leaving the room, there are no issue  

If I create my local tracks in Chrome I don't have any problem, everybody who joined is receiving `JitsiMeetJS.events.conference.TRACK_REMOVED`

## Current behavior

In Firefox, we are not receiving some messages like  `JitsiMeetJS.events.conference.TRACK_REMOVED`

## Expected Behavior

The behaviour in Firefox should be the same as Chrome

## Steps to reproduce

base.ts
```ts
constructor() {
	private connection: any;
	private room: any;

	const initOptions = {
			disableAudioLevels: true
		};
	const options = {
		serviceUrl: 'https://beta.meet.jit.si/http-bind',
		hosts: {
			domain: "beta.meet.jit.si",
			muc: "conference.beta.meet.jit.si",
		},
	};

	JitsiMeetJS.init(initOptions);
	JitsiMeetJS.setLogLevel(JitsiMeetJS.logLevels.ERROR);
	this.connection = new JitsiMeetJS.JitsiConnection(null, null, options);
	this.setConnectionListeners(this.connection);
}

private setConnectionListeners(connection: any): void {
	connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_ESTABLISHED, this.onConnectionSuccess.bind(this));
	connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_FAILED, this.onConnectionFailed.bind(this));
	connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_DISCONNECTED, this.onConnectionDisconnected.bind(this));
	connection.connect();
}

private setRoomListeners(room: any) {
	room.on(JitsiMeetJS.events.conference.TRACK_ADDED, this.onTrackAdded.bind(this));
	room.on(JitsiMeetJS.events.conference.TRACK_REMOVED, this.onTrackRemoved.bind(this));
	room.on(JitsiMeetJS.events.conference.CONFERENCE_JOINED, this.onConferenceJoined.bind(this));
	room.on(JitsiMeetJS.events.conference.USER_JOINED, this.userJoined.bind(this));
	room.on(JitsiMeetJS.events.conference.USER_LEFT, this.onUserLeft.bind(this));
}

private onConnectionSuccess(): void {
	const confOptions = {
		openBridgeChannel: true
	};

	this.room = this.connection.initJitsiConference('conference', confOptions);
	this.setRoomListeners(this.room);
	this.room.join();
}

private onConferenceJoined(): void {
	console.log("joined");
	JitsiMeetJS.createLocalTracks({ devices: ['audio', 'video'] }).then(this.onLocalTracks.bind(this));
}

private onLocalTracks(tracks: any): void {
	tracks.forEach((track: any) => {
		this.room.addTrack(track);
	});
}

private onTrackAdded(track: any): void {
	console.log(TRACK Added", track)
}

//This function is called when we click on a button in html
public stopLocalTracks(): void {
	this.room.getLocalTracks().forEach((track: any) => {
		this.room.removeTrack(track);
		track.dispose();
	});
}
```

# Environment details
OS: Windows 10  
Browser: Firefox 78

**Comment by sapkra** [comment]
Can you test it again with the latest release please? There have been some changes/refactorings in the past month.

**Comment by Razvan-Stafan** [comment]
I have tested right now with the last version of master, but I have the same problem. When I dispose the tracks from Firefox, I don't receive `JitsiMeetJS.events.conference.TRACK_REMOVED`. The tracks are not deleted so anybody who joins the conference will try to get the disposed tracks.

**Comment by samuelsimoes** [comment]
Can confirm that it still happening. I am trying to find where it is failing on the code.

**Comment by jallamsetty1** [comment]
Closing this issue as this has been fixed in the tip.
