### ISSUE TITLE
"Checkout the examples" link in README.md does not link to examples

### ISSUE THREAD

**Issue by amagee** [jitsi/lib-jitsi-meet#1272]
I'm not certain where it should link to, perhaps here: https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example ?

**Comment by norlowska** [comment]
Actually, this link is under the "Installation" heading and it is linking to `lib-jitsi-meet` installation "guide". In this context, I think the destination is correct, maybe the text is not intuitive.
Ideally, there should be links to both (installation and example).
