### ISSUE TITLE
Honor videoQuality.maxBitratesVideo setting when simulcast is disabled

### ISSUE THREAD

**Issue by jienco** [jitsi/lib-jitsi-meet#1280]
## Description
The recently added functionality to configure the bitrates through the videoQuality setting is amazing (https://github.com/jitsi/lib-jitsi-meet/commit/f74cd0abe9c696a9c3ca7dbb9ca170e6e84d6756). Thank you so much for adding that. We are testing that for non-simulcast, so that clients send only one quality, to reduce bandwidth and CPU usage. Also we are testing with H264 in our case.

## Current behavior
When disabling simulcast, instead of honoring the maxBitrate value passed in the configuration, it is using the hardcoded HD_BITRATE (2500 Kbps).

## Expected Behavior
As a consumer of this library, I would like the maxBitrate to be honored even when I disable simulcast.

## Possible Solution
In TraceablePeerConnection->setMaxBitrate, remove the check `this.isSimulcastOn()` so that it always uses `this.tpcUtils.simulcastEncodings[encoding].maxBitrate` (https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/TraceablePeerConnection.js#L2055).

I tested it and it works well. I am willing to submit a PR if this change would be accepted.

## Steps to reproduce
Use the following settings in your config. In this case we want to achieve 1Mbps video, with just one level (non-simulcast):

```
    disableSimulcast: true,
    preferH264: true,
    disableH264: false,
    videoQuality: {
      maxBitratesVideo: {
        low: 1000000,
        standard: 1000000,
        high: 1000000,
      },
    },
```

# Environment details
Custom UI using lib-jitsi-meet, own hosted jitsi servers.

**Comment by jallamsetty1** [comment]
Hey there, setting the bitrate to HD_BITRATE for non-simulcast case was intentional. If we want this to be configurable, then we need to introduce another key-value pair in maxBitratesVideo since there will be only one encoding and low value will get picked for Firefox and the high value will get picked for non-Firefox users if low/high values happen to be different (which is not your case so its working fine for you).

**Comment by jienco** [comment]
Thank you very much @jallamsetty1 for your quick answer and very helpful explanation. After some testing we went back to VP8 simulcast in the end it was a better experience for us than H264 one quality.

I am closing the issue since the way was implemented was intentional. In the future if we or someone needs it I can submit a PR to add this extra option as you mentioned. Thank you very much.
