### ISSUE TITLE
Too many logs when connected

### ISSUE THREAD

**Issue by huzaifaaak** [jitsi/lib-jitsi-meet#1283]
## Description
I am creating RN app. As soon as I do **connection.connect()**. It starts logging too much output on the debugger. I have tried connecting it with conference and that works fine.

## Current behavior
Logs keep on printing in the debug screen
<img width="978" alt="Screenshot 2020-08-12 at 8 45 58 pm" src="https://user-images.githubusercontent.com/52660166/90037429-a3127380-dcdd-11ea-9928-5fec43d250c2.png">

<img width="1093" alt="Screenshot 2020-08-12 at 8 45 50 pm" src="https://user-images.githubusercontent.com/52660166/90037451-aa398180-dcdd-11ea-9a79-5956951f37e7.png">

## Expected Behavior
Only necessary logs should print when the error occurs. Since, logs keep coming at high speed It is hard for me to debug stuff. It eats up memory too.

**Code**

 ```
const room = 'noonecanjointhis';
      const getConfig = await createConfig(room);
      JitsiMeetJS.init({
        enableAnalyticsLogging: false,
        ...getConfig.config,
      });
      const options = _constructOptions(
        getConfig.config,
        getConfig.locationURL,
        room,
      );
      const connection = new JitsiMeetJS.JitsiConnection(null, null, options);
      console.log('options passed', options);
      connection[JITSI_CONNECTION_URL_KEY] = getConfig.locationURL;

      connection.addEventListener(
        JitsiConnectionEvents.CONNECTION_DISCONNECTED,
        _onConnectionDisconnected,
      );
      connection.addEventListener(
        JitsiConnectionEvents.CONNECTION_ESTABLISHED,
        _onConnectionEstablished,
      );
      connection.addEventListener(
        JitsiConnectionEvents.CONNECTION_FAILED,
        _onConnectionFailed,
      );
      connection.connect({
        id,
        password,
      });
```

# Environment details
RN: 0.63.2
Node: v10.16.1
Env: IOS

**Comment by saghul** [comment]
You can set the log level to warning or error if you want less verbose logging: https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md
