### ISSUE TITLE
Documentation cosmetic update for lib-jitsi-meet

### ISSUE THREAD

**Issue by yashodhanmohan** [jitsi/lib-jitsi-meet#1294]
I've added a documentation overhaul update for lib-jitsi-meet in the Handbook. Please let me know if it can be added here as well.

The PR is here - https://github.com/jitsi/handbook/pull/83

This is how it is supposed to look in the handbook after the PR is merged -
<img width="1791" alt="Screenshot 2020-08-18 at 12 49 56 PM" src="https://user-images.githubusercontent.com/6680427/90482844-79c86c00-e151-11ea-8d1d-ef3292fdcd6b.png">
<img width="1792" alt="Screenshot 2020-08-18 at 12 50 07 PM" src="https://user-images.githubusercontent.com/6680427/90482852-7cc35c80-e151-11ea-9edc-9f4c47f2e2a3.png">

**Comment by sapkra** [comment]
I would say just create a PR and wait for feedback.

**Comment by Ryoma-Liu** [comment]
how to customize the css style of jitsi meeting?
