### ISSUE TITLE
Permission denied on hangup

### ISSUE THREAD

**Issue by devfelipereis** [jitsi/lib-jitsi-meet#1308]
I have an app running um localhost and everything was working fine...
Today I started again to test some stuff and the hangup button is not working properly.

I get permission denied for this route:

https://web-cdn.jitsi.net/meetjitsi_4370.993/libs/close3.min.js

and my readyToClose event will not fire.

Anyone having this?

**Comment by damencho** [comment]
Please when you have problems or questions use the community forum before opening new issues.

This is not a lib-jitsi-meet issue.
