### ISSUE TITLE
Remove the Join meeting button

### ISSUE THREAD

**Issue by DavidLozzi** [jitsi/lib-jitsi-meet#1310]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Previously, when someone connected to my page they were instantly added to the meeting. Now we get the Join Meeting button. Can I override the behavior and let them right in?

## Current behavior
---
users are prompted with a Join meeting button

## Expected Behavior
---
users enter the meeting without having to click again

## Possible Solution
---
make it go away

## Steps to reproduce
---
just load up the app

# Environment details
---
```
  <script src="https://meet.jit.si/libs/lib-jitsi-meet.min.js"></script>

...

const newOptions = Object.assign(options,
      {
        roomName: `${brand.title} - ${options.roomTitle}`,
        userInfo: {
          userId: user.userId,
          displayName: user.name
        },
        generateRoom: false,
        enableCalendarIntegration: false,
        prejoinPageEnabled: false,
        gatherStats: false,
        parentNode: document.getElementById('play-here'),
        localRecording: {
          enabled: true,
          format: 'flac'
        },
        interfaceConfigOverwrite: {
          SHOW_JITSI_WATERMARK: false,
          SHOW_WATERMARK_FOR_GUESTS: false,
          SHOW_POWERED_BY: true,
          APP_NAME: brand.title,
          TOOLBAR_BUTTONS: [
            'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
            'fodeviceselection', '-hangup', '-profile', '-info', 'chat', '-recording', 'localrecording',
            '-livestreaming', '-etherpad', 'sharedvideo', 'settings', 'raisehand',
            'videoquality', 'filmstrip', '-invite', '-feedback', '-stats', 'shortcuts',
            'tileview', 'videobackgroundblur', 'download', 'help', '-mute-everyone'
          ],
          SETTINGS_SECTIONS: ['devices', 'language', '-moderator', 'profile', '-calendar'],
          // MOBILE_APP_PROMO: false, // if this is enabled then it removes the app download need, but then errors
          SUPPORT_URL: 'http://remoteparty.social'
        }
      }
    );

    // eslint-disable-next-line no-undef
    const api = new JitsiMeetExternalAPI('meet.jit.si', newOptions);
```

You can see it in action at https://virtualhappuhour.app/test

**Comment by damencho** [comment]
Please when you have questions and problems use the community forum before opening new issues.

Use `configOverwrite ` to pass `prejoinPageEnabled: false,`. There are settings in your example that need to go in configOverwrite and passing them directly to the iframeAPI constructor has no effect.
