### ISSUE TITLE
Implement kicking user out function in Jitsi External API

### ISSUE THREAD

**Issue by pavinduLakshan** [jitsi/lib-jitsi-meet#1314]
Currently, it is not possible to kick out a user in Jitsi External API.  Since no one is working on it as stated [here](https://community.jitsi.org/t/external-api-kick-function/32432/6), I would like to implement it in the Jitsi External API.

**Comment by saghul** [comment]
Thanks for volunteering! Here is how the toggleLobby command was added, the kick participant command should be very similar, hopefully this servers as guidance: https://github.com/jitsi/jitsi-meet/commit/4bfc80ecb913f0614fa158392bd958dc6d9a0671#diff-6e17c8c4f062496776d635d89187d13c

**Comment by pavinduLakshan** [comment]
@saghul Thanks for your guidance. Using that as a reference, I implemented the ability to kick participants in external API. Please have a look and provide with me feedback to proceed. Thanks.
