### ISSUE TITLE
Cannot connect websocket to custom Jitsi server

### ISSUE THREAD

**Issue by TranHHoang** [jitsi/lib-jitsi-meet#1358]
Hi everyone,

I just deployed a custom Jitsi server on my Azure VM and now I'm trying to run the example code with it. The problem is the connection was failed with error:

`lib-jitsi-meet.min.js:1 WebSocket connection to 'wss://dystancevm.southeastasia.cloudapp.azure.com/xmpp-websocket' failed: Error in connection establishment: net::NET::ERR_CERT_AUTHORITY_INVALID`

I checked with `ws://` but still got the same error.

I have followed the Jitsi Quick Install, using self-signed certificate at first and replaced it with Let's Encrypt later, but the error still remains. 

What could I do to resolve this issue? Thanks.

**Comment by damencho** [comment]
When you have questions and problems use the community forum before opening new issues, thank you.

Make sure you are not using alpn multiplexing: https://jitsi.github.io/handbook/docs/devops-guide/faq#how-to-migrate-away-from-multiplexing-and-enable-bridge-websockets
