### ISSUE TITLE
Very long connection (not from first attempt) and console errors

### ISSUE THREAD

**Issue by nikitaodnorob** [jitsi/lib-jitsi-meet#1376]
Hi! I try to using lib-jitsi-meet with options and conference options:
```js
export const getConnectionOptions = roomName => ({
    hosts: {
        domain: 'meet.jit.si',
        muc: 'conference.meet.jit.si',
        focus: 'focus.meet.jit.si',
    },
    serviceUrl: 'https://meet.jit.si/http-bind?room=' + roomName,
    clientNode: 'http://jitsi.org/jitsimeet',
});

export const conferenceOptions = {
    openBridgeChannel: 'websocket'
};
```
But today I have problems with connection (queries to `https://meet.jit.si/http-bind` take at least 15 seconds, sometimes a minute) and errors in console `[modules\xmpp\strophe.ping.js] Ping timeout`. Was something happened with Jitsi Meet or it was some breaking change? Two weeks ago this code worked good

**Comment by damencho** [comment]
We see some load issues. Probably is fine now. 

Use the community forum for questions or problems before opening new issues, thank you.

**Comment by eltonlin1998** [comment]
I know this is unrelated to the issue, but I had a really tough time to get a basic example of lib-jisti-meet to work, but after copy and pasting your config object, suddenly everything worked - so thank you very much. 

I wonder what where / how did you come up with these options for hosts, serviceUrl and clientNode, and where can I read documentation that describes them more in detail (I tried looking in the API docs for this repository, but it doesn't explain those properties). Thanks again!

**Comment by nikitaodnorob** [comment]
@eltonlin1998 I looked example https://meet.jit.si/config.js, but some options (e.g. the appending `roomName` to `serviceUrl`) were got by experiments

**Comment by eltonlin1998** [comment]
I see, thanks so much Nikita!
