### ISSUE TITLE
Encoded audio/video streams not requested at PC initialization

### ISSUE THREAD

**Issue by sridummy** [jitsi/lib-jitsi-meet#1380]
Uncaught DOMException: Failed to execute 'createEncodedStreams' on 'RTCRtpReceiver': Encoded audio streams not requested at PC initialization

it was working fine before suddenly i encountered this issue someone please help me

![Screenshot 2020-10-20 at 5 46 35 PM](https://user-images.githubusercontent.com/30023455/96586406-9a05da00-12fe-11eb-9030-38018f776797.png)

**Comment by jallamsetty1** [comment]
@sridummy, please upgrade to the the latest lib-jitsi-meet - https://community.jitsi.org/t/help-stops-work-with-new-chrome-version-86-0-4240-75/80715/28.
