### ISSUE TITLE
Sample Jitsi Project freezes Firefox when inviting Chrome

### ISSUE THREAD

**Issue by samuelsimoes** [jitsi/lib-jitsi-meet#1382]
First, thank you for the whole efforts put on Jitsi, it is an amazing piece of software!

## Description
There's a strange issue on the [Jitsi Example Code](https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example) where if you start a conference from Firefox and open it on Chrome, the Firefox completely freezes. I am facing this issue in my custom implementation too, but I couldn't replicate it on the https://meet.jit.si/

Running with log level error I could manage to get an "infinite loop" on the console with these two lines.
![screenshot_2](https://user-images.githubusercontent.com/1456228/96920223-440e6f00-1483-11eb-8b80-7820272c3f42.png)

```
Halt: There are no SSRC groups in the remote description.
The description does not look like plan-b
```

## Current behavior
Described above.

## Expected Behavior
To not freeze Firefox?

## Possible Solution
Sadly I don't know.

## Steps to reproduce

The steps are a bit lengthy because this has an isolated project showing the issue.

1. Download the sample project https://github.com/samuelsimoes/jitsi-issue (this is basically the Jitsi Example code packed to run on Express with HTTPS)
2. On the root of project. create the SSL certificates to run it through HTTPS with: `openssl req -nodes -new -x509 -keyout server.key -out server.cert`
3. Install the project dependencies with: `npm install` (it just Express)
4. Start the project with `PORT=3000 npm run start`
5. Access `https://localhost:3000` on Firefox, skip the insecure warnings, and then allow your camera.
6. Access `https://localhost:3000` on Chrome, skip the insecure warnings, and then allow your camera.
7. You will notice that Firefox will be pretty slow, and then it will start to consume a lot of memory.

# Environment details
Nothing specific, I am using some configs that I saw at https://meet.jit.si/config.js

I tested it on Firefox 81.0 on Linux and Windows and Chrome 85.0.4183.121 on Linux and Windows.

**Comment by samuelsimoes** [comment]
Ok, playing a bit here, using `openBridgeChannel: 'websocket'` instead `openBridgeChannel: true` looks to solve this situation.

**Comment by jallamsetty1** [comment]
Closing this as the issue has been resolved.
