### ISSUE TITLE
Cannot join existing conference with Private Jitsi Meet server from lib-jitsi-meet

### ISSUE THREAD

**Issue by pavinduLakshan** [jitsi/lib-jitsi-meet#1402]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
We are using `lib-jitsi-meet` in our React app and using a private Jitsi Meet instance. Everything works well in Chrome and Chromium browsers, but the participants can't join the conference on Firefox. When looked at the Firefox console, it can be seen that the `/http-bind` endpoint of our *private Jitsi server* is being blocked by Devtools for ~10s.  Therefore, it takes Firefox users more time to join the call than the users on Chromium-based browsers. Since we want the users to join the call in as minimum time as possible, this is severely affecting the core functionality of our app.

**However, such a problem doesn't happen when using public Jitsi servers.**. Therefore, we are wondering what is the issue. We used [this self-hosting guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart) to host the private Jitsi server.

## Current behavior
Firefox users take more than ~10 seconds to join an existing call. Errors can be seen in the Firefox console saying that the `http-bind` endpoint of our private Jitsi server is being blocked by Firefox dev tools. After some time, it again gets unblocked. Then only the participants on Firefox can join the call.

## Expected Behavior
Firefox users should be able to join an existing call as same as the Chrome users. The `http-bind` endpoint should not be blocked by Firefox dev tools for some time.

## Possible Solution
No solution found yet.

## Steps to reproduce
1. Create a conference using lib-jitsi-meet with a private Jitsi Meet server.
2. Join the created conference from a Firefox browser.

# Environment details
Browser: Firefox 82.0.3 (64-bit)
Operating systems: Windows, MacOS

**Comment by everflux** [comment]
Do you have websockets enabled? Otherwise it could be related to this: https://community.jitsi.org/t/firefox-and-safari-endless-loop-with-tounifiedplan/99940
