### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by zvs001** [jitsi/lib-jitsi-meet#1405]
yarn error:
```
lib-jitsi-meet: Command failed.
Exit code: 127
Command: webpack -p
Arguments: 


```

npm error:
```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! lib-jitsi-meet@0.0.0 postinstall: `webpack -p`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the lib-jitsi-meet@0.0.0 postinstall script.
```

## Description
Can't install package.
Btw I have webpack and install worked some time ago.

## Expected Behavior
package can be installed

## Possible Solution
do not use webpack in hooks

## Steps to reproduce
yarn install or npm install

# Environment details
node 12
"lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#d2153eb404ddadef6d5b89ae8c499fa144280531",

**Comment by saghul** [comment]
What operating system are you using?

**Comment by zvs001** [comment]
macos, but it is not related.

I investigated problem a little bit.
I opened folder: `cd node_modules/lib-jitsi-meet/`
1) after manual run I got: `sh: webpack: command not found`
So actually I didn't have global webpack. But after install I got another error:
`[webpack-cli] Unknown argument: -p`

I tried few:
`npm i webpack-cli`
`npm i webpack -g`
`npm i webpack@4 -g`

2) Then I tried to install packages within folder (dev packages)
`npm install`

Now it worked. (within folder)

But project install will continue get crash.

## 
Looks like you have npm `@jitsi` scope. Why you wouldn't publish it with compiled output?

Otherwise looks like it is required to download dev packages. So probably you have to move them to dependencies section.

##

I'm trying to integrate js side from jitsi-meet to react-native app.

**Comment by sapkra** [comment]
We already have an issue for it: #484 
In the meantime you can use my npm package: [@lyno/lib-jitsi-meet](https://www.npmjs.com/package/@lyno/lib-jitsi-meet)
I'm updating the package on every major release and it is also using the same version numbers.

**Comment by zvs001** [comment]
@sapkra thanks. I will try package.
Issue you attached is 3 years old and it is still actual.

**Comment by sapkra** [comment]
Closing it in favor for #484. Saghul already posted an update why there has not been any progress in the past year.
