### ISSUE TITLE
Why is this library not available on npm?

### ISSUE THREAD

**Issue by vladislav-puzyrev** [jitsi/lib-jitsi-meet#1409]
Why is this library not available on npm?

**Comment by sergeyd63** [comment]
we use this one:
https://www.npmjs.com/package/@lyno/lib-jitsi-meet

but it's not up to date. the last push was a month ago

@sapkra is there a chance for an update? please? pretty please? 

there was a logger bug fix merged.

**Comment by sapkra** [comment]
@sergeyd63 Which version do you need? The package currently is on the latest stable release already.

@vladislav-puzyrev I'm going to close this issue because we already covered this topic in another one: https://github.com/jitsi/lib-jitsi-meet/issues/484

**Comment by sergeyd63** [comment]
@sapkra there was a push today [https://github.com/jitsi/lib-jitsi-meet/commit/997f7a501b217d81007b07a219a91310d85f118a](997f7a501b217d81007b07a219a91310d85f118a)

the `jitsi-meet-logger` was updated
current one is breaking Electron 11

thanks

**Comment by sapkra** [comment]
I introduced a beta tag. The new version is `2.5276.0-beta`.

**Comment by sergeyd63** [comment]
Thank you @sapkra 
it's working now
