### ISSUE TITLE
JWT token valid for one room can unlock any room

### ISSUE THREAD

**Issue by slykar** [jitsi/lib-jitsi-meet#1427]
## Description

I'm using JWT token authentication and I only want to allow users with a valid JWT to create a room.
Guest users should be able to join already created rooms.

I did a fresh install today and configured everything according to https://jitsi.github.io/handbook/docs/devops-guide/secure-domain.

Looks like this might be related to #1200. 

## Current behavior

Guest:
1. open meeting url, e.g. jitsi.example.com/myorg/roomA
2. you get a message that you need to wait for the host
3. you wait :)

Host for **roomB**:
1. open meeting jitsi.example.com/myorg/roomA
2. > Sorry! You are not allowed to be here :(
3. Looks like it's working, but...

back to Guest:
1. room gets unlocked, even tough the real host is not there yet
2. anyone can join now, see each other and talk

## Expected Behavior
Guest:
1. open meeting url, e.g. jitsi.example.com/myorg/roomA
2. you get a message that you need to wait for the host
3. you wait :)

Host for **roomB**:
1. open meeting jitsi.example.com/myorg/roomA
2. > Sorry! You are not allowed to be here :(

back to Guest:
1. you are still waiting for the real host
2. other people also need to wait
3. conference cannot be started without the real host

## Possible Solution

I'm not sure. Looks like when the JWT is completely wrong it works fine. You get a "red" authentication error message.
Probably not even an issue with `lib-jitsi-meet`, but since the JWT token docs are found here, I'm posting here.

## Steps to reproduce

See **Current behavior**

# Environment details
```
jitsi-meet-prosody/stable,now 1.0.4466-1 all [installed,automatic]
jitsi-meet-tokens/stable,now 1.0.4466-1 all [installed]
jitsi-meet-turnserver/stable,now 1.0.4466-1 all [installed,automatic]
jitsi-meet-web-config/stable,now 1.0.4466-1 all [installed,automatic]
jitsi-meet-web/stable,now 1.0.4466-1 all [installed,automatic]
jitsi-meet/stable,now 2.0.5142-1 all [installed]
jitsi-videobridge2/stable,now 2.1-376-g9f12bfe2-1 all [installed,automatic]
prosody/stable,now 0.11.2-1 amd64 [installed,automatic]
```

```
$ cat /etc/jitsi/jicofo/sip-communicator.properties
org.jitsi.jicofo.BRIDGE_MUC=JvbBrewery@internal.auth.jitsi.example.com
org.jitsi.jicofo.auth.URL=EXT_JWT:jitsi.example.com
```

**Comment by damencho** [comment]
Secure domain instructions are to use username and password not jwt. 

For jwt you should use https://github.com/jitsi/jitsi-meet/blob/9535f84775b40d0de05640aa9158d25a027fed29/resources/prosody-plugins/token/util.lib.lua#L36, allow_empty_token to control whether you allow guests.
And https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L61 token_verification module to limit access to rooms when that is available in the jwt.

**Comment by slykar** [comment]
The docs seem to be kind of misleading then. They say:

> When using token based authentication, the URL must use EXT_JWT as the scheme instead:
> org.jitsi.jicofo.auth.URL=EXT_JWT:jitsi-meet.example.com

Sample config files in the docker setup have a piece like this:

```
{{ if $ENABLE_AUTH }}
  {{ if eq $AUTH_TYPE "jwt" }}
org.jitsi.jicofo.auth.URL=EXT_JWT:{{ .Env.XMPP_DOMAIN }}
  {{ else }}
org.jitsi.jicofo.auth.URL=XMPP:{{ .Env.XMPP_DOMAIN }}
  {{ end }}
{{ end }}
```

`$AUTH_TYPE "jwt"` is used to enable the `mod_auth_token`.

---

Generally I thought I would be able to modify some Lua plugin to just require a valid JWT when creating the room, because I can't enable room creation for everyone. Setting `allow_empty_token = true` would not work for me.

However, this works https://github.com/jitsi/lib-jitsi-meet/issues/1057#issuecomment-628129669 ... kind of. It shows the behavior I've described. Leaving this as a note to anyone who might stumble on this issue.
