### ISSUE TITLE
setLastN changes lastN for all participants

### ISSUE THREAD

**Issue by DanielMcAssey** [jitsi/lib-jitsi-meet#1435]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
The setLastN on conference actually sets the LastN for all participants even if done by a non-moderator user.

## Current behavior
---
setLastN sets the LastN on all participants
## Expected Behavior
---
setLastN should set the LastN of the current participant only
## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
Do you have a way to reproduce / test this? If this were the case things would be very wrong in production and we'd have noticed.

**Comment by bgrozev** [comment]
The `channelLastN` option in `config.js` used to affect the whole conference, but that was changed with jitsi/jicofo#632.

**Comment by bgrozev** [comment]
I just tested `JitsiConference.setLastN()` (thanks @gpolitis for pointing it out) and it only affects the local participant as expected. Please describe the issue in more detail.
