### ISSUE TITLE
Mobile Safari: The remote audio got suspended after unplugging earphones

### ISSUE THREAD

**Issue by nadelicious** [jitsi/lib-jitsi-meet#1443]
## Description
  The remote audio got suspended/interrupted after I unplugged my earphones using Mobile Safari.

## Current behavior
The remote audio got suspended/interrupted after I unplugged my earphones.

## Expected Behavior
Remote audio should not be suspended whenever I unplugged in my earphones.

## Possible Solution
No current solution as of this moment.
Could be related? https://stackoverflow.com/questions/10232908/is-there-a-way-to-detect-a-mobile-safari-audio-interruption-headphones-unplugg

## Steps to reproduce
Join the call using mobile safari with earphones. While in a call, unplug the earphones. Afterwards,  you cannot hear anymore the remote participant audio.

# Environment details
**Config**
 ```
p2p: {
    enabled: false,
}
disableSimulcast: true 
```
***Devices used***
IPhone 12, Iphone X, Iphone 8

***IOS Versions***
14.2, 14.3

**Note:**  This issue also occurs in meet.jitsi.

**Comment by everflux** [comment]
You can listen for the event and Reenable Audio. Imho this it not a jitsi issue per se but how iOS works.

**Comment by zsinba** [comment]
the same issue with Bluetooth

**Comment by nadelicious** [comment]
this is fixed.
