### ISSUE TITLE
Recorder initiator and terminator are always undefined.

### ISSUE THREAD

**Issue by saygun** [jitsi/lib-jitsi-meet#1454]
## Description
I am using `jitsi-meet`. What I would like to do is showing a notification when the recording has started. Currently, there is one [if statement](https://github.com/jitsi/jitsi-meet/blob/master/react/features/recording/middleware.js#L158) that checks for the existence of `initiator` of `recorderSession`. 

That `recorderSession` is received from the event which fired from `lib-jitsi-meet`
```javascript
if (session.getStatus() === 'off') {
  session.setTerminator(participant);
} else if (session.getStatus() === 'on') {
  session.setInitiator(participant);
}
```

## Current behavior
Whether I start the recording or stop it. `initiator` and `terminator` always return undefined thus recording started notification is never rendered.
```javascript
// recorderSession
{
  ...
  initiator: undefined,
  terminator: undefined,
  ...
}
```

## Expected Behavior
`session.initiator` and `session.terminator` properties should be set to participant's `jid`. 

## Possible Solution
I am not sure, to be honest, but I can work on this issue with little help/guide.

## Steps to reproduce
The starting recorder will not show the notification.

# Environment details
`lib-jitsi-meet: github:jitsi/lib-jitsi-meet#ae45a0648f6a9acd562b253b212289fcb5bd6b05`
`jitsi-meet: stable/jitsi-meet_5142`

P.S I checked the `meet.jit.si` and the same behavior is present there.

**Comment by damencho** [comment]
Have you tried it on meet.jit.si, it is already working there?

**Comment by saygun** [comment]
@damencho Yes, I have tried it. Recording started notification is also not rendered on `meet.jit.si`.

**Comment by damencho** [comment]
These values are set in jicofo and just received from lib-jitsi-meet.

**Comment by damencho** [comment]
Hum. I will check, take a look later today.

**Comment by damencho** [comment]
How are you testing this, opening two tabs start recording from one and check notifications on the other?

**Comment by saygun** [comment]
That's the thing. It shows the "Recording started" notification to another user when I test it with two tabs.

I was doing the test with one user. I have disabled notification sounds by using `disableRecordAudioNotification` flag in `config.js`. So I was trying to show the notification to `initiator` like as same as recording stopped notification. When `initiator` stops the recording, `showStoppedRecordingNotification` gets called.

**Comment by saygun** [comment]
Closing the issue. Thank you for clarifying.
