### ISSUE TITLE
WS connection drops after keep alive interval

### ISSUE THREAD

**Issue by bukharin** [jitsi/lib-jitsi-meet#1465]
Hi,

After keepalive interval lib-jitsi-meet drops WS connenction with error `Detected that shard changed from undefined to null `

It seems after [this commit](https://github.com/jitsi/lib-jitsi-meet/commit/cb484cf48ccd3d56cf9bb2e9d452bd7aa644ac8a#diff-6728f0c5879db904f5a1e1a64073e0ddb1ca03bac3c2e20ba73ffa196a32d7d6R416)

**Comment by damencho** [comment]
What do you mean after the keepalive interval? 
This commit adds a check to check the headers coming from the webserver checking for 'x-jitsi-shard'. 
What are your problem and use case, do you reproduce it every time and how do you reproduce it?

**Comment by bukharin** [comment]
@damencho after 60 sec (default keep-alive interval) lib-jitsi-meet fetches `/xmpp-websocket` address. Our installation does not have `x-jitsi-shard` header in the response (null). Also we don't configure `shard` option (undefined).

In the commit above you have a strict comparison (null !== undefined). In this case `li-jitsi-meet` emit `CONFERENCE_FAILED` event with `conference.otherError` code.

**Comment by damencho** [comment]
> In the commit above you have a strict comparison (null !== undefined).

🤦

**Comment by damencho** [comment]
Thank you for the report. Can you test, does https://github.com/jitsi/lib-jitsi-meet/pull/1467 fixes it for you?

**Comment by bukharin** [comment]
@damencho yes it does, thank you

**Comment by billybobilly** [comment]
Leaving a note in case someone needs this too.  In our case, we don't store the shard in header, so it fails on null responseShard.

had to add null test to this line:
 433               if (responseShard !== shard && responseShard !== null) {

Not sure if it's the smartest fix, but worked for us.
