### ISSUE TITLE
iOS Chrome not using Unified Plan

### ISSUE THREAD

**Issue by jkowens** [jitsi/lib-jitsi-meet#1480]
## Description

When joining a conference with another participant from Chrome on iOS, the session is immediately terminated. The error in the javascript console:

>ERROR2021-01-27T15:41:37.691Z [modules/xmpp/JingleSessionPC.js] addRemoteStream failed: InvalidAccessError: Failed to set remote offer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan.

## Possible Solution

It appears the browser check to determine if it uses unified plan is not accurate for Chrome on iOS which is based on the webkit engine.

See: https://github.com/jitsi/lib-jitsi-meet/blob/301e3a22dd76341b15d3846ab539e713d8e7569b/modules/browser/BrowserCapabilities.js#L210

I believe the `usesUnifiedPlan` function should be updated to something like this:

```
    usesUnifiedPlan() {
        if (this.isFirefox() || (this.isChrome() && this._bowser.isEngine('webkit')) {
            return true;
        }

        if (this.isSafari() && typeof window.RTCRtpTransceiver !== 'undefined') {
            // https://trac.webkit.org/changeset/236144/webkit/trunk/LayoutTests/webrtc/video-addLegacyTransceiver.html
            // eslint-disable-next-line no-undef
            return Object.keys(RTCRtpTransceiver.prototype).indexOf('currentDirection') > -1;
        }

        return false;
    }
```

# Environment details
iOS 14.4, Chrome 87, docker-jitsi-meet:stable-5142-4

**Comment by jallamsetty1** [comment]
There is some more work needed on the client for other browsers to work on iOS.

**Comment by jallamsetty1** [comment]
This should be fixed now in the tip of the master.

**Comment by jkowens** [comment]
@jallamsetty1 thank you!
