### ISSUE TITLE
how to enable blur background with lib jitsi meet?

### ISSUE THREAD

**Issue by clark-97** [jitsi/lib-jitsi-meet#1507]
I want to enable blur background with lib jitsi meet, I saw [jitsi-meet/JitsiStreamBlurEffect.js at master · jitsi/jitsi-meet · GitHub](https://github.com/jitsi/jitsi-meet/blob/master/react/features/stream-effects/blur/JitsiStreamBlurEffect.js) ,but still don’t know how to enable blur background. I checked [JitsiTrack](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ljm-api#jitsitrack) setEffect( **effect** ) ,what is the effect specific for blur background?
Forum related links: [Does lib jitsi meet support blur background?](https://community.jitsi.org/t/does-lib-jitsi-meet-support-blur-background/94060)

**Comment by damencho** [comment]
This is supported but implemented outside the library. Jitsi-meet uses lib-jitsi-meet and has blur implemented and enabled. Look at jitsi-meet code for that.

Please, when you have questions or problems use the community forum before opening new issues.
