### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by Fuzzyma** [jitsi/lib-jitsi-meet#1517]
Importing lib-jitsi-meet throws if jquery is not included. This is a strange requirement. Jquery can easily be imported where it is needed. Forcing the user to include it, shouldn't be required. 

I only counted 104 uses of jquery throughout the whole project. These could be easily replaced by vanillajs which would remove this "burden" from the project :)

Let me know what you think!

**Comment by saghul** [comment]
One of our core dependencies, strophe.js requires it.

We chose to keep it out since being such a common library applications can provide it to avoid having it embedded more than once.

**Comment by Fuzzyma** [comment]
It seems like you copied Strophe.js into your own code instead of listing it as a dependency. Why is that?

Also I visited the Strophe.js repository. They don't have jquery as dependency and even if they did, they allow import via esm which again would resolve the problem.
So what is the actual reason?

**Comment by saghul** [comment]
Oh! Maybe this has changed? I'd swear strophe was the culprit.

In that case we'd 100% welcome a PR that gets rid of jQuery here in lib-jitsi-meet!

**Comment by Fuzzyma** [comment]
@saghul So I double-checked and I missed the devDependency on jquery BUT they never ever use it! Instead they have a custom builder as a replacement for jquery in their code. That's maybe even something you can utilize in your strophe code as well (esm imports ftw).

**Comment by Fuzzyma** [comment]
What browsers are you targeting with lib-jitsi-meet? Do you still require ie11 support?

**Comment by saghul** [comment]
IE11 is certainly out of the question :-) Since We need to support recent WebRTC, any modern browser should do.


> Instead they have a custom builder as a replacement for jquery in their code.

Where is this?

**Comment by Fuzzyma** [comment]
@saghul Here it is: https://github.com/strophe/strophejs/blob/a159a35798d1ea1931aee46b0f79f7bf4a8aac2c/src/core.js#L26

I realized its only for building xmpp related messages. It doesn't seem to be usable to retrieve something from the dom. But that shouldn't be a problem either since `querySelector` can be easily used as an replacement :)

Sidenode: This one should be a separate issue but is there a reason that parts of the files are still commonjs modules?

**Comment by saghul** [comment]
> @saghul Here it is: https://github.com/strophe/strophejs/blob/a159a35798d1ea1931aee46b0f79f7bf4a8aac2c/src/core.js#L26
> 
> 

Those seem to be functions that have a $ in the name. Is there some build time magic?

> 
> I realized its only for building xmpp related messages. It doesn't seem to be usable to retrieve something from the dom. But that shouldn't be a problem either since `querySelector` can be easily used as an replacement :)
> 
> 
> 
> Sidenode: This one should be a separate issue but is there a reason that parts of the files are still commonjs modules?

No specific reason other than this library predates ES6 and not even all modules have been migrated to ES6 classes.

**Comment by Fuzzyma** [comment]
Having a function with $ in the name is totally valid. Not sure what magic you are looking for :D.

So you are generally open to convert all of those as well?

If you have some free time to chat about that, I would be open :)

**Comment by saghul** [comment]
I took another look and looks like we do wrap many messages in jQuery to make some processing easier.

So I think the changes necessary here would be pretty big actually.

**Comment by Fuzzyma** [comment]
You are using it 104 times. But most of the time it's a simple `find`. I can prepare a pr for that - no problem :)

**Comment by saghul** [comment]
Let's give it a try!

**Comment by Fuzzyma** [comment]
@saghul there you go: #1518

**Comment by saghul** [comment]
JQuery is now bundled in, closing.
