### ISSUE TITLE
Diposing a track with an effect doesn't call TRACK_REMOVED.

### ISSUE THREAD

**Issue by maxirozay** [jitsi/lib-jitsi-meet#1537]
#### Diposing a track with an effect doesn't call TRACK_REMOVED.
---

#### When I call .dispose() on a track with an effect it removes the track without calling TRACK_REMOVED. When I recreate the track it removes the track and directly add the new one (the listener TRACK_ADDED is called after the TRACK_REMOVED). If I call .setEffect() to remove the effect the behavior is the same. This is the behavior for 3 or more users if I have 2 users when I call dispose() it calls TRACK_REMOVED then directly call TRACK_ADDED with the same track.
---

#### When I call .dispose() on a track with an effect it removes the track and call TRACK_REMOVED on other users.
---

#### Calling `room.removeTrack(tracks[0])` before `dispose()` call the TRACK_REMOVED listener.
---

####
```
room.on(JitsiMeetJS.events.conference.TRACK_ADDED, track => {
  console.log('add', track.getType(), track.getParticipantId(), track)
})
room.on(JitsiMeetJS.events.conference.TRACK_REMOVED, track => {
  console.log('remove', track.getType(), track.getParticipantId(), track)
})

const tracks = await JitsiMeetJS.createLocalTracks({ devices: ['video'] })
room.addTrack(tracks[0]) // call TRACK_ADDED

tracks[0].setEffect(new Effect()) // if I remove the effect it works as expected

// it works if I call `await room.removeTrack(tracks[0])`
tracks[0].dispose() // doesn't call TRACK_REMOVED
```
---

# Environment details
####
Window 10
firefox, brave, chrome
node 12.18.3
jitsi https://meet.jit.si/libs/lib-jitsi-meet.min.js
####
---

**Comment by maxirozay** [comment]
Also when I dispose a track on Firefox 87 it doesn't trigger the TRACK_REMOVED event. Even with `room.removeTrack()`. It works fine on chrome and brave.

**Comment by saghul** [comment]
Paging @jallamsetty1

**Comment by maxirozay** [comment]
I just noticed something else on **firefox**. When I have music playing on my laptop and I turn on the mic, the music stops. Then I turn off the mic and everything on my browser is telling me that my mic is off (no issue, no log, no mic icon on the browser) but the music is still not playing. Then I close my tab and the music starts playing again like the mic was not really disposed. Everything works correctly on chrome and brave, the music comes back when I turn off the mic.

When I say "turn off the mic" that means calling `dispose()` on the audio track.

**Comment by bukharin** [comment]
Related issue, I guess https://github.com/jitsi/jitsi-meet/issues/8482

**Comment by jallamsetty1** [comment]
> Related issue, I guess [jitsi/jitsi-meet#8482](https://github.com/jitsi/jitsi-meet/issues/8482)

Thanks, this is a known issue with Unified plan browsers because of the way they handle track addition and removal at the peerconnection level. I will looking into it soon. This however is different from the issue described above when effects are applied on the tracks.

**Comment by jallamsetty1** [comment]
@maxirozay I see that JitsiLocalTrack#dispose is stopping the effect and restoring the original stream/track on the JitsiLocalTrack but doesn't replace them on the peerconnection. Therefore there is mismatch of the streams when it tries to remove the track from the conference. 
All the jitsi-meet clients remove the effect first by calling track.setEffect() before disposing the track and therefore we don't see the issue there. I will open a PR for fixing this.

**Comment by maxirozay** [comment]
Thanks!
