### ISSUE TITLE
The remoteTrack.videoType is undefined for camera tracks

### ISSUE THREAD

**Issue by jerry2013** [jitsi/lib-jitsi-meet#1572]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
because of the change to JitsiConference.js in https://github.com/jitsi/lib-jitsi-meet/commit/d73723dae68ccbda83b529ed30c2c3340d9f3e0d , the videoType of a remote track is undefined when received, if the type is in fact 'camera'.

this causes compatibility problems if 1) the client relies on videoType for rendering logic, 2) mixed client lib versions in the same room (e.g. current stable to next stable)

## Current behavior
the videoType from a newly received remote camera track is `undefined`.

## Expected Behavior
videoType to be camera when it is a camera track.

## Possible Solution
always send 'videoType' in presence as before - revert the change in JitsiConference.js

## Steps to reproduce
2 person join beta.meet with camera on, inspect the videoType of remote video tracks

# Environment details
meet unstable

**Comment by damencho** [comment]
videoType defaults to camera and this had been the case for long time, so there is no need to send it.  https://github.com/jitsi/lib-jitsi-meet/blob/3cd9d31b9719e8cdf0cd0b43ff1afe608dd698c8/modules/RTC/RTC.js#L185

**Comment by paweldomas** [comment]
@damencho maybe then the field should be initialized to camera instead of being `undefined`?

**Comment by jerry2013** [comment]
Yes but the JitsiRemoteTrack.videoType is set via ChatRoom.getMediaPresenceInfo, and if the presence for videoType is missing, it's undefined.

**Comment by Fuzzyma** [comment]
I ran into this today. When I receive remote video, it has no video type and also no handlers attached. The video is sometimes also just blank

**Comment by zsinba** [comment]
> I ran into this today. When I receive remote video, it has no video type and also no handlers attached. The video is sometimes also just blank

the same issue。

**Comment by xXTraceXx** [comment]
Same issue. In previous version of lib-jitsi-meet api the video track was of type `camera` or `desktop` and this was very useful.

**Comment by jadhavsaurabh** [comment]
> Same issue. In previous version of lib-jitsi-meet api the video track was of type `camera` or `desktop` and this was very useful.

@xXTraceXx Any update on this? I tried to handle this by accessing the videoType in setTimeout/setInterval It worked but still behaving weirdly

**Comment by Fuzzyma** [comment]
@saghul can we at least get a workaround for this? Is there any event we can listen to so we can react once the videoType is available?

**Comment by saghul** [comment]
I don't know sorry, I have not been involved in this particular bug. @jallamsetty1 thoughts? (please read up)

**Comment by Fuzzyma** [comment]
I researched and it seems like the newly documented `TRACK_VIDEOTYPE_CHANGED` is what I was looking for. I can listening to it and adapt as needed if the videoType is undefined

**Comment by damencho** [comment]
Isn't that fixed with https://github.com/jitsi/lib-jitsi-meet/commit/79afa717178c8e79390af2178870358bbf17759d

**Comment by dkgrieshammer** [comment]
> Isn't that fixed with [79afa71](https://github.com/jitsi/lib-jitsi-meet/commit/79afa717178c8e79390af2178870358bbf17759d)

it should be; 
previous workaround `video.videoType = video.videoType === "desktop" ? "desktop" : "camera" //set videoType directly` no longer needed 🙏

**Comment by Fuzzyma** [comment]
No the fix just sets a default and that default is sometimes wrong. You still need to listen for the video type change event to rectify that if a wrong video type was set

**Comment by jallamsetty1** [comment]
> No the fix just sets a default and that default is sometimes wrong. You still need to listen for the video type change event to rectify that if a wrong video type was set

Why do you think the default is sometimes wrong ? The client adds the videoType in presence only when it's different from 'camera'. If it is something different than 'camera' then it should be present in the incoming presence for the remote peer and will be read correctly when the remote track is created.

**Comment by dkgrieshammer** [comment]
I also have the issue that when I initiate screen sharing (and calling `dispose` of oldTrack before, which feels weird but seems to be the only way to circumvent a massive timeout before track change on receiver side), the inital type of track received on TRACK_ADDED is apparently sometimes wrong the first time sharing is started; it's videoType = 'camera' even though its a desktop track

The way I create the desktop track is sth like this 

```js
//get old track
const oldTrack = conference.getLocalVideoTrack()
// dispose to circumvent time out
oldTrack?.dispose()
// create new desktop track
jsMeet.createLocalTracks({ devices: ['desktop'] })
  .then((tracks) => conference.replaceTrack(oldTrack, tracks[0]))
  .then(// add local track)
  .catch(//...)
``` 
track on receiver's side in TRACK_ADDED is videoType === 'camera'
