### ISSUE TITLE
iceservers overwritten on message receive

### ISSUE THREAD

**Issue by psi-4ward** [jitsi/lib-jitsi-meet#1589]
The [`_onSystemMessage`](https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/xmpp/xmpp.js#L523) handler gets invoked when a messages comes in like 

```xml
<message xmlns="jabber:client" from=".." to=".." type="groupchat">
  <subject>My-Room</subject>
  <delay xmlns="urn:xmpp:delay" from=".." stamp="2021-04-30T08:29:43Z"/>
</message>
```

which triggers [`onReceiveStunAndTurnCredentials`](https://github.com/jitsi/lib-jitsi-meet/blob/e354745db501e3bc943da3b7e52087fb78be0bcf/modules/xmpp/strophe.jingle.js#L333) resulting in overwriting 
[`this.jvbIceConfig.iceServers` and `this.p2pIceConfig.iceServers`](https://github.com/jitsi/lib-jitsi-meet/blob/e354745db501e3bc943da3b7e52087fb78be0bcf/modules/xmpp/strophe.jingle.js#L394) with an empty array.
So there are no turn candidates anymore.

**Comment by saghul** [comment]
Ping @damencho

**Comment by damencho** [comment]
@psi-4ward which version of ljm do you use.
I think that was addressed in https://github.com/jitsi/lib-jitsi-meet/commit/3c9913ed61abe28aec1e8268ca62dd59a0ccdfc5

**Comment by psi-4ward** [comment]
> @psi-4ward which version of ljm do you use.
> I think that was addressed in [3c9913e](https://github.com/jitsi/lib-jitsi-meet/commit/3c9913ed61abe28aec1e8268ca62dd59a0ccdfc5)

I've seen the code and the commit is included in my build. 

* getStunAndTurnCredentials() => onReceiveStunAndTurnCredentials() with extdisco:2
    => Prosody replies turn config
* later _onSystemMessage() gets invoked the first time and triggers onReceiveStunAndTurnCredentials() again with the subject message

so the problem is, that _onSystemMessage does not receive the external-services on first invocatin

**Comment by damencho** [comment]
Hum, I'm trying to understand what is going on... and by the way thank you for the report.
 
You are receiving messages before Strophe being connected? As when Strophe fires it is connected we remove the hanlder:                 https://github.com/jitsi/lib-jitsi-meet/blob/e354745db501e3bc943da3b7e52087fb78be0bcf/modules/xmpp/xmpp.js#L283
I think the case you describe is handled by this ...

**Comment by psi-4ward** [comment]
I think I've found your issue:

strophe.addHandler: 
```js
  addHandler: function addHandler(handler, ns, name, type, id, from, options) {
    var hand = new Strophe.Handler(handler, ns, name, type, id, from, options);
    this.addHandlers.push(hand);
    return hand;
  },
```

so we have to remove Stophe.Handler Instance instead of the `this._onSystemMessage.bind(this)` reference.

Following Code works for me:

```js
            this._sysMessageHandler = this.connection._stropheConn._addSysHandler(
                this._onSystemMessage.bind(this),
                null,
                'message'
            );
```

**Comment by damencho** [comment]
Good catch, can you add one more thing to the PR, please. 
After this line https://github.com/jitsi/lib-jitsi-meet/blob/e354745db501e3bc943da3b7e52087fb78be0bcf/modules/xmpp/xmpp.js#L283
It misses:
this._sysMessageHandler = null;

Thanks

**Comment by damencho** [comment]
Fixed with https://github.com/jitsi/lib-jitsi-meet/pull/1590

**Comment by damencho** [comment]
Thanks for the report and contribution and sorry

**Comment by psi-4ward** [comment]
theres another one https://github.com/jitsi/jitsi-meet/pull/7534 :p :D
