### ISSUE TITLE
JitsiConference.sendMessage() throws error when trying to send custom 'json-message'

### ISSUE THREAD

**Issue by martinemmert** [jitsi/lib-jitsi-meet#1592]
## Description
When I try to send an object through the method `sendMessage()` of the class `JitsiConference` I receive an error.
The error also appears to be present at the current `meet.jit.si` deployment.

```
lib-jitsi-meet.min.js:1 Uncaught TypeError: Cannot read property 'appendChild' of null
    at Builder.c (lib-jitsi-meet.min.js:1)
    at E.sendMessage (lib-jitsi-meet.min.js:10)
    at ie.sendTextMessage (lib-jitsi-meet.min.js:10)
    at ie.sendMessage (lib-jitsi-meet.min.js:10)
    at <anonymous>:1:6
```
The documentation hints that this should be possible:

```
// JitsiConference.js:2636
/**
 * Sends a message to a given endpoint (if 'to' is a non-empty string), or
 * broadcasts it to all endpoints in the conference.
 * @param {string} to The ID of the endpoint/participant which is to receive
 * the message, or '' to broadcast the message to all endpoints in the
 * conference.
 * @param {string|object} message the message to send. If this is of type
 * 'string' it will be sent as a chat message. If it is of type 'object', it
 * will be encapsulated in a format recognized by jitsi-meet and converted to
 * JSON before being sent.
 * @param {boolean} sendThroughVideobridge Whether to send the message through
 * jitsi-videobridge (via the COLIBRI data channel or web socket), or through
 * the XMPP MUC. Currently only objects can be sent through jitsi-videobridge.
 */
JitsiConference.prototype.sendMessage = function(
        message,
        to = '',
        sendThroughVideobridge = false) { ...
```

## Current behavior
- The payload is correctly converted into a JSON string and the `elementType` is set to `json-element`
- The `Strophe.Builder` throws an error and the payload is not sent.

## Expected Behavior
- The payload is correctly converted into a JSON string and the `elementType` is set to `json-element`
- The `Strophe.Builder` throws no error and the payload is sent.

## Steps to reproduce

1. goto https://meet.jit.si/
2. start a random conference and join the room
3. open the developer console
4. send a message through the conference

`window.APP.store.getState()["features/base/conference"].conference.sendMessage({foo: "bar"})`

# Environment details
Chrome, importing `lib-jitsi-meet` from self-hosted server.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

`window.APP.store.getState()["features/base/conference"].conference.sendMessage('some message')`

**Comment by martinemmert** [comment]
Why is this issue closed? 
This is not a question but an actual bug inside the library's code and exists on your live systems.

**Comment by damencho** [comment]
I showed you the correct code which works.

**Comment by damencho** [comment]
Aa there is a |object param.

**Comment by damencho** [comment]
We prefer even bugs to first discuss them in the community forum, so in the future please do that.

**Comment by damencho** [comment]
There is comment:
```
    // Through videobridge we support only objects. Through XMPP we support
    // objects (encapsulated in a specific JSON format) and strings (i.e.
    // regular chat messages).
```
So I think this is your problem with the format of the message.

**Comment by damencho** [comment]
Yeah, there is a bug around the nickname ... not sure why though.

**Comment by martinemmert** [comment]
@daimoc thanks for reopening this issue and take the time to have a second look.

I identified the `.up()` method which is called after the `.c()` method, that attaches the `json-message` node as the reason for this error message. 

```
let m = $msg({ to: "foobar", type: "groupchat" });
m.c("json-message", { xmlns: '...' }, "{ "foo": "bar" }");
// Builder {nodeTree: message, node: message}
m.c("json-message", { xmlns: '...' }, "{ "foo": "bar" }").up()
// Builder {nodeTree: message, node: null}
```

The [documentation](http://strophe.im/strophejs/doc/1.4.2/files/strophe-umd-js.html#Strophe.Builder.c) of `Strophe.Builder.c()` says: 

> Add a child to the current element and make it the new current element.
>
> This function moves the current element pointer to the child, unless text is provided.  If you need to add another child, it  is necessary to use up() to go back to the parent in the tree.

This appears to be not the case and the documentation is miss leading. If you provide a `string` or `number` the method `c()` behaves like `t()`

```js
c (name, attrs, text) {
    const child = Strophe.xmlElement(name, attrs, text);
    this.node.appendChild(child);
    if (typeof text !== "string" && typeof text !=="number") {
        this.node = child;
    }
    return this;
}

// ...

t (text) {
    const child = Strophe.xmlTextNode(text);
    this.node.appendChild(child);
    return this;
}
```

I don't have a correctly set up `lib-jitsi-meet` setup currently, therefore I can't create a propper push requests with tests. 

---


> We prefer even bugs to first discuss them in the community forum, so in the future please do that.

You are doing a great job with the software, and I see your effort in giving good answers and be helpful in the forum. 
I searched for about 2 hours through the forum and was not sure this is the right place to discuss actual bugs.
It appears to be a place where people ask for consultancy and don't discuss issues like that.
