### ISSUE TITLE
Changing camera on mobile browser (Android) does not work on some devices

### ISSUE THREAD

**Issue by plantiword** [jitsi/lib-jitsi-meet#1599]
We are using our own hosted Jitsi server (latest stable version: 2.0.5765-1 on Ubuntu 18.04) to embed videocalls on a web platform. Our solution is used on both desktops and mobile devices.

We have received reports that in certain Android devices the functionality for changing the camera (front to back, or viceversa) does not work (video comes all black, audio is not affected).

I'm attaching the console log from one of these tests in case it helps. I previously reported this as an addition to issue #5425 on jitsi-meet (https://github.com/jitsi/jitsi-meet/issues/5425) but after getting the logs I figure it would be better to report it here.

[my.jitsi.server-1620144228436.log](https://github.com/jitsi/lib-jitsi-meet/files/6422970/my.jitsi.server-1620144228436.log)

**Comment by lq111lq** [comment]
In certain Android devices（most of them are android 10）， when calling getUserMedia method  with an new camera`s deviceId ，browser will throws an error message（NotReadableError: Could not start video source）if not close the old track。

**Comment by lq111lq** [comment]
https://developer.android.com/reference/android/hardware/camera2/CameraManager#openCamera(java.lang.String,%20android.hardware.camera2.CameraDevice.StateCallback,%20android.os.Handler)

**Comment by saghul** [comment]
Closing since this can only be handled in the application layer. Generally speaking opening 2 cameras is not supported.
