### ISSUE TITLE
Deprecate and remove Plan B sdpSemantics

### ISSUE THREAD

**Issue by AmilKey** [jitsi/lib-jitsi-meet#1601]
## Description
---
[Deprecation] Plan B SDP semantics, which is used when constructing an RTCPeerConnection with {sdpSemantics:"plan-b"}, is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers. The standardized SDP format, "unified-plan", has been used by default since M72 (January, 2019). Dropping support for Plan B is targeted for M93 (Canary: July 15, 2021; Stable: August 24, 2021).

https://bugs.chromium.org/p/chromium/issues/detail?id=857004

## Possible Solution
---
Looks like we can use iceConfig.sdpSemantics = 'unified-plan' by default

**Comment by jallamsetty1** [comment]
This has been addressed in https://github.com/jitsi/lib-jitsi-meet/pull/1625

**Comment by jallamsetty1** [comment]
The client can now switch to using the unified-plan implementation using this config.js flag - https://github.com/jitsi/jitsi-meet/blob/master/config.js#L86
