### ISSUE TITLE
jitsi-meet-tokens installation

### ISSUE THREAD

**Issue by wuttke** [jitsi/lib-jitsi-meet#1604]
## Description

Unable to install jitsi-meet-tokens (for JWT token auth)

I am using a fresh Jitsi install:

```
root@h2884530:~# dpkg -l | grep jitsi
ii  jitsi-meet                      2.0.5765-1                               all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.4900-1                               all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.4900-1                               all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.4900-1                               all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.4900-1                               all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2              2.1-478-gc6da57bd-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)
root@h2884530:~# dpkg -l | grep prosody
ii  jitsi-meet-prosody              1.0.4900-1                               all          Prosody configuration for Jitsi Meet
ii  prosody                         0.10.0-1build1                           amd64        Lightweight Jabber/XMPP server
```

## Current behavior

```
root@h2884530:~# apt-get install jitsi-meet-tokens
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 jitsi-meet-tokens : Hängt ab von: prosody-trunk (>= 1nightly747) ist aber nicht installierbar oder
                                    prosody-0.11 ist aber nicht installierbar oder
                                    prosody (>= 0.11.2) aber 0.10.0-1build1 soll installiert werden
```

Sorry for the German messages. It says "unsatisfied dependencies".

## Expected Behavior

Package should install cleanly.

## Possible Solution

JITSI installed Prosody 0.10.0-1build1.
Why didn't it install a better version? (>=0.11.2?)

## Steps to reproduce

Use apt to install Jitsi on a fresh Linux machine.

# Environment details

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
2019112700
```

**Comment by damencho** [comment]
Please, when you have questions and problems use the community forum before opening new issues, thank you.

You need to update your prosody as pointed in the messages. 

> Why didn't it install a better version? (>=0.11.2?)

Cause the repositories you use do not have it. You need to go to the prosody site and follow their instructions for the update. There are number of posts in the forum describing the process. https://community.jitsi.org/t/how-to-how-do-i-update-prosody/72205

**Comment by wuttke** [comment]
Thanks for the quick response. I think a pointer/link to these helpful instructions is necessary, both in the outdated tokens documentation (https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md - here it is recommended to installing an old nightly build) and in the installation guide (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart - here there is no indication that it might be beneficial to install a more recent prosody version first as compared to the one the jitsi package installs automatically).
