### ISSUE TITLE
SDP AudioStream codec parameter typo-error

### ISSUE THREAD

**Issue by 403262617** [jitsi/lib-jitsi-meet#1624]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, I checked community.jitsi.org to see if the same or similar bugs have already been discussed. (https://community.jitsi.org/t/opusmaxaveragebitrate-not-working-anymore-in-2-0-5870/99680)

## Description
In latest version 2.0.5870, `opusMaxAverageBitrate` is not effective to control audio quality (OPUS bitrate) in `config.js` due to a typo-error causing browser not recognize it.

## Current behavior
OPUS bitrate will use browser's default value in WebRTC.

## Expected Behavior
OPUS bitrate is controlling in `config.js` by option `opusMaxAverageBitrate`.

## Possible Solution
Correct somewhere there having a typing-error code.

## Steps to reproduce
Create 2 servers with latest and older version separately, and configured the `opusMaxAverageBitrate` option to use developer tool to watch the WebRTC stats.

# Environment details
Chrome browser, both Windows and macOS operating system

# Screenshots for more details
Latest version
<img width="800" alt="Screen Shot 2021-05-28 at 5 25 12 PM" src="https://user-images.githubusercontent.com/24491069/119965018-61d52100-bfdc-11eb-8bd6-310b6c42a65b.png">

Older version
<img width="750" alt="Screen Shot 2021-05-28 at 5 23 55 PM" src="https://user-images.githubusercontent.com/24491069/119964975-5550c880-bfdc-11eb-85b7-20d7c00b9040.png">

**Comment by jallamsetty1** [comment]
@muscat1 can you please take a look at this ?

**Comment by damencho** [comment]
Fixed with a2560f9
