### ISSUE TITLE
Duplicate audio in p2p on mobile

### ISSUE THREAD

**Issue by Jacky-Rolo** [jitsi/lib-jitsi-meet#1631]
## Description: Duplicate audio in p2p on mobile

Hello,

We are encountering some issues with the latest releases of **lib-jitsi-meet on mobile**. When two participants are in the room, the audio is duplicated and slightly time shifted, creating an echo effect. We have observed the shift to be up to a few seconds. As soon as a third participant joins the call, the duplicated tracks disappear and the audio appears normal. However the audio would be duplicated again once the third person leaves.

We have tried rolling back through the different versions of the library to pinpoint when this appeared. The issue appears on [release 5515](https://github.com/jitsi/lib-jitsi-meet/releases/tag/jitsi-meet_5515), and is not reproducible on [release 5513](https://github.com/jitsi/lib-jitsi-meet/releases/tag/jitsi-meet_5513). The [diff between these](https://github.com/jitsi/lib-jitsi-meet/compare/jitsi-meet_5513...jitsi-meet_5515) show a [single commit](https://github.com/jitsi/lib-jitsi-meet/commit/c534f748849a308d08b06e306f5a66709ccae056) related to video contraints.

The issue is not reproducible when running inside of a web browser on desktop. On all our tests on mobile, we have fixed the react-native-webrtc version to 1.89.2 so it seems not to be at fault here.

We have been able to successfully **reproduce** the issue on the **official Jitsi iOS client (21.1.0)**. It therefore seems that our own client code is not at fault here.

The issue only appears when `p2p.enabled` is set to `true`, when it is set to `false` the issue does not appear. It seems to be an issue with p2p. When the 3rd user leaves the call it also takes a bit of time before the audio gets duplicated, looks like the time needed to switch back to p2p, which points in the same direction.

As the pinpointed commit has some relation with video constraints, here are the contraints used on our side during testing.

```json
{
  "resolution": 360,
  "fps": 25,
  "constraints": {
    "video": {
      "height": { "ideal": 720, "max": 720, "min": 180 },
      "width": { "ideal": 1280, "max": 1280, "min": 320 },
      "aspectRatio": 16 / 9,
    },
  },
};
```

## Current behavior
In 1-1 call (p2p ), the audio is duplicated and slightly time shifted, creating an echo effect.

## Expected Behavior
the audio should not have echo effect.

## Steps to reproduce
Start a 1-1 call on the official Jitsi iOS client (21.1.0)  (both user using iOS, I did NOT test Android)
- you can join third user to the call, echo effect will disappear  
- when third user leave, and wait a while, echo effect will appear again

### community jitsi 
I posted this issue to community, currently, no one reply now. so I forward to here.
- https://community.jitsi.org/t/duplicate-audio-in-p2p-on-mobile/100551

**Comment by Jacky-Rolo** [comment]
I tested official Jitsi iOS client (21.2.0) today, CAN NOT re-produce echo issue ...

**Comment by Jacky-Rolo** [comment]
> I tested official Jitsi iOS client (21.2.0) today, CAN NOT re-produce echo issue ...

I tested one more time today, official Jitsi iOS client (21.2.0) echo issue happen again.

**Comment by saghul** [comment]
What audio device are you using when testing?

**Comment by Jacky-Rolo** [comment]
> What audio device are you using when testing?

iPhone 6s and iPhone X, this is what you are asking  ?   

feel FREE to ask me anything or do any test, many thanks !!!

**Comment by saghul** [comment]
I mean, are you using the speaker or some bluetooth audio device for example?

**Comment by Jacky-Rolo** [comment]
> I mean, are you using the speaker or some bluetooth audio device for example?

Both side are speaker.

We just did another test, can NOT re-produce now ...

**Comment by saghul** [comment]
We made no change that could explain what you are observing.

**Comment by erengms** [comment]
We are having the same issue on iOS devices.

**Comment by Jacky-Rolo** [comment]
Hi @atomjump , @erengms 

Can you also post some detail to  https://community.jitsi.org/t/duplicate-audio-in-p2p-on-mobile/100551  
or post new post

I feel, core team did NOT spend too much time on github issue

many thanks

**Comment by suraj-desai** [comment]
Hi, @Jacky-Rolo @erengms @atomjump 
I am trying to integrate lib-jitsi-meet in react native project. I am not able to find any documentation regarding it.
If u can point me to the documentation or help me in getting started or point me to any working repo, would be much appreciated.
Thanks

**Comment by Jacky-Rolo** [comment]
you need more explicit what's you looking for ? 

To integrate jitsi, official project is a workable example
- https://github.com/jitsi/jitsi-meet

**Comment by saghul** [comment]
This issue was fixed in https://github.com/jitsi/lib-jitsi-meet/commit/a8e3a5748902c26ca9cf2ffcd078b2cec16e3216

**Comment by atomjump** [comment]
Hi Saghul, has this change been brought live on Jitsi Meet /the Jitsi appstore, yet?  We tested it this morning from one Android phone to another (both running the latest public version of the app), and it still seemed to have the echo.

**Comment by saghul** [comment]
This is fixed in the apps version 22.0.1. Android is rolling out but it's not fully rolled out yet, so make sure you check the version, you might have not received the update yet. We hope to complete the rollout this week.

**Comment by f8122dac91** [comment]
I have been experiencing this on Android since December last year. Currently I am using v23.6.1 on Android 14 on a Google Pixel 5a device.

**Comment by saghul** [comment]
Unlikely to be the same issue. Any chance it's echo?
