### ISSUE TITLE
The remoteTrack.videoType is undefined for share screen tracks

### ISSUE THREAD

**Issue by thanhtuyenpkk** [jitsi/lib-jitsi-meet#1641]
when start share screen i have a track
my code

> handleTrackAddedEvent(track) {
> 		if (track.isLocal()) {
> 			return;
> 		}
> 		if (track.type === 'video') {
> 			console.log('222', track, track['videoType'], track.videoType, track.videoType === 'desktop');
> 		} else if (track.type === 'audio') {
> 			handleTrackAdded(track, this.props);
> 		}
> 	}
> 

my console log
> h {_events: {…}, _eventsCount: 3, _maxListeners: undefined, addEventListener: ƒ, off: ƒ, …}addEventListener: ƒ (e,t)audioLevel: -1conference: ae {eventEmitter: a, options: {…}, eventManager: b, participants: {…}, connection: c, …}containers: [video#remote-video-b2ead142]disposed: falsehandlers: Map(0) {}hasBeenMuted: trueisP2P: truemuted: falseoff: ƒ (e,t)ownerEndpointId: "b2ead142"removeEventListener: ƒ (e,t)rtc: T {eventEmitter: a, on: ƒ, addEventListener: ƒ, off: ƒ, removeEventListener: ƒ, …}ssrc: 1744477009stream: MediaStream {muted: false, id: "b950d184-e957-46fe-b079-9ac58a568b88-1", active: true, onaddtrack: ƒ, onremovetrack: ƒ, …}track: MediaStreamTrack {kind: "video", id: "2d8642f4-5ce2-41ab-bbae-c5d4e09ca69f-1", label: "2d8642f4-5ce2-41ab-bbae-c5d4e09ca69f-1", enabled: true, muted: false, …}**type: "video"videoType: "desktop"**_containerHandlers: {abort: ƒ, canplay: ƒ, canplaythrough: ƒ, emptied: ƒ, ended: ƒ, …}_events: {track.trackMuteChanged: Array(2), track.audioLevelsChanged: ƒ, track.videoTypeChanged: ƒ}_eventsCount: 3_maxListeners: undefined_streamInactiveHandler: ()=>{}__proto__: h **undefined undefined false**

but when i get videoType  of remoteTrack it is undifined i don't know why?
any body can't help me

**Comment by thanhtuyenpkk** [comment]
i turn off p2p this work

**Comment by jadhavsaurabh** [comment]
> i turn off p2p this work

@thanhtuyenpkk How did you solved this issue?
