### ISSUE TITLE
Black screen on iOS, but its working on Android OS

### ISSUE THREAD

**Issue by coolman200** [jitsi/lib-jitsi-meet#1644]
The same title, I use Vue to develop web app but its working on Android OS then iOS is failed. 

![1624425397018](https://user-images.githubusercontent.com/52725981/123050398-3d316500-d433-11eb-9696-835fd97c6113.jpg)

As picture, iOS always show black screen, can anyone help ? 

Thanks a lot.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues. Thank you.
