### ISSUE TITLE
How to setting mute everyone in server site

### ISSUE THREAD

**Issue by thanhtuyenpkk** [jitsi/lib-jitsi-meet#1648]
Hi im install jitsi in ec2. but in my sever when join conference 
fisrt user is moderator, this user can mute every one
but seconds user, third user .... is not moderator they can't see option mute every one

I found my problem but don't know to how sett all user are moderator on sever to mute every one.
Any body can't help me this problem
Thanks you.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
You need to enable https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_allowners.lua

**Comment by thanhtuyenpkk** [comment]
@damencho how to enable, ex number line code
mod_muc_allowners.lua  i see it is default file

**Comment by damencho** [comment]
Put it in the module of the main conference muc here:
https://github.com/jitsi/jitsi-meet/blob/52ee9b5151a0f1768fadb38224b42fdeaafdd485/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L66

Just add "muc_allowners".
