### ISSUE TITLE
Meta: TypeScript

### ISSUE THREAD

**Issue by saghul** [jitsi/lib-jitsi-meet#1683]
The writing was on the wall, but this post made it clear: https://medium.com/flow-type/clarity-on-flows-direction-and-open-source-engagement-e721a4eb4d8b Flow is not for us.

Thus, we are going to start migrating this library to TypeScript.

This won't happen overnight, the plan is to do it gradually. In https://github.com/jitsi/lib-jitsi-meet/pull/1682 I adapted the build system to use Webpack 5 so we can use ts-loader. The library will thus be offered in 2 flavors: umd as before, compiled with Webpack, and as an es6 module, compiled with TSC.

I have integrated the handmade types from https://github.com/jitsi/lib-jitsi-meet/pull/1503 here too. Thanks a lot @garyhuntddn ! Also, thanks @sapkra for starting the discussion in https://github.com/jitsi/lib-jitsi-meet/pull/1027

Once this lands we can hopefully migrate the library little by little.

**Comment by garyhuntddn** [comment]
Just seen that you e been doing a load of work on this - @saghul would you be up for a chat about how I can help out in the next steps?

**Comment by saghul** [comment]
Oh, I forgot we kept this open! The first bits of TS code have already made it to the repo and the plan going forward is to write new code in TS and migrate the old one eventually.

Thanks for your help with the types!

If you think there is room for further improvements please open an issue and let's look at them! At least the core part is done now.

**Comment by garyhuntddn** [comment]
Not sure if this is true of anyone else - but I get this issue pinned at the top of the issues list. I'd have thought it would have disappeared when you closed it and I can't seem to get rid of it.

Is the pinned option something you control?

**Comment by saghul** [comment]
Yep we can set the pinned issues. Now that this is closed and work is underway I'll close this.
