### ISSUE TITLE
Some participants can't hear others

### ISSUE THREAD

**Issue by c0m1t** [jitsi/lib-jitsi-meet#1693]
## Description
Sometimes, some participants cannot hear others audio. This does not happen always.

The participants get the following error:
```
Error: replace track failed
```
Seems like `_findTransceiver` returns `null`.

```
2021-08-23T10:09:26.998Z [modules/RTC/JitsiLocalTrack.js] <y._setStream>:  Setting new MSID: 18d4c9f8-5b45-404b-a4c1-96292aee9c83 c9a3fccd-4a92-4a41-a1bc-580e344c6c46 on LocalTrack[undefined,audio]
arguments: ["2021-08-23T10:09:26.998Z","[modules/RTC/JitsiLocalTrack.js]","<y._setStream>: ","Setting new MSID: 18d4c9f8-5b45-404b-a4c1-96292aee9c83 c9a3fccd-4a92-4a41-a1bc-580e344c6c46 on LocalTrack[undefined,audio]"]
logger: console
2021-08-23T10:09:27.029Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=JVB,initiator=false,sid=9e167nh5m18g0] Replace track error: Error: replace track failed
arguments: ["2021-08-23T10:09:27.029Z","[modules/xmpp/JingleSessionPC.js]","<Object.callback>: ","JingleSessionPC[session=JVB,initiator=false,sid=9e167nh5m18g0] Replace track error:",{"message":"replace track failed","name":"Error","stack":"Error: replace track failed\n    at h.replaceTrack (https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:1:256474)\n    at w.replaceTrack (https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:17:54128)\n    at n (https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:1:238524)\n    at a._processQueueTasks (https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:10:207065)\n    at process (https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:17:8022)\n    at https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:25:15307\n    at m (https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:25:15422)\n    at a (https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:25:14780)"}]
logger: console
error
10:09:27
2021-08-23T10:09:27.034Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Error: replace track failed Script: null Line: null Column: null StackTrace:  Error: Error: replace track failed
    at https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:10:45725
    at async https://room.domain/libs/app.bundle.min.js?v=sync-libjitsimeet-28aug:48:394956
    at async Promise.all (index 0)
    at async Promise.all (index 0)
arguments: ["2021-08-23T10:09:27.034Z","[JitsiMeetJS.js]","<Object.getGlobalOnErrorHandler>: ","UnhandledError: Error: replace track failed","Script: null","Line: null","Column: null","StackTrace: ","Error: Error: replace track failed\n    at https://room.domain/libs/lib-jitsi-meet.min.js?v=sync-libjitsimeet-28aug:10:45725\n    at async https://room.domain/libs/app.bundle.min.js?v=sync-libjitsimeet-28aug:48:394956\n    at async Promise.all (index 0)\n    at async Promise.all (index 0)"]
logger: console
10:09:27
exception
Error: Error: replace track failed
```

**Comment by Maders** [comment]
@jallamsetty1, your comment will be highly insightful for us to resolve the issue. 😊

**Comment by jallamsetty1** [comment]
@c0m1t Can you please be more specific about what is happening ? Are you saying that when this error is seen on a particular user, all other participants are not able to hear this user ? If so, can you please provide us the steps to reproduce this issue and add the browser details as well.

**Comment by c0m1t** [comment]
@jallamsetty1  We updated `lib-jitsi-meet` to the latest stable version and that error in logs is gone but the problem persists in some way. In a conference that are more than 12 people, the problem occurs. Here's what happens usually:
The user who has joined the conference as the 13th person(or more) tries to unmute, the mute indicator locally changes but for remote participants, he/she will still remain muted, with mute indicator shown on the filmstrip. There is no error in the client logs and apparently `lib-jitsi-meet` successfully mutes/unmutes the local participant but others cannot be notified and no audio track is sent.
Can this be an integration problem between `lib-jitsi-meet` and `jicofo` or `jvb` modules?

**Comment by jallamsetty1** [comment]
> @jallamsetty1 We updated `lib-jitsi-meet` to the latest stable version and that error in logs is gone but the problem persists in some way. In a conference that are more than 12 people, the problem occurs. Here's what happens usually: The user who has joined the conference as the 13th person(or more) tries to unmute, the mute indicator locally changes but for remote participants, he/she will still remain muted, with mute indicator shown on the filmstrip. There is no error in the client logs and apparently `lib-jitsi-meet` successfully mutes/unmutes the local participant but others cannot be notified and no audio track is sent.
> 
> Can this be an integration problem between `lib-jitsi-meet` and `jicofo` or `jvb` modules?

Can you check if the 13th participant sends a source-add to Jicofo when they unmute ? Also only when Jicofo advertises this new source to the other participants in the call via a source-add, they will be able to see the other participant as unmuted.  Is your Jicofo/JVB running the latest version as well ?

**Comment by c0m1t** [comment]
@jallamsetty1 Thank you. We haven't been able to fix this issue but it turned out it's probably because of our `jitsi-meet` project which is not updated to the latest version; we used the latest stable version of jitsi, without our changes, and the audio problem was gone.
