### ISSUE TITLE
latest lib-jitsi-meet has issues.

### ISSUE THREAD

**Issue by AjayShivanagol** [jitsi/lib-jitsi-meet#1722]
I am at the master branch and if I do **npm install** I am getting the following error.
cc @jallamsetty1 
![Screenshot from 2021-09-21 20-36-43](https://user-images.githubusercontent.com/29257275/134196913-e4eaf095-ff98-4b24-adbf-993fd8ef362d.png)

**Comment by AjayShivanagol** [comment]
I hope the following PR created an issue https://github.com/jitsi/lib-jitsi-meet/pull/1721
CC @tmoldovan8x8

**Comment by damencho** [comment]
@saghul @tmoldovan8x8 Can you take a look, I confirm master is broken.
