### ISSUE TITLE
Uncaught TypeError: Cannot destructure property 'id' of 'undefined'

### ISSUE THREAD

**Issue by mnasyrov** [jitsi/lib-jitsi-meet#1755]
## Description

I've got a user report with the error: 

```
TypeError: Cannot destructure property 'id' of 'undefined' as it is undefined.
    at Object.Yt.isReactNative.getStreamID ([REMOVED]/main.34a3d636.js:257:385988)
    at Function.getStreamID ([REMOVED]/main.34a3d636.js:257:468312)
    at Xo._remoteTrackAdded ([REMOVED]/main.34a3d636.js:257:433634)
    at Xo._usesUnifiedPlan.onTrack ([REMOVED]/main.34a3d636.js:257:427928)
    at RTCPeerConnection.s ([REMOVED]/main.34a3d636.js:257:656464)
```

<img width="1791" alt="Screenshot 2021-10-15 в 12 52 01" src="https://user-images.githubusercontent.com/445680/137474346-1b111478-b337-433a-8012-d1533a0cc4bb.png">

---

## Current behavior

Remote media tracks are not added.

---

## Possible Solution

It seems like a handler of `track` event of PeerConnection should be ready to get empty `streams` array. 

The current handler in `modules/RTC/TraceablePeerConnection.js`
```
        this.onTrack = evt => {
            const stream = evt.streams[0];

            this._remoteTrackAdded(stream, evt.track, evt.transceiver);
            stream.addEventListener('removetrack', e => {
                this._remoteTrackRemoved(stream, e.track);
            });
        };
        this.peerconnection.addEventListener('track', this.onTrack);
```

---

## Steps to reproduce

Unknown steps

---

# Environment details

- lib-jitsi-meet, tag 1265
- Yandex Browser 20.2.0.1145 (64-bit), MacOS

---

**Comment by vany-egorov** [comment]
Got same issue with YandexBrowser.

**Comment by bukharin** [comment]
Could not reproduce on Yandex.Browser 21.9.0.1488 (64-bit) MacOS

**Comment by mnasyrov** [comment]
@saghul What about the issue which @bukharin found with Safari 13? It seems like the same one.
More details here: https://github.com/jitsi/lib-jitsi-meet/issues/1713#issuecomment-921522229
