### ISSUE TITLE
Layer suspension broken in latest lib-jitsi-meet

### ISSUE THREAD

**Issue by bukharin** [jitsi/lib-jitsi-meet#1759]
## Description

`lib-jitsi-meet` does not suspend simulcast layers when JVB signals `idealHeight: 0`. Seems starts from [this refactoring](https://github.com/jitsi/lib-jitsi-meet/commit/d27a510f844562ef8e25a10ae655d103227ec7ac)

``` json
{"colibriClass":"SenderVideoConstraints", "videoConstraints":{"idealHeight":0}}
```

## Current behavior

Does not suspend any layer

## Expected Behavior

`lib-jitsi-meet` should suspend all layers when receive `idealHeight: 0` from JVB

**Comment by jallamsetty1** [comment]
Thanks for the report, I have identified the issue and will be opening a PR soon.
