### ISSUE TITLE
There is no video occasionally when Android is involved（有安卓参与的情况下偶发无影像）

### ISSUE THREAD

**Issue by zsinba** [jitsi/lib-jitsi-meet#1782]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
This is a rather strange phenomenon, and this problem only occurs on Android systems.
Windows10 and IOS15.X meetings, everything is normal;
Android and Windows10 participate in the conference, occasionally there is no Android image on Windows10;
Android and IOS15.X participated in the meeting, occasionally there is no Android image under IOS;
Whether it is a one-to-one meeting or a one-to-many meeting, only Android will have this problem. Windows, Mac, and iOS do not have this problem.
Android version: 9 and 10;
Windows version: 10 and 11;
Chrome version: 92 major version;
iOS version: 15 major versions;

--
这是一个比较奇怪的现象，仅在安卓系统上面会有这个问题。 
Windows10 和 IOS15.X会议 , 一切都是正常的；
Android与Windows10参会，偶发的在Windows10上面没有安卓的影像；
Andorid与IOS15.X参会，偶发的在IOS下面没有安卓的影像；
这不管是一对一的会议，还是一对多的会议，仅安卓会出现这个问题。Windows、Mac，iOS都不会有这个问题。
安卓版本：９和１０；
Windows版本：10和11；
Chrome版本：92大版本；
iOS版本：15大版本；

## Current behavior
---
There is not too much operation, just enter the meeting through the URL. Whether the meeting password is used or not has no effect on the results. I have tried them all.

## Expected Behavior
---
It works.
## Possible Solution
---
Under the Android browser, there is an issue in getting the camera stream and transmitting or receiving.

## Steps to reproduce
---
In the case of using libjs, this problem is relatively easy to reproduce

# Environment details
---
Android version: 9 and 10;
Windows version: 10 and 11;
Chrome version: 92 major version;
iOS version: 15 major versions;

**Comment by zsinba** [comment]
This problem has nothing to do with the Windows version, Chrome version, iOS version, and Mac version. It is a phenomenon that has appeared in the past year. There was no such issue before.

**Comment by saghul** [comment]
Please provide browser console logs for the failing device, it's virtually impossible to help you otherwise.

**Comment by zsinba** [comment]
The problem seems to have disappeared.  After the upgrade, this problem did not occur again.
