### ISSUE TITLE
P2P failures with Google Chrome 96

### ISSUE THREAD

**Issue by NewEraCracker** [jitsi/lib-jitsi-meet#1793]
After updating from Google Chrome 95 to 96 (automatic update) these error messages started appearing.

![image](https://user-images.githubusercontent.com/416945/142459207-525def29-31ff-42b1-a587-8c942ef62a26.png)

If I revert the virtual machine to Google Chrome 95 and do calls before Chrome updates itself, then there are none of these errors.

Custom application using lib-jitsi-meet 
Google Chrome 96.0.4664.45

**Comment by saghul** [comment]
PIng @jallamsetty1

**Comment by NewEraCracker** [comment]
I've tried to reproduce this again in the virtual machine without success. I wonder if this is caused by some experiment that Google enables for a percentage of the users.

Working Google Chrome 95 offer: https://pastebin.com/gmb5fR2k

Seems to work Google Chrome 96 offer: https://pastebin.com/ap5cwdXG

Causes the error above offer: https://pastebin.com/MVrJKKz2

**Comment by NewEraCracker** [comment]
I was looking online and found this list of H264 codecs: https://gist.github.com/eladkarako/119e91525d34db9f61cca23b18fd62a0

The good offers only include `profile-level-id=42` while the bad offer has `profile-level-id=4d` and `profile-level-id=64`

**Comment by jallamsetty1** [comment]
@NewEraCracker When you hit the issue can you please capture the browser console logs also the meet logs by executing `APP.conference.saveLogs(); ` on the console ? This should automatically download a JSON file that has the SDPs to your local machine. These 2 logs will help us identify what the issue is, thanks!

**Comment by NewEraCracker** [comment]
[meetlog.txt](https://github.com/jitsi/lib-jitsi-meet/files/7572351/meetlog.txt)

**Comment by fippo** [comment]
there is this rtx codec with id 117
```
a=fmtp:117 apt=124
```
point to 124 which is
```
a=rtpmap:124 ulpfec/90000
```

Do chrome logs show something along the lines of 
```
ERROR:webrtc_video_engine.cc(3421)] RTX PT=120 not mapped to regular video codec or RED codec (PT=127).
```
(with different payload types)? There seems to be a bug that makes rtx refer to ulpfec but so far i haven't been able to pin it down.

**Comment by NewEraCracker** [comment]
@fippo Can you point me to how to collect Chrome logs? Is there maybe a workaround for disabling these faulty codecs on Chrome 96 so p2p can work with alternative ones?

**Comment by fippo** [comment]
https://support.google.com/chrome/a/answer/6271282?hl=en has some instructions.
https://webrtc.github.io/webrtc-org/native-code/logging/ is better but a bit dated.

**Comment by NewEraCracker** [comment]
I reproduce this in meet.jit.si

```
[5020:6384:1201/084553.165:ERROR:webrtc_video_engine.cc(3402)] RTX PT=117 not mapped to regular video codec or RED codec (PT=124).
[5020:6384:1201/084553.167:ERROR:webrtc_video_engine.cc(1178)] GetChangedRecvParameters called without any video codecs.
[5020:6384:1201/084553.169:ERROR:sdp_offer_answer.cc(4281)] Failed to set local video description recv parameters for m-section with mid='1'. (INVALID_PARAMETER)
[5020:6376:1201/084553.172:ERROR:sdp_offer_answer.cc(1944)] Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'.
```

And here's the jingle triggering the error: https://pastebin.com/NXqpR8ZB

**Comment by aninditasadhukhan** [comment]
Hi can you please update how can I resolve this issue? My jitsi meet version is 2.0.6173-1.

Conference call is not working in Google Chrome version 96. Remote user is showing audio/video muted, but originally it is unmuted. Can you please give some light on this? Also call is not ended properly, I am facing camera access issue as well.

Please let me know how can I fix this issue.

Thanks for your cooperation.

**Comment by jallamsetty1** [comment]
@aninditasadhukhan Are you able to reproduce this on meet.jit.si ? I am not running into the same issue with Chrome 96.0.4664.55 on macOS 11.6.

**Comment by NewEraCracker** [comment]
This seems specific to Chrome 96.0.4664.45 running on Windows systems.
Edge and Opera don't seem to be affected. Also tested Chrome 97 Beta and all works fine there.

@aninditasadhukhan Your issue may be different, maybe this fix is needed: https://github.com/jitsi/lib-jitsi-meet/pull/1798/files and confirm that you are using latest version of lib-jitsi-meet.

**Comment by aninditasadhukhan** [comment]
Nope I am not be able to reproduce it in meet.jit.si. But my self hosted application was working properly for 5 months in google chrome previous version. But from today my google chrome version upgraded to 96. In the updated version the application is not working. In the conference audio video is not coming Windows 10 desktop google chrome version 96 it is not working. It is working in firefox

**Comment by aninditasadhukhan** [comment]
> This seems specific to Chrome 96.0.4664.45 running on Windows systems. Edge and Opera don't seem to be affected. Also tested Chrome 97 Beta and all works fine there.
> 
> @aninditasadhukhan Your issue may be different, maybe this fix is needed: https://github.com/jitsi/lib-jitsi-meet/pull/1798/files and confirm that you are using latest version of lib-jitsi-meet.

@NewEraCracker: Thanks for your response. My lib-jitsi-meet is not the updated one. Can you please confirm if I upgrade lib-jitsi-meet to latest version the will it be compatible to jitsi-meet version 2.0.6173-1

**Comment by NewEraCracker** [comment]
@aninditasadhukhan It should work, however I recommend you check first in a staging environment. A thing to note is Google Chrome 96 removes plan-b support. Check that you are not using plan-b.

**Comment by DanielMcAssey** [comment]
To provide a bit of context @aninditasadhukhan the fix I have a PR open for was because a later version of lib-jitsi-meet changed how video types were sent to the JVB and only affects a video track which was added to the conference in a muted state, it most likely doesnt affect the standard jitsi meet instance, however if you have a custom implementation and you recently upgraded your JVB it may be the reason, however I dont think its related to this issue regarding Chrome 96.

**Comment by aninditasadhukhan** [comment]
> To provide a bit of context @aninditasadhukhan the fix I have a PR open for was because a later version of lib-jitsi-meet changed how video types were sent to the JVB and only affects a video track which was added to the conference in a muted state, it most likely doesnt affect the standard jitsi meet instance, however if you have a custom implementation and you recently upgraded your JVB it may be the reason, however I dont think its related to this issue regarding Chrome 96.

Nope I did not upgrade JVB. It was running in google chrome older versions for 5-6 months. But in google chrome 96 audio video is absolutely not working.

**Comment by jbg** [comment]
@aninditasadhukhan If you are using an old version of lib-jitsi-meet you are probably using plan-b which Chrome 96 removed support for. If this is the problem you will see errors in the browser console referring to Plan B. The solution is to update lib-jitsi-meet.

**Comment by NewEraCracker** [comment]
Still an issue with latest Google Chrome **96.0.4664.93** on Windows

**Comment by NewEraCracker** [comment]
I apply this patch on lib-jitsi-meet and p2p works: https://pastebin.com/aVUSXHwW

Sharing this information for public interest and disclaiming any copyrights or warranties explicit or implied.

**Comment by aninditasadhukhan** [comment]
I am facing one issue in chrome 96 after upgrading lib-jitsi-meet to latest version. In a lobby enabled room when user tried to log in after accepting/rejecting the user "Knocking Participant list" pop up is not disappearing. It is freezing in the screen. Could you please help e in this regards? I am really not getting any solutions to fix this issue.

**Comment by aninditasadhukhan** [comment]
I am getting below errors in browser console.

2021-12-09T12:01:20.929Z [JitsiConference.js] <p2pJingleSession.terminate.reason>:  An error occurred while trying to terminate P2P Jingle session {code: undefined, reason: 'item-not-found', msg: 'Recipient not in room', session: 'JingleSessionPC[session=P2P,initiator=true,sid=327261fc8d5b]'}

**Comment by NewEraCracker** [comment]
After investigation most likely the error by @aninditasadhukhan is caused by this commit: 5a4232f9083fd1ef49c89fb164afdd9aff23dcaa where _stopP2PSession had its parameter format refactored.

For fix I suggest the following change on JitsiConference.js
```            if (reason) {```
to:
```            if (options.reason) {```

The effects, for the moment are just an error message that should not be there.

@saghul Please have a look. Thanks!

**Comment by saghul** [comment]
`reason` is destructured here: https://github.com/jitsi/lib-jitsi-meet/blob/8aa35dae401f32a7eafe2b7dec159827c4bb2a84/JitsiConference.js#L3552

So the variable will be defined at that point. Do you have a traceback?

**Comment by NewEraCracker** [comment]
What I am saying is prior to the refactor, at this point **reason** would in most cases be undefined: https://github.com/jitsi/lib-jitsi-meet/blob/8aa35dae401f32a7eafe2b7dec159827c4bb2a84/JitsiConference.js#L3599

After the refactor this is, if undefined, set to 'success'. I guess you could check for (reason !== 'success') also to avoid the error message.

**Comment by saghul** [comment]
Ah, I see what you mean now. Yep, will fix.

**Comment by aninditasadhukhan** [comment]
> Ah, I see what you mean now. Yep, will fix.

Please let me know what is the fix. I am stuck with this. Thanks,

**Comment by saghul** [comment]
Note this will remove the harmless error message, there will be no other functional change.
