### ISSUE TITLE
Cannot switch between authenticated conferences (Settings.js bugs)

### ISSUE THREAD

**Issue by champtar** [jitsi/lib-jitsi-meet#18]
Hi,

When using authenticated conferences, jicofo checks if "machineID" == "machineID in session".
"sessionid" is stored in localStorage, "jitsiMeetId" (machineID) is stored in localStorage but per conference, so you get a new one per conference,and you cannot switch conference because you hit https://github.com/jitsi/jicofo/blob/86fdbf031cab144f672c472e609cd56c0aded1e6/src/main/java/org/jitsi/jicofo/auth/AbstractAuthAuthority.java#L464

sessionid and jitsiMeetId need to be together (preferably global and not per conference)

Also Settings.js exists in both lib-jitsi-meet and jitsi-meet, maybe we should rename or delete one of them.

**Comment by paweldomas** [comment]
Hi ! Thanks for the report we have this one on our schedule.

**Comment by paweldomas** [comment]
It should be fixed now !

**Comment by champtar** [comment]
Thanks, will try tomorrow
