### ISSUE TITLE
participant.setRole is not a function

### ISSUE THREAD

**Issue by p-fruck** [jitsi/lib-jitsi-meet#1800]
I might be mistaken here because I am using the unfinished typescript definitions, but even looking at the js code of lib-jitsi-meet I cannot find the issue

## Description
---
I want to update the role of a given participant to moderator, which does not work currently. I'd like to use following code:
```ts
    const participant = conference.getParticipantById(participantId);
    console.info(participant);
    console.info(participant.setRole);
    participant.setRole('moderator');
```

## Current behavior
---
- The participant object is logged
- The participant role is logged as `undefined`
- invoking `participant.setRole('moderator')` results in an error

## Expected Behavior
---
The `setRole` function should be available to use on the participant

## Possible Solution
---

## Steps to reproduce
---
Initialize a conference and use the above code

# Environment details
---
Tested on a public jitsi instance using `lib-jitsi-meet v4628`

**Comment by p-fruck** [comment]
Seems like the error was related to an outdated jitsi instance. What really confuses me though is the fact that `setRole` doesn't 'really' update the role, but instead `grantOwner()` is used to set the... umm... `'moderator'` role? Is there some documentation out there which explains how the `'owner'` role (which doesn't seem to exist inside the user object?) differs from the `'moderator'` role?

**Comment by damencho** [comment]
https://xmpp.org/extensions/xep-0045.html#affil
https://xmpp.org/extensions/xep-0045.html#roles

**Comment by damencho** [comment]
This is a server-side operation and the change in affiliation and role is received back from the server and set role changes local state to reflect server-side state.

**Comment by p-fruck** [comment]
Ok I see, I will investigate further issues using the xmpp docs. Thank you!
