### ISSUE TITLE
Screen Sharing Issue

### ISSUE THREAD

**Issue by tiofabby** [jitsi/lib-jitsi-meet#1821]
Hi, I upgraded to a recent version of lib-jitsi-meet (e9e3709) and screen sharing stopped working. The video of desktop being shared is not showing up on other participant screens. My code is very similar to default example.js file.

There are no warning or error showing up when switching from cam to desktop in `switchVideo()` or from `onRemoteTrack()` when receiving the updated track, it just look like the new stream of video/desktop received by participants is kind of empty.

By looking in more details into `track` object in console, we can see that 1rst time we receive it the `MediaStreamTrack.muted` is **false**, but when user switches, the new track received has such field set to **true**. Could it be the reason why nothing is being shown up and stream is empty? See below a screenshot of such difference from one same user receiving a remoteTrack for video/cam and then for video/desktop (from same part.):

![IssueSharing](https://user-images.githubusercontent.com/9844354/145445702-2922bb65-1a8c-4a09-ade2-05739f6159ba.png)

1. Could such field explained why the stream is empty and nothing shows for the video/desktop of participant?
2. If it does, can we force such field to be true when switching video? So other participants receive it correctly set up?
3. If not, any idea what could be happening?

Thank you
Fabrice

**Comment by DanielMcAssey** [comment]
Could be related? https://github.com/jitsi/lib-jitsi-meet/pull/1798

**Comment by tiofabby** [comment]
Hi @DanielMcAssey and @damencho 
Looks like this one may be related indeed to #1798 . So I tried as suggested by @damencho in 1798 to run the latest commit from master (8aa53da , 2021/12/10)  to see if the fix added was fixing the screen sharing issue but looks like it is not, see screenshot below, my Video/Desktop stream is still received empty (muted) and nothing get displayed for participants:

![image](https://user-images.githubusercontent.com/9844354/145545765-e9fd28b0-6976-40dd-8dd5-57f381b52131.png)

I feel grateful you guys are helping on that
Thank you
Fabrice

**Comment by tiofabby** [comment]
This issue just disappeared when fixing another wss connection issue between Client and Jitis platform. Closing the issue then.
