### ISSUE TITLE
JingleSessionPC setVideoCodecs task failed error

### ISSUE THREAD

**Issue by denis-ionov** [jitsi/lib-jitsi-meet#1828]
Got error 
`
2021-12-20T10:25:55.360Z [/index.js] <eval>:  JingleSessionPC[session=P2P,initiator=true,sid=90bf3398e5d9] setVideoCodecs task failed: OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Called in wrong state: have-remote-offer
`
on second participant joins the room. Then after few seconds got `ping timeout` error. Running self-hosted (docker) with xmpp and colibri sockets are off. SCTP is enabled. Testing in chrome 96.0.4664.110.

**Comment by denis-ionov** [comment]
And for some reason, second participant can receive only two events (eg first participant mute|unmute own audio track, then second participant gets this events - track_mute_changed, and thats all, further events from first participant dont reach second participant). And if turn off p2p at conference options, no JingleSessionPC error appears, but `ping timeout` error persists (and events bug too)

**Comment by saghul** [comment]
I've seen this one too, but it was harmless because we re-negotiate the session right after IIRC. Other than seeing the warning, do you observe any problem?

What version of the images are you using?

**Comment by jallamsetty1** [comment]
> `2021-12-20T10:25:55.360Z [/index.js] <eval>: JingleSessionPC[session=P2P,initiator=true,sid=90bf3398e5d9] setVideoCodecs task failed: OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Called in wrong state: have-remote-offer`

This  has been fixed in the latest version of the library.

**Comment by jallamsetty1** [comment]
Closing this as the issue has been resolved already.
