### ISSUE TITLE
is there a version controlled location for external_api.js?

### ISSUE THREAD

**Issue by hypergig** [jitsi/lib-jitsi-meet#1837]
I help out with a browser extension that integrates jitsi and for a while we use to dynamically import the lib from https://meet.jit.si/external_api.js, until one day the firefox reviewers took issue with this. They prefer to see some version controlled representation of the all external libs. 

So I was wondering, is there a place in github where I can find the minified traspiled version of `external_api.js` that is hosted in  https://meet.jit.si/external_api.js? I just learned of https://www.npmjs.com/package/@jitsi/web-sdk but unfortunately our project isn't really instrumented for this yet. Simply being able to get the `external_api.js` from a place in github would be the easiest option, if it exists.

Thanks!

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

The external_api should be sourced from the deployment with which it is used. The version and implementation follow the releases in that environment. Using different versions may cause unpredicted problems.

**Comment by hypergig** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.
> 
> The external_api should be sourced from the deployment with which it is used. The version and implementation follow the releases in that environment. Using different versions may cause unpredicted problems.

My apologies and thank you
