### ISSUE TITLE
isAuthenticatedUser seems to be `false` for JWT authenticated users

### ISSUE THREAD

**Issue by sapkra** [jitsi/lib-jitsi-meet#1845]
## Description
I would expect that `isAuthenticatedUser` is `true` for all authentication methods. But maybe this is on purpose?

```javascript
if (isAuthenticatedUser) {
    // For authenticated users generate a random ID.
    mucNickname = RandomUtil.randomHexString(8).toLowerCase();
}
```

## Current behavior
`isAuthenticatedUser` is only `true` if a user has used a password to authenticate

```javascript
if (credentials.password) {
    this.authenticatedUser = true;
}
```

**Comment by damencho** [comment]
What are the other authentication methods? Do you mean tokens ... that's kind of transparent for the ljm those are just params passed to the connection URL ... only username and password are used for xmpp authentication.
So that is only when credentials are available.

**Comment by sapkra** [comment]
Thank you for your quick response.
Yes, I mean e.g. JWT tokens, so I think you just answered the question. But in that case the variable naming is not that clear and should be renamed to something more descriptive or at least a comment should be added which clarifies it.

**Comment by damencho** [comment]
I agree :)
