### ISSUE TITLE
With P2P disabled, unmuting the first participant's camera does not work if the second participant joined while it was muted

### ISSUE THREAD

**Issue by jbg** [jitsi/lib-jitsi-meet#1851]
### Description:

If P2P is disabled, and the second participant joins while the first participant's camera is muted, the first participant can no longer unmute their camera (the video tracks do not get added).

### Steps to reproduce:

1. Open https://meet.jit.si/testingp2pdisabled#config.prejoinPageEnabled=false&config.p2p.enabled=false
2. Mute the camera.
3. Open the same page in a second browser tab (or second browser, or second computer).
4. Unmute the camera in the first browser tab.

### Expected behavior:

The camera should unmute and be visible to the second participant.

### Actual behavior:

The camera is not unmuted — the video tracks are not re-added — although the UI shows that it is unmuted.

### Version information:

Reproducible on 6726 but not on 6433. Currently reproducible on meet.jit.si.
Browser / app version: Chrome 97.0.4692.71 arm64
Operating System: macOS 12.0.1

Also tested with Firefox 96 on Mac and Linux — behaviour is the same.

### Additional information:

I've filed this on lib-jitsi-meet because it appears to affect custom UIs based on lib-jitsi-meet as well, I don't believe it's specific to jitsi-meet. This lib-jitsi-meet commit (cc @jallamsetty1) appears to introduce the issue: https://github.com/jitsi/lib-jitsi-meet/commit/e566291864046cadba2ef0af7fc2e31b513e3b4b as rolling back to an earlier commit resolves it.

**Comment by NewEraCracker** [comment]
@jbg Can this maybe be fixed by: https://github.com/jitsi/lib-jitsi-meet/pull/1798/files ?

**Comment by DanielMcAssey** [comment]
I havent tested it yet, but I believe that my PR is now obsolete as videoType is sent on presenceUpdate now.

**Comment by jbg** [comment]
videoType does appear to be sent correctly, but the tracks don't get added
