### ISSUE TITLE
[P2P] Video Traffic To Jitsi Video Bridge in P2P Session

### ISSUE THREAD

**Issue by laurenzfg** [jitsi/lib-jitsi-meet#1871]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
When we establish a peer to peer call between two Jitsi Meet Android clients, we have two video flows: A Peer-To-Peer-Flow and a flow to the meet.jit.si Videobridge.

## Current behavior
We have two video carrying flows (guessing from the bandwidth consumed)

## Expected Behavior
We see the high bandwidth peer to peer flow and a very low bandwidth flow with control information to the JVB.

## Possible Solution
Disable sending video to the JVB if the session is peer to peer.

## Steps to reproduce
1. Have two Android Phones running Jitsi Meet version `21.4.1 build 214010` join a video conference hosted on meet.jit.si
2. Observe flows on the router, e.g. using `tshark`

# Environment details
Lab setup. Two Android Emulator Phones are in the same IPv4 only LAN behind a NAT. See attached picture for the flows observed.

![Jitsi_rtt10ms__20220131-21h54m32s](https://user-images.githubusercontent.com/7126826/152522094-f91321ae-9e8b-444a-995e-c7bffcafebe6.png)

**Comment by saghul** [comment]
A quick test you can do is disable P2P. That way there will only be the JVB. Do you observe the same traffic pattern?

**Comment by saghul** [comment]
Also, ping @jallamsetty1

**Comment by jallamsetty1** [comment]
Are the android clients using mobile browser or using the react native apps ?

**Comment by laurenzfg** [comment]
The clients use the native app obtained via F-Droid.

**Comment by saghul** [comment]
Any chance you can test the latest version (21.6.x) ?

**Comment by laurenzfg** [comment]
Sure Thing. I'll:
- run 21.4.1 version with P2P disabled as suggested
- run 21.6 version with P2P enabled

**Comment by saghul** [comment]
> * run 21.6 version with P2P enabled

Also try with it disabled pl.

**Comment by laurenzfg** [comment]
Version 21.4.1 with P2P disabled
![Jitsi_rtt10ms_pfifo5_20220205-15h23m22s](https://user-images.githubusercontent.com/7126826/152647771-6e0614ef-b281-4d59-acc2-42eddfacf01c.png)

Version 21.6 with P2P enabled
![Jitsi_rtt10ms_pfifo5_20220205-15h32m21s](https://user-images.githubusercontent.com/7126826/152647779-972cc11a-4fe3-4ff7-b32f-8f76d92b5a22.png)

Version 21.6 with P2P disabled
![Jitsi_rtt10ms_pfifo5_20220205-16h07m44s](https://user-images.githubusercontent.com/7126826/152647784-cd0b2b7b-d564-4379-ab11-d9b3e55c8b64.png)

If you have troubles understanding the plots: The emulated phones are dubbed "right" and "left" and the charts show the flows from the central router to the phones. So from the phones' perspective: The downstream.

Each phone has a downstream of 4mbit and an upstream of 100mbit to the router.
The router has a 1gbit connection to the wider internet.

**Comment by saghul** [comment]
Looks like they send way less traffic to the server when P2P is disabled. Is there no datachannel problem? That would explain why the JVB connection doesn't ramp up.

**Comment by laurenzfg** [comment]
> Looks like they send way less traffic to the server when P2P is disabled. Is there no datachannel problem? That would explain why the JVB connection doesn't ramp up.

Only downstream (phones' perspective) is plotted.

**Comment by laurenzfg** [comment]
But yes, it is odd:
- That JVB only sends a ~900kbit stream
- we have the same JVB stream PLUS a P2P video stream if P2P enabled

So thank you so far for assessing the error with me. Is there anything I can do to help you debug the issue?

**Comment by saghul** [comment]
We'll try to reproduce the problem here and see what's going on.

**Comment by saghul** [comment]
I just reproduced this on a personal server (where it's easy for me to run tshark). According to the logs we do suspend the media over the bridge, but I see audio / video traffic going to it.

**Comment by saghul** [comment]
We got this one fixed in https://github.com/jitsi/lib-jitsi-meet/pull/1926 -- New Android and iOS betas are out with the fix, can you please give them a try? (the settings view is now dark, that's an indication that you are running the latest beta).

**Comment by laurenzfg** [comment]
looks good to me! Thanks for delivering a fix so swiftly! Closing this.

BTW it would be nice if you'd provide the beta APK on Github or your web page / or provide a build script to build from master. I ended up downloading it via Gogle Play to my phone to extract the APK.

**Comment by saghul** [comment]
> or provide a build script to build from master.

You can always run `./gradlew assembleRelease` from the android directory. We use Google Play for testing, sorry, adding more to the process is not possible.
