### ISSUE TITLE
No SSRC lines found in remote SDP for remote stream

### ISSUE THREAD

**Issue by bukharin** [jitsi/lib-jitsi-meet#1873]
## Description

I found a lot of errors on source-addition in our Sentry logs with latests `lib-jitsi-meet`

```
 No SSRC lines found in remote SDP for remote stream ...
```

```
remote track removal failed - track not found
```

## Current behavior

Problem was introduced in [this commit](https://github.com/jitsi/lib-jitsi-meet/commit/989b7165978cc2daec7002b066c38cb49f581adc)

When participants leaves the conference - `ljm` set port to `0` for m-line to reuse them for new sources, but later could not find associated ssrc lines.

Actual no audio/video problems found, just a lot of errors.

## Expected Behavior

No errors thrown

## Possible Solution

May be we need to check for `port==0` ?

## Steps to reproduce

- To see the errors in browser console you need to enable this option `enableWindowOnErrorHandler: true`.
- Make the conference with multiple participants (3+)
- Leave the conference for each
- You will see in console:

![image](https://user-images.githubusercontent.com/3126568/152630656-1b595fd7-f629-431b-83ac-60a40952b6ce.png)

# Environment details

Chrome 97

ping @jallamsetty1

**Comment by damencho** [comment]
I think this was fixed with https://github.com/jitsi/lib-jitsi-meet/commit/161835ec58a3e2592cb0e00ec10a3dda4fda11c3

**Comment by bukharin** [comment]
@damencho I reproduce it on latest lib-jitsi-meet commit

**Comment by jallamsetty1** [comment]
This hasn't been fixed yet. It is a non-issue since the browser fires these 'track' and 'trackremoved' events when an m-line is rejected by setting the port 0 and the remote ssrcs are removed from the m-line. These do not affect client's functionality in any way.

**Comment by Duonglam44** [comment]
@jallamsetty1 I also got this issue.

## Behavior:

- 2 Users join the room.
- The 2nd user encounters the error below and subsequently cannot see/hear User 1's camera/microphone.

=> The error displayed is identical to the one in this thread.
# My big problem is that the 2nd user is unable to interact with User 1 in the room.

Can you help me explain this?

![Uploading Screenshot 2024-03-19 at 11.05.19.png…]()

**Comment by saghul** [comment]
What version are you using?

**Comment by Duonglam44** [comment]
hi @saghul 
I am currently using jitsi meet version 8719.

**Comment by saghul** [comment]
@jallamsetty1 thoughts?

**Comment by jallamsetty1** [comment]
@Duonglam44 8719 is from last summer. Its hard to tell what could be causing it. Did you change anything recently on your deployment? Are your client and backend versions out of sync?

**Comment by jallamsetty1** [comment]
Is this happening on Chrome 122 for p2p calls? If so, you will need to update to the latest stable that was released yesterday for the fix.

**Comment by Duonglam44** [comment]
hi @jallamsetty1
> Are your client and backend versions out of sync?

- Yes, our versions are sync!

> Did you change anything recently on your deployment?

- I am not sure but maybe we are not change any importance.
- Can you tell me which config might be related to this issue that we cannot change?

> Chrome 122 for p2p calls?

- Yes, chrome version is 122.x.x. 
- Can you tell me the exact version for the fix?

**Comment by jallamsetty1** [comment]
> * Can you tell me the exact version for the fix?

https://github.com/jitsi/lib-jitsi-meet/commit/0129be6cccb4bd6f561ce382d92ca1d0172d5520 is the fix for this issue. I am closing this ticket since it has been fixed already.
