### ISSUE TITLE
Data channels support is disabled!

### ISSUE THREAD

**Issue by haovn577** [jitsi/lib-jitsi-meet#194]
Just got this error with latest version.

```
Logger.js:89 [/modules/xmpp/strophe.util.js] <Object.Strophe.log>:  Strophe: error: Data channels support is disabled!
Error: Data channels support is disabled!
    at RTC.selectEndpoint (https://sub.example.com/libs/lib-jitsi-meet.min.js?v=139:4:16583)

```

What's wrong with the configuration?

**Comment by damencho** [comment]
This is not an issue, the behavior hasn't changed, its just we introduced the errors and the print. We will be fixing it these days. (We try to send the first selected endpoint event to data channel, just before the datachannel is opened, it was the same way before that with the difference it silently failed to send it).
