### ISSUE TITLE
The build process does not remove files from the types/auto folder

### ISSUE THREAD

**Issue by garyhuntddn** [jitsi/lib-jitsi-meet#1953]
## Description
The build process automatically generates typescript .d.ts definition files, inferring as many types as possible and using the jsdocs to augment them.

Files are generated that map to the .js and .ts files in the project.

They are placed in the types/auto folder.

## Current behavior
If a .js or .ts file is deleted and a build performed the associated .d.ts is not affected

## Expected Behavior
When a .js or .ts file is deleted and a build performed the associated .d.ts should be removed

## Possible Solution
Introduce a clean within the build that empties the types/auto folder

## Steps to reproduce
Delete a .js file with no dependencies and build the project. The associated .d.ts file will still be present.

# Environment details
Windows / Linux

**Comment by garyhuntddn** [comment]
I plan on tackling this one unless somebody else gets there first

**Comment by saghul** [comment]
Go for it Gary!

**Comment by garyhuntddn** [comment]
Turned out to be incredibly simple - https://github.com/jitsi/lib-jitsi-meet/pull/1954

**Comment by saghul** [comment]
Awesome, merged!
