### ISSUE TITLE
UI Customization

### ISSUE THREAD

**Issue by amjidkhanmohmand** [jitsi/lib-jitsi-meet#1972]
Hello Team JITSI!
I am trying to add jitsi as a feature to my app. All I wanted is to customize the UI like I will allow the users to be speakers in the meeting, while other users can just raise a hand and send messages. Is there any way to achieve such a thing in an Android App? Kindly help me out, your help would be highly appreciated. Below is my code.
Thanks and Regards
Amjid Khan Mohmand

`
public class MeetingActivity extends FragmentActivity implements JitsiMeetActivityInterface {

    @BindView(R.id.main_lay)
    FrameLayout main_lay;
    @BindView(R.id.sub_lay)
    FrameLayout sub_lay;

    JitsiMeetView jitsiMeetView;
    JitsiMeetConferenceOptions options;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_meeting);
        ButterKnife.bind(this);
        jitsiMeetView = new JitsiMeetView(MeetingActivity.this);

        try {
             options = new JitsiMeetConferenceOptions.Builder()
                    .setServerURL(new URL("https://meet.jit.si"))
                    .setRoom("isporty123")
                    .setAudioMuted(false)
                    .setVideoMuted(false)
                    .setAudioOnly(false)

                    .setFeatureFlag("kick-out.enabled",false)
                    .setFeatureFlag("invite.enabled",false)
                    .setFeatureFlag("meeting-password.enabled",false)
                    .setFeatureFlag("recording.enabled",false)
                    .setFeatureFlag("raise-hand.enabled",true)
                    .setFeatureFlag("lobby-mode.enabled","disabled")
                    .setSubject("My test Meeting")
                    .setFeatureFlag("add-people.enabled",false)
                    .setWelcomePageEnabled(false)
                    .setConfigOverride("requireDisplayName", true)
                    .build();

            jitsiMeetView.join(options);

            sub_lay.addView(jitsiMeetView, new ViewGroup.LayoutParams(
                    ViewGroup.LayoutParams.WRAP_CONTENT,
                    ViewGroup.LayoutParams.WRAP_CONTENT));

            JitsiMeetActivity.launch(this, options);

        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

    }

    @Override
    protected void onActivityResult(
            int requestCode,
            int resultCode,
            Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        JitsiMeetActivityDelegate.onActivityResult(
                this, requestCode, resultCode, data);
    }

    @Override
    public void onBackPressed() {
        JitsiMeetActivityDelegate.onBackPressed();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        jitsiMeetView.dispose();
        jitsiMeetView = null;

        JitsiMeetActivityDelegate.onHostDestroy(this);
    }

    @Override
    public void onNewIntent(Intent intent) {

        super.onNewIntent(intent);
        JitsiMeetActivityDelegate.onNewIntent(intent);
    }

    @Override
    public void onRequestPermissionsResult(
            final int requestCode,
            final String[] permissions,
            final int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        JitsiMeetActivityDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    protected void onResume() {
        super.onResume();

        JitsiMeetActivityDelegate.onHostResume(this);
    }

    @Override
    protected void onStop() {
        super.onStop();

        JitsiMeetActivityDelegate.onHostPause(this);
    }

    @Override
    public void requestPermissions(String[] permissions, int requestCode, PermissionListener listener) {

        JitsiMeetActivityDelegate.requestPermissions(this, permissions, requestCode, listener);

    }
}
`

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
What doesn't work with your code?

**Comment by amjidkhanmohmand** [comment]
Thanks for the immediate reply, I will use the community forum next time. The issue is that I am unable to customize the UI in the android app. Furthermore, If I use the share screen function the PIP is not working where on the other hand when I use it before screen sharing it works fine, this is the SDK details that I am using
`implementation ('org.jitsi.react:jitsi-meet-sdk:3.+') { transitive = true }`

**Comment by amjidkhanmohmand** [comment]
basically what I needed is to customize the UI in such a way that only the users which I have allowed to be a speaker in meetings will have the access to speak, video call, share screens, etc. while other users can only listen, raise a hand, send a message, and see participants only.

Q. Is there any way to achieve it in android or does it has to be handled on the server?

**Comment by damencho** [comment]
This sounds like enabling AV moderation in the meeting. But that option is available only inside the UI and cannot be controlled from outside the SDK for the moment. Any PRs are welcome.

**Comment by amjidkhanmohmand** [comment]
hmm, is there any way to call a function when unmute button is clicked in the participant's list? I need to call a custom function there

**Comment by amjidkhanmohmand** [comment]
I think I can handle the UI with a trick if I know how to call a function on the unmute button

**Comment by saghul** [comment]
> mplementation ('org.jitsi.react:jitsi-meet-sdk:3.+') { transitive = true }

make sure you are using SDK 5, version 3 is really old.

The app is written in React Native, in order to modify the UI you need to modify the JS source (in the jitsi-meet repo) and rebuild the SDK. See: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

**Comment by amjidkhanmohmand** [comment]
Thanks a lot to both of you, you have provided so much guidance @saghul, @damencho
