### ISSUE TITLE
Study says that Jitsy when muted still sends audio

### ISSUE THREAD

**Issue by rosa2** [jitsi/lib-jitsi-meet#2007]
## Description
The [University of Wisconsin–Madison](http://www.wisc.edu/) published an [study](https://news.wisc.edu/youre-muted-or-are-you-videoconferencing-apps-may-listen-even-when-mic-is-off/) saying that different apps/browser services for video-conference when muted still sends audio. This was re-studied by the Loyola University Chicago, [conducted a more formal investigation](https://wiscprivacy.com/papers/vca_mute.pdf) where Jitsy appears as one. The results are going to be shown in the [Privacy Enhancing Technologies Symposium](https://petsymposium.org/2022/) in July. 
I think that it would be good for Jitsy to show a change in this, don't you think?

## Current behavior

Jitsy sends audio when mutted.

## Expected Behavior

No to send audio.

And as always, thanks for this great software.

**Comment by saghul** [comment]
Jitsi does not send any audio when you are muted.

What the study found is that we don't close the microphone when muting. I don't know if that is the case for all the apps they checked.

There are technical and not so technical reasons for doing this:

- speed when opening / closing the audio device
- avoiding the need for renegotiations in certain cases
- avoid audio profile changes when using Bluetooth (it'd go from HFP to A2DP and back)
- having the ability to provide the "trying to talk? You are muted" notifications to the user 

That's off the top of my head.

**Comment by rosa2** [comment]
Thanks for the fast answer :smile_cat: 
Sorry for my English, I explain badly.
In Spanish
https://unaaldia.hispasec.com/2022/04/las-apps-de-mensajeria-y-videoconferencia-te-escuchan-incluso-cuando-estas-muteado.html
So you don't send the audio.
Maybe it is a good idea that one of you go to the presentation.
I will tray to get the video since I am very interested on this and privacy.

Have a good day and if you don't close this, I will report back :)

**Comment by saghul** [comment]
No worries, I could understand you perfectly fine.

This news has made the rounds over the past few weeks, and IIrC there was one single app which still sent audio elsewhere, the rest did what we do, which at this point is industry standard behavior.

I'm closing this because there nothing really actionable. Like I'm the case of video muting, it doesn't matter what the software promises, if you need to be sure, you need a hardware kill switch, or the equivalent of a post-it note in front of your camera.
