### ISSUE TITLE
Example inconsistently works

### ISSUE THREAD

**Issue by Dan2552** [jitsi/lib-jitsi-meet#2020]
## Description

The example located in `doc/example` (https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example) only works sometimes.

In contrast, we see it works consistently when all clients are using the iframe version.

* Image on the left is of console when it's successful
* image on the right is of console when it's unsuccessful -- we don't get audio/video and according to the logs it hasn't recognised the active "JingleSession".

<img width="1600" alt="Screenshot 2022-05-27 at 17 27 48" src="https://user-images.githubusercontent.com/1478221/170741938-03cf27c9-8bde-4060-8f0f-a19222da3be6.png">

## Current behavior

Inconsistency works with audio/video

## Expected Behavior

Consistently works

## Possible Solution

I have no idea otherwise I wouldn't be opening the issue 😄 but I would suggest look into "JingleSession" discovery

## Steps to reproduce

1. Connect client using the iframe
2. Connect 2nd client using the example (both connected to the same room)
3. Possibly have a working call / possibly not
4. Refresh the example app. Goto 3.

# Environment details

We changed the script in index to use:

```html
<script src="https://meet.jit.si/libs/lib-jitsi-meet.min.js"></script>
```

We changed the config to use:

```js
const options = {
    hosts: {
        domain: 'meet.jit.si',
        muc: 'conference.meet.jit.si'
    },
    serviceUrl: 'wss://meet.jit.si/xmpp-websocket'
};
```

We also tried (but it made no difference):

```js
const confOptions = {
  p2p: {
    enabled: false
  }
};
```

(and of course the room name passed into `initJitsiConference`)

**Comment by damencho** [comment]
If you are using meet.jit.si you need to pass ?room= parameter, or you can end up on different shards and not see each other.

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/0c44b9a478336849d01e488c428db8551dabb7ac/connection.js#L107

**Comment by Dan2552** [comment]
Seems to work, thank you!

I am a little surprised this isn't handled by the underlying SDK rather than the client code, but we're happy we have a working solution, and it seems to be a great software 👍. Thank you!
