### ISSUE TITLE
[modules/xmpp/strophe.util.js] <Yo.ct.Strophe.log>:  Strophe: error: Cannot set properties of undefined (setting 'shard')

### ISSUE THREAD

**Issue by archer87pl** [jitsi/lib-jitsi-meet#2025]
I am getting error after trying to use lib according to documentation:
![image](https://user-images.githubusercontent.com/13657224/171576476-9b53b6bc-4f64-4382-8764-860c2ac28637.png)

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by archer87pl** [comment]
Many thanks! Adding `deploymentInfo: {}` solved the issue.

**Comment by saghul** [comment]
Ah, that's why I saw it fixed in my copy of the code :-)
