### ISSUE TITLE
Multi-stream: video type has changed after unmute! desktop to camera

### ISSUE THREAD

**Issue by DanielMcAssey** [jitsi/lib-jitsi-meet#2029]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
I am using the experimental multi-stream support and I am trying to share a camera and desktop screen share at the same time, I am unable to as it seems the Desktop JitsiTrack property "track" gets overriden with the cameras "track" property.

The only real warning in the console is the `[modules/RTC/JitsiLocalTrack.js] LocalTrack[1,video]: video type has changed after unmute! desktop camera`

This warning only happens when I unmute the desktop track while the camera track is already unmuted.

## Current behavior
---
Cant stream Desktop and Camera at the same time
## Expected Behavior
---
Stream both Desktop and Camera and independently mute/unmute both tracks
## Possible Solution
---

## Steps to reproduce
---
Try share both camera and desktop
# Environment details
---
Custom

**Comment by damencho** [comment]
Can you test it on beta.meet.jit.si? Do you experience the same?

**Comment by DanielMcAssey** [comment]
Apologies this is a custom lib-jitsi-meet integration, not jitsi-meet.

I beleive I have found out why, but not a solution.
In https://github.com/jitsi/lib-jitsi-meet/blob/ac88ed98b59824ff4fe2022a8c54ba4f50c740e7/modules/RTC/JitsiLocalTrack.js#L424 its expected that the constraints will satisfy finding a desktop stream with the same `deviceId` property (e.g. 'screen:5:0'), however in https://github.com/jitsi/lib-jitsi-meet/blob/ac88ed98b59824ff4fe2022a8c54ba4f50c740e7/modules/RTC/RTCUtils.js#L587 its expecting a `desktopSharingSourceDevice` property instead.

**Comment by damencho** [comment]
> Apologies this is a custom lib-jitsi-meet integration, not jitsi-meet.

jitsi-meet is using lib-jitsi-meet and on beta.meet.jit.si you can test the latest lib-jitsi-meet with enabled multi-stream. If it works there it must be something on your side and you can debug lib-jitsi-meet running there to see what is the difference.

**Comment by DanielMcAssey** [comment]
Just debugged it on beta.meet.jit.si, is the expectation that when you unmute a desktop track, a new track should be created then replace the original desktop track, rather than calling unmute() on the original desktop track?

**Comment by jallamsetty1** [comment]
> Just debugged it on beta.meet.jit.si, is the expectation that when you unmute a desktop track, a new track should be created then replace the original desktop track, rather than calling unmute() on the original desktop track?

Yes, exactly!
