### ISSUE TITLE
When using lib-jitsi-meet for custom GUI，Failed to get desktop stream for electron app

### ISSUE THREAD

**Issue by steady-join** [jitsi/lib-jitsi-meet#2036]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
When using lib-jitsi-meet for custom GUI ，Failed to get desktop stream for electron app
```
  shareScreen = async () => {
    try {
      const res = await JitsiMeetJS.createLocalTracks({
        devices: ["desktop"],
      });
    } catch (error) {
      throw error;
    }
  };
  
render() {
    return (
      <div className="App">
          <button onClick={this.shareScreen}>share screen</button>
      </div>
    );
  }
```
## Current behavior
<img width="958" alt="image" src="https://user-images.githubusercontent.com/29935583/174478905-bd726b44-c8c6-44dd-a1f8-b1257042fd22.png">

---
## Expected Behavior
---
What should I do to screen share，Think you
## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Are you using the electron-sdk https://github.com/jitsi/jitsi-meet-electron-sdk#screen-sharing

**Comment by steady-join** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by steady-join** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.
> 
> Are you using the electron-sdk https://github.com/jitsi/jitsi-meet-electron-sdk#screen-sharing

Thank you very much, but I see that jitsi-meet-electron-sdk needs to be embedded in the site in ifrane, it seems that the GUI cannot be customized

**Comment by damencho** [comment]
Then look at the implementation and provide it in your code, it is a simple one adding a function to the window iframe. 

You can checkout jitsi-meet-electron and see it works and you will have a working example to debug and look when implementing yours.

**Comment by pouriamoosavi** [comment]
## you don't necessarily need `jitsi-meet-electron-sdk` to share your screen using `electron` and `lib-jitsi-meet`.

I write it here just for future developers who want to use this combination (`electron`, `lib-jitsi-meet`) and want to have the ability to share screen. Honestly, this should be somehow mentioned in the docs.

Using `jitsi-meet-electron-sdk` forces you to use `IframeAPI`, and in my opinion, changing your entire application to use another API is not very convenient. And as everybody suggests it, it was a little annoying to work around this problem. 

The main problem or the error mentioned in this topic is thrown from here: https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/ScreenObtainer.js#L130
The `JitsiMeetScreenObtainer` variable just doesn't exist in this project for some reason. But it is used! So by adding this to `window`, everything should work fine.

Here is the code. Hope it would help someone else:

Main process, This part is just like electron docs. Make sure to change `types` and `source.name`'s condition base on your needs:
```
const { ipcMain, desktopCapturer } = require('electron');
// other methods...
ipcMain.on("start-desktop-capturer", () => {
  desktopCapturer.getSources({ types: [/*'window', */'screen'] }).then(async sources => {
    for (const source of sources) {
      if (source.name === "Screen 1" || source.name === "Entire Screen" /*mainWindow.getTitle()*/) {
        mainWindow.webContents.send('desktop-capturer-source-id', source.id)
        return
      }
    }
  })
})
```

Preload (context bridge), Two way communication between renderer and main. I used event-like communication for this:
```
const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld(
  'electron',
  {
    // other methods...
    startDesktopCapturer: () => ipcRenderer.send('start-desktop-capturer'),
    onDesktopCapturer:(fn)=>{
      ipcRenderer.removeAllListeners('desktop-capturer-source-id')
      ipcRenderer.on('desktop-capturer-source-id',fn)
    },
  }
```

Renderer (for example index.html), This is the *hacky* part. We add `JitsiMeetScreenObtainer` to `window` and add the `openDesktopPicker` function to it. We don't need its first argument (`chert` in my code). We call the second argument with the `sourceID` from electron's `desktopCapturer`:
```
window.electron.startDesktopCapturer();
window.electron.onDesktopCapturer(async (event, sourceID) => {
  window.JitsiMeetScreenObtainer = {
    openDesktopPicker: function(chert, cb) {
      cb(sourceID, "screen")
    }
  }
})
```

After that, just create a `localTrack` anywhere in your code. **Don't pass `desktopSharingSourceDevice`  to it** as it may break it:
```
window.JitsiMeetJS.createLocalTracks({
  devices: ["desktop"],
})
.then(localTrackCreated)
.catch(localTrackError);
```

Tested with:
"electron": "^23.1.0",
"lib-jitsi-meet": "v1593.0.0+1d99f862"
