### ISSUE TITLE
Other side not seeing camera track removal

### ISSUE THREAD

**Issue by NewEraCracker** [jitsi/lib-jitsi-meet#2037]
## Description
---
We have a custom application using lib-jitsi-meet. Currently P2P mode is disabled on our configuration.

## Current behavior
---

When a new call is made and camera is activated, if during call, participant disables camera, the other participant will see a frozen picture (there is no track removal event).

## Expected Behavior
---

Track is removed.

## Possible Solution
---

IDK. But for testing we've reverted f3a2f61e3fd6ffef04dc5a7bf8534d9c0866a529 and d742dff746a076cc5247e65ad403ffc0ff4762e2 on our build. And this works again.

## Steps to reproduce
---

Make a new call with camera on.
Turn it off while there is a 2nd participant.
2nd participant sees frozen picture.

# Environment details
---

Latest lib-jitsi-meet v1456.0.0+261736ba
Chrome 102.0.5005.115

jitsi-meet-prosody/stable,now 1.0.6155-1 all [installed,upgradable to: 1.0.6260-1]
jitsi-meet-turnserver/stable,now 1.0.6155-1 all [installed,upgradable to: 1.0.6260-1]
jitsi-meet-web-config/stable,now 1.0.6155-1 all [installed,upgradable to: 1.0.6260-1]
jitsi-videobridge2/stable,now 2.1-681-g3544ed05-1 all [installed,upgradable to: 2.2-9-g8cded16e-1]
jicofo/stable,now 1.0-877-1 all [installed,upgradable to: 1.0-900-1]
prosody-0.11/unknown,now 1nightly143-1~focal amd64 [installed]

---

Should jitsi packages be updated to latest versions in our systems as an alternative fix?

Thanks.

**Comment by DanielMcAssey** [comment]
Getting this too, we also run a custom application and the remote side does not get the TRACK_REMOVED event, they only receive an onmute RTC event and no further.

This is will multi-stream enabled though

**Comment by NewEraCracker** [comment]
In our application we now hook the TRACK_MUTE_CHANGED and run the remove logic on mute (to hide camera) and add logic on unmute (to attach camera again to html).

So far works good. We'll be testing during next week with multiple devices to see if that does the trick.

If this new behaviour is intended going forward, please let me know and this issue can be closed.

**Comment by DanielMcAssey** [comment]
@NewEraCracker not sure if its because I am using the unstable docker images, but I dont get a TRACK_MUTE_CHANGED event either, I see the RTC onmute event, but no further propagation. Will test further

**Comment by NewEraCracker** [comment]
Just to be clear. I am doing the following when track is added:
```
      track.addEventListener(
        TRACK_MUTE_CHANGED,
        onRemoteTrackMuteChanged
      );
```
And cleaning this listener when track is removed
```
      track.removeEventListener(
        TRACK_MUTE_CHANGED,
        onRemoteTrackMuteChanged
      );
```

**Comment by DanielMcAssey** [comment]
Unfortunately not, all I get is below and no further events, with a frozen image, I have added console output from the first line of the TRACK_MUTE_CHANGED event handler and it does not get outputted.

`2022-06-27T11:21:16.487Z [modules/RTC/JitsiRemoteTrack.js] <Tc._onTrackMute>:  "onmute" event(1656328876487): RemoteTrack[userID: 2e8aa2d3, type: video, ssrc: 854305047, p2p: false, sourceName: 2e8aa2d3-v0, status: readyState: live, muted: true, enabled: true]`

**Comment by NewEraCracker** [comment]
Closing this issue as not affecting our application anymore after mute handlers implemented.

**Comment by NewEraCracker** [comment]
Re-opening this issue in hopes of community input.

I am using the latest version of the `jitsi-videobridge` (currently `2.2-45-ge8b20f06-1`).

On an earlier version of lib-jitsi-meet with the `sourceNameSignaling` feature-flag turned off, the `JitsiTrackEvents.TRACK_MUTE_CHANGED` listener fires correctly on both unmute and mute of a remote video track.

However with the latest lib-jitsi-meet the `sourceNameSignaling` feature-flag is now forced on as legacy code was removed. When I update to this version on our custom application, things apparently work as expected, except `JitsiTrackEvents.TRACK_MUTE_CHANGED` event - no longer see it firing.

Is there anything else I could do to see when a participant removes/mutes their camera?

**Comment by NewEraCracker** [comment]
Just to be clear, this is a bug with [v1534.0.0+add651fc](https://github.com/jitsi/lib-jitsi-meet/commits/add651fc7eb277d48108ce4cf73e915119304525).

The events from JitsiRemoteTrack.js are reached:
![image](https://user-images.githubusercontent.com/416945/201111517-8a478684-7ab3-4915-ae61-3edb011b6337.png)

I added the console.warn manually for testing:
![image](https://user-images.githubusercontent.com/416945/201111175-a771076c-9c8a-4b6b-98d4-1dc8ae381a88.png)

In mean time, going to stick with [v1532.0.0+b19a9991](https://github.com/jitsi/lib-jitsi-meet/commits/b19a9991e972e70e5de1720a5d27d5f219a4a184) version where I had disabled all multi-stream related things manually.

**Comment by NewEraCracker** [comment]
> Unfortunately not, all I get is below and no further events, with a frozen image, I have added console output from the first line of the TRACK_MUTE_CHANGED event handler and it does not get outputted.
> 
> `2022-06-27T11:21:16.487Z [modules/RTC/JitsiRemoteTrack.js] <Tc._onTrackMute>: "onmute" event(1656328876487): RemoteTrack[userID: 2e8aa2d3, type: video, ssrc: 854305047, p2p: false, sourceName: 2e8aa2d3-v0, status: readyState: live, muted: true, enabled: true]`
> 
> EDIT: Just to add to this, calling mute instead of remove actually triggers the TRACK_MUTE_CHANGED event

I have accessed in my custom application calling `await track.mute();` before `await conference.removeTrack(track);` is a valid workaround for this issue.

Another alternative is to patch `JitsiConference.js`:
```
diff --git a/JitsiConference.js b/JitsiConference.js
index 3489b3ba..981d1e07 100644
--- a/JitsiConference.js
+++ b/JitsiConference.js
@@ -1300,8 +1300,15 @@ JitsiConference.prototype.replaceTrack = function(oldTrack, newTrack) {
         logger.warn(`JitsiConference.replaceTrack oldTrack (${oldTrack} does not belong to this conference`);
     }
 
+    let promise = Promise.resolve();
+
+    if (oldTrackBelongsToConference && !oldTrack.isMuted() && !newTrack) {
+        promise = oldTrack.mute();
+    }
+
     // Now replace the stream at the lower levels
-    return this._doReplaceTrack(oldTrackBelongsToConference ? oldTrack : null, newTrack)
+    return promise
+        .then(() => this._doReplaceTrack(oldTrackBelongsToConference ? oldTrack : null, newTrack))
         .then(() => {
             oldTrackBelongsToConference && this.onLocalTrackRemoved(oldTrack);
             newTrack && this._setupNewTrack(newTrack);
```

I'm happy that now at least there is either a workaround by code of our application and/or patch the library itself.

No warranties express or implied.
