### ISSUE TITLE
Can this library be used with 8x8 Jitsi as a Service?

### ISSUE THREAD

**Issue by asadmalik3** [jitsi/lib-jitsi-meet#2051]
Hi,

Can I use this library with 8x8 Jitsi as a Service to create a custom video conference UI?

Thanks

**Comment by saghul** [comment]
Yes it can! We are in the process of having a more comprehensive example, but for now you can get started by following: https://github.com/saghul/sandbox-html/tree/main/jaas-ljm

**Comment by asadmalik3** [comment]
@saghul Thanks for the example, it is quite comprehensive. What about scenarios like screen share, mute/un-mute etc?

**Comment by saghul** [comment]
We will be working on an even more comprehensive example, but all of those are currently possible. You'd have to dig into the docs / code a bit for now alas.

**Comment by asadmalik3** [comment]
@saghul Thanks for the info. I will close this ticket for now.
