### ISSUE TITLE
Unable to import lib-jitsi-meet.min.js locally using ESM syntax

### ISSUE THREAD

**Issue by icanotc** [jitsi/lib-jitsi-meet#2055]
## Description
The lib-jitsi-meet.min.js library does not have named or default exports

## Current behavior
The minified JS does not have named or default exports.
Direct import (such as `import "./vender/lib-jitsi-meet.min.js";') works fine in the browser, but IDE will complain about unresolved variables and does not provide IntelliSense on the JitsiMeetJS object.
## Expected Behavior
The minified JS does have named or default exports.

## Possible Solution
Add a named import called "JitsiMeetJS" or add a default export.

## Steps to reproduce
```js
    import {onMount} from "svelte"
    import {JitsiMeetJS} from "./lib/vender/lib-jitsi-meet.min.js";
    
    console.log(JitsiMeetJS)
```
The browser emits an error:
```
Uncaught SyntaxError: The requested module '/src/lib/vender/lib-jitsi-meet.min.js' does not provide an export named 'JitsiMeetJS' (at App.svelte:4:13)
```
The weird part is that the `import {JitsiMeetJS} from "./lib/vender/lib-jitsi-meet.min.js";` is auto-completed by the IDE (WebStorm).

If i don't use named imports, for example:
```js
    import {onMount} from "svelte"
    import JitsiMeetJS from "./lib/vender/lib-jitsi-meet.min.js";

    console.log(JitsiMeetJS)
```
The browser still complains
```
Uncaught SyntaxError: The requested module '/src/lib/vender/lib-jitsi-meet.min.js' does not provide an export named 'default' (at App.svelte:4:12)
```

# Environment details
WebStorm on MacOS with M1, MacOS 12.3
Running Chrome 103.0.5060.53, arm64
The project is a generic svelte project, reproductions are tested in both svelte and js files.

**Comment by icanotc** [comment]
Thanks, I used this method because I had a lot of errors when I used the ESM target and tar.gz. plus if I load ljm in a script tag, the IDE would always complain that ljm is resolved, which makes it really hard to debug sometimes.

Here's the error when i vender the ESM target
```
Failed to resolve import "../sdp/SdpSimulcast.ts" from "src/lib/vender/esm/modules/RTC/TraceablePeerConnection.js". Does the file exist?
12:07:22 PM [vite] Internal server error: Failed to resolve import "../sdp/SdpSimulcast.ts" from "src/lib/vender/esm/modules/RTC/TraceablePeerConnection.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/vincent/Documents/Github/jitsi-svelte-integration/src/lib/vender/esm/modules/RTC/TraceablePeerConnection.js
  17 |  import SDPUtil from '../sdp/SDPUtil.js';
  18 |  import SdpConsistency from '../sdp/SdpConsistency.js';
  19 |  import SdpSimulcast from '../sdp/SdpSimulcast.ts';
     |                            ^
  20 |  import { SdpTransformWrap } from '../sdp/SdpTransformUtil.js';
  21 |  import * as GlobalOnErrorHandler from '../util/GlobalOnErrorHandler.js';
      at formatError (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39055:46)
      at TransformContext.error (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39051:19)
      at normalizeUrl (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58329:26)
      at async TransformContext.transform (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58478:57)
      at async Object.transform (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39292:30)
      at async doTransform (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:50012:29)
```
And under that file, its actually not importing the js file. This error is also present when i used the .tar.gz from the latest release. 
```js
import SDPUtil from '../sdp/SDPUtil.js';
import SdpConsistency from '../sdp/SdpConsistency.js';
import SdpSimulcast from '../sdp/SdpSimulcast.ts'; //<= its importing the TS file, which doesnt exist.
import { SdpTransformWrap } from '../sdp/SdpTransformUtil.js';
```
After changing that to `sdp/SdpSimulcast.js`, the browser gives the following error:
```
Uncaught SyntaxError: The requested module '/src/lib/vender/esm/modules/util/GlobalOnErrorHandler.js' does not provide an export named 'default' (at CallStats.js:4:8)
```
And this is caused by GlobalOnErrorHandler.js not using ESM syntax for exports.
```js
module.exports = GlobalOnErrorHandler;
//# sourceMappingURL=GlobalOnErrorHandler.js.map
```
When I try to fix these errors, more and more errors related to ESM imports start to appear.

**Comment by saghul** [comment]
> Thanks, I used this method because I had a lot of errors when I used the ESM target and tar.gz.

What errors do you get? We use the ESM bundle on our React Native build without issues.

**Comment by icanotc** [comment]
> What errors do you get? We use the ESM bundle on our React Native build without issues.
I have included the error message in my last comment.

**Comment by icanotc** [comment]
https://github.com/jitsi/lib-jitsi-meet/blob/2682b4ecee666234434effa411a7c4eb1fd67c17/modules/RTC/TraceablePeerConnection.js#L19-L21
Seems like this is where the error is. Imports in this case does not need .ts at the end, it will cause errors after compilation.

Error:
```
Failed to resolve import "../sdp/SdpSimulcast.ts" from "src/lib/vender/esm/modules/RTC/TraceablePeerConnection.js". Does the file exist?
12:07:22 PM [vite] Internal server error: Failed to resolve import "../sdp/SdpSimulcast.ts" from "src/lib/vender/esm/modules/RTC/TraceablePeerConnection.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/vincent/Documents/Github/jitsi-svelte-integration/src/lib/vender/esm/modules/RTC/TraceablePeerConnection.js
  17 |  import SDPUtil from '../sdp/SDPUtil.js';
  18 |  import SdpConsistency from '../sdp/SdpConsistency.js';
  19 |  import SdpSimulcast from '../sdp/SdpSimulcast.ts';
     |                            ^
  20 |  import { SdpTransformWrap } from '../sdp/SdpTransformUtil.js';
  21 |  import * as GlobalOnErrorHandler from '../util/GlobalOnErrorHandler.js';
      at formatError (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39055:46)
      at TransformContext.error (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39051:19)
      at normalizeUrl (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58329:26)
      at async TransformContext.transform (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58478:57)
      at async Object.transform (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39292:30)
      at async doTransform (/Users/vincent/Documents/Github/jitsi-svelte-integration/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:50012:29)
```

**Comment by ralyodio** [comment]
https://svelte.dev/repl/16b375da9b39417dae837b5006799cb4?version=3.25.0

I used this trick, but now I get:

`Uncaught (in promise) TypeError: global2 is undefined`

**Comment by saghul** [comment]
I think you're right, the import shouldn't have the ".ts" extension. It probably works for us because it goes through another translation. I'll take a look.

**Comment by saghul** [comment]
I made a PR with a fix in https://github.com/jitsi/lib-jitsi-meet/pull/2062 -- Not sure where that `global2` comes from, I tried your REPL link but it has no LJM code.

**Comment by icanotc** [comment]
I'll try to make an example soon, I remember trying dynamically importing LJM and running into the same problem. I'll see if i can replicate it again.

**Comment by ralyodio** [comment]
Can we fix this?

`import JitsiMeetJS from 'https://esm.sh/lib-jitsi-meet@1.0.6';`  // doesn't work

**Comment by saghul** [comment]
We don't maintain that build.

**Comment by ralyodio** [comment]
Yes I know but esh.sh errors are due to poor ESM support by the library in question.

**Comment by saghul** [comment]
We don't have a 1.0.6 version of this library, so I wouldn't know what random version someone put there.

Please report the actual underlying issue.
