### ISSUE TITLE
lib-jitsi-meet/doc/example ,when I run it ,something wrong happens

### ISSUE THREAD

**Issue by dualven** [jitsi/lib-jitsi-meet#2060]
I put lib-jitsi-meet/doc/example  on a web server , when I  access it . there is something wrong happened . I don't  know why. would you please give me some tips ? 
![sunlogin_20220709113256](https://user-images.githubusercontent.com/2209534/178090006-de8ce26c-0270-4c19-b77b-d455f12bf304.png)

**Comment by dualven** [comment]
@ibc  @legastero could you give me some help ?~~

**Comment by saghul** [comment]
Please don't poke random people.

Your problem is you need to be using HTTPS or WebRTC won't work.

**Comment by saghul** [comment]
Please ask in our community is you have further questions.

**Comment by dualven** [comment]
@saghul  thank you very much ! I s  our community  here : https://community.jitsi.org/  ?   now I am not familiar with this, then I will read more here , and thank you again !

**Comment by saghul** [comment]
Yes, that is our community.
