### ISSUE TITLE
Integrating lib-jitsi-meet to react-native fails

### ISSUE THREAD

**Issue by steady-join** [jitsi/lib-jitsi-meet#2089]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
react-native version：0.68.1
node：14.19.1
cocoapods: 1.11.3

---

## Current behavior
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/29935583/183378391-caa833cc-1a70-4129-9d73-342e6bd93a5a.png">

---

## Expected Behavior
Connect to the server normally to obtain audio and video streams，can you help me . thanks!
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
Did you integrate react-native-webrtc and polyfill the global environment?

**Comment by steady-join** [comment]
@saghul Yes, I have inherited react-native-webrtc and refer to jit
The polyfill of si-meet, can now link to the server and join the room, but can't get the stream, the lib will report an abnormal error, how should I solve it, thank you

**Comment by saghul** [comment]
There are a bunch of things that need to be polyfilled. You can check what we do here: https://github.com/jitsi/jitsi-meet/blob/master/react/features/mobile/polyfills/index.js

**Comment by steady-join** [comment]
@saghul I have copied all the polyfills to my react-native project, but there will be some errors, is there any other configuration, thank you

<img width="736" alt="image" src="https://user-images.githubusercontent.com/29935583/183389101-3fbc461b-6221-4cb8-afa7-906451496e12.png">

**Comment by saghul** [comment]
Those are not errors but warnings, you can ignore them.

**Comment by steady-join** [comment]
Thank you, do you have a demo of the rc minimized form? I can't receive the stream now, I don't know how to solve it, thank you

**Comment by saghul** [comment]
Alas, no, we have this as part of Jitsi Meet itself.

**Comment by steady-join** [comment]
@saghul hi, why is this error thrown in the lib？thak you

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/29935583/183598555-40392e64-2fee-4be7-9528-1f810c459532.png">

**Comment by saghul** [comment]
Not sure, is that a failing import?

**Comment by steady-join** [comment]
import is normal, additionally... why can't the lib be used in react-native-debugger? will cause business exceptions. debugger-version 0.12.1 , how can i view redux data，Thank you

**Comment by saghul** [comment]
> why can't the lib be used in react-native-debugger?

Because react-native-webrtc has some sync methods.

**Comment by steady-join** [comment]
hi, I try to replace the entry of jitsi-meet with my application, when I turn on audio/video, there will be the following error, why is this? Think you！
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/29935583/184592909-5a190d1c-3701-4027-b91c-fdeb818702e4.png">
<img width="506" alt="image" src="https://user-images.githubusercontent.com/29935583/184592951-641c929f-1e5a-4009-9b40-1a59aacc5382.png">

**Comment by saghul** [comment]
Initialize the entire library with that object, it's used a bit haphazardly...

**Comment by steady-join** [comment]
This is what happened, what is the difference between the use of react-native and the web, thank you very much for your answer

**Comment by saghul** [comment]
Other than the need for polyfills, some features not working (like VAD) and the fact that audio tracks are automatically played back, everything ellse should be the same.

**Comment by steady-join** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/29935583/184605758-ad06bd95-6e37-4b1e-be94-52260f29fcf9.png">
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/29935583/184605904-337a7d57-b6d9-4d3f-be0e-960720c79676.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/29935583/184606594-6cb4d66d-ed3b-4bd0-b387-5d8ba3c7c746.png">



> Initialize the entire library with that object

After many tests, this lib-jitsi-meet seems to depend on multiple reducer business codes, and it is not easy to build an app through react-native scaffolding...

Is there a good plan to get me out of business? Think you！

**Comment by saghul** [comment]
Not sure how that is related.

Yes, we use a myriad of reducers, because our app has many "features".

In terms of working with LJM though, you need to pass a complete config object to JitsiMeetJS.initialize, also when creating a connection and when initializing a conference.

**Comment by steady-join** [comment]
Think you!
