### ISSUE TITLE
TRACK_REMOVED not called on remote tracks

### ISSUE THREAD

**Issue by maxirozay** [jitsi/lib-jitsi-meet#2120]
## Description
I updated Jitsi last friday and since then `JitsiMeetJS.events.conference.TRACK_REMOVED` is called only for local tracks. The last version (2.0.7001-1) I had was working fine.
same issue [here](https://community.jitsi.org/t/track-dispose-doesnt-call-track-removed-in-the-conference/116091) and [here](https://github.com/jitsi/lib-jitsi-meet/issues/2037)

## Current behavior
I have a listener `jitsiRoom.on(JitsiMeetJS.events.conference.TRACK_REMOVED, onTrackRemoved)` which is called when I turn off my track but not when another user turn off their track.

log from the user after disposing an audio track (the receiver has no log after the track is disposed):
```
2022-09-28T12:11:36.812Z [JitsiConference.js] <Mu._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession
2022-09-28T12:11:36.839Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=JVB,initiator=false,sid=fvf5r4lmjsehg]  Replace track done!
2022-09-28T12:11:36.942Z [modules/xmpp/JingleSessionPC.js] <peerconnection.onnegotiationneeded>:  JingleSessionPC[session=JVB,initiator=false,sid=fvf5r4lmjsehg] onnegotiationneeded fired on TPC[id=2,type=JVB]
```

## Expected Behavior
The listener should be called whenever any user dispose a track.

## Steps to reproduce
Listen to `JitsiMeetJS.events.conference.TRACK_REMOVED`, open 2 tabs, dipose a track on one tab and see if the listener was called on the other tab.

# Environment details
windows 11, debian 11
brave 1.43.93, firefox 93.13.0
jitsi-meet 2.0.7648-1 lib-jitsi-meet is the one provided with this version of jitsi-meet I also tried with meet.jit.si for my backend

**Comment by maxirozay** [comment]
Should we rather use mute or dispose to turn off a track ? We're using dispose to remove the tracks from the conference and the server since they're not needed anymore rather than having a dead track and to have only one way to turn off a track but maybe there's a good reason to use mute.

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by maxirozay** [comment]
Thank you for your response I assume I need to use mute instead of dispose then. By turning off I mean muting so the user has no audio or video anymore.

To clarify, I used to dispose the track when a user mute their track and before they leave. Now I should only mute without disposing when the user want to mute the track and dispose before leaving ?

**Comment by jallamsetty1** [comment]
> To clarify, I used to dispose the track when a user mute their track and before they leave. Now I should only mute without disposing when the user want to mute the track and dispose before leaving ?

Yes, that is how the client is expected to work. Muting the track when the user mutes and the  tracks need to be disposed only before leaving.
