### ISSUE TITLE
Where is the bridge between lib-jitsi-meet and C++ code in WebRTC?

### ISSUE THREAD

**Issue by alexivaner** [jitsi/lib-jitsi-meet#2141]
Hello everyone,
I am trying to build a custom WebRTC and add my custom frame encryptor.
I successfully built it in android and it could work successfully. 
In Android, we have JNI to become the bridge between java and C++ through react-native-webrtc.
For example, finally, react-native-webrtc will call PeerConnection.java  inside WebRTC to connect to RTPSender.cc

But I wonder where is the bridge between lib-jitsi-meet JavaScript and C++,  if I would to have the same WebRTC modification for electron, where I should start? Since here lib-jitsi-meet does not use react-native-webrtc. Thank you.

**Comment by saghul** [comment]
Hi there!

This library relies on the globals supplied by either the browser or browser-like environment. In React Native, that is done with the `registerGlobals()` function. On Electron, your best bet is probably to make a custom Electron build which includes your changes to WebRTC.

Generally speaking, you should only need your custom code on RN, on the browser you can use insertable streams to implement the same logic in JS.

**Comment by alexivaner** [comment]
Last time I tried already Insertable Streams API, and implement encryption and decryption using WebAssembly. But then, my android app could not decrypt video that was encrypted through insertable streams, but it can decrypt video from another android app. The other way around, my website app could decrypt video from my android. Only my android could not decrypt video from insertable streams.

We already make sure that our encryption code is exactly the same as well as the encryption key and IV Key. Then after that, we come to the conclusion that maybe the package we encrypt through insertable streams is different from the package we encrypt using frame encryptor inside our android's webRTC. We try to solve this problem but still did not find the solution until 2 weeks. That's why we try to use the same customized webRTC for electron chromium, but thus far actually becomes more complicated.

Any idea regarding this? Or do I need to do additional steps for insertable streams? Thank you so much anyway for the discussion.

**Comment by saghul** [comment]
It's hard to tell on the abstract, but generally speaking, it should doable.
