### ISSUE TITLE
Strophe: BOSH-Connection failed: improper-addressing

### ISSUE THREAD

**Issue by yu358769601** [jitsi/lib-jitsi-meet#2145]
Thank you for your hard work.
First of all, I went to the official forum, and there is no corresponding answer to all the questions of https. I have configured ssl here, both front and back.

My backend part uses docker-jitsi-meet, which is started in docker, and its configuration is as follows.

# Directory where all configuration will be stored.
CONFIG=~/.jitsi-meet-cfg.

# Exposed HTTP port.
HTTP_PORT=8000.

# Exposed HTTPS port.
HTTPS_PORT=8443.

# System time zone.
TZ=shanghai.
ENABLE_XMPP_WEBSOCKET=0.
# Public URL for the web service (required).
PUBLIC_URL= https://wrtc195.haoleen.com:8443.
DOCKER_HOST_ADDRESS=192.168.1.195.
XMPP_CROSS_DOMAIN=true

My example.js configuration is as follows

const serverURL = 'wrtc195.haoleen.com:8443';
const options = {
    hosts: {
        domain: serverURL,
        muc: `conference.${serverURL}`,
    },
    bosh: `//${serverURL}/http-bind`,
};

Visit my web page with a certified address
https://wrtc195.haoleen.com:10086/
Get the result
Logger.js:154 
       2022-11-02T06:35:51.213Z [modules/xmpp/strophe.util.js] <mt.Strophe.log>:  Strophe: BOSH-Connection failed: improper-addressing
The next few steps are
Connection Failed!

This should be the proof of the correct configuration of my certificate.
2022-11-02T06:52:24.008Z [modules/RTC/RTCUtils.js] onUserMediaSuccess

Because of the communication between docker containers, I also put them in a network segment to prevent possible network problems.

![image](https://user-images.githubusercontent.com/24730382/199420734-4e8ac316-90eb-4af5-92d3-467ff47f7d66.png)
![image](https://user-images.githubusercontent.com/24730382/199420848-3277cdac-3f9f-4ccb-a1d9-2e9a07cdcb6d.png)

I really don't know what's wrong right now. At present, the back-end project with front-end launched by docker can be used normally in LAN.

**Comment by damencho** [comment]
> First of all, I went to the official forum, and there is no corresponding answer to all the questions of https.

Then create a topic with your question. We try to keep trackers with issues and the forum is the place for questions, Thank you.





> const serverURL = 'wrtc195.haoleen.com:8443';
Why this is different than:


> Visit my web page with a certified address
> https://wrtc195.haoleen.com:10086/

Open the link https://wrtc195.haoleen.com:10086/config.js these are the settings that jitsi-meet passes to lib-jitsi-meet and you can use that. Your domain and muc settings are wrong.
