### ISSUE TITLE
XMPP connection dropped!

### ISSUE THREAD

**Issue by mrbaig97** [jitsi/lib-jitsi-meet#2168]
I got the following connection failed error
![error](https://user-images.githubusercontent.com/77655571/205692908-c4720bf8-9a6d-4614-a43c-cd7e894641d2.jpg)

**Comment by saghul** [comment]
Looks like a regular connection error between you and the server.

**Comment by saghul** [comment]
What makes you think that? With the logs you showed I can only conclude that.

**Comment by mrbaig97** [comment]
ok thanks
