### ISSUE TITLE
Userpart of focusUserJid is hardcoded in strophe.jingle.js

### ISSUE THREAD

**Issue by denzs** [jitsi/lib-jitsi-meet#2191]
I just deployed Jitsi using the docker templates and i set the JICOFO_AUTH_USER to 'jicofo' instead of the default value 'focus'

Long story short: this has made me walk down a path of very strange errors i could only fix with damenchos help.
-> https://community.jitsi.org/t/problem-with-jingle-sessions/120002/8

I think the reason is:
https://github.com/jitsi/lib-jitsi-meet/blob/5b1c75531c1fd07570dc1b45e9f8347949f3e801/modules/xmpp/strophe.jingle.js#L157

The value should propably be derived from the userpart of config.focusUserJid instead of being hardcoded.
Otherwise JICOFO_AUTH_USER should not be configurable within the docker templates etc. i think..

**Comment by saghul** [comment]
This is alas hardcoded in too many places.

It was a mistake on my part to make it configurable in Docker.
