### ISSUE TITLE
Console infinite output log

### ISSUE THREAD

**Issue by Lsq6647** [jitsi/lib-jitsi-meet#2197]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---When two people join a meeting, if the following actions are executed frequently, the browser console will output logs like crazy
 (Log content: logger.info(`${this} onnegotiationneeded fired on ${this.peerconnection }`);)
・Camera start/stop
・Start/stop screen sharing
・Change the background

## Current behavior
--- 
log :
...
Logger.js:154 2023-01-04T07:31:57.992Z [modules/xmpp/JingleSessionPC.js] <peerconnection.onnegotiationneeded>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] onnegotiationneeded fired on TPC[id=5,type=P2P]
Logger.js:154 2023-01-04T07:31:57.994Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] onnegotiationneeded executed - OK
Logger.js:154 2023-01-04T07:31:57.999Z [modules/xmpp/JingleSessionPC.js] <Jo._responderRenegotiate>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: setting remote description
Logger.js:154 2023-01-04T07:31:58.010Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: creating answer
Logger.js:154 2023-01-04T07:31:58.023Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: setting local description
Logger.js:154 2023-01-04T07:31:58.027Z [modules/RTC/TraceablePeerConnection.js] <Vd.setSenderVideoConstraints>:  TPC[id=5,type=P2P] Setting degradation preference [preference=maintain-framerate,track=LocalTrack[2,video]
Logger.js:154 2023-01-04T07:31:58.028Z [modules/RTC/TraceablePeerConnection.js] <Vd.setSenderVideoConstraints>:  TPC[id=5,type=P2P] setting max height=2160,encodings=[{"active":true,"adaptivePtime":false,"networkPriority":"low","priority":"low","scaleResolutionDownBy":1}]
Logger.js:154 2023-01-04T07:31:58.030Z [modules/xmpp/JingleSessionPC.js] <peerconnection.onnegotiationneeded>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] onnegotiationneeded fired on TPC[id=5,type=P2P]
Logger.js:154 2023-01-04T07:31:58.038Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] onnegotiationneeded executed - OK
Logger.js:154 2023-01-04T07:31:58.043Z [modules/xmpp/JingleSessionPC.js] <Jo._responderRenegotiate>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: setting remote description
Logger.js:154 2023-01-04T07:31:58.056Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: creating answer
Logger.js:154 2023-01-04T07:31:58.062Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: setting local description
Logger.js:154 2023-01-04T07:31:58.071Z [modules/RTC/TraceablePeerConnection.js] <Vd.setSenderVideoConstraints>:  TPC[id=5,type=P2P] Setting degradation preference [preference=maintain-framerate,track=LocalTrack[2,video]
Logger.js:154 2023-01-04T07:31:58.072Z [modules/RTC/TraceablePeerConnection.js] <Vd.setSenderVideoConstraints>:  TPC[id=5,type=P2P] setting max height=2160,encodings=[{"active":true,"adaptivePtime":false,"networkPriority":"low","priority":"low","scaleResolutionDownBy":1}]
Logger.js:154 2023-01-04T07:31:58.075Z [modules/xmpp/JingleSessionPC.js] <peerconnection.onnegotiationneeded>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] onnegotiationneeded fired on TPC[id=5,type=P2P]
Logger.js:154 2023-01-04T07:31:58.078Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] onnegotiationneeded executed - OK
Logger.js:154 2023-01-04T07:31:58.081Z [modules/xmpp/JingleSessionPC.js] <Jo._responderRenegotiate>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: setting remote description
Logger.js:154 2023-01-04T07:31:58.091Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: creating answer
Logger.js:154 2023-01-04T07:31:58.109Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: setting local description
Logger.js:154 2023-01-04T07:31:58.117Z [modules/RTC/TraceablePeerConnection.js] <Vd.setSenderVideoConstraints>:  TPC[id=5,type=P2P] Setting degradation preference [preference=maintain-framerate,track=LocalTrack[2,video]
Logger.js:154 2023-01-04T07:31:58.119Z [modules/RTC/TraceablePeerConnection.js] <Vd.setSenderVideoConstraints>:  TPC[id=5,type=P2P] setting max height=2160,encodings=[{"active":true,"adaptivePtime":false,"networkPriority":"low","priority":"low","scaleResolutionDownBy":1}]
Logger.js:154 2023-01-04T07:31:58.120Z [modules/xmpp/JingleSessionPC.js] <peerconnection.onnegotiationneeded>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] onnegotiationneeded fired on TPC[id=5,type=P2P]
Logger.js:154 2023-01-04T07:31:58.123Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] onnegotiationneeded executed - OK
Logger.js:154 2023-01-04T07:31:58.127Z [modules/xmpp/JingleSessionPC.js] <Jo._responderRenegotiate>:  JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: setting remote description
Logger.js:154 2023-01-04T07:31:58.140Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: creating answer
Logger.js:154 2023-01-04T07:31:58.153Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=false,sid=61de5fc15c59] Renegotiate: setting local description
Logger.js:154 2023-01-04T07:31:58.159Z [modules/RTC/TraceablePeerConnection.js] <Vd.setSenderVideoConstraints>:  TPC[id=5,type=P2P] Setting degradation preference [preference=maintain-framerate,track=LocalTrack[2,video]
...

## Expected Behavior
--- Do not output log in the console infinitely, want to know where the problem is

## Possible Solution
---

## Steps to reproduce
---
・Camera start/stop
・Start/stop screen sharing
・Change the background

# Environment details
---base 7882

**Comment by damencho** [comment]
Do you reproduce the same with the latest from master?

**Comment by Lsq6647** [comment]
> Do you reproduce the same with the latest from master?

Mine is not the latest version, it is jitsi-meet version 7882。thank you for your reply

**Comment by devium** [comment]
I had the same issue, independent of version.
Make sure, your websocket setup is correct. I updated https://github.com/jitsi-contrib/jitsi-helm without reading the release notes for v1.3.0, which changed with websocket configuration.
