### ISSUE TITLE
Unable to Implement Video Background Blur and Virtual Background using lib-jitsi-meet API

### ISSUE THREAD

**Issue by ajirthanbalasingham** [jitsi/lib-jitsi-meet#2251]
I'm currently working on a video conferencing application using the lib-jitsi-meet API, and I'm having trouble implementing the video background blur and virtual background features. I have tried to follow the documentation and examples provided by the API, but I'm still not able to get these features to work.

I would really appreciate some guidance or assistance on how to properly implement these features using the lib-jitsi-meet API. Specifically, I would like to know which API functions or parameters I need to use, and how to properly configure them.

Thank you very much for your help!

**Comment by saghul** [comment]
Virtual backgrounds / blur are implemented using our "effects" API. Specificallt, the JitsiLocalTrack.setEffect API call. You can use our own implementation as a guideline: https://github.com/jitsi/jitsi-meet/blob/master/react/features/stream-effects/virtual-background/JitsiStreamBackgroundEffect.js

**Comment by icc-guerrero** [comment]
Im using lib-jitsi-meet in a React Native app (using polyfills and react-native-webrtc). Would it be possible to use this? Any example?

**Comment by saghul** [comment]
It's not possible to implement like that on RN. It needs to be implemented natively for performance.
