### ISSUE TITLE
Lib-jitsi-meet enable simulcast layers for desktop tracks on VP8

### ISSUE THREAD

**Issue by bukharin** [jitsi/lib-jitsi-meet#2264]
## Description

Introduced in https://github.com/jitsi/lib-jitsi-meet/commit/05edc9b599df58726b75562f5d89b7939bdba9ef

## Current behavior

`RTPSender.setParameters` does not invokes for desktop tracks and does not disable encodings layers. 

## Expected Behavior

LJM should disable encoding for lower layers in low FPS sharing mode

## Possible Solution

Compare current encodings with new one, instead of comparing resolution only?

## Steps to reproduce

- Open meet.jit.si
- Open meeting in Chrome and start sharing
- Open this meeting in Firefox to switch to VP8
- In `chrome://webrtc-internals` you will see 3 active sending layers

![image](https://user-images.githubusercontent.com/3126568/233782288-634f8243-3ade-41aa-9ad3-ba5a4bed1535.png)

FYI: @jallamsetty1

**Comment by saghul** [comment]
Ping @jallamsetty1 ?

**Comment by jallamsetty1** [comment]
This has been fixed here already - https://github.com/jitsi/lib-jitsi-meet/commit/843a44fa4606e37e6d57ed1d1d5db8c23c48e548

**Comment by jallamsetty1** [comment]
This has been fixed here already - https://github.com/jitsi/lib-jitsi-meet/commit/843a44fa4606e37e6d57ed1d1d5db8c23c48e548
