### ISSUE TITLE
conference.getBreakoutRooms().sendParticipantToRoom() Not working?

### ISSUE THREAD

**Issue by eddsaura** [jitsi/lib-jitsi-meet#2288]
Hi, 

We are implementing breakout rooms in our app ( https://github.com/Stooa/Stooa ) and I can't make this function work. I get no logs or anything and after doing the `sendParticipantToRoom` I check rooms again and nothing happened.

We need to make something similar to the `autoAssignToBreakoutRooms()` function.

We are using last lib-jitsi-meet version.
```"lib-jitsi-meet": "https://github.com/jitsi/lib-jitsi-meet/releases/download/v1640.0.0%2B8c9c4df5/lib-jitsi-meet.tgz"```

So first of all, we are in a conference.

![image](https://github.com/jitsi/lib-jitsi-meet/assets/13334047/a5e5ad87-4255-49a9-867f-930f266f3673)

And then we create the room

```js
const createBreakoutRoom = name => {
    if (!isModerator) {
      return;
    }
    try {
      conference.getBreakoutRooms().createBreakoutRoom(name);
    } catch (error) {
      throw new Error(error);
    }
  };
```

It works, now I have two rooms, the main and the second one.

![image](https://github.com/jitsi/lib-jitsi-meet/assets/13334047/17702ce2-c04c-46ed-9f92-6f524c39cd96)

Cool, now I want to send a participant to the second room, so we have this function.

```js
  const sendParticipantToRoom = (participantJid, roomId) => {
    const { _rooms } = getBreakoutRooms();
    const room = _rooms[roomId];

    if (!room) {
      console.error(`Invalid room: ${roomId}`);

      return;
    }

    console.log('TRYING to move this guy', participantJid, 'to room', room.jid);
    conference.getBreakoutRooms().sendParticipantToRoom(participantJid, room.jid);
  };
```

This is what we get from that log.

```
TRYING to move this guy 834aefdd-cfa5-4372-8662-5e9c11eb7449@meet.jitsi/WlxC0OhX_Tsw to room ee45db44-196e-4e9d-bf6b-10364d7d81f5@breakout.meet.jitsi
```

Idk what to do.

**Comment by eddsaura** [comment]
thank you @saghul . So what is the `sendParticipantToRoom()` for? I think I don't get it hahah 😅

**Comment by saghul** [comment]
It sends that message indicating the target participant that it should move to that room.

**Comment by Bloodiko** [comment]
Do I understand this correctly ? 

This would mean that actions on breakout rooms are not independant in the library, as the messages get sent to the frontend, which would require the frontend. 
The big advantage of the lib is to be a headless Jitsi User - am I wrong ?

**Comment by saghul** [comment]
You are right, that's how it was designed. Some frontend a may want to show a dialog for example.
