### ISSUE TITLE
no way to retrieve lib-jitsi version

### ISSUE THREAD

**Issue by DanielRuf** [jitsi/lib-jitsi-meet#2340]
## Description
Currently none of the dist files or source files of all releases contain any version string.

## Current behavior
No way to retrieve the version of the lib.

## Expected Behavior
Something like `jQuery.fn.jquery` but for lib jitsi to get the currently used version.

## Possible Solution
Add the version string to source and dist files and add a method to retrieve that in the browser / during runtime.

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.


You can using https://github.com/jitsi/lib-jitsi-meet/blob/77e6803f1915174ba4bce2cb36f942cce55d6005/JitsiMeetJS.ts#L93

**Comment by DanielRuf** [comment]
The commit hash is not a version string =)

**Comment by DanielRuf** [comment]
> This Issue tracker is only for reporting bugs and tracking code related issues.

From my POV this is a bug / an issue related to the code, because there is no easy way to tell which version (who dooes compary the version by commit hash?) of lib-jitsi is actually used in the browser.

Please add the version that you have at https://github.com/jitsi/lib-jitsi-meet/releases or alternatively use the Git tag (not just the commit hash).

**Comment by damencho** [comment]
Those versions contain the hash, we have been using that for years and there are no plans for changing it. 
There are cases where we use lib-jitsi-meet without having a released binary version, which is another usecase where having only hash covers it.

**Comment by DanielRuf** [comment]
> All information is available in github, it matches the commit to release.

Thanks, yes I am aware of this URL. Unfortunately there are only Git tags / GitHub releases starting from 2022.

Still, having the tag also there (if set) would make things easier when identifying the version for debugging so we can easily check the changelogs.

**Comment by saghul** [comment]
We cannot change the past since we used to embed LJM differently. Today you can get the tag from the commit, as @damencho said. Any specific reason why this isn't good enough? If you are interested in debugging, it's just one extra step to go from the commit hash to the tag, AFAICT.
