### ISSUE TITLE
Not able to configure restriction to join user as a guest it is joining as a moderator

### ISSUE THREAD

**Issue by LokeshPahadiya** [jitsi/lib-jitsi-meet#2341]
1. I have configure the jitsi meet in ubuntu and it is successfully run but i want to add some configuration it can possible user will be join as a guest one will be moderator. but in my case Whenever someone joins first he becomes a moderator i do not want this. I want to restrict user they can only join as guest only i want this plz help me in this.
I want to add the jwt authentication in this what will be the username and what will be the password how to pass the jwt by our application plz suggest the full example.(How to extract the jwt token).I have configure the jitsi meet in ubuntu and it is successfully run but i want to add some configuration it can possible user will be join as a guest one will be moderator. but in my case Whenever someone joins first he becomes a moderator i do not want this. I want to restrict user they can only join as guest only i want this plz help me in this.
2. I want to add the jwt authentication in this what will be the username and what will be the password how to pass the jwt by our application plz suggest the full example.(How to extract the jwt token).

**Comment by saghul** [comment]
Please use our community forum for these kind of questions. I'll repluy here and close, so please take the discussion there if you have further questions.

1. If you enable token auth then only participants with a token will be moderators. You can set allow_empty_token to true, but they will not be moderators.

2. There is no username, it's the token itself that provides the auth. The token is passed as a query parameter in the url: https://example.com/room?jwt=xxx
