### ISSUE TITLE
Laggy screensharing when VP9 is enabled.

### ISSUE THREAD

**Issue by NewEraCracker** [jitsi/lib-jitsi-meet#2342]
## Description
---
Currently when e2ee is disabled (there by vp9 will be used if supported) viewing screenshare for the remote participant will be laggy, while when e2ee is enabled (there by vp8 will be forced) screenshare is smooth as in previous versions.

In both cases. Camera track is smooth, so no problem there.

Is there a bridge update required?

## Current behavior
---
Laggy screenshare with vp9.

## Expected Behavior
---
Smooth screensharing experience.

## Possible Solution
---
Give a configuration workaround to disable vp9 for screensharing tacks.

## Steps to reproduce
---
Make a screenshare on Chrome with e2ee disabled for the conference = Laggy.
Make a screenshare on Chrome with e2ee enabled for the conference = Smooth.

# Environment details
---
Chrome on Windows.
Jitsi [v1678.0.0+77e6803f](https://github.com/jitsi/lib-jitsi-meet/releases/tag/v1678.0.0%2B77e6803f)
Latest officially released bridge: 2.0.8719 (2023-06-12)

**Comment by NewEraCracker** [comment]
Looks like this issue is known since 2021:

https://stackoverflow.com/questions/68741890/webrtc-screen-sharing-with-vp9-low-fps
https://bugs.chromium.org/p/webrtc/issues/detail?id=13016

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by jallamsetty1** [comment]
This is because of https://bugs.chromium.org/p/webrtc/issues/detail?id=13016. If you want higher fps, you can set the `desktopSharingFrameRate.max` to > 5 and this is configurable via config.js, settings menu and through `JitsiConference:setDesktopSharingFrameRate()` API.
