### ISSUE TITLE
Please remove not used layers fields

### ISSUE THREAD

**Issue by Romick2005** [jitsi/lib-jitsi-meet#2387]
Seems like you do not use [layers](https://github.com/jitsi/lib-jitsi-meet/blob/f8a18cf09f4fd3ea66fa0dd92c918ff8f7e11da5/modules/connectivity/ConnectionQuality.js#L23) property anywhere, so I guess it could be removed. 
Don't you think so?
![image](https://github.com/jitsi/lib-jitsi-meet/assets/17779660/08f960e6-5936-4a6f-83dc-d573823fc0d1)

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by Romick2005** [comment]
I would also remove **width** property as not used.

**Comment by Romick2005** [comment]
Also I do not get this `target += videoQualitySettings[simulcastFormat.target]; ` as previously there were sum for targetRN numeric value, but how that suppose to work for 'low', 'standard' and 'hight' string concatenation?
![image](https://github.com/jitsi/lib-jitsi-meet/assets/17779660/8faee570-8863-4418-9e3a-9bf795c6afda)

**Comment by jallamsetty1** [comment]
Thanks @Romick2005 for the observation. Yes, they are currently not being used. Will you be able to open a PR for this?
