### ISSUE TITLE
Unlocked meetings vs "waiting for moderator" - Can we get open meetings back?

### ISSUE THREAD

**Issue by hf5pro** [jitsi/lib-jitsi-meet#2404]
Jitisi was my preferred meeting link because it's just one click and the meeting is on. For me, convenience and speed is what counts and google meet is an extra click more than jitsi.

But I like to use my meeting link from any device even if not logged in, sometimes I'm on the go or on another device but still want to start the meeting. This was made impossible now due to the requirement for the moderator to be logged in. Also logging in the app with google is super difficult because it doesn't recognize the google account from my phone. I deinstalled the app now.

I have no clue why it was changed, maybe legal requirements?

I would like to have the old jitsi back where I can just use a link and the meeting starts and that's it.

I appreciate any feedback.

**Comment by saghul** [comment]
Authentication was introduced in August as a last ditch effort to combat abuse. You can check the blog post here: https://jitsi.org/blog/authentication-on-meet-jit-si/

This has also been discussed in other issues and in our community.

Sorry but we can't revert to the old behavior.

This only affects meet.jit.si, if you self-host jitsi meet this does not apply.
