### ISSUE TITLE
Simulcast remains active despite configuration attempts to disable it.

### ISSUE THREAD

**Issue by Kreshnik** [jitsi/lib-jitsi-meet#2424]
---
## Description

Simulcast remains active despite configuration attempts to disable it.

---

## Current behavior

Despite using the low level JavaScript API, Simulcast does not turn off.

---

## Expected Behavior

Expecting Simulcast to be disabled.

---

## Possible Solution

Not available.

---

## Steps to reproduce

1. Initialize with: `JitsiMeetJS.init({disableSimulcast: true});`

---

## Environment details

- Browser: Chrome 
- Version: 120.0.6099.109

---

**Comment by saghul** [comment]
What codec are you using? @jallamsetty1 does that option disable SVC too?

**Comment by Kreshnik** [comment]
@saghul from WebRTC internals;
```
codec (mimeType=video/VP9, payloadType=101, id=CIT01_101)
```

**Comment by jallamsetty1** [comment]
@Kreshnik Do you think it's a regression? I think this option was deprecated long time back, looks like we forgot to update the docs.  The preferred way to disable simulcast is to add it to the options passed to `initJitsiConference`.

**Comment by Kreshnik** [comment]
@saghul @jallamsetty1, indeed, the issue was with the outdated documentation. I managed to disable simulcast by passing it to the initJitsiConference configuration as shown below:
```
{
    conference: {
      disableSimulcast: true,
      
    }
}
```
