### ISSUE TITLE
lib-jitsi-meet/doc/example /index.html 

### ISSUE THREAD

**Issue by news00** [jitsi/lib-jitsi-meet#2476]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
I change to my test server. Why doesn't it work?

![image](https://github.com/jitsi/lib-jitsi-meet/assets/25659337/c144c9bc-3d7c-446a-b4ea-2b93cdf5cdc6)

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by news00** [comment]
I use IFrame API is work...

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
Share the code you use?

Is your deployment working in 3 tabs using jitsi-meet directly?

**Comment by saghul** [comment]
The seem to be using https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example

**Comment by news00** [comment]
My code




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jitsi/lib-jitsi-meet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月5日(星期二) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jitsi/lib-jitsi-meet] lib-jitsi-meet/doc/example /index.html  (Issue #2476)





 
Share the code you use?
 
Is your deployment working in 3 tabs using jitsi-meet directly?

**Comment by news00** [comment]
How do I listen to the device status of a remote conference person? I read the documentation and it doesn't seem to provide those events...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jitsi/lib-jitsi-meet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月5日(星期二) 晚上9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jitsi/lib-jitsi-meet] lib-jitsi-meet/doc/example /index.html  (Issue #2476)





 
The seem to be using https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example

**Comment by saghul** [comment]
What do you mean by device status?

**Comment by news00** [comment]
Cameras and microphones of other conference participants off or on...






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jitsi/lib-jitsi-meet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jitsi/lib-jitsi-meet] lib-jitsi-meet/doc/example /index.html  (Issue #2476)





 
What do you mean by device status?

**Comment by saghul** [comment]
That sounds like adaptivity kicking in due to bandwidth constraints. Check the logs.

**Comment by news00** [comment]
So it's the lack of support for these features?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jitsi/lib-jitsi-meet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jitsi/lib-jitsi-meet] lib-jitsi-meet/doc/example /index.html  (Issue #2476)





 
That sounds like adaptivity kicking in due to bandwidth constraints. Check the logs.

**Comment by saghul** [comment]
I'm not sure what you mean. A user could be suspended (ie no video is received for them) if there is not enough bandwidth, for example.
