### ISSUE TITLE
TypeError: _this.isCollectingLocalStats is not a function (it is undefined)

### ISSUE THREAD

**Issue by Romick2005** [jitsi/lib-jitsi-meet#2489]
After `jitsiConnectionEstablished` I tried to call  ```JitsiMeetJS.createLocalTracks({ devices: ['audio'] });```
But got an error: `"error": [TypeError: _this.isCollectingLocalStats is not a function (it is undefined)]`

I am using latest react-native@0.73.6

**Comment by damencho** [comment]
Can you reproduce the same error on alpha.jitsi.net?

**Comment by Romick2005** [comment]
Using raw git code pointing main to the index.js. Directly.

**Comment by saghul** [comment]
Did you initialize the library by calling `JitsiMeetJS.init` ?

**Comment by Romick2005** [comment]
> Did you initialize the library by calling `JitsiMeetJS.init` ?

Yes, sir. Only one time on project initial setup.
lib-jitsi-meet version is `git reset --hard 006457f`.

```
JitsiMeetJS.init({
  disableAudioLevels: false,
  useIPv6: false,
  disableThirdPartyRequests: true,
});
```

**Comment by Romick2005** [comment]
> Can you reproduce the same error on alpha.jitsi.net?

Sorry, but I am not sure how to check it there as I use react-native mobile app together with latest lib-jitsi-meet code.

**Comment by damencho** [comment]
> > Can you reproduce the same error on alpha.jitsi.net?
> 
> Sorry, but I am not sure how to check it there as I using react-native mobile app together with latest lib-jitsi-meet code.

Yeah, I was wondering how is possible jitsi-meet web and mobile already using this and works without a problem, that's why I was asking about some test and I did not see the react-native line.

**Comment by Romick2005** [comment]
More info.
It is createLocalTracks from JitsiMeetJS.ts with extra console.log:
![image](https://github.com/jitsi/lib-jitsi-meet/assets/17779660/5943fbe5-259b-4a93-9fe7-d14eb8fffebc)

This is my code and how it is used:
![image](https://github.com/jitsi/lib-jitsi-meet/assets/17779660/8ac2ddfb-975c-4a40-ab41-a347a099e7a3)

And this is output from console:
![image](https://github.com/jitsi/lib-jitsi-meet/assets/17779660/ed5bee54-b15a-4b1f-962e-fd4ef0dcb947)

**Comment by Romick2005** [comment]
PS Could it be related with generator creating some different this for an object call? Because if I use it like regular promise it is working )
Working code sample:

![image](https://github.com/jitsi/lib-jitsi-meet/assets/17779660/539e0559-eebb-400b-94ae-6f7d0fa9b88a)

**Comment by Romick2005** [comment]
Chances is 0%. It is calling after JitsiMeetJS. And as you can see JitsiMeetJS.isCollectingLocalStats is defined before calling  JitsiMeetJS.createLocalTracks inside saga generators:
`yield call(JitsiMeetJS.createLocalTracks, { devices: ['audio'] });`
and then error comes:
`TypeError: _this.isCollectingLocalStats is not a function (it is undefined)`

**Comment by saghul** [comment]
I wonder if `call` is changint the `this` bidning?

**Comment by Romick2005** [comment]
So it is better to have arrow function or better go with my [fix](https://github.com/jitsi/lib-jitsi-meet/pull/2490).
Please check it and merge if possible.

Thank you!

**Comment by Romick2005** [comment]
> I wonder if `call` is changint the `this` bidning?

I assume yes. It is changing this context. So to be safe, please merge my no context dependent fix )

**Comment by Romick2005** [comment]
Ithink you are wrong here as my fix makes things more clear.
1) You do not have to import whole LocalStatsCollector into JitsiMeetJS just for calling isLocalStatsSupported only one. It is better to have isCollectingLocalStats inside Statistics as it is related to this and it is more proper place for this method and Statistics file already have imported LocalStatsCollector as LocalStatsCollector. So it is double win win.
2) This fix will make method isCollectingLocalStats not dependent on this context as in reality it should not be as have no context base dependency. So having it as static method in Statistics is also win-win.

It is sad that you do not see any improvement in my fix.

PS Can you please ask some alternative opinion on this? Looks like you do not like changes even for good.

**Comment by saghul** [comment]
I appreciate you trying to fix things here. That's why I'm spending some time trying to show you why this fix is not correct.

This library is used by tons of customers, you can't just decide "this is better" so I'm deprecating the function.

It's a marginal improvement at best, and definitely not worth the churn.

Last, you keep ignoring the fact that Statistics is not exposed to the library consumers in UMD form, which means the non-deprecated API is not even reachable.

**Comment by Romick2005** [comment]
I think you are wrong again and did not pay attention to my changes. I've removed deprecated warning as you suggested, because it make sense.

So please be more attentive next time.
