### ISSUE TITLE
addRemoteStream failed: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription.  Duplicate a=msid lines detected

### ISSUE THREAD

**Issue by cuongdang1997** [jitsi/lib-jitsi-meet#2498]
addRemoteStream failed: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription.  Duplicate a=msid lines detected

## Description
The 2nd person is out of MTG while the 3rd person joins MTG

## Current behavior
１．Chrome Host→access meeting
２．Edge Host →access meeting
３．Chrome Host →access meeting
The access of person number 2 (Edge) is interrupted

After verifying the access order of the hosts
case 1: Chrome1 -> Edge -> Chrome2: If Chrome2 accesses, edge is interrupted
case 2: Edge -> Chrome1 -> Chrome2: If Chrome2 accesses, edge is interrupted
case 3: Chrome -> Edge -> FireFox: If FireFox accesses, edge is interrupted
case 4: Edge -> Chrome -> FireFox: If FireFox accesses, edge is interrupted

## Expected Behavior
The second person is not out of MTG when the third person joins MTG

## Steps to reproduce
１．Chrome Host→access meeting
２．Edge Host →access meeting
３．Chrome Host →access meeting
The access of person number 2 (Edge) is interrupted

After verifying the access order of the hosts
case 1: Chrome1 -> Edge -> Chrome2: If Chrome2 accesses, edge is interrupted
case 2: Edge -> Chrome1 -> Chrome2: If Chrome2 accesses, edge is interrupted
case 3: Chrome -> Edge -> FireFox: If FireFox accesses, edge is interrupted
case 4: Edge -> Chrome -> FireFox: If FireFox accesses, edge is interrupted

# Environment details
Chrome 122.0.6261.129, Edge 123.0.2420.65, FireFox 124.0.1 
<img width="1301" alt="image" src="https://github.com/jitsi/lib-jitsi-meet/assets/35336062/4a2dca8c-f549-4b8b-af42-0f95318cc36b">

**Comment by cuongdang1997** [comment]
@jallamsetty1  Could you help me solve this problem? i'm using version release [v1389.0.0+313e0dd3](https://github.com/jitsi/lib-jitsi-meet/releases/tag/v1389.0.0%2B313e0dd3)

**Comment by damencho** [comment]
That was fixed in the latest versions, so you can update.

**Comment by cuongdang1997** [comment]
@damencho But we have put the product into use, it is difficult to update, can you give me a temporary solution?

**Comment by saghul** [comment]
Your version is 2 years old. That is an incredibly long time for WebRTC applications.

I'm afraid your only choice is to upgrade.

The good news is that , generally speaking, we don't break our APIs all that often, so it should be reasonably straightforward to do.

**Comment by cuongdang1997** [comment]
@damencho, @saghul Could you please tell me which code commit this bug has been fixed on?

**Comment by saghul** [comment]
That's impossible to know because your release is so old. Plan B was dropped for example, which is a huge change.

**Comment by muratersin** [comment]
Same issue when start screen sharing. Did you find a solution for this? @cuongdang1997.

**Comment by damencho** [comment]
@muratersin this is fixed in latest stable release.
