### ISSUE TITLE
Start recording option not visible when the app is embedded 

### ISSUE THREAD

**Issue by VivekDikshith** [jitsi/lib-jitsi-meet#2524]
We have hosted the jitsi server in our onprem env. We are embedding the jitsi within our webapp. In the config.js we have set the flowing properties

config.localRecording.disable = false;
config.localRecording.notifyAllParticipants = false;
config.localRecording.disableSelfRecording = false;

as well
config.recordingService.enabled = true;

However, the Start recording option is not visible within the app. When we launch the meet in a new tab, the option is visible.

When launched in new tab

![image](https://github.com/jitsi/lib-jitsi-meet/assets/76480248/0dabd9f6-9834-4bd7-8f3b-cdae2414299f)

within app:

![image](https://github.com/jitsi/lib-jitsi-meet/assets/76480248/88f559c3-6eb1-4dcd-b976-9e6ce2309d3a)

**Comment by saghul** [comment]
IIRc it's not possible to use it within an iframe.

**Comment by saghul** [comment]
👍
