### ISSUE TITLE
Contradicting docs for Jwt Token & lacking feature to disable video and screen sharing features

### ISSUE THREAD

**Issue by gitusertd** [jitsi/lib-jitsi-meet#2550]
## Description
The Jitsi JWT token documentation is contradictory between 

- https://developer.8x8.com/jaas/docs/api-keys-jwt
- https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

Which one has the correct docs?

Also, could it be possible to extend the `features` struct field to have extra option to disable `video`, `screen-sharing`, `image`, `file`?

## Possible Solution

- Which JWT structure to use? (I think the one with 8x8.com is beneficial to have the `features` struct field).

- on 8x8.com, the `features` struct field should be extended to include these keys: `video`, `screen-sharing`, `image`, `file`. So that it is possible to make audio call only (without video), or disable file sharing, or disable screen-sharing, or disable sending image, etc.

**Comment by damencho** [comment]
> The Jitsi JWT token documentation is contradictory between
> 
> * https://developer.8x8.com/jaas/docs/api-keys-jwt
> * https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md
> 
> Which one has the correct docs?

These two are different docs. The first one is related to jaas. The second one is for jitsi-meet open-source project. Jaas uses the open-source one as base and extend it.



> Also, could it be possible to extend the `features` struct field to have extra option to disable `video`, `screen-sharing`, `image`, `file`?

These depends on your UI and its implementation, you can add in your token whatever you want, depends what is reading and using it, whether those are handled. 



> * Which JWT structure to use? (I think the one with 8x8.com is beneficial to have the `features` struct field).
> *

If you are using Jaas, use the one from the docs on 8x8.com.



> * on 8x8.com, the `features` struct field should be extended to include these keys: `video`, `screen-sharing`, `image`, `file`. So that it is possible to make audio call only (without video), or disable file sharing, or disable screen-sharing, or disable sending image, etc.

These fields are optional, adding them gives you more control.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
