### ISSUE TITLE
lib-jitsi-meet failed to init due to '', {"line":141401, "columnt": 13, "sourceURL": "http://localhot:8081/index.android.bundle?platform-android&dev=true&hot=false&minify=false"}

### ISSUE THREAD

**Issue by asvetlenko** [jitsi/lib-jitsi-meet#274]

**Comment by lyubomir** [comment]
I'm guessing that you're attempting to run lib-jitsi-meet on React Native. If that's the case, please refer to https://github.com/jitsi/jitsi-meet-react/commit/2f23d984245324e79156eeec9e447667b3c76d33. As the jitsi-meet-react commit in question states the latest master of lib-jitsi-meet may not be able to run on React Native and a temporary workaround has been provided until lib-jitsi-meet is fixed.

Given that I have to be guessing from the subject and there is no description provided to this issue, I'm afraid I'd rather close it.
