### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by asvetlenko** [jitsi/lib-jitsi-meet#276]
I have problems with installation  "lib-jitsi-meet".
package.json :
"dependencies": {  
    "lib-jitsi-meet": "jitsi/lib-jitsi-meet"
},

I found what is going wrong. "lib-jitsi-meet" use dependency: "socket.io-client": "1.3.6" . 
And it crashed process of the installation. 
If you try to install only socket.io-client with version 1.3.6  (npm install socket.io-client@1.3.6)
you will get errors , because version 1.3.6 very bad.
If developers of the library "lib-jitsi-meet" change version of the dependency to "socket.io-client": "1.*" you will not get errors.
Next problem with "string-replace"  module. I also get errors related with it:

ERROR in Entry module not found: Error: Cannot resolve module 'string-replace' in /Users/mac-182/workspace/t/node_modules/lib-jitsi-meet

I use "windows 10 + git bash" or "Mac os x EL Capitan version 10.11.3" for develop.

**Comment by saghul** [comment]
Both of those package versions have been updated. Sorry for the delay! Closing.
