### ISSUE TITLE
Install jitsi meet api in the server

### ISSUE THREAD

**Issue by gekobe** [jitsi/lib-jitsi-meet#277]
Hello, 

is there any way to embed the jitsi meet api with all the sources in my server to make changes on it?

Thank you.

**Comment by damencho** [comment]
Please use the mailinglist to ask questions before opening issues.

You can install it and modify it, or use the installed version as an iframe in your web app, there is an API to control some functionality: https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md
Or you can use lib-jitsi-meet and wrote your own web app and you can use jitsi-meet as an example.
