### ISSUE TITLE
Issue making the final browserify JS 

### ISSUE THREAD

**Issue by ayushch3** [jitsi/lib-jitsi-meet#317]
I made few changes to the few Javascript in modules and I am trying to do make && make clean. It is failing with the following error

cp ./app.bundle.min.js ./app.bundle.min.map \
        ./app.bundle.js ./app.bundle.js.map \
        ./external_api.js.map ./external_api.js \
        ./external_api.min.map ./external_api.min.js \
        libs
cp node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js \
        node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map \
        node_modules/lib-jitsi-meet//lib-jitsi-meet.js \
        node_modules/lib-jitsi-meet//lib-jitsi-meet.js.map \
        node_modules/lib-jitsi-meet//connection_optimization/external_connect.js \
        libs
cp: cannot stat ‘node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js’: No such file or directory
cp: cannot stat ‘node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map’: No such file or directory
cp: cannot stat ‘node_modules/lib-jitsi-meet//lib-jitsi-meet.js’: No such file or directory
cp: cannot stat ‘node_modules/lib-jitsi-meet//lib-jitsi-meet.js.map’: No such file or directory
cp: cannot stat ‘node_modules/lib-jitsi-meet//connection_optimization/external_connect.js’: No such file or directory

**Comment by damencho** [comment]
Please use the mailinglist for questions and problems, before opening new issues.
Did you do npm install before doing make? There are couple of instruction in jitsi-meet Readme, take a look there.
