### ISSUE TITLE
JitsiConference room list with their status

### ISSUE THREAD

**Issue by ksreeni** [jitsi/lib-jitsi-meet#318]
I have a requirement to know list of Jitsi conference rooms created in the server and their status.

**Comment by damencho** [comment]
Please when having questions or problems, write to the mailinglist before opening new issues.

Currently list of ongoing conferences and all conferences and statistic per conference, including participants is available through callstats integration. Other than that you can query jvb REST for statistics and get the number of ongoing conferences and number of participants. (https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest-videobridge.md)
