### ISSUE TITLE
Audio is not working in Windows-10 OS

### ISSUE THREAD

**Issue by gsandeep828** [jitsi/lib-jitsi-meet#342]
Hi Team,

I am facing audio issues while integrating jitsi in my project, Audio is not working in windows 10 OS, tested in chrome and firefox browsers and also Not showing any errors in console but its working in mac os x and windows-7 with chrome browser.

Can any one please suggest what could be the issue?

**Comment by saghul** [comment]
Please use the mailing list for questions. Make sure you test other audio web applications with your setup to make sure it's not an environment issue.
