### ISSUE TITLE
[request] Way to query videobridge about lastN

### ISSUE THREAD

**Issue by webintoit** [jitsi/lib-jitsi-meet#386]
Is there any way to ask videobridge about lastN endpoints array? There is issue when new user connects to muc, he tries to render all videostreams in conference, but tracks can be frozen.
How it works now: Videobridge tries to send datachannel message, but fails with message `no datachannel opened for user`, and when datachannel will open, bridge does not tries to send this message again. It will be great to query videobridge about lastN after datachannel is opened.

**Comment by paweldomas** [comment]
This sounds like videobridge bug and should be fixed there.

**Comment by paweldomas** [comment]
I don't know when someone will get to fix it, but this event could be used for that: https://github.com/jitsi/jitsi-videobridge/blob/master/src/main/java/org/jitsi/videobridge/EventFactory.java#L86

**Comment by gpolitis** [comment]
@webintoit thanks for reporting this! Could you please file a bug against the JVB, like @paweldomas suggested?

**Comment by webintoit** [comment]
![image](https://cloud.githubusercontent.com/assets/5518513/23825377/4a872452-0691-11e7-983f-c7fd2f42aca1.png)

**Comment by webintoit** [comment]
![image](https://cloud.githubusercontent.com/assets/5518513/23825385/821db732-0691-11e7-8108-20f5a88c28bb.png)

**Comment by bgrozev** [comment]
This seems unrelated, please open a new issue (or better, send a message to the mailing list).

**Comment by gpolitis** [comment]
For the record, the issue that @webintoit originally reported is fixed with https://github.com/jitsi/jitsi-videobridge/pull/429/commits/7461702a5eaefb81fea9a3896a5b4c73cbcec3a9

**Comment by webintoit** [comment]
Thank you guys. You`re best :beer:
