### ISSUE TITLE
Cannot read property 'disableAudioLevels' of undefined

### ISSUE THREAD

**Issue by nzhtrtlc** [jitsi/lib-jitsi-meet#414]
Hi, i followed the Getting Started in the doc.

I added jitsi api 
`<script type="text/javascript" src="https://meet.jit.si/libs/lib-jitsi-meet.min.js"></script>`

And i wrote the code as docs says
`JitsiMeetJS.init();
var options = {};
options.disableAudioLevels = false;
var connection = new JitsiMeetJS.JitsiConnection(null, null, options);`

When i refresh my page
my console.log is 

> [modules/RTC/RTCBrowserType.js] <Array.r>:  This appears to be Chrome, ver: 56
lib-jitsi-meet.min.js:1 Uncaught TypeError: Cannot read property 'disableAudioLevels' of undefined
    at Function.s.init (lib-jitsi-meet.min.js:1)
    at Object.init (lib-jitsi-meet.min.js:1)
    at (index):11
Can you tell me where is my mistake ? Or is that a bug in the api ?

Thanks.

**Comment by damencho** [comment]
Please use the mailinglist for asking questions, before opening an issue.

options.disableAudioLevels should be passed to JitsiMeetJS.init();
Take a look at [lib-jitsi-meet API](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md)
