### ISSUE TITLE
Unused this.peerconnection in RTCUtils.js

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#423]
The `modules/RTC/RTCUtils.js` class holds a `this.peerconnection` that, AFAIS, it not used anywhere:

https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/RTCUtils.js#L708

Can it be just removed?

**Comment by saghul** [comment]
I actually think we should use it here: https://github.com/jitsi/lib-jitsi-meet/blob/81a1b0a31b96723cde5b5b708e8b685fa0915f2c/modules/RTC/TraceablePeerConnection.js#L150

**Comment by ibc** [comment]
Well, that is definitely used. My point is that the `this.peerconnection` in RTCUtils.js should be removed because it has no use.

**Comment by saghul** [comment]
I was agreeing with you :-) It is not used, but I think we should use it where I pointed it out, since we seem to be doing the same work: getting the class to instantiate based on the browser.

**Comment by ibc** [comment]
Yep, `RTCUtils.js` should expose the native/detected/shim `RTCPeerConnection` class.
