### ISSUE TITLE
Safari: TraceablePeerConnection error

### ISSUE THREAD

**Issue by webintoit** [jitsi/lib-jitsi-meet#425]
There is an error fires, when trying to connect with safari (with temasys plugin). 
```
_createOfferOrAnswer 
TypeError: this.peerconnection.createAnswer.bind is not a function. (In 'this.peerconnection.createAnswer.bind(this.peerconnection)', 'this.peerconnection.createAnswer.bind' is undefined)
```

**Comment by saghul** [comment]
I just tested it and didn't get that problem. Are you testing against meet.jit.si?

**Comment by webintoit** [comment]
Nope, i tested it with own UI, using latest lib-jitsi-meet. 
Error happening after jitsiConference.replaceTrack' is called (i think).
```coffeescript
replaceVideoStream: (newStream) ->
      localVideo = @getLocalVideo()
      @room.replaceTrack(localVideo, newStream).then ->
        localVideo.dispose() if localVideo
```

**Comment by saghul** [comment]
@paweldomas do you think this can be related to the P2P work?

**Comment by webintoit** [comment]
I tested it just now with meet.jit.si, it woks there. So it should be local error, but i doing all by documentation.  :ugly_smile:

**Comment by webintoit** [comment]
Yeap) 
Tested https://beta.meet.jit.si/aa with two browsers: safari && chrome. 
I saw same error in safari console. So 2 users == p2p, @saghul, you`re right.

**Comment by saghul** [comment]
Thanks for confirming @webintoit 🙇

**Comment by paweldomas** [comment]
yes, it could be related. I will take a look

**Comment by paweldomas** [comment]
Here's the PR that fixes this particular issue. Hopefully your app will work, but I see that meet.jit.si is having some problems even with the "non p2P" version. Looks like the main video on large area does not repaint unless I resize the window.

https://github.com/jitsi/lib-jitsi-meet/pull/426

**Comment by webintoit** [comment]
@paweldomas, tested, it works! Thank you guys. 👍
