### ISSUE TITLE
Mute and Unmute functionality is not working in firefox

### ISSUE THREAD

**Issue by gsandeep828** [jitsi/lib-jitsi-meet#446]
I'm building an application based on the example by using lib-jitsi-meet.js. when i click mute and un-mute buttons in chrome the functionality is working as expected but come to firefox they are not working.

**Comment by saghul** [comment]
Can you provide some more details? I know we don't stop the camera on Firefox, but no video is transmitted anyway. I just tested it locally and am not seeing the remote video when they mute in Firefox.

**Comment by gsandeep828** [comment]
We are not using video, actually i am trying to mute the audio local track by using lib-jitsi-meet track.mute(); function and its not throwing any kind of errors in console and also tried to set the muted properties for audio element as i work around but it didn't succeed.

**Comment by sapkra** [comment]
I think this is fixed now. If this problem still exists please create a new issue.
