### ISSUE TITLE
unable to  see start/stop live stream option in my jitsi

### ISSUE THREAD

**Issue by tarlesurendra** [jitsi/lib-jitsi-meet#450]
Hello

I have installed the jitsi-meet from the below link on ubuntu 14.04
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

i am able to install successfully on my server Ip 54.214.113.198 and its working but i can not see the 
option that is " start/stop live stream" 

Please may i know how can i fix this problem and let me know the steps or command to resolve that easily..

I would appreciated the help.

Thank you

Thank you

**Comment by saghul** [comment]
You need to install jibri in addition to what you already installed in order for recording to work. Please see https://github.com/jitsi/jibri

**Comment by damencho** [comment]
Hi, could you please use the mailinglist when you have questions or problems, before opening issues. Thanks.

**Comment by tarlesurendra** [comment]
Hello 

i got the below error 

 service jibri-xmpp start
jibri-xmpp: unrecognized service


please may i know the how can i solve this issue.

Thank you

**Comment by tarlesurendra** [comment]
Hello saghul,
 
 i am followed the instructions which you gave me but when at time of point 

Support daemon systemd configurations

ibri expects XOrg and icewm to be running as daemons. To accomplish this, copy the example systemd files from the systemd directory into the appropriate place (/etc/systemd/system/ on Ubuntu 16).

    cp jibri/systemd/*.service /etc/systemd/system/

To start the supporting services

    service jibri-xorg start
    service jibri-icewm start

To start the jibri controller daemon (will not start properly until config.json is properly configured for your Jitsi Meet install)

    service jibri-xmpp start

i have tried above which gave in your link but i got below error for start the services 

service jibri-xorg start
jibri-xorg: unrecognized service

service jibri-icewm start
jibri-icewm: unrecognized service

service jibri-xmpp start
jibri-xmpp: unrecognized service


Please may i know how can i fix this problem and issue 

i would appreciated your help.

Thank you

**Comment by aaronkvanmeerten** [comment]
It sounds like you aren't using systemd.  What init system package are you using?

**Comment by tarlesurendra** [comment]
Hello,

Thank you for your kind reply

i have created  2 instances on AWS that is first is 54.214.113.198 and i have install jitsi-meet on that server IP 54.214.113.198 and its working fine when access the IP 54.202.245.8 in browser  and on 2nd instance that is 54.202.245.8 which install ubuntu 16 and also install jibri on 54.202.245.8 server and services are working fine now on that.

now i am stucked in the point of "Configuring Jibri" from the below link

https://github.com/jitsi/jibri

i dont understand below explanations on the giving helping Link

================================================================

Connecting Jibri to Jitsi Meet

    Jibri requires some settings to be enabled within a Jitsi Meet configuration. This changes include virtualhosts and accounts in Prosody, settings for the jitsi meet web (within config.js) as well as jicofo sip-communicator.properties

    Network: Make sure that port 5222 on your Jicofo instance is open to the Jibri instance. This may means some combination of Security Groups (if in AWS), or local firewall configuration.

    Prosody
        Create the recorder virtual host entry in /etc/prosody/prosody.cfg.lua :

    VirtualHost "recorder.yourdomain.com"
      modules_enabled = {
        "ping";
      }
      authentication = "internal_plain"

        Restart prosody daemon after edits are complete

    Prosody: create accounts for the two methods Jibri uses to connect

    prosodyctl register jibri auth.yourdomain.com jibripass
    prosodyctl register recorder recorder.yourdomain.com jibripass

The first account is the jibri username and password. The second account is the selenium username and password. Record the passwords you choose, as they will be used in config.json below.
================================================================

i dont understand  above explanations so please may i know what steps needs to be done and what data to be inserted as per my details of server to show the recording options and stream options

what value should i changed in below code?

VirtualHost "recorder.yourdomain.com"
  modules_enabled = {
    "ping";
  }
  authentication = "internal_plain"

please give me correct value to set up in above code and where need to change please explain me so
i will do that at my end

please give me correct steps for above to set up at my side and i really would be appraciated your help.

Thank you

**Comment by tarlesurendra** [comment]
Hello,

Thank you for your reply 

now i have solved the services issue and i have installed the ubuntu 16 my new AWS instance 54.202.245.8 and also able to install necessary resources for jibri . i have another instalnce  which is 54.214.113.198 and jitsi -meet installed on that  server IP 54.214.113.198 now i am stuck in below explanations which given in link
https://github.com/jitsi/jibri

=============================================================

Connecting Jibri to Jitsi Meet

    Jibri requires some settings to be enabled within a Jitsi Meet configuration. This changes include virtualhosts and accounts in Prosody, settings for the jitsi meet web (within config.js) as well as jicofo sip-communicator.properties

    Network: Make sure that port 5222 on your Jicofo instance is open to the Jibri instance. This may means some combination of Security Groups (if in AWS), or local firewall configuration.

    Prosody
        Create the recorder virtual host entry in /etc/prosody/prosody.cfg.lua :

    VirtualHost "recorder.yourdomain.com"
      modules_enabled = {
        "ping";
      }
      authentication = "internal_plain"

        Restart prosody daemon after edits are complete

    Prosody: create accounts for the two methods Jibri uses to connect

    prosodyctl register jibri auth.yourdomain.com jibripass
    prosodyctl register recorder recorder.yourdomain.com jibripass
==============================================================

what value should i change in below code 

 VirtualHost "recorder.yourdomain.com"
      modules_enabled = {
        "ping";
      }
      authentication = "internal_plain"

and 

what value should be inserted in below code 

 prosodyctl register jibri auth.yourdomain.com jibripass
    prosodyctl register recorder recorder.yourdomain.com jibripass


please help me to set up the correct value for above as per my servers details so i can change myself to work recording and stream options

i really appraciated your help

thank you

**Comment by tarlesurendra** [comment]
Hello 

Please let us know the solutions for above and also give details steps for "Configuring Jibri" under all steps and what exact values of data should we need to use?

We are awaiting for your response.

Thank you

**Comment by aaronkvanmeerten** [comment]
So I'm not sure what parts you're confused about, as you've pasted a large section from the documentation.
You'll need to alter your prosody settings file, which live on the jitsi meet instance.  Depending on your deployment your file may be in a different path, but the example install uses /etc/prosody/prosody.cfg.lua

Then you'll need to add the snippets from the example, altering yourdomain.com to match your prosody domain name.
You'll also need to run the commands in the snippet about to register accounts against the new domain you've created and also the auth domain that already exists.  You will alter yourdomain.com to match your existing prosody domain setting.

Just so you know, you'll have better luck posting to the mailing list, as this issue tracker is meant to track issues, not questions around configuration.

**Comment by tarlesurendra** [comment]
Hello,

Thank you for your kind update.

i have alter settings in prosudo but its now showing stream option in my jitsi meet

please check below link 

https://54.214.113.198/sss

please what is the best solutions or any easy steps to run video stream easily on my jitsi-meet

I would appreciated your help

Thank you

**Comment by tarlesurendra** [comment]
Hello,

Please provide me simple steps to show the video stream options in my jitsi-meet.

I am awaiting for the response.

Thank you

**Comment by saghul** [comment]
> Just so you know, you'll have better luck posting to the mailing list, as this issue tracker is meant to track issues, not questions around configuration.

@tarlesurendra Please use the mailing list.

**Comment by tarlesurendra** [comment]
Hello,

i have posted issue on 	issues@jitsi.org but i dont get any response please help me to solve 
video stream issue.

 i have instaledl jitsi-meet on AWS instance on ubuntu that is https://54.214.113.198/sss and jibri is installed on another instance of IP 54.202.245.8  and i have followed the all jibri insallatons instructions from the below link
   https://github.com/jitsi/jibri

video stream option is not showing in https://54.214.113.198/sss 

Kindly check above link and please provide any best solutions to world video stream option perfeclty.

 We would appreciated your help

Thank you

**Comment by alfredogt** [comment]
Hello,

The problem you describe indicates that jibri has not been connected to prosody, so jitsi-meet does not detect it.
You should check the prosody and jibri-xmpp logs and look for connection errors.

Sign up for this list, it seems to be more active.

http://lists.jitsi.org/mailman/listinfo/users

Then you can write to: users@jitsi.org

Greetings.

**Comment by astuter** [comment]
Hello @tarlesurendra , 
Did you get this working?
