### ISSUE TITLE
how to unmute for participant jitsi meet?

### ISSUE THREAD

**Issue by nguyendatdh93** [jitsi/lib-jitsi-meet#457]
Hi Team.

I want to custom some thing jitsi meet for my website. I want that : Moderator can unmute for any participant in room. Please! Can you tell me How to do that?.

I can see function 
JitsiConference.prototype.muteParticipant = function(id) {
    const participant = this.getParticipantById(id);
    if (!participant) {
        return;
    }
    this.room.muteParticipant(participant.getJid(), true);
};

in jitsiConference.js. I try to change  false in this.room.muteParticipant(participant.getJid(), false); like this
JitsiConference.prototype.muteParticipant = function(id) {
    const participant = this.getParticipantById(id);
    if (!participant) {
        return;
    }
    this.room.muteParticipant(participant.getJid(), false);
};

But it is not work. 

If someone have any idea. please tell me. thank a lot.

sorry all . My english is not good.

Thank all.

**Comment by webintoit** [comment]
Hi. There is no method to unmute user. 
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java#L1508

You can compile you own jicofo instance without this lines, but this is not good idea for your users.

You can compile jicofo from sources: 
```sh
service jicofo stop

apt-get -y update \
    && apt-get -y install git wget unzip \
    && apt-get -y install default-jdk ant maven

git clone https://github.com/jitsi/jicofo.git focus

cd focus \
    && git checkout YOUR_BRANCH \
    && wget -O lib/maven-ant-tasks-2.1.3.jar http://central.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar \
    && mvn dependency:resolve \
    && ant -lib lib/maven-ant-tasks-2.1.3.jar dist.lin64 \
    && unzip dist/linux/jicofo-linux-x64-build.SVN.zip


rm -rf /usr/share/jicofo \
   && mv jicofo-linux-x64-build.SVN.zip  /usr/share/jicofo

service jicofo start
```

**Comment by nguyendatdh93** [comment]
Hi.
First, thank you a lot.
But I don't understand. I installed flow link :
https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md. I
also installed jicofo on my server. If now i remove this line
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/
JitsiMeetConferenceImpl.java#L1508

so, how can I use this function?. You can give me more
detail instructions?.

Thank you so much,

2017-04-20 16:01 GMT+07:00 Andrey Davydov <notifications@github.com>:

**Comment by webintoit** [comment]
First of all, clone jicofo locally, or fork it. 
Modify source, just remove :
```java
if (!doMute && !fromJid.equals(toBeMutedJid))
        {
            logger.warn("Do not allow unmuting other participants!");
            return false;
        }
```
Then, compile modified jicofo, replace jicofo with your compiled one. 
Run compiled jicofo. 
After that 'iq > mute > false ' requests will work.

**Comment by nguyendatdh93** [comment]
Thank you.

I had worked like this. :

I remove from jicofo.
after that, i run jicofo like this
./jicofo.sh --host=localhost --domain=<mydomain> --secret=1234567
--user_domain=auth.<mydomain> --user_name=focus --user_password=12345678

I dont know how to start jicofo like a servive : service jicofo restart.
because it is not in the guide document
https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md.

then. I insert a function like below in path and design a button unmute on
UI call this function: node_modules/lib-jitsi-meet/JitsiConference.js

JitsiConference.prototype.unMuteParticipant = function(id) {
    const participant = this.getParticipantById(id);
    if (!participant) {
        return;
    }
    console.log('chay vao day');
    this.room.muteParticipant(participant.getJid(), false);
};

that function will next run to function muteParticipant in path :
node_modules/lib-jitsi-meet/modules/xmpp/chatRoom.js

muteParticipant(jid, mute) {
        logger.info('set mute', mute);
        const iqToFocus = $iq(
            { to: this.focusMucJid,
                type: 'set' })
            .c('mute', {
                xmlns: 'http://jitsi.org/jitmeet/audio',
                jid
            })
            .t(mute.toString())
            .up();

        this.connection.sendIQ(
            iqToFocus,
            result => logger.log('set mute', result),
            error => logger.log('set mute error', error));
    }

then. I rebuild node_module.

But it still not working.!.
it is image error:
[image: Hình ảnh nội tuyến 1]

thank you so much

2017-04-20 17:01 GMT+07:00 Andrey Davydov <notifications@github.com>:

**Comment by nguyendatdh93** [comment]
Oh. it worked for me. I rebuild file jar for jicofo. so it worked.
Thank team so much. !

2017-04-20 17:01 GMT+07:00 Andrey Davydov <notifications@github.com>:

**Comment by nkod-pl** [comment]
@nguyendatdh93 could you help me do something similar?
I did all those steps, i see in console set mute false
but it doesnt change anything.also mvn install, recompiled jicofo.jar,
replaced, restarted jicofo, still nothing.

**Comment by nkod-pl** [comment]
@webintoit why this no longer works, i send iq set mute false, see it in console but nothing happens, still muted.

**Comment by saghul** [comment]
Oh, this is still open? Closing. We don't so this because it has severe privacy implications, one shouldn't be able to unmute another participant.

**Comment by aalupov** [comment]
my solutuin is 
in JitsiMeetConferenceImpl.java to remove
if (!doMute && !fromJid.equals(toBeMutedJid))
        {
            logger.warn("Do not allow unmuting other participants!");
            return false;
        }
and at end of method boolean handleMuteRequest to modify to
        if (succeeded)
        {
            participant.setMuted(doMute);
            return true;
        }

        return false;

in ChatRoom.js

    /**
     * TODO: Document
     * @param iq
     */
    onMute(iq) {
        const from = iq.getAttribute('from');

        if (from !== this.focusMucJid) {
            logger.warn('Ignored mute from non focus peer');

            return;
        }
        const mute = $(iq).find('mute');

        if (mute.length && mute.text() === 'true') {
            this.eventEmitter.emit(XMPPEvents.AUDIO_MUTED_BY_FOCUS, mute.attr('actor'));
        } else if (mute.length && mute.text() === 'false') { 
        	this.eventEmitter.emit(XMPPEvents.AUDIO_UNMUTED_BY_FOCUS, mute.attr('actor'));
        } else {
            // XXX Why do we support anything but muting? Why do we encode the
            // value in the text of the element? Why do we use a separate XML
            // namespace?
            logger.warn('Ignoring a mute request which does not explicitly '
                + 'specify a positive mute command.');
        }
    }

in JitsiConferenceEventManager.js to add

    chatRoom.addListener(XMPPEvents.AUDIO_UNMUTED_BY_FOCUS,
            actor => {
                // TODO: Add a way to differentiate between commands which caused
                // us to mute and those that did not change our state (i.e. we were
                // already muted).
                Statistics.sendAnalytics(createRemotelyMutedEvent());

               // conference.mutedByFocusActor = actor;

                // set isMutedByFocus when setAudioMute Promise ends
                conference.rtc.setAudioMute(false).then(
                    () => {
                        conference.isMutedByFocus = false;
                        conference.mutedByFocusActor = null;
                    })
                    .catch(
                        error => {
                            conference.mutedByFocusActor = null;
                            logger.warn(
                                'Error while audio unmuting due to focus request', error);
                        });
            }
        );

**Comment by ashirwad007786** [comment]
@aalupov Is this solution to unmute participants working for you?

**Comment by aalupov** [comment]
> @aalupov Is this solution to unmute participants working for you?

yes, I did mute\unmute video even

**Comment by reysy** [comment]
hi @aalupov, can you share you solution for audio/video mute/unmute please?

**Comment by dyros26** [comment]
@aalupov is this the correct one? or should i replace it with return false?

if (succeeded)
{
participant.setMuted(doMute);
return true;
}

i got disconnected when 1 participant join the room.
![Screen Shot 2020-05-25 at 12 25 01 PM](https://user-images.githubusercontent.com/49423503/82778159-1fd24600-9e83-11ea-9823-1f90cbc44571.png)

**Comment by dyros26** [comment]
already fixed it. thanks

**Comment by dyros26** [comment]
Is the lib-jitsi-meet is for web only?
How can i receive unmute on mobile?

**Comment by ulab** [comment]
> one shouldn't be able to unmute another participant.

I find your lack of ideas disturbing. ;-)

You can easily fix privacy implications by asking the user if he wants to be unmuted by a moderator.

An even better option would be to have two "levels" of muting. A high priority layer would be the user enabling or disabling his microphone and the second layer would be a moderator "mute".

If the user disabled his mic, unmuting of the moderator would not affect that. On the other hand a moderator could mute a participant no matter if he has his mic enabled or disabled.

**Comment by ramalingamvarkala** [comment]
@aalupov, Iam not getting unmute button in UI
