### ISSUE TITLE
Multiple Video Tracks 

### ISSUE THREAD

**Issue by bilhamil** [jitsi/lib-jitsi-meet#464]
Currently, lib-jitsi-meet only allows an endpoint to add one video track to a conference. I am wondering if it is at all planned to eventually support adding multiple video tracks? Is there a suggested work around? The most obvious use case would be having a webcam plus screenshare. I will note that, in my particular application, I would like to be able to support an arbitrary number of video tracks. My understanding is that the videobridge supports endpoints sending multiple video tracks to an extent, but that lib-jitsi-meet does not. 

I implemented a semi-functioning version of this in a clone of lib-jitsi-meet about a year ago, but things seem to have changed quite a bit since then. I am not sure, but it seems like the more difficult parts of the problem are managing multiple simulcast streams and bitrate adaptivity. I assume there are probably other complications. I guess I am just wondering if this is something on the team's radar?

**Comment by Kidav** [comment]
I'm also interested in supporting at least two video tracks.

**Comment by Kidav** [comment]
I think it would be nice to distinguish between  ss video track and camera video track , so SDPDiffer.toJingle have to mark video tracks by num or like so on

**Comment by afrokick** [comment]
Any news?

**Comment by saghul** [comment]
No news, we are still only supporting a single video track per participant at the moment. I'm not aware of any plans to change this.

**Comment by saghul** [comment]
@afrokick I don't think that's currently possible with Jitsi. Maybe by hacking around and closing streams for pupil-pupil communication... but that would be very brittle, and we didn't design Jitsi Meet with that in mind.

Sorry about that.

**Comment by Sylchauf** [comment]
You can use a new connection to share more than one video track.
I use this workaround to send camera track and share screen track. Be careful, the second connection must not send audio track.

**Comment by saghul** [comment]
We have now added the ability to set "effects" on video tracks. Jitsi Meet now uses this feature to mix camera and screensharing into a single stream by using a canvas.

**Comment by tiofabby** [comment]
Hi @saghul , how can we use such effect feature within lib-jitsi-meet? Is it something that could be documented in https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md#installation ?
Thank you!

**Comment by saghul** [comment]
@jallamsetty1 can you please help?

**Comment by jallamsetty1** [comment]
Sure, we can add the documentation for setEffect. Please take a look at https://github.com/jitsi/jitsi-meet/blob/master/react/features/stream-effects/presenter/JitsiStreamPresenterEffect.js for reference. The methods startEffect(), stopEffect() and isEnabled() have to be defined for a particular effect. Please let us know if you have any questions.

**Comment by saghul** [comment]
Thanks Jaya!

**Comment by tiofabby** [comment]
Thank you @jallamsetty1 !! :-)

**Comment by clark-97** [comment]
I want to enable blur background with lib jitsi meet, I saw https://github.com/jitsi/jitsi-meet/blob/master/react/features/stream-effects/blur/JitsiStreamBlurEffect.js ,but still don't know how to enable blur background. I know JitsiTrack.setEffect(**effect**) ,what is the **effect** specific?

**Comment by AK-Inspify** [comment]
any updates in this? We use dual camera system which stream two video track from two separate cameras in one peer and endpoint? Using effect is cpu consuming since two cameras high resolutions cameras. Any plans to support multiple video tracks?

**Comment by saghul** [comment]
Not at the moment, sorry.

Note that you could open the cameras at a lower resolution and then create an effect for the composition. The effect will have some impact (drawing in the canvas) but it should be reasonable.
