### ISSUE TITLE
RTCBrowserType.supportsSimulcast() is too limited

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#470]
Current code:

```js
    /**
     * Whether jitsi-meet supports simulcast on the current browser.
     * @returns {boolean}
     */
    supportsSimulcast() {
        // This mirrors what sdp-simulcast uses (which is used when deciding
        // whether to actually enable simulcast or not).
        // TODO: the logic should be in one single place.
        return window.chrome !== undefined;
    }
```

Just to summarize: Microsoft Edge **does** have `window.chrome` and, for sure, we don't want simulcast on it.

**Comment by ibc** [comment]
NOTE: Even forcing `supportsSimulcast()` to return `false`, the local SDP answer is mangled and simulcast added.

**Comment by bgrozev** [comment]
> NOTE: Even forcing supportsSimulcast() to return false, the local SDP answer is mangled and simulcast added.

I believe this is due to sdp-simulcast (the package) using the same check (for window.chrome). This is what I was referring to in the comment.

**Comment by ibc** [comment]
> I believe this is due to sdp-simulcast (the package) using the same check (for window.chrome).

Sorry, indeed it was clear in the comment.

So, any chance to improve such a check within the `sdp-simulcast` package?

**Comment by paweldomas** [comment]
maybe sdp-simulcast should take this as an option instead of doing detection by itself ?

**Comment by ibc** [comment]
> maybe sdp-simulcast should take this as an option instead of doing detection by itself ?

Given the amount of WebRTC platforms, plugins, shims, etc. it's clear IMHO that a small library should not attempt to detect anything. So 100% agreed.

**Comment by gpolitis** [comment]
I agree with that, and I'm also in favor of removing sdp-simulcast alltogether.

**Comment by saghul** [comment]
Agreed on removing the check from sdp-simulcast.

> I agree with that, and I'm also in favor of removing sdp-simulcast alltogether.

What do you mean here @gpolitis? Putting the sdp-simulcast functionality inside lib-jitsi-meet?

**Comment by paweldomas** [comment]
Should be fixed in https://github.com/jitsi/lib-jitsi-meet/pull/474

**Comment by ibc** [comment]
Thanks, however now there is a NPM peer dependency issue. After `npm install`:

```
lib-jitsi-meet@0.0.0 /Users/ibc/src/lib-jitsi-meet
├── sdp-simulcast@0.2.0
└── UNMET PEER DEPENDENCY webpack@1.14.0

npm WARN babel-loader@7.0.0 requires a peer of webpack@2 but none was installed.
```

**Comment by ibc** [comment]
Fair enough, thanks.
