### ISSUE TITLE
Don't set description.sdp

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#472]
In various places within the RTC module, the `sdp` attribute of a `RTCSessionDescription` is mangled:

In `TraceablePeerConnection.js`:

```js
localDescription.sdp = transformer.toRawSDP();
```

As per spec, the `sdp` attribute is read-only and eventually things may just fail. It's better to create a new description from scratch. In fact, the spec no longer requires passing a real `RTCSessionDescription` instance, but just a `RTCSessionDescriptionInit` which basically is a common Object with two keys: `type` and `sdp`.

**Comment by paweldomas** [comment]
A PR that fixes these issues will be welcome !

**Comment by ibc** [comment]
Believe me, I'm very busy right now fighting with a Windows 10 computer in which, sometimes, the touchpad scroll works :)

**Comment by saghul** [comment]
Agreed, a PR would be most welcome.

**Comment by fippo** [comment]
checked and as far as I can see in all places modifying sdp a new RTCSessionDescription is returned. Which is probably silly, those places should just return an {} object.

Please holler if wrong
