### ISSUE TITLE
[Edge] Need to signal end of remote candidates

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#476]
### The problem

Microsoft Edge does not implement Trickle-ICE, which means that remote candidates cannot be added at any time. And worse, the ORTC `RTCIceTransport` implementation in Edge won't start ICE procedures until an empty candidate `{ }` is given.

So, when the SDP offer from jitsi-videobridge is received, the WebRTC shim (see the exact flow [here](https://github.com/ibc/lib-jitsi-meet/blob/edge-pc/modules/RTC/ortc/RTCPeerConnection.js#L1078)) extracts the candidates from the remote SDP offer, signals them to the `RTCIceTransport` via `addRemoteCandidate(candidate)` and, after that, it also signals an empty candidate via `addRemoteCandidate({})` (otherwise [ICE procedures won't start](https://rawgit.com/aboba/edgertc/master/msortc-rs3.html#widl-RTCIceTransport-addRemoteCandidate-void-RTCIceGatherCandidate-remoteCandidate)).

And even **worse**: after such an empty candidate, `addRemoteCandidate()` cannot be called again with candidates receives later (they would be ignored).

This is not an issue when talking to the server since all the candidates already exists in the SDP. But when it comes to do P2P, remote candidates arrives at any time.

The current [code](https://github.com/ibc/lib-jitsi-meet/blob/edge-pc/modules/RTC/ortc/RTCPeerConnection.js#L1078) works in server mode, but won't work in P2P because it assumes that all the candidates are in the SDP and won't accept candidates given later.

At the same time, the WebRTC `peerconnection.addIceCandidate()` method does **not** allow passing `null` or an empty object as argument, so here another problem.

### Proposal
 
So, a solution coming to my mind is that the library (maybe `JingleSessionPC.js`) calls `peerconnection.addIceCandidate({ })` (with an empty object) just in *Edge*, so the ORTC WebRTC shim will internally call `iceTransport.addRemoteCandidate({ })`), and must do that once it knows that all the remote candidates have been given, this is:

  * If this is a peerconnection with the jitsi-videobridge server, then the library knows that no more remote candidates will be given after calling `setRemoteDescription()`, so call `addIceCandidate({ })` after it.
  * If this is a P2P peerconnection, then somehow signal end of candidates to the remote peer and, on receipt of it, call `addIceCandidate({ })`.

Again, just call `addIceCandidate({ })` if the browser is Edge.

Is something like this possible?

**Comment by ibc** [comment]
More info:

* Somebody must call `iceTransport.addRemoteCandidate({ })`(otherwise ICE won't even start).
* I cannot do it within the ORTC `RTCPeerConnection` shim, because I don't know whether this is a P2P call or not and, if it's P2P, I have no way to know when the remote has sent its last candidate.

**Comment by ibc** [comment]
As told in the meeting, making P2P work in Edge requires too many changes and opens the door to new issues. Hope Edge is just forced to not use P2P (at least for now).

**Comment by saghul** [comment]
@emcho WDYT? I lean towards not doing P2P until Edge supports trickle ICE properly.

**Comment by fippo** [comment]
overtaken by events
