### ISSUE TITLE
How to know local user id

### ISSUE THREAD

**Issue by subsub** [jitsi/lib-jitsi-meet#494]
How do I know local users' id when he/she joined the conference? I read the available docs don't seem to provide such functionality. Am I missing something?

**Comment by alfredogt** [comment]
hi,
look here:
https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiConference.js#L1511

room.myUserId();

I also think I should be in documentation.
Regards

**Comment by subsub** [comment]
@alfredogt Thank you

**Comment by vivekdoshi2** [comment]
@subsub , I think you should close the issue if it solves your problem.
