### ISSUE TITLE
FacingMode for local track is not working

### ISSUE THREAD

**Issue by subsub** [jitsi/lib-jitsi-meet#497]
Currently, the video of my local track is moving the opposite of user's movement, I want to make the local track to display the video like a mirror (mirroring user's movement). I tried to set facingMode to both user and environment when creating local track but none is working. The movement in the video still the opposite of user's movement.
Please help what am I missing?
Thank you

**Comment by alfredogt** [comment]
Hi,
Try this:
JitsiMeetJS.createLocalTracks ({facingMode: 'user'})...

I want to recommend that you join this list:
Http://lists.jitsi.org/mailman/listinfo/users

And then you can send your questions to:
Users@jitsi.org

You can find answers faster.

Greetings.

**Comment by saghul** [comment]
@subsub Mirroring is achieved using a CSS transformation:

```
transform: scaleX(-1);
```

**Comment by subsub** [comment]
@saghul oh, I see... So what's the purpose of `facingMode` option then? I mean what does it do, the 'visible' impact to that user can see by setting faceMode?

**Comment by saghul** [comment]
@subsub It's meant for mobile devices which have 2 cameras, one facing the user and the other facing the environment.
