### ISSUE TITLE
[Edge] ICE error: Wrong MESSAGE-INTEGRITY

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#498]
### The issue

In some cases, Edge cannot establish the ICE connection with JVB. The next screenshot shows:

* At the left: a successful ICE connection, and a random ICE Binding request sent by Edge which gets a OK response from JVB.
* At the right: a similar ICE Binding request sent by Edge which gets an error response from JBC.

![ice-ok-left-ice-wrong-right](https://cloud.githubusercontent.com/assets/16191/26703568/90f9a1b0-472a-11e7-91a7-d9c8102fc30c.png)

The following  screenshot shows the error response sent by JVB (Wrong MESSAGE-INTEGRITY):

![ice-error-response](https://cloud.githubusercontent.com/assets/16191/26703587/9fa08c7e-472a-11e7-8022-8d4120ce687c.png)

So, it may happen that:

1. Indeed Edge is generating Binding request with wrongly calculated MESSAGE-INTEGRITY, or
1. JVB is wrongly checking the request's MESSAGE-INTEGRITY.

### How to reproduce it

I cannot yet confirm that the issue just happens in the following scenario. However it may be  related:

1. Make Chrome enter a room.
1. Make Firefox join that room (or another Chrome).
1. Make Edge join that room.

This scenario means that, at the beginning, Chrome and Firefox try a P2P connection and then they move to the SFU once Edge joins. From my point of view this should have zero impact in how Edge (or any other browser) performs the ICE procedures with JVB.

Said that, I've not seen any kind of ICE role conflict. The JVB sends the SDP offer so it becomes ICE controlling (as per RFC) and Edge receives the SDP offer so becomes ICE controlled. This is ok in the traces above.

**Comment by saghul** [comment]
@bgrozev @gpolitis Can we look a this next week guys?

**Comment by ibc** [comment]
NOTE: I'm perfectly able to reproduce the problem with just two browsers (Edge and Chrome) in a room. It seems to be random.

**Comment by ibc** [comment]
I've ported copy&pasted the jitsi Edge `RTCPeerConnection` shim into my [mediasoup demo](https://demo.mediasoup.org).

I've also seen a STUN 401 from mediasoup (wrong credentials) but just once and after doing many "page reloads" in the Edge tab. I will try to confirm this tomorrow so we can figure out whether this is a bug in Edge or in ice4j.

**Comment by bgrozev** [comment]
Iñaki, do you still have the pcap files? Can you please upload them?

**Comment by bgrozev** [comment]
You can get some useful information from the bridge logs if you add this to /etc/jitsi/videobridge/logging.properties:
org.ice4j.stack.StunStack.level=FINEST

**Comment by ibc** [comment]
AFAIS pcaps generated in the server do NOT contain captures of unsuccessful ICE connections, so I see nothing in those pcaps when Edge fails to establish ICE with the JVB. But I do have a pcap captured in Edge.

**Comment by ibc** [comment]
PCAP file captured in Edge when ICE fails (as shown above):

[error2.zip](https://github.com/jitsi/lib-jitsi-meet/files/1060941/error2.zip)

**Comment by bgrozev** [comment]
Thanks, @ibc! It looks like there are STUN packets coming from Edge which have the wrong USERNAME attribute. I suspect the length field is not set correctly, which makes the Value field span a byte that should be padding.
https://tools.ietf.org/html/rfc5389#section-15

<img width="1059" alt="screen shot 2017-06-13 at 16 52 59" src="https://user-images.githubusercontent.com/3264699/27106467-2444f2f8-5059-11e7-83ab-cb57c6fefef5.png">
<img width="1073" alt="screen shot 2017-06-13 at 16 52 51" src="https://user-images.githubusercontent.com/3264699/27106468-244aef96-5059-11e7-97f6-84767d7fc05a.png">

**Comment by ibc** [comment]
Amazing catch, @bgrozev !

However, I've never got this issue when connecting EDGE to mediasoup (with the very same `RTCPeerConnection` shim I've coded for jitsi). There is a difference: mediasoup is a ICE-Lite server (I set `iceLite: true` in the corresponding ORTC parameter in Edge) but IMHO that should not affect here since being a ICE-Lite endpoint just mean that no Binding requests are sent fro the server to Edge.

Anyhow, I cannot guarantee that this error does never happen with mediasoup because I've not done so many tests as with JVB.

I can directly report this error to people in Microsoft involved in Edge's ORTC. I will report it, ok?

Thanks a lot.

**Comment by bgrozev** [comment]
Yeah, I think we should report this to the Edge developers.

About mediasoup: perhaps they have friendlier parsing, or they discard BRs which fail to authenticate (as opposed to sending an error response).

**Comment by ibc** [comment]
> About mediasoup: perhaps they have friendlier parsing, or they discard BRs which fail to authenticate (as opposed to sending an error response).

Oh no, I'm the author, and ICE parsing is strict and, in case of error, I log it in a very verbose way:

* https://github.com/versatica/mediasoup/blob/master/worker/src/RTC/StunMessage.cpp#L332
* https://github.com/versatica/mediasoup/blob/master/worker/src/RTC/IceServer.cpp#L110

:)

Anyhow, the screenshots you have placed above clearly show a padding error in the USERNAME field, probably due to a wrong length value.

I'll report the issue and let you know.

**Comment by bgrozev** [comment]
> Oh no, I'm the author, and ICE parsing is strict and, in case of error, I log it in a very verbose way

Ah, alright, I didn't know that. Then there must be something in our code which triggers it.

Another thing: in your dump there are pairs of BRs with the same transaction ID, sent one after the other (without a timeout). This doesn't seem right either.

**Comment by ibc** [comment]
Reported in Edge Issue Tracker: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12332512/

**Comment by ibc** [comment]
> Another thing: in your dump there are pairs of BRs with the same transaction ID, sent one after the other (without a timeout). This doesn't seem right either.

What does BR stand for?

**Comment by bgrozev** [comment]
Binding Request

**Comment by ibc** [comment]
Ah ok. Yes, I've sent that, and it produces an error in JVB ("the request with transaction ID N was already replied") but I just ignored it given that should not produce any real problem (IMHO).

**Comment by bgrozev** [comment]
Workaround here: https://github.com/jitsi/ice4j/pull/118

**Comment by ibc** [comment]
Hi @bgrozev, the workaround does not work. Having it enabled ICE never connects.

I attach two pcaps:

a) ICE hack enabled (it does not work)
b) ICE hack disabled (it randomly works, and it this pcap it works so ICE connects)
[ice-hack.zip](https://github.com/jitsi/lib-jitsi-meet/files/1102925/ice-hack.zip)

**Comment by bgrozev** [comment]
Thanks, @ibc, I'm looking into it.

**Comment by bgrozev** [comment]
Can you please test again on edge.jitsi.net? My fix seems broken, if that works I'll push an update.

**Comment by ibc** [comment]
I'll test tomorrow. Thanks.

**Comment by saghul** [comment]
I had a quick test with @bgrozev and it looked promising at first (3 successful calls in a row) but it failed again afterwards. We'll take more pcaps tomorrow.

**Comment by ibc** [comment]
In my current tests, it's behaving as the original code. This is, it randomly successes or fails.

**Comment by ibc** [comment]
Here a new pcap of a failing Edge connection:

[2017-06-27-Edge-ICE-error.zip](https://github.com/jitsi/lib-jitsi-meet/files/1105934/2017-06-27-Edge-ICE-error.zip)

**Comment by ibc** [comment]
And here a pcap of a successful connection from Chrome:

[2017-06-27-Chrome-ICE-OK.pcapng.zip](https://github.com/jitsi/lib-jitsi-meet/files/1105939/2017-06-27-Chrome-ICE-OK.pcapng.zip)

**Comment by bbaldino** [comment]
i've been looking into this and have what i believe is a fix here: https://github.com/jitsi/ice4j/pull/130

**Comment by bbaldino** [comment]
this was fixed by the pr above
