### ISSUE TITLE
[Edge] Wrong VP8 video from Edge to Chrome if ENABLE_VP8_PICID_REWRITING=True

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#520]
This is the video from Edge rendered in Chrome/Firefox:

<img width="1385" alt="captura de pantalla 2017-05-10 a las 20 30 02" src="https://cloud.githubusercontent.com/assets/16191/25914744/9de7068c-35bf-11e7-8631-0b144a0ef06e.png">

It just happens if `ENABLE_VP8_PICID_REWRITING=True`.

**IMPORTANT:** This does not happen the other way around. This is, even with `ENABLE_VP8_PICID_REWRITING=True`, the video from Chrome/Firefox is properly rendered in Edge.

**Comment by gpolitis** [comment]
This should be fixed with https://github.com/jitsi/jitsi-videobridge/pull/495

**Comment by gpolitis** [comment]
This should be now fixed in the latest JVB.
