### ISSUE TITLE
TraceablePeerconnection.js assumes simulcast

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#522]
In `TraceablePeerConnection.prototype.setRemoteDescription` [method](https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/TraceablePeerConnection.js#L1535):

```js
TraceablePeerConnection.prototype.setRemoteDescription
= function(description, successCallback, failureCallback) {
    this.trace('setRemoteDescription::preTransform', dumpSDP(description));

    // TODO the focus should squeze or explode the remote simulcast
    // eslint-disable-next-line no-param-reassign
    description = this.simulcast.mungeRemoteDescription(description);
```

This is assuming simulcast without even checking `RTCBrowserType.supportsSimulcast()`.

**Comment by saghul** [comment]
@paweldomas The last patch which touched this part was P2P, do you have any recollection if this was needed? Also, maybe @bbaldino knows?

**Comment by paweldomas** [comment]
how do you see that it was P2P that touched that ? For me this originates from "initial commit". I think we need to ask @gpolitis if that's needed

**Comment by saghul** [comment]
@paweldomas Sorry, I didn't mean you wrote it :-) But the code moved around at that time.

**Comment by paweldomas** [comment]
Yes, it moved from one directory to another

**Comment by paweldomas** [comment]
I'm just curious how do you evaluate "which was the last patch that touched this" ?

**Comment by bbaldino** [comment]
i believe this is because, by default, this call just 'implodes' any remote simulcast streams in the incoming offer (makes it invisible, basically).  we always want to do this, so there's no check.

**Comment by saghul** [comment]
@paweldomas git blame. It's hard to do proper "git archeology" when there is so much code moving around, but I thought you might know. I'll be looking into this, so worry not!

**Comment by ibc** [comment]
So, to clarify, nothing to be done regarding this issue, right?

**Comment by saghul** [comment]
Nope, I just checked just in case and disabling simulcast works properly. I guess we made a mistake somewhere while testing yesterday...
