### ISSUE TITLE
[Edge] stats audioLevel issue

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#528]
According to the [spec](https://www.w3.org/TR/webrtc-stats/#dom-rtcmediastreamtrackstats-audiolevel), `audioLevel` in stats should be in the range 0..1 (0 is silence). However Edge produces negative values (not sure about the range, but usually with little mic level, it's around -10).

`RTPStatsCollector.js` normalizes Chrome/Firefox values to 0..1. In order to do the same with Edge, an algorithm must be given.

**Comment by ibc** [comment]
[This](https://github.com/ibc/lib-jitsi-meet/commit/7a430de4bd45011c5aa8d8994cb449516f209dc8#diff-d9538dad7e95640e2b2fe4427dfdb5ebR899) is the related code in `RTCStatsCollector.js`.

**Comment by ibc** [comment]
The response regarding `audioLevel` I got from a Microsoft Edge developer is the following:

> We didn't convert the log scale value (dB) to linear scale when we first implemented the stats a couple years ago.  We will probably do a major update in the area down the road when the stats spec stabilizes.

**Comment by ibc** [comment]
Got a better response:

> "0" is full scale, "-10" is 10 dB below full scale. We only report in the range of [-100, 0], so we consider "-100" as silence, which is the default value within our media stack.

So let's work on that.

**Comment by ibc** [comment]
NOTE: However, `audioLevel` reports in Edge's stats don't look very realistic as its value is always around -10 (which is 0.9 in the 0..1 range).

**Comment by ibc** [comment]
Another issue: Edge always includes an `audioLevel` property in `type="track"` stats, even for video tracks. This produces a warning in lib-jitsi-meet "Received audio level for non-audio track").

**Comment by saghul** [comment]
> Another issue: Edge always includes an audioLevel property in type="track" stats, even for video tracks. This produces a warning in lib-jitsi-meet "Received audio level for non-audio track").

Can we filter that?

**Comment by ibc** [comment]
Filtering that would require the same check that the lib already does later (that check producing the warning log). The `type="track"` stat object generated by Edge does not include info regarding which kind of media it carries.

**Comment by ibc** [comment]
The `audioLevel` has been fixed and the ugly warning above has been avoided.
