### ISSUE TITLE
[Edge] Local IP:port not shown

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#529]
When in Edge, the local IP:port is not shown when clicking on "Show more" in the self-view video. It shows "Address: N/A".

However, I can confirm that proper data is being given via the `StatisticsEvents.CONNECTION_STATS` event. In fact, in `RTCStatsCollector.js`, when this is called:

```js
this.eventEmitter.emit(
        StatisticsEvents.CONNECTION_STATS,
        this.peerconnection,
        {
            'bandwidth': this.conferenceStats.bandwidth,
            'bitrate': this.conferenceStats.bitrate,
            'packetLoss': this.conferenceStats.packetLoss,
            'resolution': resolutions,
            'framerate': framerates,
            'transport': this.conferenceStats.transport
        });
```

This is the content of such a object:

```json
{  
  "bandwidth":{  

  },
  "bitrate":{  
    "upload":0,
    "download":0,
    "audio":{  
      "upload":0,
      "download":0
    },
    "video":{  
      "upload":0,
      "download":0
    }
  },
  "packetLoss":{  
    "total":0,
    "download":0,
    "upload":0
  },
  "resolution":{  

  },
  "framerate":{  

  },
  "transport":[  
    {  
      "ip":"52.90.94.230:10000",
      "type":"udp",
      "localip":"2.136.213.170:57934",
      "p2p":false
    }
  ]
}
```

However, such a IP is not shown in the UI. I've checked the rest of the code and also the corresponding React component in the `jitsi-meet` code and I don't find anything that would prevent the IP:port from being displayed (even if some other connection data, such as `framerate` and `resolution` is not given (due #523)).

**Comment by ibc** [comment]
So closing this?

**Comment by saghul** [comment]
👍
