### ISSUE TITLE
Failing to install lib-jitsi-meet on fresh ubuntu machine

### ISSUE THREAD

**Issue by cyberbandya007** [jitsi/lib-jitsi-meet#531]
I am facing issue while building jitsi-meet. The required lib-jitsi-meet is not getting installed from 'npm install'. Following is the error I am facing.

> lib-jitsi-meet@0.0.0 postinstall /home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet
> webpack -p

/home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:11
    new webpack.LoaderOptionsPlugin({
    ^

TypeError: webpack.LoaderOptionsPlugin is not a constructor
    at Object.<anonymous> (/home/skarambelkar/src/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:11:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/skarambelkar/src/jitsi-meet/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/skarambelkar/src/jitsi-meet/node_modules/webpack/bin/webpack.js:39:40)
npm WARN babel-loader@7.0.0 requires a peer of webpack@2 but none was installed.
npm WARN eslint-plugin-mocha@2.0.0 requires a peer of eslint@^2.0.0 but none was installed.
npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! lib-jitsi-meet@0.0.0 postinstall: `webpack -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lib-jitsi-meet@0.0.0 postinstall script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lib-jitsi-meet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lib-jitsi-meet
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lib-jitsi-meet
npm ERR! There is likely additional logging output above.

This looks like some issue with lib-jitsi-meet package in npm repository. Looks like it is not compliant with required webpack api. Can someone please check the repository contents and fix this problem?

Appreciate any response on this.

Thank you,
Sandeep Karambelkar

**Comment by subsub** [comment]
I have the same problem, error on postinstall: webpack -p

**Comment by fidellr** [comment]
me too i got the same error when processing the postinstall scripts `webpack -p` in this command
``` > webpack -p

child_process.js:634
    throw err;
    ^

Error: Command failed: \my-lib-jitsi-meet\lib-jitsi-meet/get-version.sh```

**Comment by thucld** [comment]
Can you show me the dependency declaration for lib-jitsi-meet in package.json?

**Comment by shamoons** [comment]
Same

**Comment by saghul** [comment]
You need to use Node 12 and npm 6. The above errors happen with very old node versions.

**Comment by thiagobrez** [comment]
Actually this happens for me with Node v12.18.4 (lts/erbium) and npm 6.14.6
