### ISSUE TITLE
Document how to run the tests

### ISSUE THREAD

**Issue by tuxayo** [jitsi/lib-jitsi-meet#573]
Without much experience in the nodejs ecosystem, I struggled with the dependencies until finding `npm install --only=dev`

But even then, running `npm test` just starts Chromium on a karma page which stay idle.

What did I miss?

**Comment by bbaldino** [comment]
hey @tuxayo, what you're seeing is an interactive run of the karma unit tests.  they launch a chrome browser window and execute inside of chrome itself.  right now it's set to continuous run by default (which is more useful for debugging).  if you want to just run the tests, you can change the `singleRun` value inside of `karma.conf.js` to `true`, then when you run `npm test` you'll get a summary afterward of the unit tests (pass/failure).  

with the interactive run, you can use chrome's debug console to step through a test and learn more about where it's failing

**Comment by tuxayo** [comment]
Thanks, it worked (I got some error, is that worth another issue?). Where should this be written to be easily found by anyone wanting to run the tests? README? TESTS.md?

**Comment by bbaldino** [comment]
i got that error too...looks like one of the tests has been broken.

yeah if you want to add a tests section in README that'd be much appreciated!

**Comment by sapkra** [comment]
Closed by https://github.com/jitsi/lib-jitsi-meet/commit/09710c7f5d8671c33d983e113e54f7a3e8497d87
