### ISSUE TITLE
Question - Support screen sharing for ios/ android

### ISSUE THREAD

**Issue by tyleralves** [jitsi/lib-jitsi-meet#576]
I'm interested in building a library that allows screen sharing for my ios/ android applications. I use react-native and it looks like like I would have no problem adapting the jitsi-meet react-native app to my needs but when I played with the app there was no screen sharing option and I don't see any mention in these docs.

Cheers!
Tyler

**Comment by jallamsetty1** [comment]
Screensharing is now available for Android on the react-native app.
