### ISSUE TITLE
Documentation for example 

### ISSUE THREAD

**Issue by inkhey** [jitsi/lib-jitsi-meet#603]
It will be cool to have a small documentation in order to try example from /doc/example.
I don't really know how to make it work.

**Comment by blueridanus** [comment]
Seconded. The code is mostly self-explanatory, but it's not particularly clear how you go about displaying the tracks, what the library needs to connect to, and what the _hosts_ object in the _options_ parameter of the [JitsiConnection](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md#jitsiconnection) constructor is.

**Comment by inkhey** [comment]
@blueridanus : The hosts objet is the configurations params for XMPP connections , the domain name for authentification , the component for muc  and an other domain name if you want an anonymous domain, to me it's almost clear because i tried to set up jitsi-meet first and those params are the same as in jitsi-meet config .

To complete the problem, i have few error of reference on the console, probably because there is a way to install the example, but no doc about it.

**Comment by sapkra** [comment]
Closing it in favor of #1189
