### ISSUE TITLE
lib-jitsi-meet  build issue on ubuntu machine

### ISSUE THREAD

**Issue by sujasj** [jitsi/lib-jitsi-meet#627]
I have executed the npm install command and got the following message. It show no ERROR. But have some warning.
`root@jitsi-server64:~/jitsi/lib-jitsi-meet/lib-jitsi-meet-master# sudo npm install
npm WARN deprecated strophe@1.2.4: This package is no longer maintained; use 'strophe.js' instead.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN prefer global jshint@2.9.5 should be installed with -g

> git-validate@2.2.2 install /root/jitsi/lib-jitsi-meet/lib-jitsi-meet-master/node_modules/git-validate
> node bin/install

WARNING: Unable to find a .git directory for this project, installation aborted.

> precommit-hook@3.0.0 install /root/jitsi/lib-jitsi-meet/lib-jitsi-meet-master/node_modules/precommit-hook
> node bin/install

> uglifyjs-webpack-plugin@0.4.6 postinstall /root/jitsi/lib-jitsi-meet/lib-jitsi-meet-master/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN lifecycle lib-jitsi-meet@0.0.0~postinstall: cannot run in wd %s %s (wd=%s) lib-jitsi-meet@0.0.0 webpack -p /root/jitsi/lib-jitsi-meet/lib-jitsi-meet-master`

After this, as per https://libraries.io/github/jitsi/lib-jitsi-meet, I executed "npm run watch" and got the following error
`root@jitsi-server64:~/jitsi/lib-jitsi-meet/lib-jitsi-meet-master# sudo npm run watch
npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

npm ERR! missing script: watch
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/jitsi/lib-jitsi-meet/lib-jitsi-meet-master/npm-debug.log`

Can someone please check this issue and let me know how to resolve this.

Thanks

**Comment by sujasj** [comment]
To resolve the issue, I have downloaded the code using git clone and installed webpack using "sudo npm install -g webpack@3.6.0"

Now am getting following log -
> root@jitsi-server64:~/jitsi/gitlib/lib-jitsi-meet# sudo npm install
npm WARN lifecycle lib-jitsi-meet@0.0.0~postinstall: cannot run in wd %s %s (wd=%s) lib-jitsi-meet@0.0.0 webpack -p /root/jitsi/gitlib/lib-jitsi-meet
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN karma-webpack@1.8.1 requires a peer of webpack@^1.1.0 || ^2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.

**Comment by saghul** [comment]
Those are not errors, they are warnings because those optional dependencies only apply to macOS. You can carry on :-)

**Comment by sujasj** [comment]
Thanks Saghul
