### ISSUE TITLE
Connection Failed issue

### ISSUE THREAD

**Issue by sujasj** [jitsi/lib-jitsi-meet#635]
Once I build the lib-jitsi-meet, I tried the example in example folder by changing the domain as "meet.jit.si" (in example.js). But got the follwing connection failed error in the local. Also I tried with local installed jitsi-meet application URL. In both case connection failed

Console Log:
`[modules/xmpp/xmpp.js] <value>:  (TIME) Strophe disconnected:	 105212.24  Logger.js:124
[modules/xmpp/xmpp.js] <value>:  XMPP connection dropped!  Logger.js:124
Connection  Failed`

Please help me to resolve the issue.

**Comment by damencho** [comment]
Do you have bosh working for the domain you are trying to use?

**Comment by sujasj** [comment]
No. Bosh is not installed

**Comment by damencho** [comment]
You can test bosh by opneing https://youdomain.com/http-bind the result should  be the same if you open https://meet.jit.si/http-bind

**Comment by sujasj** [comment]
Yes both results are same

**Comment by damencho** [comment]
Can you paste the whole js console log, it may reveal something more, cause the two lines you posted doesn't ring a bell at all.

**Comment by sujasj** [comment]
Hi, Here am attaching the screenshot for the console log
![consolelog](https://user-images.githubusercontent.com/32899748/32643630-a7982886-c602-11e7-931b-a942dec743ba.png)

**Comment by damencho** [comment]
Are you loading the app from a web server? 
Loading the file from the local filesystem will not work. This is a webrtc application in order to work it needs to be served from a webserver using https (http will not work).

**Comment by sujasj** [comment]
Yes, am running from the local file system, will move to the server and will check again. Thanks for your information

**Comment by sujasj** [comment]
It is worked after loading the sample from a web server. Thank you so much for your help.

**Comment by Duonglam44** [comment]
@damencho how can i by pass this issue on local ?
i am currently using jitsi-meet version 8719
many thanks
