### ISSUE TITLE
Chat Implementation

### ISSUE THREAD

**Issue by sujasj** [jitsi/lib-jitsi-meet#644]
Hi,
I need to implement a video conferencing / chat session to my  web application. To implement the Chat session, I found the function to send messages to participant as "sendTextMessage()". Also for sending messages via data Chanel is "sendEndpointMessage()". Here which function will be used to send the message in between the participants in the conference and how to synchronize the message display. Can anyone provide a sample code or any related discussion to implement chat on my web application. 
Thanks,
Suja

**Comment by damencho** [comment]
lib-jitsi-meet already has implemented chat functionality.
https://github.com/jitsi/lib-jitsi-meet/blob/3aa2356f7a5d81b36b3dafe5307e1f52b6e6ceb7/JitsiConference.js#L565
And you can listen for incoming messages, for example take a look how jitsi-meet is doing that:
https://github.com/jitsi/jitsi-meet/blob/5c464a7bdad95b5a87330ed119b093f9e715bbb5/conference.js#L1864
