### ISSUE TITLE
Can't set custom resolution for newGUM

### ISSUE THREAD

**Issue by Kukunin** [jitsi/lib-jitsi-meet#653]
I get a problem with setting a resolution for `getUserMedia`. It just ignores `resolution` option for `createLocalTracks` function. 

as a proof here is a stack trace from the debugger:

* `JitsiMeetJS.createLocalTracks` https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiMeetJS.js#L259
* `RTC.obtainAudioAndVideoPermissions` https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/RTC.js#L203
* `RTCUtils.newObtainAudioAndVideoPermissions` https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/RTCUtils.js#L1448
* `RTCUtils.newGetConstraints` https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/RTCUtils.js#L391

`RTCUtils.newGetConstraints` ignores `options.resolution` completely. 

Yes, I know, I can set `options.constraints` directly (I guess that's not a part of the public interface), but there is the other problem: if constraints fail, it goes into endless loop.

The reason is the check here https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiMeetJS.js#L325 to try again with lower the resolution, which affects nothing.

**Comment by saghul** [comment]
> Yes, I know, I can set options.constraints directly (I guess that's not a part of the public interface)

It is part of the interface, you can set the video constraints you like there.

Ping @bbaldino @virtuacoplenny for the endless loop thing.
