### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by sujasj** [jitsi/lib-jitsi-meet#667]
Hi, 
I have integrated the Video Conferencing/Chat functionality to my application. Now I  need to implement the screen sharing. Can anyone provide a sample code or any related discussion to implement screen sharing on my web application.
Thanks,
Suja

**Comment by chandrantwins** [comment]
Hi Suja 

Please can you share your ideas.. how to integrate video conferencing and chat functinality.. is there any documentation

**Comment by sujasj** [comment]
Hi, Once you build the lib-jitsi-meet, will got the js files. Using that you can run the sample given in the source code.  The source code provides the video conferencing functionality. For chat implementation, pls follow https://github.com/jitsi/lib-jitsi-meet/issues/644

**Comment by chandrantwins** [comment]
Hi Sujasj Thanks for your message. I am totally new to jitsi. Please can you send me what are the files will be generated  from lib-jitsi-meet. Its better send me screenshot of folder and files. How with that files i can execute samples.. Sorry i dont have basic knowledge of Jitsi. Thats why i am asking for very basic help. Thanks for your understanding

**Comment by saghul** [comment]
For requesting a desktop sharing track, see `createLocalTracks` and the `devices` option. For general questions please use the mailing list.
