### ISSUE TITLE
Support token for authentication with lib-jitsi-meet

### ISSUE THREAD

**Issue by nathando** [jitsi/lib-jitsi-meet#680]
The [JItsi External API](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md.) is already able to authenticate using a token 
However, using lib-jitsi-meet, we still are unable to do this, as mention in the [doc](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md):

> token - secret generated by the provider of Jitsi Meet video conferencing services. The token will be send to the provider from the Jitsi Meet server deployment for authorization of the current client. NOTE: not implemented yet. You can safely pass null

Any plan on having this on lib-jitsi-meet soon ? The lib provide much more control on the UI for developers. I could create a PR if some one can give some pointer on which part of the code should be changed.

**Comment by damencho** [comment]
External API and jitsi-meet are using lib-jitsi-meet, so tokens work everywhere. What problem do you see with lib-jitsi-meet?

**Comment by nathando** [comment]
oh really ? 
It works using External API:

```
var options = {
   jwt: "<jwt_token>",
   noSsl: false
};
var api = new JitsiMeetExternalAPI(domain, options);

```
But it does not work using lib-jitsi-meet: 
```
var connection = new JitsiMeetJS.JitsiConnection(<app_id>, <jwt_token>, options);
```
It the error I've got is: **connection.passwordRequired**

**Comment by nathando** [comment]
My bad, turns out it's because the token is expired. It works on lib-jitsi-meet as well.
But we should remove the `NOTE: not implemented yet. You can safely pass null` in the api doc

**Comment by xophio** [comment]
@nathando I'm having trouble in generating a compatible token. Can you please explain to me how you have done it.

**Comment by saghul** [comment]
@nathando Updated, thanks!

**Comment by nathando** [comment]
@xophio I just followed this [format](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md) and use jwt to encode it. Remember to specify the correct secret in your server vs. client (simpler method).

**Comment by xophio** [comment]
@nathando You are right, it was because I used different secrets on the server vs clients. Thanks!
