### ISSUE TITLE
Unable to join room

### ISSUE THREAD

**Issue by xophio** [jitsi/lib-jitsi-meet#688]
I've installed jitsi-meet using quick install, tested and it is working fine.

Issue is when I try using the lib-jitsi-meet, I'm getting an error while trying to join a room 
"Strophe: error: caps.generateCapsAttrs is not a function
TypeError: caps.generateCapsAttrs is not a function at ChatRoom.sendPresence"

**Comment by antobinary** [comment]
Hi @xophio 
It is possible that you were missing dependency scripts. The example has this section:
```<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script src="libs/jquery-2.1.1.min.js"></script>
    <script src="libs/strophe/strophe.js"></script>
    <script src="libs/strophe/strophe.disco.min.js?v=1"></script>
    <script src="../../lib-jitsi-meet.js"></script>
    <script src="example.js" ></script>
</head>```
Speciphically the Strophe* ones. I hit this issue too but resolved it by adding the links to the libraries
