### ISSUE TITLE
bad video quality remoteTrack

### ISSUE THREAD

**Issue by bbiaudet** [jitsi/lib-jitsi-meet#694]
Hello, sorry for my english, I'm french;)

I can not find how to receive the HD stream of other participants to display them in full screen. The function of the onRemoteTrack example shows SD quality.

how to do ?

Thank you for your help

**Comment by saghul** [comment]
What server are you testing against? Does it work when to target meet.jit.si? Note that the server may choose to send you SD if it detects you don't have enough bandwidth for HD.

**Comment by bbiaudet** [comment]
the server is a debian if I use the interface of jitsi I have the image in HD with the same connection.

**Comment by saghul** [comment]
But when you test with lib-jitsi-meet, are you testing the meet.jit.si servers or your own installation? If it's tha latter, can you paste your config?

**Comment by bbiaudet** [comment]
its my server.

        ar config = { // eslint-disable-line no-unused-vars
        // Configuration
        //

        // Alternative location for the configuration.
        //configLocation: './config.json',

        // Custom function which given the URL path should return a room name.
        //getroomnode: function (path) { return 'someprefixpossiblybasedonpath'; },


        // Connection
        //

        hosts: {
        // XMPP domain.
        domain: 'livecode.concept-permis.fr',

        // XMPP MUC domain. FIXME: use XEP-0030 to discover it.
        muc: 'conference.livecode.concept-permis.fr',

        // When using authentication, domain for guest users.
        //anonymousdomain: 'guest.example.com',

        // Domain for authenticated users. Defaults to <domain>.
authdomain: 'livecode.concept-permis.fr',

// Jirecon recording component domain.
jirecon: 'jirecon.livecode.concept-permis.fr',

// Call control component (Jigasi).
call_control: 'callcontrol.livecode.concept-permis.fr',

// Focus component domain. Defaults to focus.<domain>.
    focus: 'focus.livecode.concept-permis.fr',
    },

    // BOSH URL. FIXME: use XEP-0156 to discover it.
    bosh: '//livecode.concept-permis.fr/http-bind',

    // The name of client node advertised in XEP-0115 'c' stanza
    clientNode: 'http://jitsi.org/jitsimeet',

    // The real JID of focus participant - can be overridden here
    focusUserJid: 'focus@auth.livecode.concept-permis.fr',


    // Testing / experimental features.
    //

    testing: {
    // Enables experimental simulcast support on Firefox.
    enableFirefoxSimulcast: false,
    // P2P test mode disables automatic switching to P2P when there are 2
    // participants in the conference.
    p2pTestMode: true,
    },

    // Disables ICE/UDP by filtering out local and remote UDP candidates in
    // signalling.
    //webrtcIceUdpDisable: false,

    // Disables ICE/TCP by filtering out local and remote TCP candidates in
    // signalling.
    //webrtcIceTcpDisable: false,
    //

    // Audio

    // Disable measuring of audio levels.
    //disableAudioLevels: false,

    // Start the conference in audio only mode (no video is being received nor
    // sent).
    startAudioOnly: false,

    // Every participant after the Nth will start audio muted.
    //startAudioMuted: 10,

    // Start calls with audio muted. Unlike the option above, this one is only
    // applied locally. FIXME: having these 2 options is confusing.
    //startWithAudioMuted: false,

    // Video

    // Sets the preferred resolution (height) for local video. Defaults to 720.
    resolution: 720,

    // Enable / disable simulcast support.
    disableSimulcast: false,

    // Suspend sending video if bandwidth estimation is too low. This may cause
    // problems with audio playback. Disabled until these are fixed.
    disableSuspendVideo: true,

    // Every participant after the Nth will start video muted.
    startVideoMuted: 10,

    // Start calls with video muted. Unlike the option above, this one is only
    // applied locally. FIXME: having these 2 options is confusing.
    //startWithVideoMuted: false,

    // If set to true, prefer to use the H.264 video codec (if supported).
    // Note that it's not recommended to do this because simulcast is not
    // supported when  using H.264. For 1-to-1 calls this setting is enabled by
    // default and can be toggled in the p2p section.
    preferH264: false,

    // Desktop sharing

    // Enable / disable desktop sharing
    disableDesktopSharing: false,

    // The ID of the jidesha extension for Chrome.
    desktopSharingChromeExtId: null,

    // Whether desktop sharing should be disabled on Chrome.
    desktopSharingChromeDisabled: true,

    // The media sources to use when using screen sharing with the Chrome
    // extension.
    desktopSharingChromeSources: ['screen', 'window', 'tab'],

    // Required version of Chrome extension
    desktopSharingChromeMinExtVersion: '0.1',

    // The ID of the jidesha extension for Firefox. If null, we assume that no
    // extension is required.
    desktopSharingFirefoxExtId: null,

    // Whether desktop sharing should be disabled on Firefox.
    desktopSharingFirefoxExtensionURL: null,

    // Try to start calls with screen-sharing instead of camera video.
    //startScreenSharing: false,

    // Recording

    // Whether to enable recording or not.
    enableRecording: false,

    // Type for recording: one of jibri or jirecon.
    recordingType: 'jibri',

    // Misc

    // Default value for the channel "last N" attribute. -1 for unlimited.
    channelLastN: -1,

    // Disables or enables RTX (RFC 4588) (defaults to false).
    //disableRtx: false,

    // Use XEP-0215 to fetch STUN and TURN servers.
    //useStunTurn: true,

    // Enable IPv6 support.
    //useIPv6: true,

    // Enables / disables a data communication channel with the Videobridge.
    // Values can be 'datachannel', 'websocket', true (treat it as
    // 'datachannel'), undefined (treat it as 'datachannel') and false (don't
    // open any channel).
    openBridgeChannel: true,


    // UI
    //

    // Use display name as XMPP nickname.
    useNicks: true,

    // Require users to always specify a display name.
    requireDisplayName: true,

    // Whether to use a welcome page or not. In case it's false a random room
    // will be joined when no room is specified.
    enableWelcomePage: false,

    // Enabling the close page will ignore the welcome page redirection when
    // a call is hangup.
    enableClosePage: true,

    // Disable hiding of remote thumbnails when in a 1-on-1 conference call.
    //disable1On1Mode: false,

    // The minimum value a video's height (or width, whichever is smaller) needs
    // to be in order to be considered high-definition.
    minHDHeight: 540,

    // Default language for the user interface.
    defaultLanguage: 'fr',

    // If true all users without a token will be considered guests and all users
    // with token will be considered non-guests. Only guests will be allowed to
    // edit their profile.
    enableUserRolesBasedOnToken: false,

    // Message to show the users. Example: 'The service will be down for
    // maintenance at 01:00 AM GMT,
    //noticeMessage: '',


    // Stats
    //

    // Whether to enable stats collection or not.
    //disableStats: false,

    // To enable sending statistics to callstats.io you must provide the
    // Application ID and Secret.
    //callStatsID: '',
    //callStatsSecret: '',


    // Privacy
    //

    // If third party requests are disabled, no other server will be contacted.
    // This means avatars will be locally generated and callstats integration
    // will not function.
    disableThirdPartyRequests: true,

    // Peer-To-Peer mode: used (if enabled) when there are just 2 participants.
    //

    p2p: {
    // Enables peer to peer mode. When enabled the system will try to
    // establish a direct connection when there are exactly 2 participants
    // in the room. If that succeeds the conference will stop sending data
    // through the JVB and use the peer to peer connection instead. When a
    // 3rd participant joins the conference will be moved back to the JVB
    // connection.
    enabled: false,

    // Use XEP-0215 to fetch STUN and TURN servers.
    //useStunTurn: true,

    // The STUN servers that will be used in the peer to peer connections
    stunServers: [
    { urls: "stun:stun.l.google.com:19302" },
    { urls: "stun:stun1.l.google.com:19302" },
    { urls: "stun:stun2.l.google.com:19302" }
    ],

    // If set to true, it will prefer to use H.264 for P2P calls (if H.264
    // is supported).
    preferH264: true

    // How long we're going to wait, before going back to P2P after the 3rd
    // participant has left the conference (to filter out page reload).
    //backToP2PDelay: 5
    },


    // Information about the jitsi-meet instance we are connecting to, including
    // the user region as seen by the server.
    deploymentInfo: {
    //shard: "shard1",
    //region: "europe",
    //userRegion: "asia"
    }
    };

**Comment by bbiaudet** [comment]
![screen-capture](https://user-images.githubusercontent.com/16972115/35431258-13237848-027c-11e8-872f-85725beb16c9.jpg)

**Comment by saghul** [comment]
I see. When you call JitsiMeetJS.createLocalTracks, are you setting the resolution in the options parameter? If not, try to pass an options object like this:

```
const options = {
    resolution: 720
};
```

**Comment by saghul** [comment]
Also, use the chrome://webrtc-internals page to check what constraints were passed to getUserMedia.

**Comment by bbiaudet** [comment]
Yes i use this options already

JitsiMeetJS.createLocalTracks({ devices: [ 'audio', 'video' ], resolution:'720' })
        .then(onLocalTracks)
        .catch(error => {
        throw error;
    });

**Comment by bbiaudet** [comment]
after use webrtc-internals : 

Caller process id: 39526
Audio Constraints
{advanced: [{googEchoCancellation: {exact: true}}, {googAutoGainControl: {exact: true}}, {googHighpassFilter: {exact: true}}, {googExperimentalNoiseSuppression: {exact: true}}, {googExperimentalEchoCancellation: {exact: true}}, {googExperimentalAutoGainControl: {exact: true}}]}
Video Constraints
{width: {min: 1280, max: 1280}, height: {min: 720, max: 720}}

**Comment by saghul** [comment]
Doh, that looks correct. I'm afraid I can't help you. Hopefully someone else from the team chimes in with some other things to try!

**Comment by bbiaudet** [comment]
Ok thanks, I thought about that, the following function does get back by the thumbnail? there is not another stream of transmit?

```
if (track.getType() === 'video') {
        $('body').append(
            `<video autoplay='1' id='${participant}video${idx}' />`);
    } else {
        $('body').append(
            `<audio autoplay='1' id='${participant}audio${idx}' />`);
    }
    track.attach($(`#${id}`)[0]);
```

**Comment by gpolitis** [comment]
Have you signaled to the bridge that you want to receive HD?

**Comment by bbiaudet** [comment]
That is to say ?

**Comment by vivekdoshi2** [comment]
How can I signal the bridge that I want this quality for the particular participant ? Is that even possible ?

**Comment by nadelicious** [comment]
Please use this ff functions..
``
room,.selectParticipant(pId);
room.pinParticipant(pId);

``

**Comment by roy2651** [comment]
you can use DOMINANT_SPEAKER_CHANGED listener somebody‘s speak，and then change the remote video，use selectParticipant get more high quality  video @bbiaudet

**Comment by sapkra** [comment]
Closing it because of inactivity and I don't think there is a problem anymore. If there are still issues please have a look in the community forum or create a new issue.
