### ISSUE TITLE
send test message

### ISSUE THREAD

**Issue by akash0091** [jitsi/lib-jitsi-meet#710]
Hello,

I have seen all function but im unable to send text messages.
Here is my test code

> <html itemscope itemtype="http://schema.org/Product" prefix="og: http://ogp.me/ns#" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
    </head>
    <body>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://meet.jit.si/external_api.js"></script>
        <script src="https://meet.jit.si/libs/lib-jitsi-meet.js"></script>

        
        <script>
            var domain = "meet.jit.si";
            var options = {
                roomName: "roomname",
                width: $(document).width()-100,
                height: $(document).height()-100,
                parent: undefined,
                configOverwrite: {},
                desktopSharingChromeSources: ['screen', 'window'],
                interfaceConfigOverwrite: {
                    filmStripOnly: true
                }
            }
            var api = new JitsiMeetExternalAPI(domain, options);
           // api.executeCommand('toggleShareScreen')
           api.executeCommand('toggleChat');
           

           function incomingMessageListener(object)
            {
                alert(object);
            }
            
            function outgoingMessageListener(object)
            {

            }
            
            api.addEventListeners({
                incomingMessage: incomingMessageListener,
                outgoingMessage: outgoingMessageListener});

        </script>
    </body>
</html>

which function i should use for sending text messages?

**Comment by saghul** [comment]
Please open an issue on the jitsi-meet repo, that's where it belongs, since you are using the external API.
