### ISSUE TITLE
How can I use lib-jitsi-meet in my react-native application?

### ISSUE THREAD

**Issue by sajidcosmo** [jitsi/lib-jitsi-meet#712]
Hi,

It would be nice if someone can help me getting started with lib-jitsi-meet in a blank react-native application.

jitsi-meet application is quite complex to take reference from.

**Comment by eroy4u** [comment]
Same question. Is there a simple example application to use lib-jitsi-meet ?

**Comment by damencho** [comment]
In the doc folder there is a documentation and example. This is what we have currently, it is generic js so you can use it with a framework of your choice.

**Comment by sajidcosmo** [comment]
I have managed to do it. Following is the way and the sample code snippet:

1) Run the following to create a project
react-native init MyProject

2) Copy https://github.com/CoSMoSoftware/wavertc/tree/master/mobile/TestProject/base in the root folder of your project.

3) Copy the missing scripts, dependencies and devDependencies from  https://github.com/CoSMoSoftware/wavertc/blob/master/mobile/TestProject/package.json in your package.json

4) Run the following 3 commands from the project directory:
npm install
react-native link react-native-background-timer
react-native link react-native-webrtc

5) Add the following in android/app/src/main/AndroidManifest.xml:
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

6) Follow the following to make iOS application ready to use with react-native-webrtc:
https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md

7) Add the following on top of App.js
global.DOMParser = require('xmldom').DOMParser;

8) import the following in the file where you are intending to use lib-jitsi-meet API:
global.DOMParser = require('xmldom').DOMParser;

9) Following is a sample code showing how to connect, join and create local tracks in right sequence:

      const ROOM_ID = ROOM_NAME.toLowerCase();
      const CONFIG_JS = CONTENT_FROM_CONFIG_JS;

      var config = mergeRecursive(JSON.parse('{"p2p":{"disableH264":false,"preferH264":true},"disableAudioLevels":true}'), CONFIG_JS);

      JitsiMeetJS.init({enableAnalyticsLogging:false, ...config});
      
      var options = Object.assign({}, config);
      options.bosh = options.bosh + '?room=' + ROOM_ID;
      var connection = new JitsiMeetJS.JitsiConnection(null, null, options);

      var onConnectionSuccess = id => {

        var conference = connection.initJitsiConference(ROOM_ID, {...config, applicationName:'Jitsi Meet', getWiFiStatsMethod:null});

        var onConferenceTrackAdded = track => {
          // use track.isLocal() to differentiate between local and remote stream
          // use track.getType() to differentiate between audio and video streams
        }
        conference.on(JitsiMeetJS.events.conference.TRACK_ADDED, onConferenceTrackAdded);

        var onConferenceTrackRemoved = function(track) {
          // Handle track removal event
        }
        conference.on(JitsiMeetJS.events.conference.TRACK_REMOVED, onConferenceTrackRemoved);

        var onConferenceJoined = function() {

          var onLocalTracks = function(tracks) {
            for (let i = 0; i < tracks.length; i++)
              conference.addTrack(tracks[i]);
          }
          JitsiMeetJS.createLocalTracks({devices: ['video']}, false).then(onLocalTracks).catch(error => console.warn('Exception caught', error));
          JitsiMeetJS.createLocalTracks({devices: ['audio']}, false).then(onLocalTracks).catch(error => console.warn('Exception caught', error));

        }
        conference.on(JitsiMeetJS.events.conference.CONFERENCE_JOINED, onConferenceJoined);

        var onConferenceLeft = function() {
          // When a participant has left the conference
        }
        conference.on(JitsiMeetJS.events.conference.CONFERENCE_LEFT, onConferenceLeft);

        conference.join();

      }
      connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_ESTABLISHED, onConnectionSuccess);

      var onConnectionFailed = function(error, message, credentials, details) {
        // When connection is failed
      }
      connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_FAILED, onConnectionFailed);

      var onConnectionDisconnected = function(msg) {
        // When connection is disconnected
      }
      connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_DISCONNECTED, onConnectionDisconnected);

      var onWrongState = function() {
        // When connection gets a wrong state
      }
      connection.addEventListener(JitsiMeetJS.events.connection.WRONG_STATE, onWrongState);

      connection.connect();

**Comment by tmy47** [comment]
It appears that the links to https://github.com/CoSMoSoftware/wavertc/tree/master/mobile/TestProject/base and 
https://github.com/CoSMoSoftware/wavertc/blob/master/mobile/TestProject/package.json  are 404'ing. Is there a way you could either update them or post the contents here? I'd like to know what the package.json looks like.

**Comment by stevezhu** [comment]
@tmy47 Solution I'm using that kind of works https://github.com/soareschen-cosmo/lib-jitsi-meet-wrapper

**Comment by atyenoria** [comment]
I managed to implement the iOS app react-native by using
1. https://github.com/jitsi/react-native-webrtc/commit/111da886907024801bb3c90116708c6aad6dbba4
2. https://github.com/jitsi/lib-jitsi-meet/commit/86961786be79ad0809a0c0775461da2b3c85deda
3. import JitsiMeetJS from '../../react/features/base/lib-jitsi-meet/_';
4. "react-native": "^0.57.3",


But, Android always got the error msg when importing JitsiMeetJS.
"""
java.lang.Boolean cannot be cast to java.lang.Double
""" 
Does anyone know the clues how to solve this??

**Comment by roy2651** [comment]
@atyenoria https://github.com/skrafft/react-native-jitsi-meet ，this is can for you

**Comment by roy2651** [comment]
> @tmy47 Solution I'm using that kind of works https://github.com/soareschen-cosmo/lib-jitsi-meet-wrapper. You should probably change the name of the storage in `lib-jitsi-meet-wrapper/storage/polyfills-browser.js` though.

@stevezhu hi，how to use this repo？

**Comment by dgeorgiev06** [comment]
Check this: https://medium.com/@dgeorgiev06/chat-and-video-conference-app-with-react-native-ignite-lib-jitsi-meet-react-native-callkit-21089944ba54

**Comment by zayedelfasa** [comment]
> @atyenoria https://github.com/skrafft/react-native-jitsi-meet ，this is can for you

its work for android, but for iOS doesn't work. I have try it.

**Comment by mayur-bhandari** [comment]
@atyenoria Can you share your code. Because i am unable to get any view on the screen.
