### ISSUE TITLE
setRemoteDescription -> InvalidStateError

### ISSUE THREAD

**Issue by webintoit** [jitsi/lib-jitsi-meet#725]
Hi guys. there is an error with[Chrome -> Firefox] meetings. 
Steps to reproduce this bug: 
- Chrome user shows video. 
- Firefox user shows video. 
Chrome user reloads browser.
![image](https://user-images.githubusercontent.com/5518513/37962219-15395334-31c3-11e8-8aab-b87fa0b1538b.png)

![image](https://user-images.githubusercontent.com/5518513/37962072-ae4a20fe-31c2-11e8-9e95-b2180887edfe.png)

**Comment by manhbiboo** [comment]
Hi @webintoit , 
Did you fix this?
I have same error.
