### ISSUE TITLE
Event Listeners not triggered - Using Vue.js

### ISSUE THREAD

**Issue by tiofabby** [jitsi/lib-jitsi-meet#745]
Hello
I am trying to use lib-jitis-meet under a vuejs project.
Connection Event listeners are not being triggered with code below.
Any idea why? There is no error message. 
Within VideoBridge platform I dont see any error within logs neither...
Thank you

<<<<<
import Vue from 'vue'
import configuration from '../config'
import Libjitsimeet from 'lib-jitsi-meet'

let connection = null
// XMPP CONNECTION_ESTABLISHED listener
var onConnectionSuccess = function () {
  Log.info('CONNECTION ESTABLISHED')
}

// XMPP CONNECTION_FAILED listener
var onConnectionFailed = function () {
  Log.info('CONNECTION FAILED')
}

// XMPP CONNECTION_DISCONNECTED listener
var onConnectionDisconnect = function () {
  Log.info('DISCONNECTED')
}

export default {

  state: () => ({
     // some stuff here
  }),

  mutations: {
   // some stuff here
  },

  getters: {
    // some stuff here
  },

  actions: {
    // Get connection to XMPP server
    getConnection ({ commit, dispatch }) {
      try {
        Libjitsimeet.init(configuration.jitsiInitOptions)
          .then(() => {
            // Connecting to XMPP server
            connection = new Libjitsimeet.JitsiConnection(null, null, configuration.jitsiOptions)
            Log.info('Jitsi connection', connection)
            // Save connection to Store
            if (connection) {
              // Create listeners to EVENTS
              dispatch('createListeners')
            } else {
              // Log error
            }
          })
          .catch(error => // Log error)
      } catch (error) {
        // Log.error('Could not initialize connection to XMMP', error)
      }
    },

    // Create XMPP connection listeners
    createListeners () {
      try {
        Log.info('Create LISTENERS on', connection)
        connection.addEventListener(
          Libjitsimeet.events.connection.CONNECTION_FAILED,
          onConnectionFailed)

        connection.addEventListener(
          Libjitsimeet.events.connection.CONNECTION_ESTABLISHED,
          onConnectionSuccess)

        connection.addEventListener(
          Libjitsimeet.events.connection.CONNECTION_DISCONNECTED,
          onConnectionDisconnect)

      } catch (error) {
         // Log.error('Could not initialize Listeners from XMPP connection', error)
      }
    }
  }
}

**Comment by roy2651** [comment]
@tiofabby hello，how to use lib-jitsi-meet in VUE
