### ISSUE TITLE
Screen Sharing Not Working FF -> Chrome

### ISSUE THREAD

**Issue by vivekdoshi2** [jitsi/lib-jitsi-meet#751]
I have used the example given **[HERE](https://github.com/jitsi/lib-jitsi-meet/tree/master/doc/example)**

Changes I have made in `example.js`

```
// Whether desktop sharing should be disabled on Firefox.
desktopSharingFirefoxDisabled: false // made it false from true
```
**Browser Version**
Chrome : 66.0
Firefox : 60.0.1

**Issue :**
By making the above change I was able to get model from FF to make ScreenShare , but whenever I try to share the screen it got black/ hangs the current video on Chrome.

Please let me know if any other details required.

**Comment by sapkra** [comment]
I think this is fixed now. If there is still a problem please open a new issue.
