### ISSUE TITLE
How to change the room?

### ISSUE THREAD

**Issue by vivekdoshi2** [jitsi/lib-jitsi-meet#759]
I have tried to leave the 1st room and the again trying to connect another room with

`connection.initJitsiConference(roomName , confOptions);`

But I am not able to connect it again , throwing error :

> Strophe: error: Cannot read property 'isFocus' of null

Do we have any function that change the room directly ?

**Comment by hristoterezov** [comment]
This is supposed to work. I'll take a look and return back to you soon.

**Comment by vivekdoshi2** [comment]
Thanks for quick response , m waiting for your feedback

**Comment by hristoterezov** [comment]
Hey @vivekdoshi2,

I've tested it and I can't reproduce the error you mentioned. But when I tried to add some tracks it didn't work for me as well. So we'll need to do some fixes to support this scenario.

We don't have such an use case for jitsi-meet and I suppose the priority of this issue won't be very high.

As a workaround I'd advise you to try to leave the room, disconnect JitsiConection (basically execute something like the `unload` function from example.js) and then create new JitsiConection, initConference, join the conference, etc. Let me know if this works for you!

**Comment by vivekdoshi2** [comment]
@hristoterezov ,

Sorry for late reply,

Yeah I was already doing that way, but that was not sound proper way of doing that, 
But if its you suggesting this way then its good from mine side too.

Do we have this feature by just calling a function like

`changeRoom('roomname'); // will do rest of the work behind the screen` 

Thanks Again.

**Comment by everflux** [comment]
This worked for me:
```
room.leave();
....
room=connection.initJitsiConference(roomname, confOptions)
....
```
Though there is no convenience API available AFAIK this ticket could be closed since the feature is available.
