### ISSUE TITLE
Jitsi Meet API library is not opening

### ISSUE THREAD

**Issue by developerajendra** [jitsi/lib-jitsi-meet#76]
Hi,

while opening this :
`<script src="https://meet.jit.si/lib-jitsi-meet.js"></script>`

It's not opening and it says.
"404 Not Found"

Thanks

**Comment by damencho** [comment]
Please discuss problems on the mailinglist before opening any issues.
Your url is wrong. It is https://meet.jit.si/libs/lib-jitsi-meet.min.js.
