### ISSUE TITLE
Showing who is talking in the room

### ISSUE THREAD

**Issue by deplop** [jitsi/lib-jitsi-meet#761]
I just use voice call so I want to show who is talking by showing the sound levels of talking people changing   like in meet.jit.si. Can I do that with the lib?

**Comment by damencho** [comment]
You just need to track the audio level changes on tracks, TRACK_AUDIO_LEVEL_CHANGED is the event.
https://github.com/jitsi/lib-jitsi-meet/blob/60b210225218377794271283770749c1a4a6f116/doc/example/example.js#L33
https://github.com/jitsi/lib-jitsi-meet/blob/60b210225218377794271283770749c1a4a6f116/doc/example/example.js#L76
