### ISSUE TITLE
jitsi-meet-tokens not support over websokcets

### ISSUE THREAD

**Issue by gmemon** [jitsi/lib-jitsi-meet#764]
Hello All,

As per https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md, tokens are not supported with websockets. To see if that has changed, I tried websockets with tokens, and it seems like over websokcets tokens are not passed to prosody:

```Jun 17 03:45:50 general warn    Error verifying token err:not-allowed, reason:token required```

So my question is what can I do such that tokens sent over websockets are passed to prosody? I would really appreciate your help!!

Thanks,
-Ghulam

**Comment by damencho** [comment]
The only change is the config for the bosh url to start with ws://? Normally, the token is passed as jwt param to the bosh connection, do you see the jwt param when exploring the ws in Network tab in the developer console?

**Comment by gmemon** [comment]
Thanks, @damencho!! I have already changed the bosh parameter in jitsi-meet config as follows:

```bosh: 'wss://unknow.host.com/xmpp-websocket'```

And without token verification, I can get it to work over websocket. With token verification, however, prosody throws the following error, as I mentioned earlier:

```Jun 17 03:45:50 general warn Error verifying token err:not-allowed, reason:token required```

The following screen shot is taken from the WS tab under Network tab in Developer Tools. As you can see that both room name and token are being passed. They just dont seem to make it to prosody. 
![screen shot 2018-06-17 at 7 36 51 pm](https://user-images.githubusercontent.com/31674038/41515894-6c261928-7266-11e8-9052-df372d65779b.png)

Perhaps something is wrong with my nginx proxy_pass parameter? My nginx websocket setup is as follows:

```
location /xmpp-websocket {
             add_header 'Access-Control-Allow-Origin' '*';
             proxy_pass      https://localhost:5281/xmpp-websocket;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";
             proxy_set_header Host $http_host;
             tcp_nodelay on;
             }
```
Would really appreciate your help in sorting this out!!

Thanks,
-Ghulam

**Comment by webintoit** [comment]
Hi, @gmemon. There is patch needs to be applied to the prosody/mod_websocket.lua to make the thing works.
See ` plugins/mod_websocket.lua`
You need to fire  some event here, similar to `bosh_session` event in  mod_bosh patch from Jitsi team.
```lua
-- on  websocket connection 

local eventName = "bosh-session"; 
--                                 ^ "websocket-session" is better here, but it needs to be exposed in mod_auth_token.lua
(hosts[session.host]).events.fire_event("bosh-session", { session = session, request = request });

```

**Comment by gmemon** [comment]
Thanks, @webintoit !! Can you please specify which function I am looking for? There is a session_open_stream function, which seems to be called after the websocket handshake is complete. But, that function does not have access to request. There is handle_request function, which has access to both session and request. But, that function only starts the websocket handshake. So, not sure where this event needs to be fired.

Thanks,
-Ghulam

**Comment by webintoit** [comment]
```lua
-- works with prosody trunk 748

function handle_request(event){
   local session = sessions[conn];
   ...
   ...
   session.request = request;
   _G.hosts[session.host].events.fire_event("bosh-session", { session = session, request = request });
}
```

**Comment by gmemon** [comment]
Thanks!!

Current prosody trunk no longer exposes session.host in handle_request. So, I ended up modifying session_open_stream as follows:

```
--- Session methods
local function session_open_stream(session, from, to)
        local attr = {
                xmlns = xmlns_framing,
                ["xml:lang"] = "en",
                version = "1.0",
                id = session.streamid or "",
                from = from or session.host, to = to,
        };
        if session.stream_attrs then
                session:stream_attrs(from, to, attr)
        end
        _G.hosts[session.host].events.fire_event("bosh-session", { session = session, request = session.websocket_request });
        session.send(st.stanza("open", attr));
end
```

**Comment by damencho** [comment]
https://hg.prosody.im/trunk/file/default/plugins/mod_websocket.lua#l299

It is now.
