### ISSUE TITLE
How to call startRecording/stopRecording from server side

### ISSUE THREAD

**Issue by gorbatenkov** [jitsi/lib-jitsi-meet#811]
Hello, with using jibri I'm able to call startRecording/stopRecording fucntions from client side to start/stop recording Jitsi Meet conference.

But what if I need to call start/stop function from server side? For example, to stop recording on a timer when no user left? How it can be done?

Thank you

**Comment by bbaldino** [comment]
Recordings stop automatically after 30 seconds if everyone else has left the call.
