### ISSUE TITLE
Safari version 11.1 GUM not working.

### ISSUE THREAD

**Issue by lsiv568** [jitsi/lib-jitsi-meet#823]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Unable to obtain camera in Safari version 11.1.  

It appears as though the issue is due to RTCUtils.int#886 where `navigator.meidaDevices.addEventListener` is being called but `addEventListener` is not a function.  I believe the root cause is with BrowserUtils.supportsDeviceChangeEvent.  This function returns true in RTCUtils.init#885 resulting in `addEventListener` being called..

## Current behavior
---
Black screen due to:
```
Unhandled Promise Rejection: TypeError: navigator.mediaDevices.addEventListener is not a function. (In 'navigator.mediaDevices.addEventListener("devicechange",n)', 'navigator.mediaDevices.addEventListener' is undefined)
(anonymous function) — lib-jitsi-meet.min.js:2:109801
promiseReactionJob
```
## Expected Behavior
---
Video tile
## Possible Solution
---
Update RTCUtils.init#886 to `navigator.mediaDevices.ondevicechange = updateKnownDevices`

## Steps to reproduce
---

# Environment details
---
Safari version 11.1

**Comment by saghul** [comment]
Doh, I think I broke that. So, `ondevicechange` **is** defined, but `addEventListener` isn't? I'll take a look.

**Comment by lsiv568** [comment]
@saghul Yes.  It appears as though not all browsers support `navigator.mediaDevices.addEventListener` even though they support events.  Testing locally my suggested change does the trick.  However, being relatively new to the code base i'm not sure what other ramifications that change may introduce.  Thanks for looking!

**Comment by saghul** [comment]
@lsiv568 Thanks for the report. I confirmed it's a bug in Safari 11, Safari 12 does have `addEventListener`. At any rate, I'm making a fix now.
