### ISSUE TITLE
Unable to set JVB ICE Servers

### ISSUE THREAD

**Issue by lsiv568** [jitsi/lib-jitsi-meet#832]
## Description
---
When a user is in an environment that requires STUN/TURN (behind firewall, etc..) in order to connect to the JVB it is not possible because the client does not have valid `iceServers`.  Therefore, they are only able to conduct 1-on-1 calls.

The below screenshots are from `chrome://webrtc-internals` using the `meet.callstats.io` and my testing deployment.  As you can see, the P2P connection for the two users has `iceServers`.  However, the P2P connection for the JVB does not.

<img width="1446" alt="screen shot 2018-10-30 at 11 18 19 am" src="https://user-images.githubusercontent.com/474935/47730211-17c70b80-dc38-11e8-8f84-936d9e9f9511.png">
<img width="1445" alt="screen shot 2018-10-30 at 11 18 34 am" src="https://user-images.githubusercontent.com/474935/47730226-21507380-dc38-11e8-87d1-658695141fa7.png">

<img width="1437" alt="screen shot 2018-10-30 at 11 48 44 am" src="https://user-images.githubusercontent.com/474935/47731104-d6376000-dc39-11e8-8a64-5e68d51281ce.png">
<img width="1398" alt="screen shot 2018-10-30 at 11 48 31 am" src="https://user-images.githubusercontent.com/474935/47731117-dcc5d780-dc39-11e8-8118-9b8e3d08e18f.png">

## Current behavior
---
When 2 users are on a call and one of them needs STUN/TURN servers in order to establish a p2p connection with the JVB, when a 3rd person joins, the user requiring STUN/TURN does not see or hear the other participants (no audio/video).  Similarly, the other participants do not see or hear the user requiring STUN/TURN.   

## Expected Behavior
---
All users should be able to connect to the JVB and see/hear one another.

## Possible Solution
---
While it's extremely possible there are issues with my configuration, I am providing `stunServers` in my config as such:
```javascript
const connectionOptions = {
  ...
  p2p: {
    ...
    stunServers: [
      { urls: "stun:stun.l.google.com:19302" },
      { urls: "stun:stun1.l.google.com:19302" },
      { urls: "stun:stun2.l.google.com:19302" }
    ]
  }
};
```
However, this value never gets set on the JVB P2P ice server config in  [ib-jitsi-meet/modules/xmpp/xmpp.js#_initStrophePlugins()](https://github.com/jitsi/lib-jitsi-meet/blob/17ca8194eb6c486f007de1337d681fc9a934f81d/modules/xmpp/xmpp.js#L479)

I updated this function to set the `iceConfig` jvb ice servers and the issue was resolved allowing the user requiring STUN/TURN to connect to the JVB.

```javascript
...
if (Array.isArray(p2pStunServers)) {
  logger.info('P2P STUN servers: ', p2pStunServers);
  iceConfig.p2p.iceServers = p2pStunServers;
  iceConfig.jvb.iceServers = p2pStunServers;
}
...
```

While this solution works, it isn't necessarily secure.  For example, I plan on using time-limited creds (30 seconds) for STUN/TURN NAT traversal.  Therefore, when the creds expire the P2P connection will be terminated.  In order for this solution to work one would need to use a large time limit for their creds which isn't secure.  

**Questions**:
1.  Am I completely missing something extremely obvious here? 
2. Is there a way to provide `iceServers` to the JVB ice config?
3. Is there a way to programatically update the `iceServers` when the creds expire/change 

## Steps to reproduce
---
Force STUN/TURN relay candidates to be generated for a client when there is more than 2 people on a call.

# Environment details
---

**Comment by damencho** [comment]
The turn servers to be used need to be configured in prosody. 
https://github.com/jitsi/lib-jitsi-meet/blob/c2f269884a4991f1cee466367b98a095ace0b811/modules/xmpp/strophe.jingle.js#L288
https://github.com/jitsi/jitsi-meet/blob/master/doc/turn.md
This way you can configure credentials for the turn servers.
