### ISSUE TITLE
Safari VP8

### ISSUE THREAD

**Issue by mishurov** [jitsi/lib-jitsi-meet#834]
It seems that VP8 support has been finally added to Safari.

Webkit's tracker bug
https://bugs.webkit.org/show_bug.cgi?id=189976

WebKit's commit
https://trac.webkit.org/changeset/236821/webkit

WebKit's ChangeLog
https://trac.webkit.org/browser/webkit/releases/Apple/Safari%2012.0.1/libwebrtc/ChangeLog

Safari Technology Preview Release 68 ChangeLog
https://developer.apple.com/safari/technology-preview/release-notes/

Release 70 is available for downloading at the moment
https://developer.apple.com/safari/download/

I'm actually an open hater of Apple's so called "ecosystem" and don't use their products by definition. But some circumstances require me to make some digging into the problem. May be it may be useful for you - to change BrowserCapabilities.js or so in order to make Jibri's web front end work on Macs.

**Comment by mishurov** [comment]
Well, I've managed to install macOS into qemu-kvm. I've updated Safari to 12.0.1 and applied simple patch for tags/jitsi-meet_3387 just to enable video for Safari's User Agent.

```diff
diff --git a/modules/browser/BrowserCapabilities.js b/modules/browser/BrowserCapabilities.js
index f8d2128..6e22a9f 100644
--- a/modules/browser/BrowserCapabilities.js
+++ b/modules/browser/BrowserCapabilities.js
@@ -77,6 +77,22 @@ export default class BrowserCapabilities extends BrowserDetection {
             && !this.isVersionLessThan('11');
     }
 
+    /**
+     * Checks if current browser is a Safari and a version of Safari that
+     * supports VP8.
+     *
+     * @returns {boolean}
+     */
+    isSafariWithVP8() {
+        if (this.isSafari()) {
+            this._version = navigator.userAgent.match(/Version\/([\d.]+)/)[1];
+
+            return !this.isVersionLessThan('12.0.1');
+        }
+
+        return false;
+    }
+
     /**
      * Checks if the current browser is supported.
      *
@@ -220,7 +236,7 @@ export default class BrowserCapabilities extends BrowserDetection {
 
         // Currently Safari using webrtc/adapter does not support video due in
         // part to Safari only supporting H264 and the bridge sending VP8.
-        return !this.isSafariWithWebrtc();
+        return !this.isSafariWithWebrtc() || this.isSafariWithVP8();
     }
 
     /**

```
Despite showing the media from the camera in Safari, it didn't send or receive any video to another participant.

It seems that the necessary changes for WebRTC were added in Release 70. I've downloaded the latest for now Safari Technology Preview, and it works! It's not quite stable because I don't know much the RTC subtleties of lib-jitsi-meet yet it works!

On the pic, I send a test sequence from Safari in KVM via Use Mock Capture Devices and receive data from host's v4l2loopback mock camera.

![screenshot_2018-11-17_13-11-24](https://user-images.githubusercontent.com/1371641/48660140-d0c97a80-ea6d-11e8-8d5b-c5e975b11772.png)

**Comment by webintoit** [comment]
This is great investigation.

**Comment by saghul** [comment]
This looks great @mishurov! Can you please send it as a PR we can merge?

**Comment by saghul** [comment]
@bbaldino can you PTAL?

**Comment by mishurov** [comment]
@saghul, I've created the PR, there're couple of lines actually.

**Comment by bbaldino** [comment]
Can you link the PR here?

**Comment by saghul** [comment]
@bbaldino https://github.com/jitsi/lib-jitsi-meet/pull/835

**Comment by saghul** [comment]
Closing, let's continue on https://github.com/jitsi/lib-jitsi-meet/pull/835

**Comment by awebdeveloper** [comment]
does this mean safari will support vp8 in video tag too

**Comment by saghul** [comment]
Yes.
