### ISSUE TITLE
Use lib-jitsi-meet in cordova app

### ISSUE THREAD

**Issue by nasanchez** [jitsi/lib-jitsi-meet#836]
I am a noob with Jitsi Meet and I'm trying to implement the conference oin my own cordova app. I downloaded the provided example and I have several problems to implement it correctly with my openfire instance.

1. Web to Web: I have an error when access to the example. The error is: 

   > Logger.js:125 [modules/xmpp/ChatRoom.js] <>:  non-anonymous rooms not supported. 

    Even though I have this error, if I acces to the exmple from another computer with chrome, it works well.

2. Web to Mobile (cordova app): It not works. I have the same example in web anb in cordova app but when I try to join de conference from cordova app, I have this error: 

   > Logger.js:125 [modules/xmpp/JingleSessionPC.js] <>:  Error renegotiating after setting new remote offer: OperationError: Malformed constraints object. 
   > 
   > [JitsiConference.js] <>:  Failed to accept incoming P2P Jingle session DOMException: Malformed constraints object.

Someone knows what's the problem?

Thanks!

**Comment by zsinba** [comment]
we got the same issue. 
did you resolve this ?

**Comment by ShahidNaumanTEO** [comment]
In my case, The local tracks are created, but the remote tracks are not added.

**Comment by shirpk** [comment]
In my case, i am getting remote tracks but with empty stream :(

**Comment by zsinba** [comment]
I finally solved the problem. Use android's WebView to execute it. Just register for camera and microphone permissions. It ended up working fine under Android, but not under IOS.

**Comment by sapkra** [comment]
@zsinba I'm absolutely not experienced with cordova but my first guess is that webrtc is not supported, so I searched for it:
https://github.com/cordova-rtc/cordova-plugin-iosrtc

Please tell me if it works for you, so I can close this issue.

**Comment by zsinba** [comment]
thanks
