### ISSUE TITLE
Leave conference bug

### ISSUE THREAD

**Issue by golyo** [jitsi/lib-jitsi-meet#841]
## Description
---
 When user leaves conference, and there are no other members, timeout error occures.

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---
connection.emuc.doLeave(roomjid) and eventEmitter.emit(XMPPEvents.MUC_LEFT)
must call, so don't need any if statement on else, in ChatRoom.js line 847.

https://github.com/jitsi/lib-jitsi-meet/pull/840

## Steps to reproduce
---
Join a conference, then leave it

# Environment details
---

**Comment by sapkra** [comment]
Already seems to be fixed in master:
https://github.com/jitsi/lib-jitsi-meet/blob/80ba679eca27b8f50bcefee004f21d746ecf8554/modules/xmpp/ChatRoom.js#L976-L996
