### ISSUE TITLE
Performance on mobile's browser

### ISSUE THREAD

**Issue by deplop** [jitsi/lib-jitsi-meet#871]
Jitsi is very great project and I'm using this lib to implement my own customized room on mobile's browser so that everyone who doesn't install mobile app can use. After a few month of deployment and testing I release that, voice (no video) is not stable as users use the same room's url on desktop's browser. 
For example if I have 7,8 people join in the room on mobile's browser, there are 2,3 of them often can't hear anything throughout the meeting. When they switch to desktop, everything is fine. The browser's version they use support webrtc. 
I believe jitsi's server side has no problem with this small size of room but I'm afraid that there is something wrong with performance on mobile's browser. It's really a bad user experience that I want to fix but I still have no idea where the problem come from. Any suggestion for this?

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening issues.

Are you using the mobile SDK? Do you reproduce the same issues on meet.jit.si?

**Comment by deplop** [comment]
Sorry for that, I'm posting this on the community. 
I'm using the javascript lib-jitsi-meet for mobile's browser version, not the sdk for mobile app. 
As I know meet.jit.si doesn't allow access from mobile's browser so I haven't tried to reproduce the issue with meet.jit.si.
