### ISSUE TITLE
P2P Audio failing with useStunTurn: true

### ISSUE THREAD

**Issue by tiofabby** [jitsi/lib-jitsi-meet#874]
Hi
I am using last version of lib-jitsi-meet and running on a jitsi docker platform (docker hub images: jitsi/jvb, jitsi/prosody,..)

When in config.js file I put 
```
p2p: {
  enabled: true,
  useStunTurn: true,
  stunServers: [
    { urls: ‘stun:stun.l.google.com:19302’ },
    { urls: ‘stun:stun1.l.google.com:19302’ },
    { urls: ‘stun:stun2.l.google.com:19302’ }
  ],
  preferH264: true,
  disableH264: false,
  backToP2PDelay: 5
}

```
I can have 2 people connecting in P2P mode with Video but without Audio!
If I change the useStunTurn value to false,
then it works fine, 
I can have 2 people connecting in P2P mode with both Audio and Video.

Thank you
Fabrice

**Comment by saghul** [comment]
What devices are you using?

**Comment by tiofabby** [comment]
I am using Mac OS audio & video devices. They have always been working fine so I dont think this is linked to devices.. unless I may be missing something..

**Comment by saghul** [comment]
Sorry, I should have been more specific. By devices I mean if it was a browser, if so what version and on what platform you were testing (you answered this already, macOS).

**Comment by tiofabby** [comment]
Yes I just made few tests then and now looks like whatever I put for useStunTurn (true or false) , I am still not getting audio. This is weird..
However, if I use FF it works fine and Chrome with FF too.
my versions are: Chrome v72 and FireFox v65.0.1

**Comment by saghul** [comment]
> However, if I use FF it works fine and Chrome with FF too.

Sorry, I'm not sure I follow. It works OK with Chrome and Firefox, but it doesn't with ???

**Comment by tiofabby** [comment]
Sorry, let me clarify:
Part1 with FireFox , Part2 with Chrome (or Opposite) -> it works fine.
Part1 with Chrome and Part2 with Chrome -> we are missing Audio.
