### ISSUE TITLE
Missing RTC.dispose() method

### ISSUE THREAD

**Issue by timsu** [jitsi/lib-jitsi-meet#890]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

When I leave a conference, I get a console error that rtc.dispose() is not a function. 

It's at the following line in JitsiConference.js:
https://github.com/jitsi/lib-jitsi-meet/blob/1bfc96a2876d6527bfa27cf46d4f1e9f6e65edbc/JitsiConference.js#L474-L479

However, the RTC class has no dispose method.

On latest master (1bfc96a2876d6527bfa27cf46d4f1e9f6e65edbc)

**Comment by damencho** [comment]
Fixed by 6209f06464b0ba5cb1e74e893a7a121387c8cc8d
