### ISSUE TITLE
Safari 12.3 -  Error negotiating after setting new remote offer

### ISSUE THREAD

**Issue by nadelicious** [jitsi/lib-jitsi-meet#903]
When using the new IOS v 12.3, I encountered this error when the call begins.

Browser: Safari
Config: Vp8 with Simulcast

https://imgur.com/3rV3iNB

**Comment by saghul** [comment]
Is unified plan enabled?

**Comment by nadelicious** [comment]
@saghul how to enable unified plan? is it via jitsi config or browser setting?

**Comment by nadelicious** [comment]
@saghul  yes web rtc unified plan is enabled.

**Comment by saghul** [comment]
We don't currently support video when using Safari with Unified Plan.

**Comment by nadelicious** [comment]
@saghul  do you any plans in the future to support this?

**Comment by jiyeyuran** [comment]
@saghul do you have any plan in the future to support this?

**Comment by saghul** [comment]
Yes, we do, no ETA though.

@nadelicious Last I checked it wasn't. Only in Safari TP versions.

**Comment by jiyeyuran** [comment]
It seems that Safari is using unified plan from v12.3 on all platform.

**Comment by saghul** [comment]
@jiyeyuran That is Safari Technology Preview, right? Well, it's not version 13. Yeah, that's correct, but release versions don't. In the past, Safari had unified plan enabled in the betas (TP) but then disabled it on released versions.

**Comment by nadelicious** [comment]
I checked on both mobile and desktop Safari 12.3, the unified plan is enabled in the experimental features setting.

**Comment by saghul** [comment]
Doh, looks like they turned it on :-/ Tough luck then, it doesn't currently work, sorry. Also, I can't provide an ETA about when it will be ready.

**Comment by jiyeyuran** [comment]
Is it hard to solve this problem? Jitsi Meet works on Firefox which is using unified plan, therefore Safari with unified plan also should works. However, if I remove the `this.usesPlanB()` limitation on `supportsVideo()`, the console show warning `ssrc not mapping`. Maybe there is very slight difference between Firefox and Safari.

**Comment by saghul** [comment]
It's not that easy, alas. We are going to look into it, but as I said, we don't have an ETA, sorry.

Of course, if you feel adventurous, I'd be happy to review a PR :-)

**Comment by jiyeyuran** [comment]
I tried as below:
1. replace `a=msid-semantic: WMS *' to `a=msid-semantic: WMS ${streamId}`
2. add simulcast ssrcs for safari with vp8
```
    /**
     * Adds multi-ssrc based simulcast into the given SDP media section offer.
     *
     * @param {Object} mediaObject - Local SDP media Object generated by sdp-transform.
     * @param {Number} numStreams - Number of simulcast streams.
     */
    addLegacySimulcast(mediaObject, numStreams) {
        if (numStreams <= 1) {
            throw new TypeError('numStreams must be greater than 1');
        }

        const ssrcCnameLine = mediaObject.ssrcs.find(line => line.attribute === 'cname');

        if (!ssrcCnameLine) {
            throw new Error('a=ssrc line with cname information not found');
        }

        const cname = ssrcCnameLine.value;
        const [ streamId, trackId ] = mediaObject.msid.split(' ');
        const ssrcs = [];

        for (let i = 0; i < numStreams; ++i) {
            ssrcs.push(this.generateSsrc());
        }

        mediaObject.ssrcGroups = [];
        mediaObject.ssrcs = [];

        mediaObject.ssrcGroups.push({
            semantics: 'SIM',
            ssrcs: ssrcs.join(' ')
        });

        for (let i = 0; i < ssrcs.length; ++i) {
            const ssrc = ssrcs[i];

            mediaObject.ssrcs.push({
                id: ssrc,
                attribute: 'cname',
                value: cname
            });

            mediaObject.ssrcs.push({
                id: ssrc,
                attribute: 'msid',
                value: `${streamId} ${trackId}`
            });
        }
    }
```
Bad lucky, it is not working.

**Comment by buddhikajay** [comment]
> It's not that easy, alas. We are going to look into it, but as I said, we don't have an ETA, sorry.
> 
> Of course, if you feel adventurous, I'd be hap

> It's not that easy, alas. We are going to look into it, but as I said, we don't have an ETA, sorry.
> 
> Of course, if you feel adventurous, I'd be happy to review a PR :-)

@saghul,
Is it possible to describe the issue ? does this has to do something with JVB as well ? I'd like to work on this as well.

**Comment by saghul** [comment]
This should be fixable only with client side (aka JavaScript) changes.

**Comment by webintoit** [comment]
First what we should do - is to avoid semantic conversion on unified plan browsers. Having a jingle offer we need to construct unified plan SDP. After adding sources to peerconnection, we must extract ssrc info from unified plan and build jingle source-add. It is best option. 
For tmp, we must decreasy frewquency of plan conversions. For example, currently ljm converts SDP like
`jingle xml -> plan b -> modifications -> unified Plan -> modifications -> rtcpeerconnection `
All transformation pipe is attached to localDescriotion, remoteDescription getters . and `setRemoteDescripton`, `setLocalDescription` interceptors, and `createAnswer/createOffer` interceptors. At some point `sdp-interop` obtain invalid cache.  We can convert sdp between semantics only on `setLocal/Remote-Description` and set corresponding `planB` version to local variable for example.

**Comment by jallamsetty1** [comment]
Hey @nadelicious, I am closing this issue since this has already been fixed.
