### ISSUE TITLE
Android Cordova: Loosing remote audio track sound when go to background

### ISSUE THREAD

**Issue by DaveLomber** [jitsi/lib-jitsi-meet#947]
## Description
I'm building an Android Cordova calling app.
We have an issue. If there is an active audio or video call.
When we put an app to background then we are loosing a remote audio track sound, so can't hear a remote party on Android side while an app is in background mode or screen locked

## Steps to reproduce
- Make an active call between Android Cordova app & Chrome browser
- put an Android app to background

# Environment details
Android 9, Cordova

We are using jitsi-met-lib

Could anyone assist with it, what we can do to prevent the issue to happen.

**Comment by sapkra** [comment]
I think this is an energy saving feature which pauses the javascript threads. You have to implement something to keep your app alive, like an overlay or maybe there are some other workarounds or ways to tell the system to not pause the app but if you lock the screen I think you have no chance to get a solution without using something like the android telecom api.

**Comment by kiranNegiloni** [comment]
Hi @DaveLomber  - We are facing similar issue on our React Native Android app. Please let us know if you found a way to resolve the issue.

**Comment by saghul** [comment]
Wops this has been open for waaay too long.

The original issue was already explained and doesn't apply to RN.
