### ISSUE TITLE
Wrong bitrate values on Firefox

### ISSUE THREAD

**Issue by HamzaKhait** [jitsi/lib-jitsi-meet#965]
## Description
---
Jitsi displays wrong bitrate value on Firefox 62 ESR (sometimes up to 59 Mbps).

## Current behavior
---
When runing wireshark, it turned out that the used bandwidth is lower than the values displayed by Jitsi 

![image](https://user-images.githubusercontent.com/11749913/63435770-caff2c00-c427-11e9-828b-ee3a7061828e.png)
![image](https://user-images.githubusercontent.com/11749913/63435790-d2bed080-c427-11e9-9c88-ade2ad0fad3e.png)

## Expected Behavior
---
Wireshark capture 
![image](https://user-images.githubusercontent.com/11749913/63435896-000b7e80-c428-11e9-8fd8-979b08047904.png)

## Possible Solution
---
@damencho's answser https://community.jitsi.org/t/huge-bandwidth-usage-on-firefox-7mbps/19424/8

## Steps to reproduce
---
Join a 4 people (or more) conference on Firefox

# Environment details
---
Firefox on Ubuntu and Windows 7/10

**Comment by jallamsetty1** [comment]
This should be fixed now.
