### ISSUE TITLE
Video tracks missing on Firefox ESR

### ISSUE THREAD

**Issue by x1gma** [jitsi/lib-jitsi-meet#988]
See the Forum post for full documentation on the issue: https://community.jitsi.org/t/video-tracks-not-being-received-send/20177

GitHub link to example: https://github.com/x1gma/jitsi-track-issues

## Description

In a custom UI based on lib-jitsi-meet on leaving and reconnecting to the conference, video tracks may be missing or video is frozen. This seems to occur more frequently in Firefox.

---

## Current behavior

On rejoining a present conference, the joining user may see a frozen video or no video at all.

---

## Expected Behavior

On rejoining a conference (which worked before the leave) the user should be able to see all other participants correctly, aswell as being seen by all participants.

---

## Possible Solution

We tracked down that the RTCPeerConnection is not being notified of new tracks being added (resp. the MediaStreams). (https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/TraceablePeerConnection.js#L246-L247 this callback is **not** being called.)

We have no further information about the frozen streams.

---

## Steps to reproduce

See the GitHub repository and the test application.

---

# Environment details

The issue is visible both on our on-prem Jitsi backend aswell as the official API and Beta-API. The test application dependencies match our main project.

## Local development 

```
> ionic info

Ionic:

   ionic (Ionic CLI)             : 4.12.0 ([...]\v10.14.1\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.3
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

---

**Comment by jallamsetty1** [comment]
@x1gma, this should be fixed. Can you please verify if this issue exists in the latest release and close this issue if it doesn't occur anymore ?
