### ISSUE TITLE
Turn off device when leave room

### ISSUE THREAD

**Issue by hung211097** [jitsi/lib-jitsi-meet#989]
Hi, I get a case that when I leave the room, I call dispose the local video track and then leave the room, finally disconnect. But in some case the light of camera is still on and icon of chrome is still on too. Do I forget to call any function?

**Comment by justficks** [comment]
You should have an array of local tracks (audio, video) like in the [example](https://github.com/jitsi/lib-jitsi-meet/blob/3c8d411c96fdfa18c57111630f29880f3f72949e/doc/example/example.js#L22)

And when you want to "Turn off video device" you can do like:
`localTracks.map(track => {track.dispose()})`

**Comment by billmorgan123** [comment]
> You should have an array of local tracks (audio, video) like in the [example](https://github.com/jitsi/lib-jitsi-meet/blob/3c8d411c96fdfa18c57111630f29880f3f72949e/doc/example/example.js#L22)
> 
> Then when you want to "Turn off devices (micro and camera)" you can do like:
> `localTracks.map(track => {track.dispose()})`
i am doing like this but its never work
await this.localTracks.forEach((track) => {
  track.dispose();
});
