### ISSUE TITLE
Electron Desktop Sharing Picker integration not working

### ISSUE THREAD

**Issue by Jip-Hop** [jitsi/lib-jitsi-meet#998]
I'm trying to get the example in this repository to work inside Electron.
But the screen sharing function isn't working.

I get this error:
```
2019-10-25T12:59:22.210Z [JitsiConference.js] <Y._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession
Logger.js:154 2019-10-25T12:59:22.210Z [modules/RTC/RTCUtils.js] <t.value>:  Using the new gUM flow
example.js:344 a {name: "gum.electron_desktop_picker_not_found", message: "Failed to detect desktop picker", stack: "Error↵    at new a (https://meet.jit.si/libs/lib-j…static/index.html"}
Logger.js:154 2019-10-25T12:59:22.218Z [modules/RTC/TraceablePeerConnection.js] <w.clearRecvonlySsrc>:  Clearing primary video SSRC!
```
I did some searching and found it should work when using `screensharing` from jitsi-meet-electron-utils. Looking at the `screensharing` module it's intended for iframes: `setupScreenSharingForWindow(iframe)`. However, the example in this repo doesn't run in an iframe, so it doesn't work. I've tried including the code in a preload script like this:

```
const electron = require("electron");

window.JitsiMeetElectron = {
    /**
     * Get sources available for screensharing. The callback is invoked
     * with an array of DesktopCapturerSources.
     *
     * @param {Function} callback - The success callback.
     * @param {Function} errorCallback - The callback for errors.
     * @param {Object} options - Configuration for getting sources.
     * @param {Array} options.types - Specify the desktop source types
     * to get, with valid sources being "window" and "screen".
     * @param {Object} options.thumbnailSize - Specify how big the
     * preview images for the sources should be. The valid keys are
     * height and width, e.g. { height: number, width: number}. By
     * default electron will return images with height and width of
     * 150px.
     */
    obtainDesktopStreams(callback, errorCallback, options = {}) {
        electron.desktopCapturer.getSources(options,
            (error, sources) => {
                if (error) {
                    errorCallback(error);
                    return;
                }

                callback(sources);
            });
    }
};
```

`JitsiMeetElectron.obtainDesktopStreams()` is available on the example page, but the code never runs and desktop capture still doesn't work.

How can I enable the desktop capture function with Electron when using `lib-jitsi-meet`?

**Comment by damencho** [comment]
Please, when having questions use the community forum before opening new issues, thank you.

So you can run and debug jitsi-meet-electron to see how it works. 
Here is a short summary:
jitsi-meet-electron-utils provides to the window JitsiMeetElectron.obtainDesktopStreams, this is used by jitsi-meet [here](https://github.com/jitsi/jitsi-meet/blob/5a934c071a5cbe64de275a25d0ed62d8193cdd03/react/features/desktop-picker/functions.js#L26) to get the available windows/screens with their thumbnails and to implement the desktop picker which then is provided to the window [here](https://github.com/jitsi/jitsi-meet/blob/6e10ca5dd2463fa413605341e52de60702270e12/conference.js#L129) as JitsiMeetScreenObtainer and is used by lib-jitsi-meet [here](https://github.com/jitsi/lib-jitsi-meet/blob/92b51e185042c944e669082c9d9de83401d6b512/modules/RTC/ScreenObtainer.js#L185).

**Comment by pouriamoosavi** [comment]
For a more detailed solution, you may want to see this: https://github.com/jitsi/lib-jitsi-meet/issues/2036#issuecomment-1465462240
Basically, it is just what @damencho said.
