### ISSUE TITLE
Unable to join the same conference room from lib jitsi meet to jitsi meet in aws

### ISSUE THREAD

**Issue by vanishree1** [jitsi/lib-jitsi-meet#999]
I'm trying to join the same call from lib jitsi meet library to jitsi meet. I'm able to join the call from all the os's chrome except from aws instance. 
---
Current behavior :
I'm starting the call from meet.jit.si/roomName
and executing the example of lib jitsi meet with the below config and giving same conference roomName.
```
const connectionConfig = {
  hosts: {
    domain: "meet.jit.si",
    focus: "focus.meet.jit.si",
    muc: "conference.meet.jit.si" // FIXME: use XEP-0030
  },
  bosh: "https://meet.jit.si/http-bind", // FIXME: use xep-0156 for that
  // The name of client node advertised in XEP-0115 'c' stanza
  clientNode: "http://jitsi.org/jitsimeet",
  preferH264: true,
  disableSimulcast: true
};

const conferenceOptions = {
  openBridgeChannel: "datachannel",
  channelLastN: 1
};
```

lib jitsi meet able to join the same conference room from chrome of mac, ubuntu and window. But not able to join the same conference room from public/private aws ec2 instance. It creates new conference.
---

Expected Behavior:

Lib jitsi meet should able to join the same conference room when we host it on aws ec2 instance.
 
---

Steps to reproduce
1) Create call on jitsi meet.
2) Host lib jitsi meet example code on aws ec2 instance(OS: ubuntu) and try to  join the same call from lib jitsi meet.

**Comment by damencho** [comment]
Use the community forum for asking questions before opening new issues.

I suppose you are seeing some CORs errors? Please add the errors you see.

The recommended way is to source the library from the deployment which you will use,  if they become out of sync it may partially or fully stop working. And when you update you will update both.

**Comment by vanishree1** [comment]
@damencho There are no errors. Conference is created with the same name , neither lib-jitsi-meet user shows up in jitsi-meet nor jitsi-meet user shows up in lib-jitsi-meet . Both joins the call independently with the same conference name.

**Comment by damencho** [comment]
So probably they are in different rooms. Share the code, without any example or some kind of error we can waste our time guessing.

**Comment by damencho** [comment]
What do you mean by `I run the same code on aws instance`? You are launching there a chrome instance and load the same page?

**Comment by damencho** [comment]
So the script you sent me was using meet.jit.si, the one you are testing with aws is using beta.meet.jit.si (1234567890@conference.beta.meet.jit.si), so there are using different deployments.
And the machine you are running chrome is so small, strophe connects after 26 seconds
>  Strophe connected:	 26400.86000005249
And muc is joined after more than 30:
> MUC joined:	 33510.00000000931

**Comment by vanishree1** [comment]
@damencho I have tried connecting with meet.jit.si, It sometimes create new conference but many times fail to join the call in aws environment but works always locally So I tried to join with beta.meet.jit.si .
<img width="1433" alt="Screen Shot 2019-10-30 at 8 58 00 PM" src="https://user-images.githubusercontent.com/8781822/67913119-ffbefa80-fbb1-11e9-9a95-68f6d1b82a46.png">

**Comment by damencho** [comment]
If the screenshot is from yesterday there were some failures on beta.meet.jit.si and this is to be expected.
I suspect your chrome may sometimes get errors when joining as it is not normal an operation that takes 2-3 seconds to take 30-40. Try increasing chrome resources, memory and cpu and try again. 
The muc join time should be between 1 and 3 seconds.

**Comment by vanishree1** [comment]
@damencho I tried it by increasing the chrome resources and it reduced the time taken for strophe and muc connection as well but still it joined a new conference. I've attached log and screenshot below.
[meet_confernce.log](https://github.com/jitsi/lib-jitsi-meet/files/3797518/meet_confernce.log)
<img width="1438" alt="Screen Shot 2019-11-01 at 3 54 41 PM" src="https://user-images.githubusercontent.com/8781822/68019215-1dc75080-fcc1-11e9-84a0-24fb33f06af5.png">

**Comment by damencho** [comment]
Do you have and the browser logs where you also tried to join the call at the same time (the second location logs)?

**Comment by vanishree1** [comment]
I've attached  browser logs of aws instance and local instance below.
[aws-conference.log](https://github.com/jitsi/lib-jitsi-meet/files/3798934/aws-conference.log)
[local-conference.log](https://github.com/jitsi/lib-jitsi-meet/files/3798935/ngrok-conference.log)

**Comment by damencho** [comment]
I suppose different times is just that the clocks on both locations are different, not that you joined both participants at different times.

I don't see a reason why this would happen other than you have some weird DNS setting on one of the places and you somehow end up on two different shards... 
To check on which shard landed your connection you need to check in network tab the headers for the bosh connection:
![image](https://user-images.githubusercontent.com/3263098/68047114-7f91b580-fcd5-11e9-8a3c-7adf006ca68c.png)

Not sure whether you can do that in aws.

**Comment by vanishree1** [comment]
@damencho By using proxy locally I was able to connect to the same conference. Any possible reason why this is happening in lib-jitsi-meet?

**Comment by damencho** [comment]
No reason. Can you give more details what is this proxy and how it changed things?
We are using lib-jitsi-meet in jitsi-meet and we are using it in aws running chrome there without a problem.

**Comment by vanishree1** [comment]
The aws instance is hosted in us-east-1 and when I used a vpn like tunnel bear to route the traffic through USA, It worked. Also I created another instance in south east Asia in aws and tried to connect locally. It worked as well.

**Comment by damencho** [comment]
In this case two conclusions: 
- you are not using our load balancers and directly connecting to the shard 
- I'm in a big confusion, not sure how this possible ... 
There is something wrong with your setup which I cannot understand.
The correct path is the following:
- 1st connection to bosh address https://meet.jit.si/http-bind?room=testroom hits the load balancer in some region, that balancer checks on which shard you need to land, as this is first connection to the room you land on a shard in that region
- 2nd connection from the second client hits the load balancer with the same address as the room  is with the same name, but that balancer will already have info for the room name and the shard it is one and will route it there
And in this situation both end on same shard and same room.

**Comment by damencho** [comment]
Oh, your bosh config is wrong:
```
  bosh: "https://meet.jit.si/http-bind", // FIXME: use xep-0156 for that
```

This should be:
```
bosh: "/meet.jit.si/http-bind", // FIXME: use xep-0156 for that
```

You can check it in: https://meet.jit.si/config.js
But still, I'm surprised why you end up on two different shards but got connected ...

**Comment by vanishree1** [comment]
@damencho , How do we mention load balancers?

Changing the bosh address also didn't work. 

I noticed that room query parameters not being passed with each http-bind call.

**Comment by damencho** [comment]
You need to pass it as bosh:
https://github.com/jitsi/jitsi-meet/blob/84b589719f4d1e9d29870ebc0d741822338ec89e/connection.js#L78

**Comment by vanishree1** [comment]
@damencho after adding above code it worked. Thanks.

**Comment by damencho** [comment]
Yeah, I had forgotten that it is not added in the lib and that got me confused...

**Comment by LokeshPahadiya** [comment]
1. I have configure the jitsi meet in ubuntu and it is successfully run but i want to add some configuration it can possible user will be join as a guest one will be moderator. but in my case Whenever someone joins first he becomes a moderator i do not want this. I want to restrict user they can only join as guest only i want this plz help me in this.
 2. I want to add the jwt authentication in this what will be the username and what will be the password how to pass the jwt by our application plz suggest the full example.(How to extract the jwt token).

**Comment by saghul** [comment]
Please don't comment on 4 year old issues.
